### PR TITLE
349: dynamic updates for edge drawings and polypoints

### LINKED ISSUE #349: Add/Remove Edge when it gets added/removed from the Triangulation Graph

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #349

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/384)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/draw/constants.js, line 12 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7_TFKq8PCDax3DVNPd:-L7_TFKq8PCDax3DVNPe:b-oq9uec) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0471b2fc067cba29551e0dd0c83b827e704a5081/src/draw/constants.js#L12)):*
> ```JavaScript
>     vertex: 0xa5005d, // darker pink
>   },
>   polypoints: {
> ```

is this what I think it is? the polypoints look dark green on the screen, not turquoise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by davidabrahams** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/draw/constants.js, line 12 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7_TFKq8PCDax3DVNPd:-L7_VgTK_nYMtuMhTiFj:b-3gjn9y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0471b2fc067cba29551e0dd0c83b827e704a5081/src/draw/constants.js#L12)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is this what I think it is? the polypoints look dark green on the screen, not turquoise
</blockquote></details>

yeah turns out this color is green:

http://www.htmlcsscolor.com/hex/006600

thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 2 of 8 files at r1, 1 of 1 files at r2.
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 4 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 1 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 1 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/class/DrawableGraph.js, line 79 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7aplFiZ45C68pKCZWo:-L7aplFiZ45C68pKCZWp:bia5m7l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/draw/class/DrawableGraph.js#L79)):*
> ```JavaScript
>   addEdgeDrawing(edge) {
>     let e = edge;
>     // make sure e goes from left to right, so that when it gets removed we know what orientation
> ```

capitalize

---

*[src/draw/class/DrawableGraph.js, line 81 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7aqEdXnxcMy48VEu52:-L7aqEdXnxcMy48VEu53:bpo4b7z) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/draw/class/DrawableGraph.js#L81)):*
> ```JavaScript
>     // make sure e goes from left to right, so that when it gets removed we know what orientation
>     //   the key is in
>     if (e.p1.x > e.p2.x || (e.p1.x === e.p2.x && e.p1.y > e.p2.y)) e = new Edge(e.p2, e.p1);
> ```

What if we made a class method on Edge that was like "sortLeftToRight()" or something that switched p1 and p2 internally?

---

*[src/draw/class/DrawableGraph.js, line 91 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7apdnclUfU1Tr3TV0X:-L7apdnclUfU1Tr3TV0Y:b-tujjbl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/draw/class/DrawableGraph.js#L91)):*
> ```JavaScript
>   removeEdgeDrawing(edge) {
>     let e = edge;
>     if (e.p1.x > e.p2.x || (e.p1.x === e.p2.x && e.p1.y > e.p2.y)) e = new Edge(e.p2, e.p1);
> ```

FYI you could do a ternary here to avoid making a let, but up to you.  Also applies to the the addEdgeDrawing function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by shanek21** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Graph.js, line 93 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384#-L7bncwVAn6CIwfDMz4b:-L7bncwWAu-clfGciiLt:b-tcv8r4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/interpret/class/Graph.js#L93)):*
> ```JavaScript
>   /**
>    * Removes a vertex from the graph, and clears all edges connected to it. Returns true if the
>    * vertex was in the graph, false otherwise.
> ```

Indent two spaces

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384)*

**Comment by davidabrahams** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/draw/class/DrawableGraph.js, line 79 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7aplFiZ45C68pKCZWo:-L7fRTf21W-CQX9Dpy30:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/draw/class/DrawableGraph.js#L79)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

capitalize
</blockquote></details>

Done.

---

*[src/draw/class/DrawableGraph.js, line 81 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7aqEdXnxcMy48VEu52:-L7fRScPBPFTO4AN_xnY:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/draw/class/DrawableGraph.js#L81)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

What if we made a class method on Edge that was like "sortLeftToRight()" or something that switched p1 and p2 internally?
</blockquote></details>

Done.

---

*[src/draw/class/DrawableGraph.js, line 91 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7apdnclUfU1Tr3TV0X:-L7fRR0GgCqfnek-hc0Q:b-ubtjw6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/draw/class/DrawableGraph.js#L91)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

FYI you could do a ternary here to avoid making a let, but up to you.  Also applies to the the addEdgeDrawing function
</blockquote></details>

Doneish, via function?

---

*[src/interpret/class/Graph.js, line 93 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7bncwVAn6CIwfDMz4b:-L7fRapoWApM15VE_SJW:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4d897b566b8e90e70846361687afc2a83c6eefc3/src/interpret/class/Graph.js#L93)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Indent two spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by shanek21** [comment]
Reviewed 3 of 4 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Edge.js, line 73 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384#-L7fUFzf80ogge17-FV1:-L7fS_iO3vrBExre0X2g:bmr7aw6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1401dffdc0880bca59551f1a7819db16791320c5/src/interpret/class/Edge.js#L73)):*
> ```JavaScript
>    * In the case e.p1.x == e.p2.x, set e.p1 to be the point with a smaller y
>    */
>   sortedLeftToRight() {
> ```

Could we make it so that every Edge we ever create automatically sorts points from left to right? Then we would never have to worry about swapped points.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384)*

**Comment by shanek21** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384#-L7fUMUvAAbmyTAcUgA_:-L7fUMUvAAbmyTAcUgAa:b-1g3fp8) (no related file):*
change commit msg `349: add Edge.sortedLeftToRight` to `349: add Edge.sortedLeftToRight()`

(at least I think that's our convention?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r3.
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Edge.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7fUFzf80ogge17-FV1:-L7fVsUJa3MgnVAlgnM9:b-iscgul) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1401dffdc0880bca59551f1a7819db16791320c5/src/interpret/class/Edge.js#L73)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Could we make it so that every Edge we ever create automatically sorts points from left to right? Then we would never have to worry about swapped points.
</blockquote></details>

oh damn that would be dank

---

*[src/interpret/class/Edge.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7fVzF8kJzWcf0FUmie:-L7fVzF92Zz0ahYfuEP2:bg0ouzo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1401dffdc0880bca59551f1a7819db16791320c5/src/interpret/class/Edge.js#L73)):*
> ```JavaScript
>    * In the case e.p1.x == e.p2.x, set e.p1 to be the point with a smaller y
>    */
>   sortedLeftToRight() {
> ```

what if this just switched p1 and p2 internally instead of returning a new edge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by davidabrahams** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7fUMUvAAbmyTAcUgA_:-L7fWSvOLXAdP7OTjJdL:b-rz2fxu) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

change commit msg `349: add Edge.sortedLeftToRight` to `349: add Edge.sortedLeftToRight()`

(at least I think that's our convention?)
</blockquote></details>

Done via not having that function

---

*[src/interpret/class/Edge.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7fUFzf80ogge17-FV1:-L7fWQWopHLPuS36weIM:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1401dffdc0880bca59551f1a7819db16791320c5/src/interpret/class/Edge.js#L73)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

oh damn that would be dank
</blockquote></details>

Done.

---

*[src/interpret/class/Edge.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7fVzF8kJzWcf0FUmie:-L7fWRKcXEKksdOHmNPs:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1401dffdc0880bca59551f1a7819db16791320c5/src/interpret/class/Edge.js#L73)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what if this just switched p1 and p2 internally instead of returning a new edge
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
*[src/draw/class/DrawableGraph.js, line 78 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384#-L7fXn6lJ1IrsnBwMUqd:-L7fXn6m3QK4BSiNiXd-:b-fuuxa) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1fcad00d1ecbfafa4fcd3f70596998581428910/src/draw/class/DrawableGraph.js#L78)):*
> ```JavaScript
>   addEdgeDrawing(e) {
>     // Make sure e goes from left to right, so that when it gets removed we know what orientation
>     //   the key is in
> ```

delete comment now maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r4.
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/384)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/384)*

**Pull request merged**
