### PR TITLE
203: Motion towards next polypoint along navmesh path

### LINKED ISSUE #203: Motion towards next polypoint along navmesh path

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #203

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/313)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 5 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fIrFWfouxU0446_79:-L0fIrFWfouxU0446_7A:b-cfip4d) (no related file):*
PR title same as issue title pls

---

*[src/bot.js, line 46 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fJBH3miH9WrtHEWxA:-L0fJBH3miH9WrtHEWxB:bdeyabv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f4a7306983ca3613c243a51fec70b429e85bac8d/src/bot.js#L46)):*
> ```JavaScript
>     target.yp = polypointShortestPath[1].point.y;
>   } else {
>     console.warn('Shortest path was null, using own location as target');
> ```

Is polypointShoertestPath[0] always our own position, why do we check for length > 1 instead of length > 0 and should we update this log to reflect that

---

*[src/helpers/map.js, line 195 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fJVI_aN6UvhUDvQl_:-L0fJVIaLZUzp0n5JGP3:b-z5m1sa) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f4a7306983ca3613c243a51fec70b429e85bac8d/src/helpers/map.js#L195)):*
> ```JavaScript
>   // getDTGraph().dynamicUpdate(unfixEdges, constrainingEdges, removeVertices, addVertices);
>   // getDTGraph().calculatePolypointGraph();
>   // drawNavMesh();
> ```

was this commented out for the demo? what should the workflow be now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fIrFWfouxU0446_79:-L0kSdXXj7C9lzjB7mBc:bb6un1j) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

PR title same as issue title pls
</blockquote></details>

Done

---

*[src/bot.js, line 46 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fJBH3miH9WrtHEWxA:-L0kPQt9s50lvhx9TBrh:b-lncn7l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f4a7306983ca3613c243a51fec70b429e85bac8d/src/bot.js#L46)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Is polypointShoertestPath[0] always our own position, why do we check for length > 1 instead of length > 0 and should we update this log to reflect that
</blockquote></details>

I believe polypointShortestPath[0] is always our own position. I examined the `getShortestPolypointPath` function, and it should always return either null, or an array length > 1. I updated the checks to reflect this.

---

*[src/helpers/map.js, line 195 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fJVI_aN6UvhUDvQl_:-L0kPyUQ6CKJYvj8Nbst:b-bm5mjg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f4a7306983ca3613c243a51fec70b429e85bac8d/src/helpers/map.js#L195)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

was this commented out for the demo? what should the workflow be now
</blockquote></details>

Yeah, it was. I'm not sure if we actually want to do this stuff? It's all slow right now, which is why we didn't have it in the demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 195 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fJVI_aN6UvhUDvQl_:-L0lu2UeuHDDSSivvOEq:boipq27) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f4a7306983ca3613c243a51fec70b429e85bac8d/src/helpers/map.js#L195)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Yeah, it was. I'm not sure if we actually want to do this stuff? It's all slow right now, which is why we didn't have it in the demo.
</blockquote></details>

Gotcha.  Is this being tracked in #310 and #311, are those the relevant issues?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 195 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0fJVI_aN6UvhUDvQl_:-L0lwtajSyB-jNgRgppS:bd9fuzr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f4a7306983ca3613c243a51fec70b429e85bac8d/src/helpers/map.js#L195)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Gotcha.  Is this being tracked in #310 and #311, are those the relevant issues?
</blockquote></details>

Yeah, once those are closed, this stuff will be fast.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by shanek21** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 191 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0zx40mVFnft9ujB8W9:-L0zx40mVFnft9ujB8WA:b-fk98qi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/da0896598dbdbc82b640fc8c0fa0418e3bf2f4a8/src/helpers/map.js#L191)):*
> ```JavaScript
> export function updateAndRedrawNavmesh(map, xt, yt) {
>   updateUnmergedGraph(getUnmergedGraph(), map, xt, yt);
>   // const { unfixEdges, constrainingEdges, removeVertices, addVertices } =
> ```

Can you put a comment in here saying why these things are commented?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by davidabrahams** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 191 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313#-L0zx40mVFnft9ujB8W9:-L1-f2QmPIbglAA62k75:bhsli52) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/da0896598dbdbc82b640fc8c0fa0418e3bf2f4a8/src/helpers/map.js#L191)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you put a comment in here saying why these things are commented?
</blockquote></details>

Done (I added the comment in 206)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r3.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by billmwong** [comment]
Reviewed 5 of 6 files at r4.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Comment by shanek21** [comment]
Reviewed 4 of 6 files at r4.
Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/313)*

**Pull request merged**
