### PR TITLE
378: lqr simulation

### LINKED ISSUE #378: Tagpro LQR Simulation
Simulate going from the zero vector to some goal vector

Added: going from any vector to any goal vector

### PR DESCRIPTION
**Pull request by shanek21**
Closes #378

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/387)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 6 of 12 files at r1.
Review status: 6 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[.travis.yml, line 1 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jbe_v6G-oetCRKP6V:-L8jbe_v6G-oetCRKP6W:bie1jjg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/.travis.yml#L1)):*
> ```YAML
> # Use matrix to run tests for multiple languages in parallel
> ```

ooooh fancy

---

*[.travis.yml, line 19 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jbiqw4rPf8zyCRUk1:-L8jbiqw4rPf8zyCRUk2:b-97g6op) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/.travis.yml#L19)):*
> ```YAML
>         - pip install -r requirements.txt
>       script:
>         - flake8 src/
> ```

do we also want to actually run a script?

---

*[simulation/src/animation.py, line 2 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jntH69grWHT80DJEg:-L8jntH69grWHT80DJEh:b5i6ulm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L2)):*
> ```Python
> import numpy as np
> import seaborn as sbs
> ```

i believe convention is `sns`

https://seaborn.pydata.org/tutorial/aesthetics.html#aesthetics-tutorial

---

*[simulation/src/animation.py, line 23 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jo1X53ZY5zp8EdtEf:-L8jo1X53ZY5zp8EdtEg:b-hzz1l7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L23)):*
> ```Python
> 
>         if save:
>             self.anim.save('asdf.mp4', writer='ffmpeg')
> ```

file name?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by billmwong** [comment]
Reviewed 9 of 12 files at r1.
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[simulation/README.md, line 22 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jpIn0Cjh1e17LVFY4:-L8jpIn0Cjh1e17LVFY5:b-i98o4b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/README.md#L22)):*
> ```Markdown
> $ pip install PACKAGE_NAME
> $ pip freeze > requirements.txt
> ```
> ```

can i get instructions on how to run the simulation and change parameters and any other things you think I might need to do in the future

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by shanek21** [comment]
Review status: 4 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 19 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jbiqw4rPf8zyCRUk1:-L8m8U9dDNaBRmSkBs8M:b-r0lezf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/.travis.yml#L19)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

do we also want to actually run a script?
</blockquote></details>

What would be in the script?

---

*[simulation/README.md, line 22 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jpIn0Cjh1e17LVFY4:-L8mir0v2RjaUSUKJ4QU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/README.md#L22)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can i get instructions on how to run the simulation and change parameters and any other things you think I might need to do in the future
</blockquote></details>

Done.

---

*[simulation/src/animation.py, line 2 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jntH69grWHT80DJEg:-L8mgcjU6OU_Czq4wYqR:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L2)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i believe convention is `sns`

https://seaborn.pydata.org/tutorial/aesthetics.html#aesthetics-tutorial
</blockquote></details>

Done.

---

*[simulation/src/animation.py, line 23 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jo1X53ZY5zp8EdtEf:-L8mgbrlAuho5eVwXZUQ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L23)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

file name?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 3 files at r2.
Review status: 5 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 19 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jbiqw4rPf8zyCRUk1:-L8new1D7l1TnqX3GaND:bj6j4kc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/.travis.yml#L19)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

What would be in the script?
</blockquote></details>

`python main.py` or similar?

---

*[simulation/README.md, line 31 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8ndYwV07qMmhxqT7vo:-L8ndYwV07qMmhxqT7vp:b-faq8e5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d2711ba37a283ee5fb6115399c2b37f6271cd50c/simulation/README.md#L31)):*
> ```Markdown
> ```
> 
> There are currently two types of simulations that can be run. The type of simulation that runs can be changed by editing `main.py` to execute the following functions:
> ```

FYI maybe outside scope of card, could change to have in command-line flag

https://docs.python.org/3/howto/argparse.html

---

*[simulation/media/sim_1d.gif, line 0 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8ndr4c8N5nzY-bcj8w:-L8ndr4c8N5nzY-bcj8x:b-pjl7aq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d2711ba37a283ee5fb6115399c2b37f6271cd50c/simulation/media/sim_1d.gif#L0)):*
add `no_control` to filename?

---

*[simulation/src/animation.py, line 23 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jo1X53ZY5zp8EdtEf:-L8ne2uWC7pEYcrrvsRp:b-ycq4va) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L23)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI could be a command line arg also

---

*[simulation/src/physics.py, line 9 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8neknq0q8LHvJtJInX:-L8neknq0q8LHvJtJInY:b-4rvr4s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d2711ba37a283ee5fb6115399c2b37f6271cd50c/simulation/src/physics.py#L9)):*
> ```Python
> def tagpro_simulate(x0, dur, dt):
>     """ Return a matrix of states calculated using TagPro physics """
>     if not (dur / dt).is_integer():
> ```

FYI damn python3 is neat

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by billmwong** [comment]
Reviewed 2 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by shanek21** [comment]
Review status: 6 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 19 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jbiqw4rPf8zyCRUk1:-L9BpsVL64ZFVUrZ-uEc:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/.travis.yml#L19)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

`python main.py` or similar?
</blockquote></details>

Done.

---

*[simulation/README.md, line 31 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8ndYwV07qMmhxqT7vo:-L9CRDwd3Sxy_rsHmWCT:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d2711ba37a283ee5fb6115399c2b37f6271cd50c/simulation/README.md#L31)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI maybe outside scope of card, could change to have in command-line flag

https://docs.python.org/3/howto/argparse.html
</blockquote></details>

Done.

---

*[simulation/media/sim_1d.gif, line  at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8ndr4c8N5nzY-bcj8w:-L8nkK8x90U8gaC397KO:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d2711ba37a283ee5fb6115399c2b37f6271cd50c/simulation/media/sim_1d.gif#L)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

add `no_control` to filename?
</blockquote></details>

Done.

---

*[simulation/src/controls.py, line 8 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8nhitZE4K15jZ4uWIg:-L9CRyp66sweJgh0R60M:b30vzo0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d2711ba37a283ee5fb6115399c2b37f6271cd50c/simulation/src/controls.py#L8)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

perhaps comments explaining at a high level what each other these matrices/arrays do would help understanding?
</blockquote></details>

Done. Let me know if that is good enough.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by shanek21** [comment]
Review status: 6 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[simulation/src/animation.py, line 23 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jo1X53ZY5zp8EdtEf:-L9CS3fE5bDlkaWXfqnX:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L23)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI could be a command line arg also
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 6 files at r3.
Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[simulation/media/sim_1d.gif, line  at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8ndr4c8N5nzY-bcj8w:-L9CX9y-5GMtanlLZJ-l:b-hndczq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/776c9d834bc6bd1ff382b29356d94d02c1a6c553/simulation/media/sim_1d.gif#L)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by shanek21** [comment]
Review status: 6 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[simulation/media/sim_1d.gif, line  at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8ndr4c8N5nzY-bcj8w:-L9CXcAi-IwCajxOUPAQ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/776c9d834bc6bd1ff382b29356d94d02c1a6c553/simulation/media/sim_1d.gif#L)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

not done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Review status: 5 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[simulation/src/animation.py, line 23 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jo1X53ZY5zp8EdtEf:-L9CXtFLA5q4eWZe73Ry:b-63zofk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L23)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI Not done.

---

*[simulation/src/animation.py, line 9 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CXKWA3QqK-A24KLsK:-L9CXKWBDTO0Rr87FGxw:b-tjvs7f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/fe78e58261e0080f4e611b9f5b59e97eefa74a9e/simulation/src/animation.py#L9)):*
> ```Python
> class TagProAnimation(object):
>     def __init__(self, solution, dt, goal_state=None, save=False):
>         if goal_state is None:
> ```

FYI

```
self.lqr = True
if goal_state is None:
    self.lqr = False
```

i like this version more

---

*[simulation/src/animation.py, line 18 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CXbAK6xkCNNomQGc8:-L9CXbAK6xkCNNomQGc9:b3sef09) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/fe78e58261e0080f4e611b9f5b59e97eefa74a9e/simulation/src/animation.py#L18)):*
> ```Python
>             self.control_signal = solution[1]
>         else:
>             self.states = solution
> ```

FYI This if/else and the one before could be refactored into one if/else

---

*[simulation/src/animation.py, line 24 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CXhng1tw7eWe5FS2v:-L9CXhng1tw7eWe5FS2w:b-7zbatu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ba87eda17e264d6dbbfda61edc09595d3a6700a0/simulation/src/animation.py#L24)):*
> ```Python
>         self.x, self.vx, self.y, self.vy = self.states[:, :, 0].T
>         if self.lqr:
>             self.ux, self.uy = self.control_signal[:, :, 0].T
> ```

FYI maybe here too? not sure

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 6 files at r3, 2 of 4 files at r4.
Review status: 11 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[simulation/src/controls.py, line 8 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8nhitZE4K15jZ4uWIg:-L9CY75XE5kRkvjhQUBi:bv4hcwp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/776c9d834bc6bd1ff382b29356d94d02c1a6c553/simulation/src/controls.py#L8)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done. Let me know if that is good enough.
</blockquote></details>

much better <3

---

*[simulation/src/physics.py, line 8 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CYH4L8RZ9infVY6hD:-L9CYH4L8RZ9infVY6hE:b-brh1tc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ba87eda17e264d6dbbfda61edc09595d3a6700a0/simulation/src/physics.py#L8)):*
> ```Python
> 
> def clip_accel(accel):
>     max_accel = 150
> ```

FYI return max(min(150, accel), -150)

---

*[simulation/src/physics.py, line 19 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CYNJX8ayxELm08G3W:-L9CYNJX8ayxELm08G3X:bmsh29f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ba87eda17e264d6dbbfda61edc09595d3a6700a0/simulation/src/physics.py#L19)):*
> ```Python
> def clip_vel(vel):
>     max_vel = 250
> ```

FYI here too

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by shanek21** [comment]
Review status: 4 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[simulation/src/animation.py, line 9 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CXKWA3QqK-A24KLsK:-L9CYCeD-zbTCmgUt60U:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/fe78e58261e0080f4e611b9f5b59e97eefa74a9e/simulation/src/animation.py#L9)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI

```
self.lqr = True
if goal_state is None:
    self.lqr = False
```

i like this version more
</blockquote></details>

Done.

---

*[simulation/src/physics.py, line 8 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CYH4L8RZ9infVY6hD:-L9CYvDF2wNpg1eaHyZ2:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ba87eda17e264d6dbbfda61edc09595d3a6700a0/simulation/src/physics.py#L8)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI return max(min(150, accel), -150)
</blockquote></details>

Done.

---

*[simulation/src/physics.py, line 19 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L9CYNJX8ayxELm08G3W:-L9CYvqg4cIfEJ-WFAxm:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ba87eda17e264d6dbbfda61edc09595d3a6700a0/simulation/src/physics.py#L19)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI here too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by shanek21** [comment]
Review status: 4 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[simulation/src/animation.py, line 23 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387#-L8jo1X53ZY5zp8EdtEf:-L9CZ52L2p6Q2GmqfMz5:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ec725ede53c0acdd500469c85274f296a1b9cd1e/simulation/src/animation.py#L23)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI Not done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Comment by billmwong** [comment]
Reviewed 4 of 6 files at r3, 2 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/387)*

**Pull request merged**
