### PR TITLE
336: add KEY_INDICES object for use in draw/keys.js

### LINKED ISSUE #336: Make a KEY_INDICES object for use in draw/keys.js
instead of the leftKeyIndex, etc.

### PR DESCRIPTION
**Pull request by shanek21**
Closes #336

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/357)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/357)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/draw/keys.js, line 18 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/357#-L6YP1WLPJxh7WC216vx:-L6YP1WM7eJEDfAjMGJo:b-75nq8l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2fbde9b6ec2660483118e2b5b8bbb01e3635f211/src/draw/keys.js#L18)):*
> ```JavaScript
> };
> const keySize = 30; // side length of keys in pixels
> const keyGap = 4; // gap between keys in pixels
> ```

make these two consts all caps as per discussion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/357)*

**Comment by shanek21** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/draw/keys.js, line 18 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/357#-L6YP1WLPJxh7WC216vx:-L6YPUEt2rvryXkSOBuz:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2fbde9b6ec2660483118e2b5b8bbb01e3635f211/src/draw/keys.js#L18)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

make these two consts all caps as per discussion
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/357)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/357)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/357)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/357)*

**Pull request merged**
