### PR TITLE
249: Find and navigate to interception point with just distance

### LINKED ISSUE #249: Find and navigate to interception point with just distance
Inception point = The first place along their path that you get to before they do

Figure out if using distance is useful

### PR DESCRIPTION
**Pull request by shanek21**
Closes #249

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/306)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 5 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/fsm.js, line 10 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306#-L0X30ChNok8BXVBTeXK:-L0X30ChNok8BXVBTeXL:blmoaku) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7810b98357197e693573899b97b55313ec702e27/src/helpers/fsm.js#L10)):*
> ```JavaScript
> 
> 
> // eslint-disable-next-line import/prefer-default-export
> ```

i believe this is disabled in our RC. if its not, can you add it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306)*

**Comment by shanek21** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/fsm.js, line 10 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306#-L0X30ChNok8BXVBTeXK:-L0XAld0wCx6xLhNcumu:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8534eaf12dbb610dec5b8baffc4b1690ce2ac253/src/helpers/fsm.js#L10)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i believe this is disabled in our RC. if its not, can you add it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r2.
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306)*

**Comment by billmwong** [comment]
Reviewed 4 of 5 files at r1, 3 of 3 files at r2.
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306#-L0fHBGYGO4SeiQJ8NUc:-L0fHBGYGO4SeiQJ8NUd:b-b1wftg) (no related file):*
Dango from me, just rename PR title to issue name pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306#-L0fHBGYGO4SeiQJ8NUc:-L0ztbOc1gE0eKVwYDdw:b-896fix) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Dango from me, just rename PR title to issue name pls
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/306)*

**Pull request merged**
