### PR TITLE
76: Fixing Max-len errors

### LINKED ISSUE #76: Eslint does not produce errors when making lines >100 characters
I thought this was the javascript convention, and seems to be the airbnb rule [here](https://github.com/airbnb/javascript/pull/510/files)

### PR DESCRIPTION
**Pull request by billmwong**
Closes #76

The airbnb config was ignoring strings and some other stuff for the max-len rule.  Now we don't ignore anything anymore, so all lines have to be 100 chars

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/163)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/drawings.spec.js, line 198 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsUNxi6ZuEqW35UW8Q-:-KsUNxi7MF8gOqFqUhak:b-zahll6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/371d46a9f81f6d1b3fab86834df10e0bd9969bbf/test/drawings.spec.js#L198)):*
> ```JavaScript
>     t.end();
>   });
>   tester.end();
> ```

This was just left off before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by billmwong** [comment]
*[test/drawings.spec.js, line 198 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsUNxi6ZuEqW35UW8Q-:-KsUOOHR-tM3dbjW6Giw:bydey6z) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/371d46a9f81f6d1b3fab86834df10e0bd9969bbf/test/drawings.spec.js#L198)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

This was just left off before?
</blockquote></details>

Haha yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.eslintrc, line 13 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsX7oCkl-Si1DVFp9uP:-KsX7oClbfb797-EimDA:b-g8363b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4f9938b358a17932a68e732073858fd8ae0dcbcc/.eslintrc#L13)):*
> ```
>     "arrow-parens": ["error", "as-needed"],
>     "no-underscore-dangle": "off",
>     "max-len": ["error", 100, 2],
> ```

What's the 2? Just curious

---

*[test/drawings.spec.js, line 198 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsX7vW1wcKR3VExqZRe:-KsX7vW1wcKR3VExqZRf:b-9nbii5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4f9938b358a17932a68e732073858fd8ae0dcbcc/test/drawings.spec.js#L198)):*
> ```JavaScript
>     t.end();
>   });
>   tester.end();
> ```

Did I somehow forget this? Youch

---

*[test/map.spec.js, line 106 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsX83DK81UHP1fjCLOr:-KsX83DK81UHP1fjCLOs:b-rs4fr5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4f9938b358a17932a68e732073858fd8ae0dcbcc/test/map.spec.js#L106)):*
> ```JavaScript
> 
> test('getTileTraversabilityInCells() ', tester => {
>   tester.test('returns correctly with entirely traversable tile, CPTL=1', t => {
> ```

Aw so dank and nested. Here, have a :dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.eslintrc, line 13 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsX7oCkl-Si1DVFp9uP:-KsXQVQvFZNhjJ5QmSwU:brbwjj8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4f9938b358a17932a68e732073858fd8ae0dcbcc/.eslintrc#L13)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

What's the 2? Just curious
</blockquote></details>

tab size. we tab with 2 spaces.  Idk how it actually affects the rule but airbnb had it in there

---

*[test/drawings.spec.js, line 198 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-KsX7vW1wcKR3VExqZRe:-KsXQeuUblIWcgINS6l0:b-vmi53x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4f9938b358a17932a68e732073858fd8ae0dcbcc/test/drawings.spec.js#L198)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Did I somehow forget this? Youch
</blockquote></details>

Yup haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by shanek21** [comment]
IS THAT A MERGE COMMIT

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-:-KsYflqgj0R2ChOjBTFH:bx4s1ie)*

**Comment by davidabrahams** [comment]
GET THAT SHIT OUT OF HERE

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-:-KsZHcpyQGhQ5AqgPDdt:bfmqkwh)*

**Comment by billmwong** [comment]
fixed

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-:-KsZek1Ih1b64Xbo7rNU:b-7ql1td)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by shanek21** [comment]
WHAT IS THIS

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-:-Ks_ay3EWFdCEbFQGTT7:behrk71)*

**Comment by billmwong** [comment]
Alright i fixed it calm down

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-:-Ks_bCPyyT37nLKxzcE1:b3i1vc5)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by billmwong** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163)*

**Comment by shanek21** [comment]
whew

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/163#-:-Ks_cBlhMh4PGa0a6ATE:bb7r1zc)*

**Pull request merged**
