### PR TITLE
154: visualize keypresses

### LINKED ISSUE #154: Create a visualization of what arrow keys are being pressed at any one time
Wouldn't it be cool if there we a semi-transparent set of arrow keys in the bottom corner of the screen and whenever the bot was pressing a key it turned red or more opaque or something?

### PR DESCRIPTION
**Pull request by shanek21**
Closes #154

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/221)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 6 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 109 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviH2G6B3ZFVl7OUcn7:-KviH2G6B3ZFVl7OUcn8:bnczgvg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L109)):*
> ```JavaScript
>     updateUi();
>     centerKeyPressesVis();
>   };
> ```

What do you think about exporting `centerKeyPressesVis()` and then doing this logic in index.js?

---

*[src/draw/drawings.js, line 117 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviIxoW0wEWNmUmomrX:-KviIxoW0wEWNmUmomrY:b-fbu42j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L117)):*
> ```JavaScript
>  */
> export function initKeyPressesVisualization() {
>   tagpro.ui.sprites.keyPressesVis = new PIXI.DisplayObjectContainer();
> ```

Make this a root-level const instead of storing it in the tagpro object?

---

*[src/draw/drawings.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviJwPglb7bkNUTLyY9:-KviJwPglb7bkNUTLyYA:b75jh29) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L120)):*
> ```JavaScript
>   tagpro.renderer.layers.ui.addChild(tagpro.ui.sprites.keyPressesVis);
>   tagpro.ui.sprites.keyPressesVis.addChildAt(
>     getPixiSquare((1.5 * -keySize) - keyGap, 0, keySize, keyOffAlpha, keyColor),
> ```

david what do you think about `(-1.5 * keySize)` vs. `(1.5 * -keySize)`, I've thought about it and I can't tell which is more understandable

---

*[src/draw/drawings.js, line 145 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviN9QYN8ITZwMbf27N:-KviN9QYN8ITZwMbf27O:b-x8vly0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L145)):*
> ```JavaScript
>  * @param {(string|undefined)} directions.y - either 'DOWN', 'UP', or undefined
>  */
> export function drawKeyPresses(directions) {
> ```

test this function pls

---

*[src/draw/drawings.js, line 167 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviKbWgN8VS_S5VD5RH:-KviKbWgN8VS_S5VD5RI:b-l2c5s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L167)):*
> ```JavaScript
>       getPixiSquare((1.5 * -keySize) - keyGap, 0, keySize, leftAlpha, keyColor),
>       leftKeyIndex,
>     );
> ```

there's a bit of repeated code with the removeChildAt addChildAt logic, could we have some sort of updateKeyDrawing() function that takes in a key index (0,1,2,3) and a boolean on|off? 

---

*[src/utils/interface.js, line 14 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviMB5VB3aOwm1s-uk-:-KviMB5VB3aOwm1s-uk0:bltojl1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L14)):*
> ```JavaScript
>   UP: 38,
>   RIGHT: 39,
>   DOWN: 40,
> ```

Why did you add these? I don't see where you use them...

---

*[src/utils/interface.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviPZORsGI5Gw3Ft8In:-KviPZORsGI5Gw3Ft8Io:bbr4emy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L92)):*
> ```JavaScript
>  */
> function press(directions) {
>   switch (directions.x) {
> ```

now that we store the current keypresses, can you put an if statement on both of these to only do these if the current keypress has changed in each direction?

---

*[src/utils/interface.js, line 142 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviLlzMaHd5xsoOlrIL:-KviLlzMaHd5xsoOlrIM:b-mmdo57) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L142)):*
> ```JavaScript
>     case KEY_CODES.Q: {
>       autonomous = !autonomous;
>       press({ x: undefined, y: undefined }); // Release all keys
> ```

This is functionally the same, did you add this because it seems more readable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[.eslintrc, line 5 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2XPTiVfn9Vvo6xT-Q:-Kw2XPTiVfn9Vvo6xT-R:br1jafv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/.eslintrc#L5)):*
> ```
>   "env": {
>     "browser": true,
>     "jquery": true,
> ```

i missed the discussion on this...why do we need this?

---

*[src/draw/drawings.js, line 37 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2V5hZgiIvXmsk2dGI:-Kw2V5hZgiIvXmsk2dGJ:b-82w47i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L37)):*
> ```JavaScript
> 
> // The current state of the keys being pressed
> export const currKeyPresses = { x: undefined, y: undefined };
> ```

I believe you can just make this empty object, if all its fields a undefined. (Or, perhaps better, initialize them to `null`, which is the "explicit" nothing value, as opposed to undefined, which is the "accidental" nothing value

---

*[src/draw/drawings.js, line 100 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2VXcCahAtekel9695:-Kw2VXcCahAtekel9696:b-qwrqkt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L100)):*
> ```JavaScript
> /*
>  * The tagpro object has a function that is called every time the user interface needs to be
>  * updated (this function is defined at tagpro.ui.update). We have made additions to the UI that now
> ```

Should we have been using this the entire time? (like, for all our other drawings). Or is this just for things that sit on the UI layer?

---

*[src/draw/drawings.js, line 109 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviH2G6B3ZFVl7OUcn7:-Kw2Vr4ZTiLys1r9-Tdh:b-jrijhy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L109)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

What do you think about exporting `centerKeyPressesVis()` and then doing this logic in index.js?
</blockquote></details>

FYI either way works for me

---

*[src/draw/drawings.js, line 117 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviIxoW0wEWNmUmomrX:-Kw2VwjYnsloho8aZrIb:b-m7wzcd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L117)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Make this a root-level const instead of storing it in the tagpro object?
</blockquote></details>

FYI Storing in the object may be convention (though honestly nobody writes bots, so we can probably define our own convention)

---

*[src/draw/drawings.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviJwPglb7bkNUTLyY9:-Kw2W5WDnZGdrgPEar6E:b-5av4na) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L120)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

david what do you think about `(-1.5 * keySize)` vs. `(1.5 * -keySize)`, I've thought about it and I can't tell which is more understandable
</blockquote></details>

I would factor out the negative and do - (1.5 * keySize) - keyGap

---

*[src/draw/drawings.js, line 149 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2WUA0lfJSF1L9qCo9:-Kw2WUA0lfJSF1L9qCoA:b-43t4ol) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L149)):*
> ```JavaScript
>     let leftAlpha;
>     let rightAlpha;
>     switch (directions.x) {
> ```

I believe these 12ish lines could be two ternary operation lines (I'd prefer it this way). You also then can make them const, instead of let

---

*[src/draw/drawings.js, line 174 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2WfrPuelHQbT4oh6I:-Kw2WfrPuelHQbT4oh6J:b-iph1ew) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L174)):*
> ```JavaScript
>     );
>   }
>   if (directions.y !== currKeyPresses.y) {
> ```

Ditto here. ternaries for shortness

---

*[src/utils/interface.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviPZORsGI5Gw3Ft8In:-Kw2Xb2jOb9j-gnPPFuO:bkfx5xc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L92)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

now that we store the current keypresses, can you put an if statement on both of these to only do these if the current keypress has changed in each direction?
</blockquote></details>

Ooooooh. Good idea. (not sure if it changes anything functionally, but definitely clever.)

---

*[src/utils/interface.js, line 142 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviLlzMaHd5xsoOlrIL:-Kw2WuYPH9wx5dXwY2_D:bv6ljco) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L142)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

This is functionally the same, did you add this because it seems more readable?
</blockquote></details>

I had a comment about this earlier. Not sure what the better way to do it is. (I'm fine with either)

---

*[test/draw/drawings.spec.js, line 253 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2XKUz85UocxNQHWbL:-Kw2XKUz85UocxNQHWbM:b-927xxl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/test/draw/drawings.spec.js#L253)):*
> ```JavaScript
>     DrawRewireAPI.__ResetDependency__('CPTL');
>     DrawRewireAPI.__ResetDependency__('PPCL');
>     DrawRewireAPI.__ResetDependency__('getPixiSquare');
> ```

NO MOAR RECT

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[src/draw/drawings.js, line 145 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2fssVRtrrH7MNbGx8:-Kw2fssVRtrrH7MNbGx9:b-8k7p5b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L145)):*
> ```JavaScript
>  * @param {(string|undefined)} directions.y - either 'DOWN', 'UP', or undefined
>  */
> export function drawKeyPresses(directions) {
> ```

FYI I dont think a test is necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[.eslintrc, line 5 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2XPTiVfn9Vvo6xT-Q:-Kw2p24T1_in4lE39RgV:b-4gijrk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/.eslintrc#L5)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i missed the discussion on this...why do we need this?
</blockquote></details>

We now use jquery on one line of code to grab the size of the user's current screen so that we can place the arrow keys in the center and have them dynamically replace themselves if the user scales their window size.

---

*[src/draw/drawings.js, line 37 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2V5hZgiIvXmsk2dGI:-Kw2pqJviLI5a9pp9vnu:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L37)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I believe you can just make this empty object, if all its fields a undefined. (Or, perhaps better, initialize them to `null`, which is the "explicit" nothing value, as opposed to undefined, which is the "accidental" nothing value
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 100 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2VXcCahAtekel9695:-Kw2ptYYIesCuZnL0ZWI:b-p5lved) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L100)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Should we have been using this the entire time? (like, for all our other drawings). Or is this just for things that sit on the UI layer?
</blockquote></details>

Just the UI layer.

---

*[src/draw/drawings.js, line 109 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviH2G6B3ZFVl7OUcn7:-Kw2qd93rs-hZHMQV3WD:b2kyog2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L109)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI either way works for me
</blockquote></details>

We discussed offline that the UI update process is only relevant for drawings, and can therefore remain in the drawings file.

---

*[src/draw/drawings.js, line 117 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviIxoW0wEWNmUmomrX:-Kw2snxLQBZ-I2zISb1q:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L117)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI Storing in the object may be convention (though honestly nobody writes bots, so we can probably define our own convention)
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviJwPglb7bkNUTLyY9:-Kw2t-az1y_c-t5Jhzvs:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L120)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I would factor out the negative and do - (1.5 * keySize) - keyGap
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 145 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviN9QYN8ITZwMbf27N:-Kw32bZArm4t8UhxHAW2:b-ckxb4v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L145)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

test this function pls
</blockquote></details>

Decided not to test

---

*[src/draw/drawings.js, line 149 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2WUA0lfJSF1L9qCo9:-Kw2ury0u5Hf7ROB_qGp:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L149)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I believe these 12ish lines could be two ternary operation lines (I'd prefer it this way). You also then can make them const, instead of let
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 167 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviKbWgN8VS_S5VD5RH:-Kw3-8DbSiSN0795yrch:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L167)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

there's a bit of repeated code with the removeChildAt addChildAt logic, could we have some sort of updateKeyDrawing() function that takes in a key index (0,1,2,3) and a boolean on|off? 
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 174 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2WfrPuelHQbT4oh6I:-Kw2uvmj8UqklmtpaYW6:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L174)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Ditto here. ternaries for shortness
</blockquote></details>

Done.

---

*[src/utils/interface.js, line 14 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviMB5VB3aOwm1s-uk-:-Kw3-LSAs6Ht7TAU3BlE:b-ux52xp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L14)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Why did you add these? I don't see where you use them...
</blockquote></details>

Forgot to remove them.

---

*[src/utils/interface.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviPZORsGI5Gw3Ft8In:-Kw32ep10RweSOMcJRND:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L92)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Ooooooh. Good idea. (not sure if it changes anything functionally, but definitely clever.)
</blockquote></details>

Done.

---

*[src/utils/interface.js, line 142 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviLlzMaHd5xsoOlrIL:-KviU5Dey3CmbSKVlH4I:b-cezh8r) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L142)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

This is functionally the same, did you add this because it seems more readable?
</blockquote></details>

I do think it is more readable, but also it gave me errors when I didn't have this. Something like `can't get x from undefined`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by shanek21** [comment]
Review status: 4 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/draw/drawings.js, line 145 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2fssVRtrrH7MNbGx8:-Kw331SLlASSXYZkcbOP:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L145)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI I dont think a test is necessary
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/draw/drawings.js, line 149 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2WUA0lfJSF1L9qCo9:-Kw3Bca8cctmlBL1qQ_q:bpbkas6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L149)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh man so nice :sparkles: 

---

*[src/draw/drawings.js, line 167 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviKbWgN8VS_S5VD5RH:-Kw3C8P0HE124b4wB9jt:bhlci0p) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L167)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Love it! What do you think of passing in a boolean instead of an explicit alpha value?  Then this can literally just be `updateKeyDrawing(leftKeyIndex, directions.x === 'LEFT');`

---

*[src/utils/interface.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviPZORsGI5Gw3Ft8In:-Kw3DB0JyB27HIBOTr2Q:bbvrtal) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L92)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh wow this code is so nice love it :dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by davidabrahams** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[.eslintrc, line 5 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw2XPTiVfn9Vvo6xT-Q:-Kw3rCtXkN-4mO7_o_Ld:b-5b5ly0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/.eslintrc#L5)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

We now use jquery on one line of code to grab the size of the user's current screen so that we can place the arrow keys in the center and have them dynamically replace themselves if the user scales their window size.
</blockquote></details>

FYI Oh that’s pretty :dango: 

---

*[src/draw/drawings.js, line 167 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviKbWgN8VS_S5VD5RH:-Kw3rtF9nrFQNJ49Mvw4:bokcko5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L167)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Love it! What do you think of passing in a boolean instead of an explicit alpha value?  Then this can literally just be `updateKeyDrawing(leftKeyIndex, directions.x === 'LEFT');`
</blockquote></details>

FYI I actually prefer it the way it is right now. I can’t think of a great reason, it just feels nicer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/utils/interface.js, line 142 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw3sX5pX3b8JYP_tMrI:-Kw3sX5pX3b8JYP_tMrJ:b-7bhjf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L142)):*
> ```JavaScript
>     case KEY_CODES.Q: {
>       autonomous = !autonomous;
>       press({ x: undefined, y: undefined }); // Release all keys
> ```

If we want to explicitly set them to falsey, I prefer set them to null. For null checking, use https://lodash.com/docs/4.17.4#isNil

Side note: can you make sure there's no bugs from changing undefineds to nulls in this PR? Like if we ever do `var === undefined`, and its `null` instead, this will end up being false (which is why I like `isNil`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 167 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-KviKbWgN8VS_S5VD5RH:-Kw5lMpY3ePcNFL6wX9Y:b-wwzc9z) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/draw/drawings.js#L167)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI I actually prefer it the way it is right now. I can’t think of a great reason, it just feels nicer.
</blockquote></details>

I considered both options and chose to write it this way. Bill, how strongly do you feel? I could possibly be convinced.

---

*[src/utils/interface.js, line 142 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw3sX5pX3b8JYP_tMrI:-Kw5koOmbvIG2UNulKc_:b-7cdrmn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L142)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

If we want to explicitly set them to falsey, I prefer set them to null. For null checking, use https://lodash.com/docs/4.17.4#isNil

Side note: can you make sure there's no bugs from changing undefineds to nulls in this PR? Like if we ever do `var === undefined`, and its `null` instead, this will end up being false (which is why I like `isNil`)
</blockquote></details>

In the key pressing code, we never check for `undefined` explicitly. We check if things are `LEFT` or `RIGHT` else do the default case. In that case the `undefined` or `null` wouldn't make a difference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/utils/interface.js, line 142 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221#-Kw3sX5pX3b8JYP_tMrI:-Kw680rt0jMoa32sMTvx:b9d4o99) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4e0adf06e1d8dc2f0909d379c35d283ab2c825b1/src/utils/interface.js#L142)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

In the key pressing code, we never check for `undefined` explicitly. We check if things are `LEFT` or `RIGHT` else do the default case. In that case the `undefined` or `null` wouldn't make a difference.
</blockquote></details>

FYI Awesome!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/221)*

**Pull request merged**
