### PR TITLE
300: Implement Funnel Clearance Algorithm

### LINKED ISSUE #300: Implement Funnel Clearance Algorithm

### PR DESCRIPTION
**Pull request by billmwong**
Closes #300

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/305)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 6 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graphUtils.js, line 103 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305#-L0WISq1ERwxprLlhDcH:-L0WISq2AasgeS8tlrjW:b40s2px) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/43ad81b8a0d272773d582421b8602b5a931f862a/src/navmesh/graphUtils.js#L103)):*
> ```JavaScript
> 
>   // Insert other point to path
>   // return cornerPoint.add(normal.times(Math.sqrt(2)));
> ```

Remove commented-out code

---

*[test/helpers/physics.spec.js, line 9 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305#-L0WKWVdByQDGTf_WS-P:-L0WKWVeJ4z3Co1koJn-:b550rj6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/33a1f48f28efd457ff9ff31306cc5b74628bc7bb/test/helpers/physics.spec.js#L9)):*
> ```JavaScript
> 
> 
> export function isRoughly(val, expected, threshold = 0.01) {
> ```

Can we move this function to a general `utils.js` file? Or something like that...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graphUtils.js, line 103 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305#-L0WISq1ERwxprLlhDcH:-L0X2eupexAke8cSxkqH:bb6un1j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/43ad81b8a0d272773d582421b8602b5a931f862a/src/navmesh/graphUtils.js#L103)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Remove commented-out code
</blockquote></details>

Done

---

*[test/helpers/physics.spec.js, line 9 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305#-L0WKWVdByQDGTf_WS-P:-L0X2U9irdYIBNI9_dx5:bb6un1j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/33a1f48f28efd457ff9ff31306cc5b74628bc7bb/test/helpers/physics.spec.js#L9)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can we move this function to a general `utils.js` file? Or something like that...
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 4 files at r3.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 4 files at r3.
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r3.
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/helpers/physics.spec.js, line 9 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305#-L0WKWVdByQDGTf_WS-P:-L0X3IXEzn0mWJIO08A5:bk8mugg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/33a1f48f28efd457ff9ff31306cc5b74628bc7bb/test/helpers/physics.spec.js#L9)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done
</blockquote></details>

Can we call it `general.js` or `generic.js` or something like that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/helpers/physics.spec.js, line 9 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305#-L0WKWVdByQDGTf_WS-P:-L0X47r0sVuH37o8fhPa:bb6un1j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/33a1f48f28efd457ff9ff31306cc5b74628bc7bb/test/helpers/physics.spec.js#L9)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can we call it `general.js` or `generic.js` or something like that?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by shanek21** [comment]
Reviewed 2 of 4 files at r4.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by shanek21** [comment]
Reviewed 2 of 4 files at r4.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r4.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/305)*

**Pull request merged**
