### PR TITLE
264: change equal to equals

### LINKED ISSUE #264: Change all "equal" to "equals"
We should just use `equals`

We mix and match `equal` and `equals` to mean the same thing

### PR DESCRIPTION
**Pull request by shanek21**
Close #264

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/325)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 5 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/325)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/325#-L3j3x7phSkZPui94lpU:-L3j3x7phSkZPui94lpV:bxlmcwd) (no related file):*
Should this go before or after #206 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/325)*

**Comment by shanek21** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/325#-L3j3x7phSkZPui94lpU:-L3j8t7FAXOaEmh8TQxb:bb77ufx) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Should this go before or after #206 
</blockquote></details>

Yes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/325)*

**Comment by billmwong** [comment]
Reviewed 5 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/325)*

**Pull request merged**
