### PR TITLE
143: changing input to setupTiles to a team color int

### LINKED ISSUE #143: Change `setupTiles` in test/tiles.spec.js to take a team color as a parameter
Right now it takes in a boolean `myColorIsBlue`. I think it would be more self-documenting if it took in a parameter `myTeamColor` which what either `teams.Red` or `teams.Blue`.

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #143

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/152)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/tiles.spec.js, line 26 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152#-KsRcpVYRUw91VCNzBLY:-KsRcpVYRUw91VCNzBLZ:bb8qizt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b0dabbc2b2b2b4ac433e70364f2813a1ab6affab/test/tiles.spec.js#L26)):*
> ```JavaScript
> export function setupTiles(teamColor) {
>   assert(_.includes([teams.RED, teams.BLUE], teamColor), `${teamColor} is not a team color`);
>   const myColorIsBlue = teamColor === teams.BLUE;
> ```

nitpick: what do you think of putting this logic inline below instead of storing a var?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/tiles.spec.js, line 26 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152#-KsRcpVYRUw91VCNzBLY:-KsSA7mmhJqUzeV6RkVf:b-7zwyc9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b0dabbc2b2b2b4ac433e70364f2813a1ab6affab/test/tiles.spec.js#L26)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

nitpick: what do you think of putting this logic inline below instead of storing a var?
</blockquote></details>

It shows up multiple times, so I think having it in a variable is cleaner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/tiles.spec.js, line 26 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152#-KsRcpVYRUw91VCNzBLY:-KsU1mygMPFSKaPwxZGh:bq42c7m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b0dabbc2b2b2b4ac433e70364f2813a1ab6affab/test/tiles.spec.js#L26)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

It shows up multiple times, so I think having it in a variable is cleaner?
</blockquote></details>

It shows up twice and one of the times is to say "not myColorIsBlue", but I'm setting this as "satisfied" cause I trust your judgement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/tiles.spec.js, line 22 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152#-KsUURRLjjPUTx3o6Qky:-KsUURRMVe-rezeMORxg:b2rxtha) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1cc4cf14f677f0f0ae77307eb7ca59ceb068d279/test/tiles.spec.js#L22)):*
> ```JavaScript
> 
> /*
>  * @param {number} teamColor 1 for red, 2 for blue
> ```

Shouldn't this have a `-`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by davidabrahams** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/tiles.spec.js, line 26 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152#-KsRcpVYRUw91VCNzBLY:-KsVbW4015nCwcDqYJX8:b-qvm8yk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b0dabbc2b2b2b4ac433e70364f2813a1ab6affab/test/tiles.spec.js#L26)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

It shows up twice and one of the times is to say "not myColorIsBlue", but I'm setting this as "satisfied" cause I trust your judgement
</blockquote></details>

Good point. Ended up going with your implementation. It's more readable.

---

*[test/tiles.spec.js, line 22 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152#-KsUURRLjjPUTx3o6Qky:-KsVbSBC3W9LGTopJSO5:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1cc4cf14f677f0f0ae77307eb7ca59ceb068d279/test/tiles.spec.js#L22)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Shouldn't this have a `-`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/152)*

**Pull request merged**
