### PR TITLE
511: fix filter in reviewable config to list resolved dispositions

### LINKED ISSUE #511: reviewable config won't let us merge PRs

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #511

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/512)

### CODE REVIEW

**Review by billmwong — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/512)* status: shanek21 must review 1 file, altodyte must review 1 file (waiting on @shanekelly)

**Review by billmwong — APPROVED** [review]
:dango: :dango: 

> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/512#-:-LcZ_aov300nO6dMPvAd:bdd6633)* status: shanek21 must review 1 file, altodyte must review 1 file (waiting on @shanekelly)

**Review by billmwong — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/512)* status: shanek21 must review 1 file, altodyte must review 1 file (waiting on @shanekelly)

**Review by PrimePalaver — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/512)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
