### PR TITLE
31: Add path planning functionality when CPTL>1

### LINKED ISSUE #31: Calculate path using >1 cpt

### PR DESCRIPTION
**Pull request by shanek21**
Closes #31 

http://i.imgur.com/oR8crxH.gifv

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/121)

### CODE REVIEW

**Comment by davidabrahams** [comment]
With high CPT, we should turn `diagonal` on in A*. Also, is applying convolution a future feature?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-:-KrMuwZAhPiAjkq1jrGT:blnbfy2)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bot.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrMvGCwDzRa7oaK_X_h:-KrMvGCwDzRa7oaK_X_i:b6rw88i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/181cc0436ad98e67708869efcd5f5c1840395a87/src/bot.js#L1)):*
> ```JavaScript
> import { PPCL } from './constants';
> ```

Maybe I screwed up and shouldn't leave a top level comment? I want to set my disposition to not OK until my top level comment is resolved, so I'm leaving this here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by shanek21** [comment]
It is a future feature. I added an issue.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-:-KrOI3IooXyLB_xgtDKJ:bl97kg1)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bot.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrMvGCwDzRa7oaK_X_h:-KrOKCIIUAXddDM-a6tH:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/181cc0436ad98e67708869efcd5f5c1840395a87/src/bot.js#L1)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Maybe I screwed up and shouldn't leave a top level comment? I want to set my disposition to not OK until my top level comment is resolved, so I'm leaving this here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by davidabrahams** [comment]
Reviewed 8 of 9 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/helpers/finders.js, line 23 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrUg6awm3Ll-7H5y3RN:-KrUg6awm3Ll-7H5y3RO:bseimy7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/54df1e91ab5a0821ed2df591acd30e5a114f9e32/src/helpers/finders.js#L23)):*
> ```JavaScript
>  * Returns the position (in pixels) of the endzone you should defend
>  *
>  * @return {object} - object with the endzone's position in pixels, x and y, and
> ```

I believe convention is to capitalize Object? We capitalize String elsewhere.

---

*[src/helpers/path.js, line 17 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrUgaRGV-aTZB_dpNbl:-KrUgaRGV-aTZB_dpNbm:b-i4knnj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/54df1e91ab5a0821ed2df591acd30e5a114f9e32/src/helpers/path.js#L17)):*
> ```JavaScript
>   // diagonal is true if we consider diagonal steps on the grid
> 
>   assertGridInBounds(grid, me.xc, me.yc);
> ```

FYI I like this. Nice and concise

---

*[src/helpers/path.js, line 51 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrUgh0EqCm9eLfR-7ZO:-KrUgh0EqCm9eLfR-7ZP:b-o3ddsw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/54df1e91ab5a0821ed2df591acd30e5a114f9e32/src/helpers/path.js#L51)):*
> ```JavaScript
>       yc: shortestPath[0].yc - me.yc,
>     };
>     const nDiff = {};
> ```

Ugh this code is so gross. Can't wait till it's readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by shanek21** [comment]
*[src/helpers/path.js, line 17 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrUgaRGV-aTZB_dpNbl:-KrVXVJyOBdyHyHK8JRS:bdo5w9q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/54df1e91ab5a0821ed2df591acd30e5a114f9e32/src/helpers/path.js#L17)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI I like this. Nice and concise
</blockquote></details>

You made this a blocking comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by shanek21** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/helpers/finders.js, line 23 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-KrUg6awm3Ll-7H5y3RN:-KrVZzXcfIwg0LY4ZwVv:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/54df1e91ab5a0821ed2df591acd30e5a114f9e32/src/helpers/finders.js#L23)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I believe convention is to capitalize Object? We capitalize String elsewhere.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 9 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by altodyte** [comment]
Reviewed 3 of 9 files at r2, 3 of 4 files at r3.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by davidabrahams** [comment]
You have to rebase now that I finished 112, but other than that, this looks :dango:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-:-KreEEBKSl5PbbBwAEbX:b-w5r059)*

**Comment by shanek21** [comment]
Rebased and functional! Ready for final review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121#-:-KrrSC-1x7tNyt41MFiF:b-4oogfs)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Comment by billmwong** [comment]
Reviewed 3 of 9 files at r2, 2 of 4 files at r3, 3 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/121)*

**Pull request merged**
