### PR TITLE
370: add chat callback with framework that parses for keywords

### LINKED ISSUE #370: Inter-Bot Communication
Read/Write to the team chat so that bots can communicate with each other

- Have some sort of API
- Read key words in the beginning of a team chat message

### PR DESCRIPTION
**Pull request by shanek21**
Closes #370

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/381)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/interface/chat.js, line 61 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381#-L7V_rJsNDqNxzFA4p2g:-L7V_rJsNDqNxzFA4p2h:b-o3h88h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L61)):*
> ```JavaScript
>  * @param {boolean} chatData.mod - whether or not the sender of the message is a mod
>  */
> export function parseChat(chatData) {
> ```

don't need to export i don't think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interface/chat.js, line 59 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381#-L7VcV9DXef4gveGRP30:-L7VcV9DXef4gveGRP31:b-lga56s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L59)):*
> ```JavaScript
>  * @param {string} chatData.c - the hex representation of the color to change the text to (for
>  *   example for flair awards)
>  * @param {boolean} chatData.mod - whether or not the sender of the message is a mod
> ```

`true if the sender is a mod`?

---

*[src/interface/chat.js, line 65 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381#-L7VdVEeTKTXVqT-d0F8:-L7VdVEeTKTXVqT-d0F9:b-ly1v0t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L65)):*
> ```JavaScript
>   if (msg.indexOf(' ') === -1) return; // no space found
> 
>   const firstWord = msg.substr(0, msg.indexOf(' ') + 1);
> ```

could use `string.split` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interface/chat.js, line 59 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/381#-L7VcV9DXef4gveGRP30:-L7VjF635HMoWhYZDaZ5:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L59)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

`true if the sender is a mod`?
</blockquote></details>

Done.

---

*[src/interface/chat.js, line 61 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/381#-L7V_rJsNDqNxzFA4p2g:-L7Vk-i_9o6pObI5QjMv:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L61)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

don't need to export i don't think
</blockquote></details>

Done.

---

*[src/interface/chat.js, line 65 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/381#-L7VdVEeTKTXVqT-d0F8:-L7Vk05D7gQI3csc6hoQ:b-z635w7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L65)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

could use `string.split` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split
</blockquote></details>

Done. I also got rid of the error checking, because there may be a case where we actually want to send a message that only contains the keyword and nothing else.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/381)*

**Comment by billmwong** [comment]
:dango:

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381#-:-L7Vl6fMTXqbs4flQbFe:bcbqss6)*

**Comment by davidabrahams** [comment]
:dango:

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/interface/chat.js, line 65 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381#-L7VdVEeTKTXVqT-d0F8:-L7Vl8OzvSgQCMTSZc0q:b5cor6f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bccce040d0f46fbca8fb7692a6b843a04adcd697/src/interface/chat.js#L65)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done. I also got rid of the error checking, because there may be a case where we actually want to send a message that only contains the keyword and nothing else.
</blockquote></details>

Neato. Just confirmed split() still works if the delimiter isnt in the string :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/381#-:-L7VlEQE7v9bonvBiXPZ:bcbqss6)*

**Pull request merged**
