### PR TITLE
218: Make Drawing API for Edges

### LINKED ISSUE #218: Make Drawing API for Edges

### PR DESCRIPTION
**Pull request by billmwong**
Closes #218 

PR into david's branch for review

screenshot from 2017-10-16 14 56 37

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/220)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/draw/drawings.js, line 179 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOUoTOielxt1G-9R2:-KvgOUoTOielxt1G-9R3:bfbbbtw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L179)):*
> ```JavaScript
>  * Runtime: O(E)
>  *
>  * @param {Graph} graph - graph to draw
> ```

Would you not put `@param {Object}` and then specify some properties of a graph?

---

*[src/draw/drawings.js, line 184 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOdSDPuRdvrLSV_qK:-KvgOdSDPuRdvrLSV_qL:b4eevrz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L184)):*
> ```JavaScript
>  */
> function drawGraphEdges(graph, thickness, color) {
>   const graphics = new PIXI.Graphics();
> ```

You could make this PIXI object have a more descriptive name, but I'll leave it up to you.

---

*[test/draw/drawings.spec.js, line 283 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgPfpcTyuZNYqHy_pT:-KvgPfpcTyuZNYqHy_pU:b-mafmqe) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/test/draw/drawings.spec.js#L283)):*
> ```JavaScript
> 
>   tester.test('calls drawGraphEdges with correct graph object', t => {
>     const mockDrawGraphEdges = sinon.spy();
> ```

Can you put this lower, to just before the rewire of `mockDrawGraphEdges`? It is easier to read when those things happen together.

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgQ8riOpU1XXr0qGYY:-KvgQ8riOpU1XXr0qGYZ:b-jbzida) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/test/draw/drawings.spec.js#L292)):*
> ```JavaScript
>     mockGraph.addEdge(middle, down);
>     mockGraph.addEdge(down, left);
> ```

FYI

Convention is unclear about whether or not we put a new line here

---

*[test/draw/drawings.spec.js, line 298 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgPYnMsg6r6R1ADBej:-KvgPYnMsg6r6R1ADBek:bvf10n8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/test/draw/drawings.spec.js#L298)):*
> ```JavaScript
> 
>     drawNavMesh(mockGraph);
> ```

Delete newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[package-lock.json, line 3 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh1brNi9xo94v0am91:-Kvh1brNi9xo94v0am92:bic74ln) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/package-lock.json#L3)):*
> ```JSON
> {
>   "name": "tagprobot",
>   "version": "0.1.0",
> ```

downgrading version seems weird

---

*[src/constants.js, line 32 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh1m8mE4dX8gH7b86K:-Kvh1m8mE4dX8gH7b86L:b9x6ny7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/constants.js#L32)):*
> ```JavaScript
> export const ntColor = 0xff8c00; // Orange
> export const navMeshColor = 0x9400ff; // Purple
> export const navMeshThickness = 4;
> ```

unit on this? is it in pixels?

---

*[src/draw/drawings.js, line 36 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh2Wozc-voHPegFNkq:-Kvh2Wozc-voHPegFNkr:b-t8ix0c) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L36)):*
> ```JavaScript
> 
> // A list of the Graph class sprites, like navigation mesh.
> let graphSprites = [];
> ```

It seems like this is at most length one, so it seems like you should just have this be the single sprite object, instead of a list length 1

---

*[src/draw/drawings.js, line 91 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh3lXy9q7-58aH8Clz:-Kvh3lXy9q7-58aH8Cm-:b-phcjje) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L91)):*
> ```JavaScript
>   const allSprites = permNTSprites
>     .concat(pathSprites)
>     .concat(graphSprites)
> ```

concat actually works even if this is a single object!

---

*[src/draw/drawings.js, line 177 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh27haKPmA8LYx0Jc4:-Kvh27haKPmA8LYx0Jc5:bl5cu88) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L177)):*
> ```JavaScript
> /*
>  * Draws edges of a graph class with a certain thickness and color.
>  * Runtime: O(E)
> ```

nice! (perhaps add V and E to our runtime docs)

---

*[src/draw/drawings.js, line 179 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOUoTOielxt1G-9R2:-Kvh1z5ob_Qp2u8o5faJ:b-42l8nd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L179)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Would you not put `@param {Object}` and then specify some properties of a graph?
</blockquote></details>

I like `{Graph}` more. Then user knows which kind of object it is can and can reference that class

---

*[src/draw/drawings.js, line 203 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh4If_N3QbV82_WDLt:-Kvh4If_N3QbV82_WDLu:bb2fv51) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L203)):*
> ```JavaScript
>  * @param {Graph} graph - graph of edges to draw
>  */
> export function drawNavMesh(graph) {
> ```

This isnt actually being called when the bot runs yet, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[package-lock.json, line 3 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh1brNi9xo94v0am91:-Kvh6MZs-xKr2f8At9wB:b-j1utuq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/package-lock.json#L3)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

downgrading version seems weird
</blockquote></details>

I did it in [this commit](https://github.com/chauncy-crib/tagprobot/commit/4ea0ba2049cfbd16109ddce3aeb8f5d349650e4a) and people were okay with it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 179 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOUoTOielxt1G-9R2:-Kvh6XSMXCc1V7b_rI1y:b9h6izi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L179)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I like `{Graph}` more. Then user knows which kind of object it is can and can reference that class
</blockquote></details>

Yeah it's a class, which is slightly different than an Object I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 184 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOdSDPuRdvrLSV_qK:-Kvh6kA4mVsfXJsbltNM:b-16qhsx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L184)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

You could make this PIXI object have a more descriptive name, but I'll leave it up to you.
</blockquote></details>

edgeGraphics? graphGraphics sounds kinda weird haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 36 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh2Wozc-voHPegFNkq:-Kvh7TnuD6nRaJ-KL7kB:bdvh1aw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L36)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

It seems like this is at most length one, so it seems like you should just have this be the single sprite object, instead of a list length 1
</blockquote></details>

Sweet yeah if concat works with one item, that makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/constants.js, line 32 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh1m8mE4dX8gH7b86K:-Kvh7jW4UlI7GiUaoSwV:b-gy1qzq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/constants.js#L32)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

unit on this? is it in pixels?
</blockquote></details>

I specify pixels in the jsdoc of the function that uses this, but I can put it here too :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 203 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh4If_N3QbV82_WDLt:-Kvh7xxX9jHNpyF0aIBM:bemw3rp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L203)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This isnt actually being called when the bot runs yet, right?
</blockquote></details>

nope, not yet!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 177 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh27haKPmA8LYx0Jc4:-Kvh9SPRhimfFkkGPiTO:br9gwc5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L177)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

nice! (perhaps add V and E to our runtime docs)
</blockquote></details>

Uhhh so E is already the number of temporarily non-traversable tiles, what should edges be?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/draw/drawings.js, line 184 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOdSDPuRdvrLSV_qK:-KvhBMcgeoPBgrLgXt8T:b-hfghm4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L184)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

edgeGraphics? graphGraphics sounds kinda weird haha
</blockquote></details>

Sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
Review status: 1 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[test/draw/drawings.spec.js, line 283 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgPfpcTyuZNYqHy_pT:-KvhCXO65VePnVWmCJAs:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/test/draw/drawings.spec.js#L283)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you put this lower, to just before the rewire of `mockDrawGraphEdges`? It is easier to read when those things happen together.
</blockquote></details>

Done.

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgQ8riOpU1XXr0qGYY:-KvhCXl12lehKjEG8o3z:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

FYI

Convention is unclear about whether or not we put a new line here
</blockquote></details>

Done.

---

*[test/draw/drawings.spec.js, line 298 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgPYnMsg6r6R1ADBej:-KvhCX7wLXK00NKPF--P:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/test/draw/drawings.spec.js#L298)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Delete newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
Review status: 1 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/draw/drawings.js, line 184 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KvgOdSDPuRdvrLSV_qK:-KvhChQ4z6iW4sfqP6mn:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L184)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
Review status: 1 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/constants.js, line 32 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh1m8mE4dX8gH7b86K:-KvhClZP3V5opdvkgnlU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/constants.js#L32)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I specify pixels in the jsdoc of the function that uses this, but I can put it here too :thumbsup: 
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 36 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh2Wozc-voHPegFNkq:-KvhCmX9dDwJgeDAlXVu:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L36)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Sweet yeah if concat works with one item, that makes sense.
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 91 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh3lXy9q7-58aH8Clz:-KvhCmq6vRxZAD5_4SsG:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L91)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

concat actually works even if this is a single object!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 7 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 177 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh27haKPmA8LYx0Jc4:-KwCi-ih018N0bE7W7AZ:b-e2wjmg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L177)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Uhhh so E is already the number of temporarily non-traversable tiles, what should edges be?
</blockquote></details>

God. dammit. hahahaha. I would say change the existing `E` to something else (you'll have to look around for comments that mention runtime in terms of E and update it though. If that's too much of a pain, just use `D` or `G` or something)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 7 files at r3.
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/draw/drawings.js, line 334 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kw_RUWfG4OGUcZoEhnY:-Kw_RUWfG4OGUcZoEhnZ:btd7soo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7e37fe92e6036161ac2cdc01257016c66f1c11eb/src/draw/drawings.js#L334)):*
> ```JavaScript
>  */
> function drawGraphEdges(graph, thickness, color) {
>   assert(graphSprite === null, 'graphSprite is not null');
> ```

nit: I like `_.isNull()`, or maybe `_.isNil()` (in case we want to handle both `undefined` and `null` equivalently)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/draw/drawings.js, line 177 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kvh27haKPmA8LYx0Jc4:-KwaO04mV-uycL7XDc79:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f6a4d3ae7dadd02d001c361496e4e418b9ad488/src/draw/drawings.js#L177)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

God. dammit. hahahaha. I would say change the existing `E` to something else (you'll have to look around for comments that mention runtime in terms of E and update it though. If that's too much of a pain, just use `D` or `G` or something)
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 334 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kw_RUWfG4OGUcZoEhnY:-KwaO0ZGSLv_YQjsJBwg:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7e37fe92e6036161ac2cdc01257016c66f1c11eb/src/draw/drawings.js#L334)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

nit: I like `_.isNull()`, or maybe `_.isNil()` (in case we want to handle both `undefined` and `null` equivalently)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 8 files at r4.
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 347 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KwapgMgZ1MVAGEo0HAg:-KwapgMgZ1MVAGEo0HAh:b-u8wk9y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f8b99a87eab156c15df9e940346ec82e4b4948d/src/draw/drawings.js#L347)):*
> ```JavaScript
> 
>   tagpro.renderer.layers.background.addChild(graphGraphics);
>   graphSprite = graphGraphics;
> ```

FYI lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 8 files at r4.
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by shanek21** [comment]
Reviewed 1 of 7 files at r2, 2 of 7 files at r3, 5 of 8 files at r4.
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 57 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KwaoxDyqgxEyNWiNEvj:-KwaoxDyqgxEyNWiNEvk:bo0zmz0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f8b99a87eab156c15df9e940346ec82e4b4948d/src/index.js#L57)):*
> ```JavaScript
> 
>   const graph = graphFromTagproMap(tagpro.map);
>   drawNavMesh(graph);
> ```

API is sorta different than the other stuff we are initially drawing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by billmwong** [comment]
*[src/index.js, line 57 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-KwaoxDyqgxEyNWiNEvj:-Kwb-4XPqC1frG1VBcWf:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f8b99a87eab156c15df9e940346ec82e4b4948d/src/index.js#L57)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

API is sorta different than the other stuff we are initially drawing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r5.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by shanek21** [comment]
Reviewed 6 of 6 files at r5.
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/triangulation.js, line 2 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kwb-w_NKWSyac1HWhuO:-Kwb-w_NKWSyac1HWhuP:bo12cr2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d9cc6395e67da9851931c2dbdefd755cd0ce9d0d/src/navmesh/triangulation.js#L2)):*
> ```JavaScript
> import { graphFromTagproMap } from './polygon';
> ```

such line very new

---

*[src/navmesh/triangulation.js, line 4 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220#-Kwb-vSPRLGQrviIHtdM:-Kwb-vSPRLGQrviIHtdN:b-py3fdx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d9cc6395e67da9851931c2dbdefd755cd0ce9d0d/src/navmesh/triangulation.js#L4)):*
> ```JavaScript
> 
> let DTGraph;
> ```

Newlines pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r7.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r7.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/220)*

**Pull request merged**
