### PR TITLE
330: Funnelling doesn't work when player is stradling a line between two triangles

### LINKED ISSUE #330: Funnelling doesn't work when player is stradling a line between two triangles

### PR DESCRIPTION
**Pull request by billmwong**
Closes #330 

This bug was happening because our first funnel was facing the wrong way, i.e. backwards.  I fix it by checking if the ball is in the area that would be effected, and then incrementing the funnel until it is facing the right way.

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/383)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 2 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by shanek21** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[src/plan/test/data.js, line 1 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7ZhwcSD6w9hFIXiObX:-L7ZhwcSD6w9hFIXiObY:bg9z0h1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/test/data.js#L1)):*
> ```JavaScript
> import { Point } from '../../interpret/class/Point';
> ```

`data.js`? Can you explain the file name? Is it a convention of some sort?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
*[src/plan/test/data.js, line 1 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7ZhwcSD6w9hFIXiObX:-L7ZiiLG5UpyRGm1obG-:b-9zffgm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/test/data.js#L1)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

`data.js`? Can you explain the file name? Is it a convention of some sort?
</blockquote></details>

No convention, so if you have a better name definitely tell me.  I didn't want to store this whole path in the test file cause it's a lot of lines

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/plan/funnel.js, line 76 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7_Rtf10RSodX1SV1wm:-L7_Rtf10RSodX1SV1wn:bn2ejz8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L76)):*
> ```JavaScript
>   const funnelIndices = [0, 0]; // the indices of the left and right points in the funnel
> 
>   let startingPortal = 1;
> ```

I would love a walk through of this code :)

I'm a little confused regarding what it means for a funnel to be backwards. I bet it's been explained to me before, but I forgot :(

---

*[src/plan/test/data.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7ZhwcSD6w9hFIXiObX:-L7_RiPmFj9umjuHgXPX:b-twj0ag) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/test/data.js#L1)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

No convention, so if you have a better name definitely tell me.  I didn't want to store this whole path in the test file cause it's a lot of lines
</blockquote></details>

Seems like this file is mainly for saving a backwardsFunnel to test with. Perhaps test/backwardsFunnelData.js?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
*[src/plan/test/data.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7ZhwcSD6w9hFIXiObX:-L7aqts24mPNFXmAWYVG:b8jtryz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/test/data.js#L1)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Seems like this file is mainly for saving a backwardsFunnel to test with. Perhaps test/backwardsFunnelData.js?
</blockquote></details>

I'm fine with that if Shane is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by shanek21** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/plan/test/data.js, line 1 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7ZhwcSD6w9hFIXiObX:-L7bobAo-fYdfoP_PBPK:bizlbj6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/test/data.js#L1)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I'm fine with that if Shane is
</blockquote></details>

:shipit: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/plan/funnel.js, line 78 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fM9t5yCiEKI6c6RN5:-L7fM9t5yCiEKI6c6RN6:b-fx70a3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L78)):*
> ```JavaScript
>   let startingPortal = 1;
>   // Skip over portal if the portal is behind us
>   const polygon1 = new Triangle(
> ```

Add a comment explaining that these two triangles make up a the polygon with the points [rClearance, lClearance, r, l]. 

---

*[src/plan/funnel.js, line 95 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fLzJB0nUHt4byjqMj:-L7fLzJB0nUHt4byjqMk:bleymgr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L95)):*
> ```JavaScript
> 
>     while (
>       leftFunnelEdge.isBetweenPoints(
> ```

does this for loop ever run >1 time? Would be an easy thing to check. Based on your talk, I believe the answer is no? But if its yes, could you explain why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by shanek21** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/plan/funnel.js, line 65 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7fOXft3ZVK_UeFQzOz:-L7fOXft3ZVK_UeFQzP-:b-1jdthl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L65)):*
> ```JavaScript
>  *   that are funnelled to be as straight as possible
>  */
> export function funnelPolypoints(path, triangleGraph) {
> ```

I feel like I wish this function could be broken up into more modular bits, but I don't really have any specific suggestions... Do you think any parts could be broken off into other functions that are called in here?

---

*[src/plan/funnel.js, line 76 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7fNm_G1tnIw1QR-CQQ:-L7fNm_G1tnIw1QR-CQR:b-t9pmdl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L76)):*
> ```JavaScript
>   const funnelIndices = [0, 0]; // the indices of the left and right points in the funnel
> 
>   let startingPortal = 1;
> ```

Rename to `startingPortalIndex` or `startingPortalIdx` or something similar?

---

*[src/plan/funnel.js, line 82 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7fNDPOAMKLW6Kqn3qT:-L7fNDPP76tpRkWArNGB:bqv3oz2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L82)):*
> ```JavaScript
>     rightPoints[0].clearancePoint,
>     leftPoints[0].clearancePoint,
>     false,
> ```

Why are you not checking for zero area here?

---

*[src/plan/funnel.js, line 90 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7fOua47oRhVjlboorz:-L7fOua47oRhVjlboos-:b-4dehtv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L90)):*
> ```JavaScript
>     false,
>   );
>   if (polygon1.containsPoint(startPoint) || polygon2.containsPoint(startPoint)) {
> ```

Add comment that this is checking if portal is behind us

---

*[src/plan/funnel.js, line 94 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7fPRnc9E7SQ2Hn2xeO:-L7fPRnc9E7SQ2Hn2xeP:b-5ickgo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L94)):*
> ```JavaScript
>     let rightFunnelEdge = new Edge(startPoint, rightPoints[funnelIndices[1]].clearancePoint);
> 
>     while (
> ```

Add general comments around this function?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/plan/funnel.js, line 65 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fOXft3ZVK_UeFQzOz:-L7fRjQsmt3k9QyeP6Hn:bf2zx2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L65)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I feel like I wish this function could be broken up into more modular bits, but I don't really have any specific suggestions... Do you think any parts could be broken off into other functions that are called in here?
</blockquote></details>

I had a similar thought reagarding the whole "is the funnel starting off backwards?" bug. Could you refactor out the bits that check that into a function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
*[src/plan/funnel.js, line 82 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fNDPOAMKLW6Kqn3qT:-L7fc7nr_bIjwX5zxXfW:by0ybpm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L82)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why are you not checking for zero area here?
</blockquote></details>

I don't care if one of the polygons has zero area, cause that means I can't be inside of it anyways.  If the clearance point is on the line between the two real points, it will cause one of these polygons to have zero area

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
*[src/plan/funnel.js, line 95 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fLzJB0nUHt4byjqMj:-L7fcTvbZaqeMPRG7dPo:b-rh22km) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L95)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

does this for loop ever run >1 time? Would be an easy thing to check. Based on your talk, I believe the answer is no? But if its yes, could you explain why?
</blockquote></details>

The answer is yes, and no I cannot easily explain why.  Making this an if statement seems to cause more bugs than it fixes, I investigated a little bit but could not figure out why or an easy fix.  Do you want me to defer this to another card or try to figure out in this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Defer to another card

**Comment by billmwong** [comment]
*[src/plan/funnel.js, line 95 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fLzJB0nUHt4byjqMj:-L855HIPzc0x88waA3Y5:bzdalxi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L95)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Defer to another card
</blockquote></details>

OK added to the description of #382 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/plan/funnel.js, line 65 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fOXft3ZVK_UeFQzOz:-L85L9ANLoyfwhtj_hL5:b-hlh5av) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L65)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I had a similar thought reagarding the whole "is the funnel starting off backwards?" bug. Could you refactor out the bits that check that into a function?
</blockquote></details>

Done, let me know what you think of this

---

*[src/plan/funnel.js, line 76 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fNm_G1tnIw1QR-CQQ:-L85L6SgUeEBR6HGasRd:bsu7n96) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L76)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Rename to `startingPortalIndex` or `startingPortalIdx` or something similar?
</blockquote></details>

Done, let me know if this is better

---

*[src/plan/funnel.js, line 78 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fM9t5yCiEKI6c6RN5:-L85L1Xmxw9rgKfz7aCU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L78)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Add a comment explaining that these two triangles make up a the polygon with the points [rClearance, lClearance, r, l]. 
</blockquote></details>

Done.

---

*[src/plan/funnel.js, line 90 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fOua47oRhVjlboorz:-L85LC7TUnszNCAN0rJj:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L90)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Add comment that this is checking if portal is behind us
</blockquote></details>

Done.

---

*[src/plan/funnel.js, line 94 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fPRnc9E7SQ2Hn2xeO:-L85LCf7ypd_ytkRN5oK:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L94)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Add general comments around this function?
</blockquote></details>

Done.

---

*[src/plan/test/data.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7ZhwcSD6w9hFIXiObX:-L85M4YuthPO7d-ecUeZ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/test/data.js#L1)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

:shipit: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BS4ARpzbx2erQCvUF:-L8BS4ARpzbx2erQCvUG:bhx6556) (no related file):*
forgot 330 in commit

---

*[src/plan/funnel.js, line 65 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L7fOXft3ZVK_UeFQzOz:-L8BSHLsfzZ4DVvZfpht:bb6ywmx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L65)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done, let me know what you think of this
</blockquote></details>

LGTM

---

*[src/plan/funnel.js, line 114 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BSWg44-E0Mb1xSUAM:-L8BSWg44-E0Mb1xSUAN:b-5mvoyd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f99b4c2d23264e2a69914a77e00f5b69ae195e10/src/plan/funnel.js#L114)):*
> ```JavaScript
> 
>   const funnelledPath = [path[0]];
>   let funnelApex = path[0].point;
> ```

upon a reread, i realize i don't remember what the apex is. Is that where the funnel turns? perhaps a comment explaining what you mean by apex?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
*[src/plan/funnel.js, line 114 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BSWg44-E0Mb1xSUAM:-L8F7e8gdjgG82sjo1kX:bucy6ka) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f99b4c2d23264e2a69914a77e00f5b69ae195e10/src/plan/funnel.js#L114)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

upon a reread, i realize i don't remember what the apex is. Is that where the funnel turns? perhaps a comment explaining what you mean by apex?
</blockquote></details>

Hmm yeah is there a better word? It's like the "top" of the funnel that the two funnel points connect to.  The first apex is the point where the ball is, and when we find a corner we need to turn we make that corner the new apex and restart the funnel algorithm from there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BS4ARpzbx2erQCvUF:-L8F85R3IFiGX_kpUKwJ:bxw44jo) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

forgot 330 in commit
</blockquote></details>

Crap, you're right, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/plan/funnel.js, line 114 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BSWg44-E0Mb1xSUAM:-L8Gz6u-wtgkjPRgXZCO:b-vmhtpo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f99b4c2d23264e2a69914a77e00f5b69ae195e10/src/plan/funnel.js#L114)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmm yeah is there a better word? It's like the "top" of the funnel that the two funnel points connect to.  The first apex is the point where the ball is, and when we find a corner we need to turn we make that corner the new apex and restart the funnel algorithm from there
</blockquote></details>

merp. explanation makes perfect sense. can't think of a good variable name. perhaps just leave a comment with the explanation you just gave?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by billmwong** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/plan/funnel.js, line 114 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BSWg44-E0Mb1xSUAM:-L8KKcq7WCIeYAuHIfWG:b-bi5t99) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f99b4c2d23264e2a69914a77e00f5b69ae195e10/src/plan/funnel.js#L114)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

merp. explanation makes perfect sense. can't think of a good variable name. perhaps just leave a comment with the explanation you just gave?
</blockquote></details>

Done, I added some more comments to try to make this algorithm clearer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r3.
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/plan/funnel.js, line 114 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383#-L8BSWg44-E0Mb1xSUAM:-L8KwDfq_6Xzi7nsoXv6:b76m436) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f99b4c2d23264e2a69914a77e00f5b69ae195e10/src/plan/funnel.js#L114)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done, I added some more comments to try to make this algorithm clearer
</blockquote></details>

Nice. Looks good :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/383)*

**Comment by shanek21** [comment]
Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/plan/funnel.js, line 76 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383#-L7fNm_G1tnIw1QR-CQQ:-L8bqqBrC_9fBLgRAJik:bsbqjb0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/41867b6204f805f30cdcbbba9f50f43f40f1550b/src/plan/funnel.js#L76)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done, let me know if this is better
</blockquote></details>

So good

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/383)*

**Pull request merged**
