### PR TITLE
254: [HOT FIX] visualizations for triangulation doesnt toggle

### LINKED ISSUE #254: [HOT FIX] visualizations for triangulation doesnt toggle
:fire:

### PR DESCRIPTION
**Pull request by billmwong**
Closes #254

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/255)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255#-KyHkIX9F9h6KfJ0i_BL:-KyHkIX9F9h6KfJ0i_BM:b-q46u3j) (no related file):*
simple present tense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255)*

**Comment by davidabrahams** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255#-KyHkjP8VUgCTVQMklAN:-KyHkjP8VUgCTVQMklAO:b-i7o9ag) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/81bc9202bcf13179ef3d9391a8ed0be15dea3dc2/src/draw/drawings.js#L245)):*
> ```JavaScript
>   _.forEach(allSprites, s => tagpro.renderer.layers.background.removeChild(s));
>   _.forEach(graphSprite, s => tagpro.renderer.layers.foreground.removeChild(s));
>   pathSprites = [];
> ```

Could just be `tagpro.renderer.layers.foreground.removeChild(graphSprite)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255)*

**Comment by billmwong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255#-KyHkIX9F9h6KfJ0i_BL:-KyHn5ycEfcnBLbLCEIx:bb6un1j) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

simple present tense
</blockquote></details>

Done

---

*[src/draw/drawings.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255#-KyHkjP8VUgCTVQMklAN:-KyHn8INDR4LMx3cAPFb:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/81bc9202bcf13179ef3d9391a8ed0be15dea3dc2/src/draw/drawings.js#L245)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Could just be `tagpro.renderer.layers.foreground.removeChild(graphSprite)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/255)*

**Pull request merged**
