### PR TITLE
440: create Serializable class

### LINKED ISSUE #440: Make Serializable interface class
Don't implement using it, just make it

### LINKED ISSUE #449: Move Graph, Point, and Edge to globals

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #440

Closes #449 

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAmS9dDCdLmpl8EV9U:-LCAmS9dDCdLmpl8EV9V:b-d0wvye) (no related file):*
I'm not sure how I feel about the `Serializable` class being in `interpret/`. It almost feels like a new folder to me? Maybe `load/` or something similar? I dunno, I just feel like I would rather spread files out than pack them in places we aren't sure they go. 

---

*[src/interpret/class/Serializable.js, line 6 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAlfGU5Js-cCg3xlBi:-LCAlfGU5Js-cCg3xlBj:b-pb9bm7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f0f1077edbdbb6af5a36ade4e49314bc0634acd/src/interpret/class/Serializable.js#L6)):*
> ```JavaScript
> /**
>  * A class representing an object which can be serialized/deserialized to/from a file. Usage
>  * would look like (assuming Cat extends Serializable, and has some method Cat.meow())
> ```

indent

---

*[src/interpret/class/Serializable.js, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAmG_O26RDfr02MOwK:-LCAmG_O26RDfr02MOwL:bwy077j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f0f1077edbdbb6af5a36ade4e49314bc0634acd/src/interpret/class/Serializable.js#L41)):*
> ```JavaScript
>   deserialize(filename) {
>     assert(false, 'Method not implemented');
>     return this;
> ```

Why have this line if it will never run?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Serializable.js, line 8 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAmsmM8x9X-IAEFWrg:-LCAmsmM8x9X-IAEFWrh:b-8bqrof) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f0f1077edbdbb6af5a36ade4e49314bc0634acd/src/interpret/class/Serializable.js#L8)):*
> ```JavaScript
>  * would look like (assuming Cat extends Serializable, and has some method Cat.meow())
>  *
>  * const timmy = new Cat("timmy");
> ```

Maybe start this with `An example:` and then indent all of your code stuff by two spaces?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
*[src/interpret/class/Serializable.js, line 19 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAoTwb4Qj1gp9lhol9:-LCAoTwb4Qj1gp9lholA:beu7m6s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f0f1077edbdbb6af5a36ade4e49314bc0634acd/src/interpret/class/Serializable.js#L19)):*
> ```JavaScript
> export class Serializable {
>   /* eslint-disable class-methods-use-this */
>   /* eslint-disable no-unused-vars */
> ```

what is the unused var?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by davidabrahams** [comment]
*[src/interpret/class/Serializable.js, line 19 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAoTwb4Qj1gp9lhol9:-LCAqJqV8Rjr3s15Dd6A:b-62at0m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f0f1077edbdbb6af5a36ade4e49314bc0634acd/src/interpret/class/Serializable.js#L19)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what is the unused var?
</blockquote></details>

it's filename in `serialize`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by davidabrahams** [comment]
*[src/interpret/class/Serializable.js, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAmG_O26RDfr02MOwK:-LCAqN2t--lxuxsgUoUj:b-a37u9h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8f0f1077edbdbb6af5a36ade4e49314bc0634acd/src/interpret/class/Serializable.js#L41)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why have this line if it will never run?
</blockquote></details>

I included it as sort of a template for what a real implementation should look like. (ie, assign data fields, then return the current object)

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by davidabrahams** [comment]
Review status: 0 of 31 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCAmS9dDCdLmpl8EV9U:-LCB7YUO3qpQbqre9w_4:b-896fig) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I'm not sure how I feel about the `Serializable` class being in `interpret/`. It almost feels like a new folder to me? Maybe `load/` or something similar? I dunno, I just feel like I would rather spread files out than pack them in places we aren't sure they go. 
</blockquote></details>

Done?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
Reviewed 36 of 43 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCB7_FH25LlONgzteeX:-LCCTzndEiSG0B483bUw:b-uqag58) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

@billmwong FYI, shane and I had an in-person discussion about where our classes should go, we thought the best idea is to place them based on what "idea" they represent, though maybe not where they are used. Therefore, I moved `Point`, `Edge`, and `Graph` to `global`, since these seem like abstract concepts that we use or can use for various applications.
</blockquote></details>

OK I wish this was its own PR but seems reasonable since you've already done it

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by davidabrahams** [comment]
Review status: 2 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCB7_FH25LlONgzteeX:-LCCa7y_CX9k31DZKp-Q:b4ud5ke) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

OK I wish this was its own PR but seems reasonable since you've already done it
</blockquote></details>

Yeah probably shoulda been. Given that you already reviewed it, it's probably easiest to just let this rider in. If you want I can separate it to another PR (its just a single commit I would move)

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by shanek21** [comment]
Reviewed 35 of 43 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/global/class/Serializable.js, line 7 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCF2SYx524MGyqxXJzJ:-LCF2SYx524MGyqxXJzK:b-zapi5j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc5d95b156d6258df5b98bb4b7ed82ac5a122214/src/global/class/Serializable.js#L7)):*
> ```JavaScript
>  * A class representing an object which can be serialized/deserialized to/from a file. Assuming Cat
>  *   extends Serializable, and has some method Cat.meow(), an example:
>  *
> ```

Delete this line?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/global/class/Serializable.js, line 7 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCF2SYx524MGyqxXJzJ:-LCF5geX5Z5mNEUQ_EBo:b-dl66rs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc5d95b156d6258df5b98bb4b7ed82ac5a122214/src/global/class/Serializable.js#L7)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Delete this line?
</blockquote></details>

RESOLVE THYSELF

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
*[src/global/class/Serializable.js, line 7 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/447#-LCF2SYx524MGyqxXJzJ:-LCF5zWP0HhskUM0quvr:b1uhr6i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc5d95b156d6258df5b98bb4b7ed82ac5a122214/src/global/class/Serializable.js#L7)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

RESOLVE THYSELF
</blockquote></details>

agressive

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r7, 4 of 6 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Comment by billmwong** [comment]
Reviewed 4 of 6 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/447)*

**Pull request merged**
