### PR TITLE
363 src dir rename

### LINKED ISSUE #363: Sometimes I don't know where our source code is

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #363

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/364)

### CODE REVIEW

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/364#-L6wwwWtN20a-AkISOXc:-L6wwwWtN20a-AkISOXd:b-fmkkgn) (no related file):*
FYI ur a toid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/364)*

**Comment by billmwong** [comment]
:dango:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/364#-:-L6wx03Wm9roB7QHEi6E:bcbqss6)*

**Comment by shanek21** [comment]
Review status: 0 of 50 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/364#-L6wx0Zn63EduNIYIavb:-L6wx0Zn63EduNIYIavc:b28qd9e) (no related file):*
> move 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/364)*

**Comment by billmwong** [comment]
Reviewed 99 of 99 files at r1.
Review status: 48 of 50 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/364)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/364#-L6wx5Td7jJFfdffSgYU:-L6wx5Td7jJFfdffSgYV:b78dqu3) (no related file):*
Travis failed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/364)*

**Pull request closed without merging**
