### PR TITLE
215: delaunay working and tests

### PR DESCRIPTION
**Pull request by davidabrahams**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/242)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 4 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/navmesh/graph.js, line 4 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvnkSuNWwp_bDr1tGp:-KxvnkSuNWwp_bDr1tGq:b9wnqcc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a4397e68a0ec7abc19378f713c6625964fc4a31b/src/navmesh/graph.js#L4)):*
> ```JavaScript
> import { assert } from '../utils/asserts';
> ```

doesnt shane like the two newlines after imports

---

*[src/navmesh/graph.js, line 38 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvpIDj25kvPnKWMuIX:-KxvpIDj25kvPnKWMuIY:b-l565rr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L38)):*
> ```JavaScript
> 
> 
> export function isLegal(insertedPoint, e, oppositePoint) {
> ```

why is this no longer a class method

---

*[src/navmesh/graph.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvoM_1yfsPJr0YWX1B:-KxvoM_1yfsPJr0YWX1C:bb71c7n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L43)):*
> ```JavaScript
>   let p2;
>   let p3;
>   if (e.p2.x === e.p1.x) {
> ```

maybe make a comment above here about how were doing this to avoid 0 slopes

---

*[src/navmesh/graph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvof6bntShlaW5vcHS:-KxvnzgTvQiAicV2F9BX:bjqd1og) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L44)):*
> ```JavaScript
>   let p3;
>   if (e.p2.x === e.p1.x) {
>     p1 = e.p1; // eslint-disable-line prefer-destructuring
> ```

grrr i see why you did this but im making a comment here so i can think more about it later

---

*[src/navmesh/graph.js, line 183 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvp2LNcJdDINOYTBRN:-Kxvp2LNcJdDINOYTBRO:b-7v08c7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L183)):*
> ```JavaScript
>           uniqueIdx[j] = false;
>           sharedIdx[i] = true;
>           continue; // eslint-disable-line no-continue
> ```

grr is it possible to refactor this

---

*[src/navmesh/triangulation.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvpfrAXWBzUTsaWtd_:-KxvpfrAXWBzUTsaWtda:b-34cdy5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/triangulation.js#L50)):*
> ```JavaScript
>     mapGraph.getVertices(),
>     new Point(-3000000, -100),
>     new Point(14000000, 10000000),
> ```

FYI lol nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/navmesh/graph.js, line 4 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvnkSuNWwp_bDr1tGp:-KxwsteU2DaRcYERY5M3:b-4k3di3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a4397e68a0ec7abc19378f713c6625964fc4a31b/src/navmesh/graph.js#L4)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

doesnt shane like the two newlines after imports
</blockquote></details>

Yup. nice catch. fixed.

---

*[src/navmesh/graph.js, line 38 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvpIDj25kvPnKWMuIX:-KxwszysoNMUnC0vtaY6:b-bbyuqh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L38)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why is this no longer a class method
</blockquote></details>

Eslint had an error that basically said because the method had no reference to `this` in it, it shouldn't be a class method. I think any method that doesn't have to be a class method shouldn't, according to eslint.

---

*[src/navmesh/graph.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvoM_1yfsPJr0YWX1B:-KxwtfNLxgG6Z2q2GUDa:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L43)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

maybe make a comment above here about how were doing this to avoid 0 slopes
</blockquote></details>

Done.

---

*[src/navmesh/graph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvof6bntShlaW5vcHS:-KxwtCon4y_SPKmsQ0vr:bhzj1jy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L44)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

grrr i see why you did this but im making a comment here so i can think more about it later
</blockquote></details>

Sure. `{p1, p2} = e;` doesn't compile here (TBH I'm not sure why). Feel free to suggest alternatives.

---

*[src/navmesh/graph.js, line 183 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvp2LNcJdDINOYTBRN:-Kxwu-xhilZ59KwXzR67:b-2nla6h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L183)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

grr is it possible to refactor this
</blockquote></details>

Yes, but the code gets way worse (IMO). I made the fix to show what it would look like in its own commit so we can easily undo it. LMK what you think of the update.

---

*[src/navmesh/triangulation.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvpfrAXWBzUTsaWtd_:-KxwuBcTU32XwqLFsfLH:b-bntlan) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/triangulation.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

FYI lol nice
</blockquote></details>

Ya I figured at least we can make the user responsible for passing in working dummy points :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/navmesh/graph.js, line 38 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-KxvpIDj25kvPnKWMuIX:-KxzaLKZP-GyfEae86St:bk6zv2r) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L38)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Eslint had an error that basically said because the method had no reference to `this` in it, it shouldn't be a class method. I think any method that doesn't have to be a class method shouldn't, according to eslint.
</blockquote></details>

OK seems legit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
*[src/navmesh/triangulation.js, line 35 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3Kp2sOnlHwVvbZEUf:-Ky3Kp2sOnlHwVvbZEUg:bgibzjm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/566ca63899abc60500a323d6a1f201c84c7b2d6c/src/navmesh/triangulation.js#L35)):*
> ```JavaScript
>   // dummy triangle contains each point
>   _.each(shuffledVertices, vertex => {
>     assert(DTGraph.findContainingTriangles(vertex).length === 1);
> ```

we could do this inside the next _.each right?  If it's gonna error out anyway, when it errors is not super important

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/navmesh/graph.js, line 183 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvp2LNcJdDINOYTBRN:-Ky3NmZaWBLWb0eHAcrM:boyexb3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L183)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

make this a break statement as discussed offline
</blockquote></details>

Done. Thanks!

---

*[src/navmesh/triangulation.js, line 35 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3Kp2sOnlHwVvbZEUf:-Ky3O6LJqnvnO-AZWxs1:b-rjo3xn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/566ca63899abc60500a323d6a1f201c84c7b2d6c/src/navmesh/triangulation.js#L35)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

we could do this inside the next _.each right?  If it's gonna error out anyway, when it errors is not super important
</blockquote></details>

So, I wanted to add an explicit check on the dummy triangle and make that assertion error different than the one in `graph.js` on line 315, to make it more clear if, in the future we don't find a containing triangle, it's because the dummy points were wrong, not because of some other implementation error. If we do it in the next _.each, we can't differentiate between the two errors. (also, an assert right before `DTGraph.addTriangulationVertex` is redundant, since there's an assert at the top of that function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/navmesh/triangulation.js, line 33 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3YJ2dKRmY664zKArE:-Ky3YJ2dKRmY664zKArF:b376l32) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/566ca63899abc60500a323d6a1f201c84c7b2d6c/src/navmesh/triangulation.js#L33)):*
> ```JavaScript
> 
>   const shuffledVertices = _.shuffle(_.without(vertices, highestP));
>   // dummy triangle contains each point
> ```

Can you capitalize, and add "check if" at the beginning of this comment

---

*[src/navmesh/triangulation.js, line 35 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3Kp2sOnlHwVvbZEUf:-Ky3YCiSj8Th51lBF71t:bjuopjg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/566ca63899abc60500a323d6a1f201c84c7b2d6c/src/navmesh/triangulation.js#L35)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

So, I wanted to add an explicit check on the dummy triangle and make that assertion error different than the one in `graph.js` on line 315, to make it more clear if, in the future we don't find a containing triangle, it's because the dummy points were wrong, not because of some other implementation error. If we do it in the next _.each, we can't differentiate between the two errors. (also, an assert right before `DTGraph.addTriangulationVertex` is redundant, since there's an assert at the top of that function.
</blockquote></details>

OK makes sense if you don't think it affect runtime

---

*[src/navmesh/triangulation.js, line 36 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3YVb7eaAkDXELyZtj:-Ky3YVb7eaAkDXELyZtk:bhfgzwd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a4397e68a0ec7abc19378f713c6625964fc4a31b/src/navmesh/triangulation.js#L36)):*
> ```JavaScript
>   // const shuffledVertices = _.shuffle(_.without(vertices, highestP));
>   const shuffledVertices = _.without(vertices, highestP);
>   _.forEach(shuffledVertices, vertex => {
> ```

each or forEach? Do we have a convention 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/navmesh/triangulation.js, line 33 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3YJ2dKRmY664zKArE:-Ky3b5PnYrNL2MzQdK_A:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/566ca63899abc60500a323d6a1f201c84c7b2d6c/src/navmesh/triangulation.js#L33)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Can you capitalize, and add "check if" at the beginning of this comment
</blockquote></details>

Done.

---

*[src/navmesh/triangulation.js, line 35 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3Kp2sOnlHwVvbZEUf:-Ky3b8nU5LqeTguyexEp:b-4lh2zq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/566ca63899abc60500a323d6a1f201c84c7b2d6c/src/navmesh/triangulation.js#L35)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

OK makes sense if you don't think it affect runtime
</blockquote></details>

The entire series of checks is `O(numVertices)`. The entirety of the triangulation algorithm is at least linear (I'm pretty sure it's worse, right?), which means this shouldn't affect anything.

---

*[src/navmesh/triangulation.js, line 36 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3YVb7eaAkDXELyZtj:-Ky3bJMDceoiDBfMJWms:bbcsk37) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a4397e68a0ec7abc19378f713c6625964fc4a31b/src/navmesh/triangulation.js#L36)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

each or forEach? Do we have a convention 
</blockquote></details>

Not officially, but everywhere in the code we do `_.each`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
*[src/navmesh/triangulation.js, line 36 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3YVb7eaAkDXELyZtj:-Ky3t4812YDH_kiZh6Kx:b-y1zlou) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a4397e68a0ec7abc19378f713c6625964fc4a31b/src/navmesh/triangulation.js#L36)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Not officially, but everywhere in the code we do `_.each`
</blockquote></details>

:police_car:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
*[src/navmesh/graph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvof6bntShlaW5vcHS:-Ky3uO0EDZgxf1yr9CW8:bqi9jj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L44)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Sure. `{p1, p2} = e;` doesn't compile here (TBH I'm not sure why). Feel free to suggest alternatives.
</blockquote></details>

add this to our eslintrc and get rid of the inline comments:

prefer-destructuring: ["error", {AssignmentExpression: {object: false}}]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 6 of 6 files at r5.
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/triangulation.js, line 36 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Ky3YVb7eaAkDXELyZtj:-Ky3vxvAT2TGU0AtYXev:b5zsuwa) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a4397e68a0ec7abc19378f713c6625964fc4a31b/src/navmesh/triangulation.js#L36)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

:police_car:
</blockquote></details>

Thank you for dah refactor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by davidabrahams** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/navmesh/graph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242#-Kxvof6bntShlaW5vcHS:-Ky41INMibj_M_Hzd3zL:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8dc5d995b8ccdaca3edc0daf5c8ad0d2c283d8ec/src/navmesh/graph.js#L44)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

add this to our eslintrc and get rid of the inline comments:

prefer-destructuring: ["error", {AssignmentExpression: {object: false}}]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r6.
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r7.
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/242)*

**Pull request merged**
