### PR TITLE
410: determine local goal velocity for future use with LQR

### LINKED ISSUE #410: Dynamically determine LQR goal velocity
Make the velocity vector tangent to the angle that the next two points in the path make.

Make the magnitude of the velocity the max velocity (if that doesn't seem to work well, try some fraction of the max)

### PR DESCRIPTION
**Pull request by shanek21**
Closes #410

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/429)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/start.js, line 48 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/429#-LBxE3DG2XtkzyDXqDmy:-LBxE3DG2XtkzyDXqDmz:bhonegf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c566cea537eb44a09873bfb2ff561d1c3e42aa13/src/start.js#L48)):*
> ```JavaScript
>   drawAllyPath(funnelledPath);
> 
>   const localGoalState = getLocalGoalStateFromPath(funnelledPath, me);
> ```

it's kinda weird that we're reaching into the lqr file to get this goalState, only to then pass it back in to the lqr file.  Thoughts?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/429)*

**Comment by billmwong** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/429)*

**Comment by shanek21** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/start.js, line 48 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/429#-LBxE3DG2XtkzyDXqDmy:-LC0-yaSBlXaTnvIlInT:b-ua9uj2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c566cea537eb44a09873bfb2ff561d1c3e42aa13/src/start.js#L48)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

it's kinda weird that we're reaching into the lqr file to get this goalState, only to then pass it back in to the lqr file.  Thoughts?
</blockquote></details>

We don't currently pass it back into the lqr file. Though, once we start using lqr I see your point. Maybe the refactor you are suggesting should go in #417?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/429)*

**Comment by billmwong** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/429)*

**Pull request merged**
