### PR TITLE
453: Offload K-matrix generation to a worker

### LINKED ISSUE #453: Offload K-matrix generation to a worker

### PR DESCRIPTION
**Pull request by billmwong**
Closes #453

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)

### CODE REVIEW

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCFbuK5DedrL1lZmzJN:-LCFbuK5DedrL1lZmzJO:b-qu6hub) (no related file):*
I gotta change some tests but here is the code if you want to early review

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/control/class/Matrix.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHoixJ0-u8mj51y53c:-LCHoixJ0-u8mj51y53d:b-82q4sy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/class/Matrix.js#L22)):*
> ```JavaScript
>   }
> 
>   serialize() {
> ```

so weird thing happened. I wrote `Serializable` assuming it would serialize to files. Later I realized this wasn't the right idea, and modified the implementation in my PR. Can we talk in person about what Serializable should look like?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
*[src/control/lqr.js, line 15 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHpIlh3g8hU-o-gdH0:-LCHpIlh3g8hU-o-gdH1:b1u0rzq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/lqr.js#L15)):*
> ```JavaScript
> let currentKs;
> ```

Did you include updates for what to do if the worker hasn't finished its calculations yet?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/control/lqr.js, line 15 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHpIlh3g8hU-o-gdH0:-LCHpS9E4qA93W36rdQW:b1ewvmx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/lqr.js#L15)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Did you include updates for what to do if the worker hasn't finished its calculations yet?
</blockquote></details>

nvm found it

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHqIkg3gc-3z4v9q1s:-LCHqIkg3gc-3z4v9q1t:b-dj99k6) (no related file):*
Can we have an in person discussion about the performance implications of this card and how we can use web workers in the future?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by billmwong** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCFbuK5DedrL1lZmzJN:-LCK31HD8_HKlJToYSYd:bbk2te4) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I gotta change some tests but here is the code if you want to early review
</blockquote></details>

So I removed the lqr tests.  I couldn't get webworkify-webpack to work in the test environment even with rewiring.  I was also thinking that since we'll be tweaking the costs and deadlines and such, it's not super helpful to have a test will need to get manually changed every time we tweak something small.  Also I don't want testing this branch to be my final TPB feature I have time to do

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHqIkg3gc-3z4v9q1s:-LCK3-iTADlSZ8GHVyx2:b-b9s2rp) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Can we have an in person discussion about the performance implications of this card and how we can use web workers in the future?
</blockquote></details>

Cha dude

---

*[src/control/lqr.worker.js, line 123 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHn5PN7-Cj7ga1Gmit:-LCK2_vOELGNYaitq3DX:b6pnxfq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/lqr.worker.js#L123)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

can this be more es6-y?

`export default function worker(self) {}` or something like that?
</blockquote></details>

Done, thanks! The docs for the worker package used this old syntax but it seems to work with es6 exports too

---

*[src/control/class/Matrix.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHoixJ0-u8mj51y53c:-LCK2jNQ7P_O_yLGWyIX:b-vhuqu7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/class/Matrix.js#L22)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

so weird thing happened. I wrote `Serializable` assuming it would serialize to files. Later I realized this wasn't the right idea, and modified the implementation in my PR. Can we talk in person about what Serializable should look like?
</blockquote></details>

Yeah, I mean in this use case I don't need files I just need to return a string a deserialize from a string.  The interface still sorta works cause both methods need to be implemented

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHqIkg3gc-3z4v9q1s:-LCL-4Ri-2VSJiRcW_8F:b817ry8) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Cha dude
</blockquote></details>

Talked in person

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCFbuK5DedrL1lZmzJN:-LCL0qcB6lWWes55P0J6:b-yroppx) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

So I removed the lqr tests.  I couldn't get webworkify-webpack to work in the test environment even with rewiring.  I was also thinking that since we'll be tweaking the costs and deadlines and such, it's not super helpful to have a test will need to get manually changed every time we tweak something small.  Also I don't want testing this branch to be my final TPB feature I have time to do
</blockquote></details>

I made #463 to look into re-enabling the tests

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by shanek21** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHqIkg3gc-3z4v9q1s:-LCLAQ6S8NhD7yYegetQ:b-y4qeh0) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Talked in person
</blockquote></details>

Amazing. this is so dank and i so happy :D really impressive

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 2 of 3 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/control/lqr.worker.js, line 123 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHn5PN7-Cj7ga1Gmit:-LCLAckh4Dvkqc7PDYeL:b-nykwce) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/lqr.worker.js#L123)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done, thanks! The docs for the worker package used this old syntax but it seems to work with es6 exports too
</blockquote></details>

litttt

---

*[src/control/class/Matrix.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/459#-LCHoixJ0-u8mj51y53c:-LCLAfxQDA3O2_Z6rFzE:b8bos69) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/248fab3ea2e9c41a94e2f8b9e665669fa11a4f16/src/control/class/Matrix.js#L22)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Yeah, I mean in this use case I don't need files I just need to return a string a deserialize from a string.  The interface still sorta works cause both methods need to be implemented
</blockquote></details>

Done b/c we cherrypicked my diff

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/459)*

**Pull request merged**
