### PR TITLE
141: Professional Readme

### LINKED ISSUE #141: Update our README
We should add an explanation of what TPB is (for the layman) and a gif of it working.

### PR DESCRIPTION
**Pull request by billmwong**
Closes #141

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/207)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 54 of 61 files at r1.
Review status: 0 of 61 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 6 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGZ13_moKGI1GlqrG7:-KuGZ13_moKGI1GlqrG8:b-j0x8j7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/714505d359e7c53dc0e4b29c4116a14ec9c2e1d5/package.json#L6)):*
> ```JSON
>   "description": "A bot to play TagPro",
>   "scripts": {
>     "start": "webpack --watch",
> ```

this is identical to `build` any reason we need both?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by davidabrahams** [comment]
Reviewed 7 of 61 files at r1.
Review status: 0 of 61 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by billmwong** [comment]
*[package.json, line 6 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGZ13_moKGI1GlqrG7:-KuG_7JMhAhX-gbTTaB6:b-5pomdr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/714505d359e7c53dc0e4b29c4116a14ec9c2e1d5/package.json#L6)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

this is identical to `build` any reason we need both?
</blockquote></details>

Resolve offline, `start` has the advantage of being able to do `npm start` instead of the full `npm run start` or `npm run build`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by shanek21** [comment]
Reviewed 61 of 61 files at r1.
Review status: 0 of 61 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuGiwC3lWXWUEWZ_puH:b-7s1bh9) (no related file):*
I think it makes sense to add the tagprobot-resources repo as a submodule in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuGu7JrMEvbSmB89ZeQ:b-my8yck) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I think it makes sense to add the tagprobot-resources repo as a submodule in this PR.
</blockquote></details>

I agree. Sorry, I wasnt sure if that was already happening in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuHJme3mVXgPf1fqjWn:b-zdlv5w) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I agree. Sorry, I wasnt sure if that was already happening in this PR.
</blockquote></details>

Oh yeah my bad I forgot about that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuHV8kTRKq4ep3woTtI:bb6un1j) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Oh yeah my bad I forgot about that
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by davidabrahams** [comment]
Review status: 61 of 63 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuHhTsoVckWWstC2LAA:b4fygoh) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Just to clarify, are all these images now on the sub module, not the TPB repo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 2 files at r2.
Review status: 61 of 63 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuHt8eRl1CZ6c_M-Kq6:b-7zogcu) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Just to clarify, are all these images now on the sub module, not the TPB repo?
</blockquote></details>

Correct.  Now all the resources are stored in a different repo (https://github.com/chauncy-crib/tagprobot-resources).  You may have to run some sort of update submodule command when the submodule updates because I think it just points to a specific commit.  But that shouldn't happen too often.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by shanek21** [comment]
Review status: 61 of 63 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuL41p3BUpiFVy6RNH8:-KuL41p3BUpiFVy6RNH9:b8jcu75) (no related file):*
It might also be nice to link to the Onboarding section of our wiki from the README.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuL41p3BUpiFVy6RNH8:-KuLZ3MKOxs4hgc27Naq:bb6un1j) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

It might also be nice to link to the Onboarding section of our wiki from the README.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: 60 of 63 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 61 of 63 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207#-KuGiwC3lWXWUEWZ_puG:-KuMaqSDnjVMCE48puru:b2rpd02) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Correct.  Now all the resources are stored in a different repo (https://github.com/chauncy-crib/tagprobot-resources).  You may have to run some sort of update submodule command when the submodule updates because I think it just points to a specific commit.  But that shouldn't happen too often.
</blockquote></details>

Beautiful. Thanks Billo!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/207)*

**Pull request merged**
