### PR TITLE
92: Cache map elements to save runtime

### LINKED ISSUE #92: Cache map elements that don't change

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #92 

```
let mapTraversabilityCells;
let tilesToUpdate; // A list of x, y pairs, which are the locations in the map that might change
let tilesToUpdateValues; // the values stored in those locations
```

We store three variables: the traversability cells of the map, the tiles that can change, and the values in those locations. We then fill `mapTraversabilityCells` once when the map loads, and create a list of the tiles that might change. Then, at every iteration, we loop through the tiles that might change, check if they changed, and if they did, update `mapTraversabilityCells`.

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/104)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kqy2-7TMydp3x40CvMa:-Kqy2-7TMydp3x40CvMb:bytthv3) (no related file):*
TODO:

[ ] add unit tests that specifically make sure the correct things are cached, and the correct things are updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/tiles.js, line 103 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kr8ahZhomcAcAkeA6T6:-Kr8ahZhomcAcAkeA6T7:b-jlcr4x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69a117abb4e67cd0a94a28faff20fd7d1000681a/src/tiles.js#L103)):*
> ```JavaScript
> export function isPermanent(tileID) {
>   return getTileProperty(tileID, 'permanent');
> }
> ```

No `@return`?
:disappointed: 
Did I lose this battle?

---

*[test/tiles.spec.js, line 125 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kr8c-KQW9OtwIpQ4TAf:-Kr8c-KQW9OtwIpQ4TAg:bekaco6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69a117abb4e67cd0a94a28faff20fd7d1000681a/test/tiles.spec.js#L125)):*
> ```JavaScript
>   t.true(isPermanent(7)); // spike
>   teardownTiles();
>   t.end();
> ```

:white_large_square: :space_invader: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/tiles.spec.js, line 125 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kr8c-KQW9OtwIpQ4TAf:-Kr9Qz2uJfwZ7rxkeGxB:bc4tx5x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69a117abb4e67cd0a94a28faff20fd7d1000681a/test/tiles.spec.js#L125)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

:white_large_square: :space_invader: 
</blockquote></details>

Sorry, what are you trying to tell me here? haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/tiles.spec.js, line 125 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kr8c-KQW9OtwIpQ4TAf:-KrAsXVJ_Fwtvt3Rqyca:bxpsbu2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69a117abb4e67cd0a94a28faff20fd7d1000681a/test/tiles.spec.js#L125)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Sorry, what are you trying to tell me here? haha
</blockquote></details>

New line before `t.end();` hahaha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/tiles.js, line 103 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kr8ahZhomcAcAkeA6T6:-KrBSyxhmnDM8B1sDViM:b-84ys22) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69a117abb4e67cd0a94a28faff20fd7d1000681a/src/tiles.js#L103)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

No `@return`?
:disappointed: 
Did I lose this battle?
</blockquote></details>

I believe you did

---

*[test/tiles.spec.js, line 125 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kr8c-KQW9OtwIpQ4TAf:-KrBUCRfdrV2t8a0ikUn:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69a117abb4e67cd0a94a28faff20fd7d1000681a/test/tiles.spec.js#L125)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

New line before `t.end();` hahaha
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kqy2-7TMydp3x40CvMa:-KrK7OhU11RDrlvBkIN5:b-896fja) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

TODO:

[ ] add unit tests that specifically make sure the correct things are cached, and the correct things are updated.
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/tiles.js, line 3 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL9fnpz8Hrb-3zKHHF:-KrL9fnpz8Hrb-3zKHHG:b7ds9d1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L3)):*
> ```JavaScript
> import keys from 'lodash/keys';
> import forOwn from 'lodash/forOwn';
> import isEmpty from 'lodash/isEmpty';
> ```

Where is this `isEmpty` function coming from? Is it defined by us? I never understood what `lodash` was.

---

*[src/tiles.js, line 75 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLA33Z0b3V_yRQSi0l:-KrLA33Z0b3V_yRQSi0m:bnszvop) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L75)):*
> ```JavaScript
>  * @return - the property for the input tile
>  */
> export function propertyFromId(tileID, property) {
> ```

 Maybe rename to:
`getPropertyFromId` or
`getTilePropertyFromId` or
`getPropertyFromTileId`?

---

*[src/tiles.js, line 88 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL9-Q6XWOltsnYUwvr:-KrL9-Q6XWOltsnYUwvs:b-myp6uf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L88)):*
> ```JavaScript
>  * @return - the property for the input tile
>  */
> export function propertyFromName(tileName, property) {
> ```

 Maybe rename to:
`getPropertyFromName` or
`getTilePropertyFromName` or
`getPropertyFromTileName`?

---

*[src/helpers/map.js, line 9 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL_GsbJHOJJkMv1f5C:-KrL_GsbJHOJJkMv1f5D:b-lpmkx7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/helpers/map.js#L9)):*
> ```JavaScript
> // A list of x, y pairs, which are the locations in the map that might change
> const tilesToUpdate = [];
> const tilesToUpdateValues = []; // the values stored in those locations
> ```

Do you not want to do another dictionary type thing like you did with the `tileTypes`?

---

*[src/helpers/map.js, line 104 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLRGim3kmX3hcidJ-7:-KrLRGim3kmX3hcidJ-8:bv1skua) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/helpers/map.js#L104)):*
> ```JavaScript
>   let x;
>   for (x = 0; x < xl * CPTL; x++) {
>     mapTraversabilityCells.push(new Array(yl * CPTL));
> ```

This should probably use `init2dArray()`

---

*[test/map.spec.js, line 326 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLaZy9mWty-fJkGJv7:-KrLaZy9mWty-fJkGJv8:b69o1bn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/map.spec.js#L326)):*
> ```JavaScript
>   // initialize current player as blue
>   setupTiles(true);
>   MapRewireAPI.__Rewire__('CPTL', 1);
> ```

This is probably my fault, but we should rewire `PPCL` anywhere that we rewire `CPTL`. So, for this one, `MapRewireAPI.__Rewire__('PPCL', 40);`. You could fix them all here or you could make an issue and assign me.

---

*[test/map.spec.js, line 525 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLc6DFJOYfIKEvsc_H:-KrLc6DFJOYfIKEvsc_I:bp17b4b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/map.spec.js#L525)):*
> ```JavaScript
>     [0, 1, 1],
>     [1, 0, 0],
>   ]);
> ```

Hmm... I actually kind of like this style of putting the expected output in-line instead of making an `expected` variable.

---

*[test/tiles.spec.js, line 80 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLcQSoK8uRQdvDEuUd:-KrLcQSoK8uRQdvDEuUe:bv1aur) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/tiles.spec.js#L80)):*
> ```JavaScript
>   const mockAmBlue = sinon.stub().returns(true);
>   TileRewireAPI.__Rewire__('amBlue', mockAmBlue);
>   TileRewireAPI.__Rewire__('amRed', mockAmRed);
> ```

This is new. Does the old way of mocking `amRed` and `amBlue` not work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: 4 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/tiles.js, line 3 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL9fnpz8Hrb-3zKHHF:-KrMoeB7CPJA4dl-MYBK:b-fsqv73) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L3)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Where is this `isEmpty` function coming from? Is it defined by us? I never understood what `lodash` was.
</blockquote></details>

FYI it's a set of javascript utility functions that basically allow Javascript to behave like a normal programming language. https://lodash.com/

For info on what isEmpty does: 

https://lodash.com/docs/4.17.4#isEmpty

---

*[src/tiles.js, line 75 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLA33Z0b3V_yRQSi0l:-KrMowovFC_NLFZtGcUQ:b-cdvmoi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L75)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

 Maybe rename to:
`getPropertyFromId` or
`getTilePropertyFromId` or
`getPropertyFromTileId`?
</blockquote></details>

I decided to omit the `get` because the function will be called frequently, and it's inputs make it clear what it is doing, so I opted for conciseness. Up to you if I should change it

---

*[src/tiles.js, line 88 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL9-Q6XWOltsnYUwvr:-KrMp8KL93rteSCOcmn5:b-34vmyd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L88)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

 Maybe rename to:
`getPropertyFromName` or
`getTilePropertyFromName` or
`getPropertyFromTileName`?
</blockquote></details>

See above

---

*[src/helpers/map.js, line 9 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL_GsbJHOJJkMv1f5C:-KrMpBMnxiF74_hKkMnx:bd70z3c) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/helpers/map.js#L9)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Do you not want to do another dictionary type thing like you did with the `tileTypes`?
</blockquote></details>

I actually did, but making objects the keys to a dict in Javascript is a pain, because it doesn't hash the objects. Instead, it just uses their "toString" method. This implementation ends up being a lot cleaner.

---

*[src/helpers/map.js, line 104 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLRGim3kmX3hcidJ-7:-KrMpOhFgHXhApULx7wZ:b-obuyd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/helpers/map.js#L104)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

This should probably use `init2dArray()`
</blockquote></details>

Wow how did we never notice that. Because this code changes significantly in #104, I made the appropriate updates there to avoid rebase headaches.

---

*[test/map.spec.js, line 326 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLaZy9mWty-fJkGJv7:-KrMr5EBYwOVDX5V6kqp:b-aqwd7d) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/map.spec.js#L326)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

This is probably my fault, but we should rewire `PPCL` anywhere that we rewire `CPTL`. So, for this one, `MapRewireAPI.__Rewire__('PPCL', 40);`. You could fix them all here or you could make an issue and assign me.
</blockquote></details>

Doing the latter. Thanks!

---

*[test/map.spec.js, line 525 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLc6DFJOYfIKEvsc_H:-KrMsjmt9QhiBzeOW7gg:bebokmy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/map.spec.js#L525)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Hmm... I actually kind of like this style of putting the expected output in-line instead of making an `expected` variable.
</blockquote></details>

Should we open an issue to do that everywhere? haha

---

*[test/tiles.spec.js, line 80 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLcQSoK8uRQdvDEuUd:-KrMsp9VPfqSiNOcRZ18:b-gas5h3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/tiles.spec.js#L80)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

This is new. Does the old way of mocking `amRed` and `amBlue` not work?
</blockquote></details>

This does almost the same thing, except making them stubs allows me to also check that they were called. See line 93 in this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/tiles.js, line 75 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLA33Z0b3V_yRQSi0l:-KrOIYT6lSD0pYGApX2Y:bo2fk7d) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L75)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I decided to omit the `get` because the function will be called frequently, and it's inputs make it clear what it is doing, so I opted for conciseness. Up to you if I should change it
</blockquote></details>

I think you should change it for clarity and consistency.

---

*[src/tiles.js, line 88 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL9-Q6XWOltsnYUwvr:-KrOIgPIHmX1d97-_XUP:b-34vmyd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L88)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above

---

*[src/helpers/map.js, line 20 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrOJv68R2lLvhow-qn4:-KrOJv68R2lLvhow-qn5:b-thdi24) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2d0df03d2ee77666a91a81f0f7b7fa2fc20fc428/src/helpers/map.js#L20)):*
> ```JavaScript
>  * @param {number} defaultVal - the value to give each element in the initialized 2D array
>  */
> export function init2dArray(width, height, defaultVal = 0, inputMatrix = undefined) {
> ```

Why pass in an `inputMatrix`?

---

*[test/map.spec.js, line 525 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLc6DFJOYfIKEvsc_H:-KrOIwVZcV_g6uqHRGO_:bwbojk3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/map.spec.js#L525)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Should we open an issue to do that everywhere? haha
</blockquote></details>

Meh...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/map.spec.js, line 525 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLc6DFJOYfIKEvsc_H:-KrO_6Hd_f7v5-JGiGaz:btklu9n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/test/map.spec.js#L525)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Meh...
</blockquote></details>

I did it anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tiles.js, line 75 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrLA33Z0b3V_yRQSi0l:-KrOiDPKCi3bMyBqf-ku:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L75)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I think you should change it for clarity and consistency.
</blockquote></details>

Done.

---

*[src/tiles.js, line 88 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrL9-Q6XWOltsnYUwvr:-KrOiGNqbJdvqiUjT52R:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/472ccb4474ca4d2d436a43f9a38a5ae314978945/src/tiles.js#L88)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

---

*[src/helpers/map.js, line 20 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrOJv68R2lLvhow-qn4:-KrOgcJ5JG06CItep-vC:b-7o6wx3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2d0df03d2ee77666a91a81f0f7b7fa2fc20fc428/src/helpers/map.js#L20)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why pass in an `inputMatrix`?
</blockquote></details>

In order to unittest `initMapTraversabilityCells` and check it was properly assigning `mapTraversabilityCells`, I had to make `initMapTraversabilityCells` modify `mapTraversabilityCells` rather than reassign it, so that I could mock `mapTraversabilityCells` and then check that it changed after I called the function. This update makes `init2dArray` able to modify an input, rather than simply returning a new array.

@billmwong Any insight with respect to if its possible unittest that a function properly reassigns a variable? If so, then I can change this back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/helpers/map.js, line 20 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrOJv68R2lLvhow-qn4:-KrQNMq55QCaMpq6udb8:b-vqe5s5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2d0df03d2ee77666a91a81f0f7b7fa2fc20fc428/src/helpers/map.js#L20)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

In order to unittest `initMapTraversabilityCells` and check it was properly assigning `mapTraversabilityCells`, I had to make `initMapTraversabilityCells` modify `mapTraversabilityCells` rather than reassign it, so that I could mock `mapTraversabilityCells` and then check that it changed after I called the function. This update makes `init2dArray` able to modify an input, rather than simply returning a new array.

@billmwong Any insight with respect to if its possible unittest that a function properly reassigns a variable? If so, then I can change this back.
</blockquote></details>

If you reassign it does it essentially undo your mock?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/helpers/map.js, line 20 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-KrOJv68R2lLvhow-qn4:-KrRW7kctSZbjIZ0JNaq:b7u03hh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2d0df03d2ee77666a91a81f0f7b7fa2fc20fc428/src/helpers/map.js#L20)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

If you reassign it does it essentially undo your mock?
</blockquote></details>

Correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-Kqy2-7TMydp3x40CvMa:-KrT4YuECsIHBrzUwZYa:bcbqss6) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done!
</blockquote></details>

:dango:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Comment by shanek21** [comment]
:dango:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104#-:-KrT4aLvgYPjzOaSUgG2:bcbqss6)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/104)*

**Pull request merged**
