### PR TITLE
187: add return type to heuristic function

### LINKED ISSUE #187: return type missing on heuristic() in helpers/path.js

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #187

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/239)

### CODE REVIEW

**Comment by billmwong** [comment]
:dango:

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/239#-:-KxfIkIuPoa3JYjNwm7O:bcbqss6)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/239)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/239)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/239#-KxhtEKYnLyW8ESMySku:-KxnJmTiM1v2uApx6qBI:bb7f2mf) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

This is pretty nit, but to me that commit isn't descriptive enough because it doesn't specifically mention A*.  `187: add return type to A* heuristic function`?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/239)*

**Pull request merged**
