### PR TITLE
411: LQR Deadline

### LINKED ISSUE #411: Dynamically determine LQR deadline
Determine how many seconds the bot should take to reach the goal state

Use euclidean distance and divide by some assumption about our average velocity.

### PR DESCRIPTION
**Pull request by billmwong**
Closes #411

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 159 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC41iDU7sD5sFY5yvNn:-LC59YC-4TqlIfy_etbi:brz23m2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L159)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

It feels dissimilar to our other code to be using arrays to represent states instead of an object with `x`, `y`, `vx`, and `vy` attributes. Are you using these because they are closer to matrices?
</blockquote></details>

Yeah I guess I could input objects to the getLQRstuff function and then just convert them to Matrices when I need to.  Then I could pass in the objects into the determineDeadline() function and this will be more readable, what do you think of that?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/control/lqr.js, line 159 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC41iDU7sD5sFY5yvNn:-LC6FPS79eORBvv8XmHY:b-ba7jdc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L159)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Yeah I guess I could input objects to the getLQRstuff function and then just convert them to Matrices when I need to.  Then I could pass in the objects into the determineDeadline() function and this will be more readable, what do you think of that?
</blockquote></details>

Sounds good to me!

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by davidabrahams** [comment]
*[src/control/test/lqr.spec.js, line 85 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC6G-mu79MVrDfEahsD:-LC6G-mu79MVrDfEahsE:ba6h1v0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/test/lqr.spec.js#L85)):*
> ```JavaScript
> 
> test('determineDeadline', tester => {
>   tester.test('uses average velocity to determind deadline', t => {
> ```

"determine"

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 163 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC414xnBJsFsFgWlCoi:-LC6VW9pBzrDjW8EKX9-:bhuemyw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L163)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Thinking through this a bit more, I'm not sure this heuristic is a good one. Maybe something like `goalVelocity.subtract(initialVelocity).magnitude() / ACCEL` would be more appropriate? Maybe talk in person?
</blockquote></details>

+ distance/ACCEL

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/control/lqr.js, line 163 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC414xnBJsFsFgWlCoi:-LC6ZdsXAA7B71UvC6Zz:b-9rl7fp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L163)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

+ distance/ACCEL
</blockquote></details>

^ I think you meant distance/MAX_VEL, plus the thing shane said initially?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by davidabrahams** [comment]
*[src/control/lqr.js, line 175 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC6ZnzxCjzYdohbKJUy:-LC6ZnzxCjzYdohbKJUz:b-dg1c6f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L175)):*
> ```JavaScript
>  */
> export function getLQRAccelerationMultipliers(initialState, goalState) {
>   const T = Math.floor(FPS * determineDeadline(initialState, goalState)); // number of time steps
> ```

Is FPS constant? If our bot is laggy, doesn't that drop FPS? there maybe a problem if we assume that we're actually applying our control on a fixed interval schedule, and this isnt the case

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 175 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC6ZnzxCjzYdohbKJUy:-LC6_AAv1IT9Y5-Jvfno:b-q7k5pn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L175)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Is FPS constant? If our bot is laggy, doesn't that drop FPS? there maybe a problem if we assume that we're actually applying our control on a fixed interval schedule, and this isnt the case
</blockquote></details>

How do you want me to handle this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/control/lqr.js, line 163 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC414xnBJsFsFgWlCoi:-LC6gVqK734BhyuLbn_5:b-c9veam) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L163)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

^ I think you meant distance/MAX_VEL, plus the thing shane said initially?
</blockquote></details>

I think it should be `(distance / MAX_VEL) + (goalVelocity.subtract(initialVelocity).magnitude() / ACCEL)`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by billmwong** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/control/lqr.js, line 159 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC41iDU7sD5sFY5yvNn:-LC6d4TS6wffcKHV9OEi:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L159)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Sounds good to me!
</blockquote></details>

Done.

---

*[src/control/lqr.js, line 163 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC414xnBJsFsFgWlCoi:-LC6moepBvog1ALzS7fS:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L163)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I think it should be `(distance / MAX_VEL) + (goalVelocity.subtract(initialVelocity).magnitude() / ACCEL)`
</blockquote></details>

Done.

---

*[src/control/test/lqr.spec.js, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC42L_C0nXQjyqp2ERO:-LC6XBhWBkI5_RVMmM6P:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/test/lqr.spec.js#L35)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Replace `total time` with `deadline`?
</blockquote></details>

Done.

---

*[src/control/test/lqr.spec.js, line 85 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC6G-mu79MVrDfEahsD:-LC6XEq6E8teWNJiuBJS:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/test/lqr.spec.js#L85)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

"determine"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/control/lqr.js, line 152 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC97r0y0tptd00M1-BH:-LC97r0y0tptd00M1-BI:b9czx8z) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L152)):*
> ```JavaScript
>  * @param {{x: number, y: number, vx: number, vy: number}} initialState
>  * @param {{x: number, y: number, vx: number, vy: number}} goalState
>  * @returns {number} the best guess for the number of seconds it will take to reach the goal state
> ```

Should this `@returns` be `number of frames` instead of `number of seconds`?

---

*[src/control/lqr.js, line 162 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC97GhP-Jjp8G1df3KC:-LC97GhP-Jjp8G1df3KD:b-2epozt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L162)):*
> ```JavaScript
>   const distance = initialPoint.distance(goalPoint);
>   // const averageVelocity = (initialVelocity.magnitude() + goalVelocity.magnitude()) / 2;
>   // let seconds = distance / averageVelocity;
> ```

Remove these comments?

---

*[src/control/lqr.js, line 199 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC98SBsAAF6XJeHxH7F:-LC98SBsAAF6XJeHxH7G:b57n7g3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L199)):*
> ```JavaScript
>   x.append([[1]]);
>   const u = currentKs.get(currentTime).scalarMultiply(-1).dot(x); // [[ax], [ay]]
>   currentTime += 1;
> ```

I realize this is old stuff, but I'm starting to get confused about how `currentTime` works in relation to the `currentDeadline`. Would you mind talking in person?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 198 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LCATvd06La0PJSPvp23:-LCATvd06La0PJSPvp24:bgu0x7b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L198)):*
> ```JavaScript
>   const x = iStateMatrix.subtract(gStateMatrix);
>   x.append([[1]]);
>   const u = currentKs.get(currentTime).scalarMultiply(-1).dot(x); // [[ax], [ay]]
> ```

look into negative indexing

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by billmwong** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/control/lqr.js, line 175 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC6ZnzxCjzYdohbKJUy:-LCAZgn95_d29lyRMdLj:b6qpc5j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9a06849a75e44c74b77a7b0b78436592ee914a61/src/control/lqr.js#L175)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Hmmm. Perhaps calculate which "timestep" we're in by keeping a timer since we recalculated the K-matrices? Ie, if the game lags, we would skip a few matrices (which is probably best). If that's too much for this PR, maybe open a card?
</blockquote></details>

I think this is done now that we determine a new deadline each frame

---

*[src/control/lqr.js, line 152 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC97r0y0tptd00M1-BH:-LCA_80ZEKj4YOP6vZuO:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L152)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Should this `@returns` be `number of frames` instead of `number of seconds`?
</blockquote></details>

Done.

---

*[src/control/lqr.js, line 162 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC97GhP-Jjp8G1df3KC:-LCA_9Ww4tS29OEkkbZf:bff6wki) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L162)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Remove these comments?
</blockquote></details>

Done, sorry

---

*[src/control/lqr.js, line 199 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/437#-LC98SBsAAF6XJeHxH7F:-LCAZbwg03xvHB3U4Rhj:bio929g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06f771e27162b21057201ec183bbcd4ed1b09972/src/control/lqr.js#L199)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I realize this is old stuff, but I'm starting to get confused about how `currentTime` works in relation to the `currentDeadline`. Would you mind talking in person?
</blockquote></details>

Done by getting rid of currentTime and currentDeadline globals

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)*

**Pull request merged**
