### PR TITLE
466: draw local goal velocity

### LINKED ISSUE #466: Draw local goal velocity

### PR DESCRIPTION
**Pull request by shanek21**
Closes #466

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/global/class/Vector.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRtWo659VRAiiC5VwC:-LCRtWo659VRAiiC5VwD:bfftroj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f64d7f50aa94e59abb2f5cb7e019b808bee6529/src/global/class/Vector.js#L31)):*
> ```JavaScript
> 
> 
>   magnitude() {
> ```

repeated code, thoughts?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by billmwong** [comment]
Reviewed 7 of 14 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/triangulation.js, line 86 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRt4Lg6TlWZ1zmj6Hg:-LCRt4Lg6TlWZ1zmj6Hh:b-chjkuq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e93d49c67ff934978c9809935dfe776e835cb207/src/draw/triangulation.js#L86)):*
> ```JavaScript
>     enemyPathGraphics.clear();
>   }
> }
> ```

FYI thank you for moving this to another file :raised_hands: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
*[src/draw/arrow.js, line 19 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRuduB95QTg36AkxS4:-LCRuduB95QTg36AkxS5:bq1cfgx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/draw/arrow.js#L19)):*
> ```JavaScript
>   const base = new Point(x, y);
>   const arrow = new Vector(dx, dy);
>   const { p1, p2 } = arrow.getPerpindicularEdgeBisectedByTip(width, base);
> ```

`Perpendicular`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by shanek21** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/draw/arrow.js, line 19 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRuduB95QTg36AkxS4:-LCRvnCZAAH6iGerLK5k:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/draw/arrow.js#L19)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

`Perpendicular`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by shanek21** [comment]
*[src/draw/draw.js, line 57 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRrv6bBeFSzs574cOe:-LCRw9t09Hx8WbHwTd1p:b-x65a7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/draw/draw.js#L57)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why did you move keys down here doe
</blockquote></details>

Chronological order. Get the triangulation, find our path, get our local goal, get our key presses.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
*[src/global/class/Vector.js, line 24 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRw5m55BxIT-g7utRz:-LCRw5m55BxIT-g7utS-:b2kz6jr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/global/class/Vector.js#L24)):*
> ```JavaScript
>    */
>   slope() {
>     assert(!this.magnitude === 0, 'Cannot calculate the slope of a vector with zero magnitude');
> ```

i think what this assert is doing is

`assert((!this.magnitude) === 0)`

which becomes either

`assert(true === 0)`
`assert(false === 0)`

which both evaluate to false

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
*[src/global/class/Vector.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRtWo659VRAiiC5VwC:-LCRwQXJCYoVAiJejNnS:bi88pju) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f64d7f50aa94e59abb2f5cb7e019b808bee6529/src/global/class/Vector.js#L31)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

repeated code, thoughts?
</blockquote></details>

i like it because it makes this class represent a vector better

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
Reviewed 13 of 14 files at r1.
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/draw/localGoal.js, line 24 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRvYWVAVjQOT0VC_3F:-LCRvYWVAVjQOT0VC_3G:bm4yqa0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/draw/localGoal.js#L24)):*
> ```JavaScript
>     x,
>     y,
>     vx / 5,
> ```

make this 5 a const somewhere?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by shanek21** [comment]
*[src/global/class/Vector.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRtWo659VRAiiC5VwC:-LCRwkFDBk3mKJ1G80it:bo0pq9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f64d7f50aa94e59abb2f5cb7e019b808bee6529/src/global/class/Vector.js#L31)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i like it because it makes this class represent a vector better
</blockquote></details>

Yeah, I'm not sure how to make them not have some shared code....

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 14 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by shanek21** [comment]
Review status: 10 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/draw/localGoal.js, line 24 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRvYWVAVjQOT0VC_3F:-LCRz8V09yen7fW9an91:bcvjgzp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/draw/localGoal.js#L24)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

make this 5 a const somewhere?
</blockquote></details>

Good idea. Done.

---

*[src/global/class/Vector.js, line 24 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRw5m55BxIT-g7utRz:-LCRz7ZvA_J23UcIlhQm:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d499f0409e9e5e8dea740d77b4c9e4967d25cd73/src/global/class/Vector.js#L24)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i think what this assert is doing is

`assert((!this.magnitude) === 0)`

which becomes either

`assert(true === 0)`
`assert(false === 0)`

which both evaluate to false
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by billmwong** [comment]
*[src/global/class/Vector.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRtWo659VRAiiC5VwC:-LCS1Y1ODz5HHvuVTOnH:b4wtj4g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f64d7f50aa94e59abb2f5cb7e019b808bee6529/src/global/class/Vector.js#L31)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yeah, I'm not sure how to make them not have some shared code....
</blockquote></details>

Make an umbrella class, thoughts

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by shanek21** [comment]
Review status: 9 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/global/class/Vector.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRtWo659VRAiiC5VwC:-LCS2r5B0cftiUcOaxUY:b9kabi5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f64d7f50aa94e59abb2f5cb7e019b808bee6529/src/global/class/Vector.js#L31)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Make an umbrella class, thoughts
</blockquote></details>

I removed `Point.magnitude()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by billmwong** [comment]
Reviewed 1 of 3 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/global/class/Vector.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/492#-LCRtWo659VRAiiC5VwC:-LCS6Qq02pnKzuvlh2Gh:b8ln68w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/2f64d7f50aa94e59abb2f5cb7e019b808bee6529/src/global/class/Vector.js#L31)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I removed `Point.magnitude()`.
</blockquote></details>

OK I made #493

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)*

**Pull request merged**
