### PR TITLE
263: add edge class

### LINKED ISSUE #263: Make Edge a class
Right now we pass around {p1: Point, p2: Point} objects.

### PR DESCRIPTION
**Pull request by shanek21**
Closes #263

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/355)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 1 of 15 files at r1.
Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
Reviewed 14 of 15 files at r1.
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 96 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YTcOK7XSIua4f08xU:-L6YTcOK7XSIua4f08xV:bmhc5qs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/utils.js#L96)):*
> ```JavaScript
>  *   infinitely in both directions
>  */
> export function areEdgesCollinear(e1, e2) {
> ```

should this be a class method?

---

*[src/interpret/utils.js, line 107 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YTaGzbeuVQU6XWVOw:-L6YTaGzbeuVQU6XWVOx:bmhc5qs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/utils.js#L107)):*
> ```JavaScript
>  * @returns {boolean} if the two points are on the same side of the edge
>  */
> export function pointsOnSameSide(p1, p2, e) {
> ```

should this be a class method?

---

*[src/interpret/utils.js, line 170 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YTjlZ88ZtshnHuqb8:-L6YTjl_coz8GNRT5fWx:b-rf9o30) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4c26cc5d1a27d513f63d4f51561bfbcd01bc42a5/src/interpret/utils.js#L170)):*
> ```JavaScript
>  * @returns {boolean} if the triangle intersects or touches the edge
>  */
> export function isTriangleIntersectingEdge(t, e) {
> ```

should this be a class method? either on Triangle or Edge

---

*[src/interpret/utils.js, line 186 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YU1gngLuhvkPvF_2_:-L6YU1gngLuhvkPvF_2a:b2o6ky6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4c26cc5d1a27d513f63d4f51561bfbcd01bc42a5/src/interpret/utils.js#L186)):*
> ```JavaScript
>   if (!pointsOnSameSide(e.p1, t.p2, t31) && !pointsOnSameSide(e.p2, t.p2, t31)) return false;
> 
>   return true;
> ```

is there a reason you changed all this stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by davidabrahams** [comment]
Reviewed 15 of 15 files at r1.
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 96 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YTcOK7XSIua4f08xU:-L6YVNlQL83GSQxn_A3G:b-bohk0m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/utils.js#L96)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

should this be a class method?
</blockquote></details>

I rly like something like e1.isCollinearWith(e2)

---

*[src/interpret/utils.js, line 107 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YTaGzbeuVQU6XWVOw:-L6YVRgvFLL0-yeesot7:b-lr0xth) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/utils.js#L107)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

should this be a class method?
</blockquote></details>

ditto here

---

*[src/interpret/utils.js, line 170 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YTjlZ88ZtshnHuqb8:-L6YVZJNpyHVxpPAHxwE:bogkgpi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4c26cc5d1a27d513f63d4f51561bfbcd01bc42a5/src/interpret/utils.js#L170)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

should this be a class method? either on Triangle or Edge
</blockquote></details>

I like it. Put it in triangle?

---

*[src/interpret/class/test/Graph.spec.js, line 2 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YVm22w1oUgtVzw2ac:-L6YVm22w1oUgtVzw2ad:b4x1oad) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/test/Graph.spec.js#L2)):*
> ```JavaScript
> import test from 'tape';
> import { Graph } from '../Graph';
> ```

so sorry that you had to rewrite all these tests :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 12 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 96 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YTcOK7XSIua4f08xU:-L6YWz9G-nKa6YEJAMWC:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/utils.js#L96)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I rly like something like e1.isCollinearWith(e2)
</blockquote></details>

Done.

---

*[src/interpret/utils.js, line 186 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YU1gngLuhvkPvF_2_:-L6YVH3PBtQebt8mjk4X:b9lhegt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4c26cc5d1a27d513f63d4f51561bfbcd01bc42a5/src/interpret/utils.js#L186)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is there a reason you changed all this stuff
</blockquote></details>

Yeah I thought it was confusing that `e1` and `e2` were not a first and second edge. They were the first and second points on an edge.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 12 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 107 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YTaGzbeuVQU6XWVOw:-L6YZXdP8EkC9JZHzBz_:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/utils.js#L107)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

ditto here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
*[src/interpret/class/Edge.js, line 35 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6Y_UbVlmx5dYZFAnyO:-L6Y_UbVlmx5dYZFAnyP:b-al21f9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/24baf070947378952293a3736b86dab90d0433db/src/interpret/class/Edge.js#L35)):*
> ```JavaScript
>    * @returns {boolean} if the two points are on the same side of the edge
>    */
>   onSameSideOfPoints(p1, p2) {
> ```

I think of this as the points being on the same side of the edge, not the edge being on the same side of the points.  It might be confusing the way this is worded?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
Reviewed 3 of 4 files at r2, 5 of 5 files at r3.
Review status: 10 of 17 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/interpret/class/test/Edge.spec.js, line 7 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6Y_j9yB_FctxB8zA3G:-L6Y_j9yB_FctxB8zA3H:b-eva0t4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/24baf070947378952293a3736b86dab90d0433db/src/interpret/class/test/Edge.spec.js#L7)):*
> ```JavaScript
> 
> 
> test('pointsOnSameSide()', tester => {
> ```

rename to the new method name, also include "Edge" in the test string here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 9 of 19 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 170 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YTjlZ88ZtshnHuqb8:-L6YaX_79xP7ZUDrHe2j:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4c26cc5d1a27d513f63d4f51561bfbcd01bc42a5/src/interpret/utils.js#L170)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I like it. Put it in triangle?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 9 of 19 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/interpret/class/Edge.js, line 35 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6Y_UbVlmx5dYZFAnyO:-L6Yaaf6691zyBZ4tjkQ:bk6n13v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/24baf070947378952293a3736b86dab90d0433db/src/interpret/class/Edge.js#L35)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I think of this as the points being on the same side of the edge, not the edge being on the same side of the points.  It might be confusing the way this is worded?
</blockquote></details>

I thought about that, but I don't find it confusing.  I think it still reads smoothly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 9 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/interpret/class/test/Edge.spec.js, line 7 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6Y_j9yB_FctxB8zA3G:-L6Ybnj47dODqH9I2A3I:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/24baf070947378952293a3736b86dab90d0433db/src/interpret/class/test/Edge.spec.js#L7)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

rename to the new method name, also include "Edge" in the test string here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
*[src/interpret/class/Edge.js, line 35 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6Y_UbVlmx5dYZFAnyO:-L6YcSc5WMmsHQX5dQiW:bw5xeyo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/24baf070947378952293a3736b86dab90d0433db/src/interpret/class/Edge.js#L35)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I thought about that, but I don't find it confusing.  I think it still reads smoothly.
</blockquote></details>

@davidabrahams what do you think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
Reviewed 6 of 6 files at r4.
Review status: 9 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 8 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/interpret/class/Edge.js, line 35 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6Y_UbVlmx5dYZFAnyO:-L6Yi8CA2XWhWDf49G3H:b-yujt91) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/24baf070947378952293a3736b86dab90d0433db/src/interpret/class/Edge.js#L35)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

@davidabrahams what do you think
</blockquote></details>

changed to `Edge.isBetweenPoints()` per in-person discussion

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
Reviewed 6 of 6 files at r5.
Review status: 8 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 4 files at r2, 2 of 6 files at r5.
Review status: 8 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 6 files at r4, 4 of 6 files at r5.
Review status: 11 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Triangle.js, line 82 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6Yl46ElZwSTwtriQnz:-L6Yl46ElZwSTwtriQo-:b-io2756) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/Triangle.js#L82)):*
> ```JavaScript
>    * @returns {boolean} if the triangle intersects or touches the edge
>    */
>   isIntersectingEdge(e) {
> ```

intersectsEdge

---

*[src/interpret/class/test/Edge.spec.js, line 7 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YlBlexTB1urphtVic:-L6YlBlexTB1urphtVid:b-l7wfbh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/test/Edge.spec.js#L7)):*
> ```JavaScript
> 
> 
> test('Edge.isOnSameSideOfPoints()', tester => {
> ```

change test name to reflect function name change

---

*[src/interpret/class/test/Triangle.spec.js, line 24 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YlHl0Zvgoq7tWzQdj:-L6YlHl0Zvgoq7tWzQdk:b-io2756) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/test/Triangle.spec.js#L24)):*
> ```JavaScript
> 
> 
> test('isIntersectingEdge()', tester => {
> ```

intersectsEdge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Triangle.js, line 82 at r6](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6Yl46ElZwSTwtriQnz:-L6YlTEX2m3zaGTEWG7p:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/Triangle.js#L82)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

intersectsEdge
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/test/Triangle.spec.js, line 24 at r6](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YlHl0Zvgoq7tWzQdj:-L6YlYtk8FgStAQnhVo9:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/test/Triangle.spec.js#L24)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

intersectsEdge
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/interpret/class/test/Triangle.spec.js, line 26 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355#-L6YlfDrE0Mpy8I2aYfD:-L6YlfDrE0Mpy8I2aYfE:b-5lgxwn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/test/Triangle.spec.js#L26)):*
> ```JavaScript
> test('isIntersectingEdge()', tester => {
>   tester.test('returns true when two edges intersect edge', t => {
>     const edge = new Edge(new Point(2, 0), new Point(4, 0));
> ```

:no_entry_sign: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/interpret/class/test/Edge.spec.js, line 7 at r6](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YlBlexTB1urphtVic:-L6Yly0e9Yn_KC4ZMQqM:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/test/Edge.spec.js#L7)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

change test name to reflect function name change
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by shanek21** [comment]
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/interpret/class/test/Triangle.spec.js, line 26 at r6](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355#-L6YlfDrE0Mpy8I2aYfD:-L6Ym-ID6QN2RS7cFVU3:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c280cd40d6102eb6c51bbb1da4d8ad589675de66/src/interpret/class/test/Triangle.spec.js#L26)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

:no_entry_sign: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r7.
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r7, 3 of 3 files at r8.
Review status: 14 of 18 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r8.
Review status: 15 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/355)*

**Pull request merged**
