### PR TITLE
475: Offload funnelling to a worker

### LINKED ISSUE #475: Offload funnelling to a worker

### PR DESCRIPTION
**Pull request by billmwong**
Closes #475 

Funnelling from ~3ms down to 0.5ms

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/global/class/Point.js, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPlZ2t6egbMftnZrbj:-LCPlZ2t6egbMftnZrbk:b1zvh6v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/global/class/Point.js#L17)):*
> ```JavaScript
>     this.x = o.x;
>     this.y = o.y;
>     if (o.clearancePoint) this.clearancePoint = new Point().fromObject(o.clearancePoint);
> ```

is `clearancePoint` a Polypoint field? should this go in the polypoint class?

---

*[src/plan/class/PolypointState.js, line 10 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPpcb7DP7zVJctjsgs:-LCPpcb7DP7zVJctjsgt:be5iqb0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/class/PolypointState.js#L10)):*
> ```JavaScript
> 
> export class PolypointState extends State {
>   constructor(point = new Point()) {
> ```

perhaps the default behavior of this should be undefined, and then set `key` to undefined if `point` isnt passed in?

---

*[src/plan/class/PolypointState.js, line 19 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPpmxmBIqPL_JUVaqz:-LCPpmxmBIqPL_JUVar-:bcqplck) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/class/PolypointState.js#L19)):*
> ```JavaScript
>   fromObject(o) {
>     this.point = (new Point()).fromObject(o.point);
>     this.key = this.point.toString();
> ```

to stay consistent, you should get the key from `o`

---

*[src/plan/test/funnel.spec.js, line 123 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPqLyy2NG8K6HTJMa3:-LCPqLyy2NG8K6HTJMa4:b-adczrv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/test/funnel.spec.js#L123)):*
> ```JavaScript
>     const portals = getPortals(path, mockTriangleGraph);
>     const funnelledPoints = funnelPolypointsFromPortals(path, portals).map(state => state.point);
>     t.same(
> ```

now that these tests exist, can we add back the tests from the LQR worker? or at least reference this PR in that issue so we have a record of how to do it

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
*[src/plan/funnel.js, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ-2MS9u9_VrS2sdCj:-LCQ-2MS9u9_VrS2sdCk:b40lzop) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/funnel.js#L41)):*
> ```JavaScript
>   // Force the first point in the funnelledPath to be our current position even if we use an old
>   //   funnelledPath
>   if (currentFunnelledPath) [currentFunnelledPath[0]] = path;
> ```

this syntax is a little hard to read. Can you do:

```
currentFunnelledPath[0] = path[0]?
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/plan/funnel.js, line 9 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ-NnX2oqiH40RILQh:-LCQ-NnX2oqiH40RILQi:b-hjurhc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/funnel.js#L9)):*
> ```JavaScript
> 
> const funnelWorker = work(require.resolve('./funnel.worker.js'));
> let currentFunnelledPath = null;
> ```

comment these two variables

---

*[src/plan/funnel.js, line 16 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ0lFhEiXobSJQi7J0:-LCQ0lFhEiXobSJQi7J1:b-e0ocy9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/funnel.js#L16)):*
> ```JavaScript
>   if (ev.data.text === 'DONE') {
>     currentFunnelledPath = _.map(JSON.parse(ev.data.funnelledPath), stateObj => (
>       (new PolypointState()).fromObject(stateObj)
> ```

Have `funnel.js` have all the old code, `funnel.master.js` tor the funnel interface, `funnel.worker.js` which just has the worker

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ17wL7uecFjscxgTf:-LCQ17wL7uecFjscxgTg:b-xclf9e) (no related file):*
Once you split this into 3 files per discussion, can you open a card to change the LQR code to follow same convention? Maybe we would bring the tests back in that card as well

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
*[src/global/class/Point.js, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPlZ2t6egbMftnZrbj:-LCQ1IGX59mlqfRNy7uW:bvxfb2t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/global/class/Point.js#L17)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

is `clearancePoint` a Polypoint field? should this go in the polypoint class?
</blockquote></details>

No, clearance point is an optional Point field

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
*[src/plan/test/funnel.spec.js, line 123 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPqLyy2NG8K6HTJMa3:-LCQ1aQ76K6CqWKQpnF_:b-ktuag6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/test/funnel.spec.js#L123)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

now that these tests exist, can we add back the tests from the LQR worker? or at least reference this PR in that issue so we have a record of how to do it
</blockquote></details>

Done, added a reference in #463

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/global/class/Point.js, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPlZ2t6egbMftnZrbj:-LCQ4ixQ69kyXWyMrP6v:b-fq5rnv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/global/class/Point.js#L17)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

No, clearance point is an optional Point field
</blockquote></details>

ohhhh. oops myb

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ17wL7uecFjscxgTf:-LCQGvm3CqCzZJIFmcgy:ba680a6) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Once you split this into 3 files per discussion, can you open a card to change the LQR code to follow same convention? Maybe we would bring the tests back in that card as well
</blockquote></details>

added to #463

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/plan/funnel.js, line 9 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ-NnX2oqiH40RILQh:-LCQH7H20E2eUaSTbMku:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/funnel.js#L9)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

comment these two variables
</blockquote></details>

Done.

---

*[src/plan/funnel.js, line 16 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ0lFhEiXobSJQi7J0:-LCQH6OaAypsFvzQJjQG:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/funnel.js#L16)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Have `funnel.js` have all the old code, `funnel.master.js` tor the funnel interface, `funnel.worker.js` which just has the worker
</blockquote></details>

Done.

---

*[src/plan/funnel.js, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQ-2MS9u9_VrS2sdCj:-LCQ1Mya8gFNHAwbXoCi:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/funnel.js#L41)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

this syntax is a little hard to read. Can you do:

```
currentFunnelledPath[0] = path[0]?
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/plan/class/PolypointState.js, line 10 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPpcb7DP7zVJctjsgs:-LCQHysXB5VfPd_9gt4l:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/class/PolypointState.js#L10)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

perhaps the default behavior of this should be undefined, and then set `key` to undefined if `point` isnt passed in?
</blockquote></details>

Done.

---

*[src/plan/class/PolypointState.js, line 19 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCPpmxmBIqPL_JUVaqz:-LCQHyf37-M2r497Ld_6:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/218afc176d0156a816d03e5cfe168b0bddb5f395/src/plan/class/PolypointState.js#L19)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

to stay consistent, you should get the key from `o`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by shanek21** [comment]
Reviewed 1 of 6 files at r1, 8 of 9 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/plan/funnel.js, line 12 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQIytH9m2sGwQFix-K:-LCQIytH9m2sGwQFix-L:bn5njma) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999c75fc16ef5aaa8c431c58397cba1c7348cfa/src/plan/funnel.js#L12)):*
> ```JavaScript
>  * @param {PolypointState[]} path
>  * @param {TriangleGraph} triangleGraph
>  * @returns {[Point[], Point[]]} list of the left and right points in each
> ```

Can you change this docstring to use the full 100 character limit

---

*[src/plan/funnel.master.js, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQJMjc339qcU4y8N54:-LCQJMjc339qcU4y8N55:b-is47nq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999c75fc16ef5aaa8c431c58397cba1c7348cfa/src/plan/funnel.master.js#L36)):*
> ```JavaScript
>  *   that are funnelled to be as straight as possible
>  */
> export function funnelPolypoints(path, triangleGraph, type) {
> ```

I'm not a huge fan of passing in a string to say whose path we are funneling. We dealt with a similar problem at some point in drawing the ally / enemy path. Any chance you can check out that code and see if you can use a similar solution?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/plan/funnel.js, line 12 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQIytH9m2sGwQFix-K:-LCQLPF2DLd-e9LjjRHe:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999c75fc16ef5aaa8c431c58397cba1c7348cfa/src/plan/funnel.js#L12)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you change this docstring to use the full 100 character limit
</blockquote></details>

Done.

---

*[src/plan/funnel.master.js, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQJMjc339qcU4y8N54:-LCQNRYqE1VrXq5ziTLf:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999c75fc16ef5aaa8c431c58397cba1c7348cfa/src/plan/funnel.master.js#L36)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I'm not a huge fan of passing in a string to say whose path we are funneling. We dealt with a similar problem at some point in drawing the ally / enemy path. Any chance you can check out that code and see if you can use a similar solution?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/plan/class/PolypointState.js, line 13 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQNasxAut82A7YgDNu:-LCQONbuDWSNS3Elrahk:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999c75fc16ef5aaa8c431c58397cba1c7348cfa/src/plan/class/PolypointState.js#L13)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI nit: saves some space if you do:

```
if (point) this.key = point.toString()
```

Then we don't even store the key if there is no point.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
Reviewed 5 of 6 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/plan/funnel.master.js, line 63 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQqfxNEvtefMABGNYF:-LCQqfxO11CwZ9Po7Orr:b6dvn54) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/948f8d87d07ae026e7bbdd9aad141137e9132a89/src/plan/funnel.master.js#L63)):*
> ```JavaScript
> 
> /**
>  * @param {PolypointState[]} path
> ```

perhaps a duplicate docstring is redundant? Maybe add to the previous docstring saying "stores the funneled points in `storedFunnelledPaths.ME`", and then something similar to this func? LMK what you think about this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
*[src/plan/funnel.master.js, line 63 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQqfxNEvtefMABGNYF:-LCQrFH36mj-3wEKCeRO:b-kxc2qn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/948f8d87d07ae026e7bbdd9aad141137e9132a89/src/plan/funnel.master.js#L63)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

perhaps a duplicate docstring is redundant? Maybe add to the previous docstring saying "stores the funneled points in `storedFunnelledPaths.ME`", and then something similar to this func? LMK what you think about this.
</blockquote></details>

@shanek21 ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by shanek21** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/plan/funnel.master.js, line 63 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQqfxNEvtefMABGNYF:-LCRWNPM6puqLb43tv-B:bh7o7b0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/948f8d87d07ae026e7bbdd9aad141137e9132a89/src/plan/funnel.master.js#L63)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

@shanek21 ?
</blockquote></details>

It doesn't feel redundant to me. If I stumble upon a function somewhere in our code that I don't know what it does, I want to go to its declaration and see what it does. I don't want to have to see if another function is similarly named and read the docstring for that function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
*[src/plan/funnel.master.js, line 63 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQqfxNEvtefMABGNYF:-LCRi6th4uqVV7qpdE6N:b-1cvjr0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/948f8d87d07ae026e7bbdd9aad141137e9132a89/src/plan/funnel.master.js#L63)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

It doesn't feel redundant to me. If I stumble upon a function somewhere in our code that I don't know what it does, I want to go to its declaration and see what it does. I don't want to have to see if another function is similarly named and read the docstring for that function.
</blockquote></details>

Okay. Can you add the sentence I put above to both docstrings then?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by billmwong** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/plan/funnel.master.js, line 63 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCQqfxNEvtefMABGNYF:-LCRk8e968FLzSkGHk9M:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/948f8d87d07ae026e7bbdd9aad141137e9132a89/src/plan/funnel.master.js#L63)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Okay. Can you add the sentence I put above to both docstrings then?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/interface/chat.js, line 22 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/479#-LCRks4nE23pVQD_i5EE:-LCRks4nE23pVQD_i5EF:b2nh5wp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1b88bfd37e86d32bea33ea5147c93887f6d5e374/src/interface/chat.js#L22)):*
> ```JavaScript
> /**
>  * Enqueues the message in the message queue to be chatted when appropriate.
>  * @param {'ALL'|'TEAM'} chat - the chat channel to send the message to
> ```

:f:

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/479)*

**Pull request merged**
