### PR TITLE
200: Bill A* Improvements

### PR DESCRIPTION
**Pull request by billmwong**
I did a small thing, close this if you don't like it

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/208)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208#-KueepmtlQYNJ-gVAWLj:-KuefuuecrUpUP_pPvYo:bb6un1j) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

simple present tense
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208)*

**Comment by davidabrahams** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/path.js, line 26 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208#-KufNuNHX6wbMJbqFQZC:-KufNuNHX6wbMJbqFQZD:boqe52g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bdd67fe7a437a2ff4563ed733b1d7e94be06f1c8/src/helpers/path.js#L26)):*
> ```JavaScript
>     this.parent = undefined;
> 
>     this.key = `${xc},${yc}`;
> ```

good fix. this makes it so it's only computed once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208)*

**Comment by billmwong** [comment]
*[src/helpers/path.js, line 26 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208#-KufNuNHX6wbMJbqFQZC:-KufXbUUgcWnyD1gcJhG:bn0cv4g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bdd67fe7a437a2ff4563ed733b1d7e94be06f1c8/src/helpers/path.js#L26)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

good fix. this makes it so it's only computed once.
</blockquote></details>

thanks but now you're blocking :expressionless: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/208)*

**Pull request merged**
