### PR TITLE
146: return types

### LINKED ISSUE #146: Add variable types to @return section in function level comments
I guess this wasn't in the convention that we are following, but it seems like it could be pretty useful?

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #146

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/151)

### CODE REVIEW

**Comment by shanek21** [comment]
Maybe this should be rebased on the furthest ahead branch. I saw some PRs with `@return` instead of `@returns`

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-:-KsOOxjadlv6JD8CbFtm:b6qf48y)*

**Comment by davidabrahams** [comment]
I believe this is the furthest ahead branch (check out the drawing). Might need to recheck that everything is in the correct format once everything is merged. I'll open an issue.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-:-KsP2Brp6J_TKF8qwcbJ:b-3t2zkr)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by billmwong** [comment]
:lgtm_cancel: :bomb: :fire: nuke this PR

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-:-KsRb5P8aCXT9qu6W6ks:bdniwvj)*

**Comment by davidabrahams** [comment]
Okay, the function comments are now unified and nice looking. This should get rereviewed.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-:-KsS71Z2cGBSuxTsPpli:bsfbu4w)*

**Comment by billmwong** [comment]
I think you gotta rebase or something cause this diff doesn't look correct

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-:-KsU3DwqibxhjGS0Wz_c:bpfr3o0)*

**Comment by davidabrahams** [comment]
Yep. Just fixed, should be good to look at now.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-:-KsVasin2VPjEOxjr14s:b-b2n2f9)*

**Comment by shanek21** [comment]
Reviewed 4 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-KsVcqCTrM-kr5pB3wFg:b-d5c19i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
> ```JavaScript
>  * @param {number} traversabilityCells - 2D array of cells. Traversable cells are 1s, others are 0.
>  */
> export function getShortestPath(myxc, myyc, target, traversabilityCells) {
> ```

Wait a second, shouldn't this pass in the `me` object and then do `me.xc` and `me.yc` inside the function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by davidabrahams** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-KsVdZtHwJ6iKi3sxx0N:bpnhtbx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Wait a second, shouldn't this pass in the `me` object and then do `me.xc` and `me.yc` inside the function?
</blockquote></details>

Idk. I prefer this implementation, but if we want to be consistent and do the me object I'm fine with that. Should i change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-KsVdirXIwbibSg60Q0A:b9y1bfs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Idk. I prefer this implementation, but if we want to be consistent and do the me object I'm fine with that. Should i change?
</blockquote></details>

Yes please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 34 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsWvsIicuiO7tSiKoRV:-KsWvsIicuiO7tSiKoRW:b8rts85) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b8e27325d5272003d92702b8230c07c635744c38/src/draw/drawings.js#L34)):*
> ```JavaScript
>  * @param {number} alpha - 0-1, where 0 is transparent
>  * @param {number} color - a hex color
>  * @return a PIXI.Graphics object
> ```

Is this an {Object}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by davidabrahams** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 34 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsWvsIicuiO7tSiKoRV:-KsWzyfq8fl90Ba4w6Rs:b-ug7090) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b8e27325d5272003d92702b8230c07c635744c38/src/draw/drawings.js#L34)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Is this an {Object}
</blockquote></details>

Fixed! Added a docstring

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-KsX1jOevGLlTCJM3q3q:b-8yq5kv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yes please
</blockquote></details>

Upon further inspection, this change originated in 118. The reason why it was done was because we no longer were computing shortest path from ourselves, but rather potential places we could end up after key presses. It made more sense to pass in the hypothetical locations, rather than a "pretend-me" object.

On a meta-note, I think we should try to comment requesting for changes on the PR where a change originated. Perhaps reviewable is making it a little difficult, because if I rebase a change in, then it looks like it came from this branch, even though the original change was in another branch. LMK what you think about this, and the best way to deal with this sort of issue in PR reviews.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by billmwong** [comment]
Reviewed 1 of 7 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-KsZitI7QMiHtTKP44Ar:b-dljj11) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Upon further inspection, this change originated in 118. The reason why it was done was because we no longer were computing shortest path from ourselves, but rather potential places we could end up after key presses. It made more sense to pass in the hypothetical locations, rather than a "pretend-me" object.

On a meta-note, I think we should try to comment requesting for changes on the PR where a change originated. Perhaps reviewable is making it a little difficult, because if I rebase a change in, then it looks like it came from this branch, even though the original change was in another branch. LMK what you think about this, and the best way to deal with this sort of issue in PR reviews.
</blockquote></details>

Put it on your retro list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by billmwong** [comment]
Reviewed 1 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by shanek21** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-Ks_daKsLqpPm9VGEF4A:-Ks_daKsLqpPm9VGEF4B:b-rdc406) (no related file):*
hahaha :tent:s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by shanek21** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-Ks_daKsLqpPm9VGEF4A:-Ks_de2r2DNZJPxlzd7P:bnsh8ee) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

hahaha :tent:s
</blockquote></details>

commit :tent:s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-Ks_dpQov-nLIZj6Qn4K:bzgwvq2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As soon as it becomes hypothetical, I agree that it doesn't make sense to pass in the `me` object. The parameters should probably be `xc` and `yc` rather than `myxc` and `myyc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-Ks_daKsLqpPm9VGEF4A:-Ks_i1FKQyF7lIvUK0SC:bb7f2mf) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

commit :tent:s
</blockquote></details>

done

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-Ks_hnKt1xvGo2ttgaWC:bqna1xk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

As soon as it becomes hypothetical, I agree that it doesn't make sense to pass in the `me` object. The parameters should probably be `xc` and `yc` rather than `myxc` and `myyc`
</blockquote></details>

I left myself a comment on 118 to do that. Until that PR is merged, getShortestPath will be the same. Set yourself to satisfied?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/path.js, line 139 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151#-KsVcqCTrM-kr5pB3wFf:-Ks_iScjo_rI95KoEQpe:bryusvb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ef8d6baa12b29cd35c012483c58ee4df15478197/src/helpers/path.js#L139)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I left myself a comment on 118 to do that. Until that PR is merged, getShortestPath will be the same. Set yourself to satisfied?
</blockquote></details>

David, you know just how to satisfy me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/151)*

**Pull request merged**
