### PR TITLE
180: Command menu can print out of order

### LINKED ISSUE #180: Command menu can print out of order
I think this can happen when you have a bad connection to the Tagpro server.

```
--- Help Menu
--- H: print this help menu
---
Q: toggle autonomous mode
V: toggle visuals
```

### PR DESCRIPTION
**Pull request by billmwong**
Closes #180

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/195)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/utils/interface.spec.js, line 20 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt53Umk3qlk_3k03meP:-Kt52skcxkELqADUkWeP:b-thypgh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c5581d5d93d18642f7daca4e44788314c389bc60/test/utils/interface.spec.js#L20)):*
> ```JavaScript
>     chat('four');
> 
>     t.deepEqual(mockQueue, ['one', 'two', 'three', 'four']);
> ```

`same`

---

*[test/utils/interface.spec.js, line 30 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt53Qab6NFIE1WcpdVN:-Kt53Qab6NFIE1WcpdVO:b-o4md6b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c5581d5d93d18642f7daca4e44788314c389bc60/test/utils/interface.spec.js#L30)):*
> ```JavaScript
>   tester.test('chats with correct delay between calls', t => {
>     const callTimes = [];
>     const emitSpy = sinon.stub().callsFake(() => {
> ```

no stub needed

---

*[test/utils/interface.spec.js, line 34 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt53cTXH6aLvEyugEyw:-Kt53cTYSqDrT_C17eQn:b-ctmqp6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c5581d5d93d18642f7daca4e44788314c389bc60/test/utils/interface.spec.js#L34)):*
> ```JavaScript
>     });
>     const mockQueue = ['one', 'two', 'three'];
>     const mockDelay = 50; // To make this test faster
> ```

our tests should have no delay. I would rewire Date() and `lastMessage`, and then have two tests, one that tests that nothing happens if Date() gives time very close to `lastMessage`, the other that tests that a message is dequeued and emitted

---

*[test/utils/interface.spec.js, line 41 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt5450KTqZSfogyDA47:-Kt5450KTqZSfogyDA48:bkq82uq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c5581d5d93d18642f7daca4e44788314c389bc60/test/utils/interface.spec.js#L41)):*
> ```JavaScript
> 
>     // Call dequeueMessages in a loop to simulate the botLoop
>     const mockLoop = setInterval(() => {
> ```

I believe if you do the above, then this loop is not needed, since really we only have to test two things (does nothing happen if current time is too recent, and does first thing pop off and get emitted if its not too recent)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by billmwong** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/utils/interface.spec.js, line 20 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt53Umk3qlk_3k03meP:-Kt54ZEU20hreV_Y0EZc:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c5581d5d93d18642f7daca4e44788314c389bc60/test/utils/interface.spec.js#L20)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

`same`
</blockquote></details>

Done.

---

*[test/utils/interface.spec.js, line 30 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt53Qab6NFIE1WcpdVN:-Kt54ZcTUaJWhLfkfICx:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c5581d5d93d18642f7daca4e44788314c389bc60/test/utils/interface.spec.js#L30)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

no stub needed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by billmwong** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/utils/interface.spec.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt5TLG3bssFkrfHzZwD:-Kt5TLG4o2LLpxZT0ml_:bdl4de7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd7ec0e256b88feb15548b253cef4512b03b4e2c/test/utils/interface.spec.js#L73)):*
> ```JavaScript
>   tester.test('does not chat if lastMessageTime is <600ms ago', t => {
>     const mockQueue = ['one', 'two', 'three'];
>     const mockLastMessageTime = new Date(new Date() + 5000); // 5s in the future
> ```

This test fails on travis sometimes, needs further investigation.  Might have to rewire getting the current date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by billmwong** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/utils/interface.spec.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt5TLG3bssFkrfHzZwD:-Kt5ZNJysdPheIrFuvOY:bycu4l5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd7ec0e256b88feb15548b253cef4512b03b4e2c/test/utils/interface.spec.js#L73)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

This test fails on travis sometimes, needs further investigation.  Might have to rewire getting the current date.
</blockquote></details>

Solved this by using the lightweight package date-fns.  Turns out you can subtract milliseconds the way I did it here, but not add them. The javascript Date() object is generally not trusted very much in the JS community and I've only ever seen people use packages to do any date/time things for them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r4.
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/utils/interface.spec.js, line 73 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt5TLG3bssFkrfHzZwD:-Kt5dAtdvkWUNbO1DMPq:bnppl6h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd7ec0e256b88feb15548b253cef4512b03b4e2c/test/utils/interface.spec.js#L73)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Solved this by using the lightweight package date-fns.  Turns out you can subtract milliseconds the way I did it here, but not add them. The javascript Date() object is generally not trusted very much in the JS community and I've only ever seen people use packages to do any date/time things for them.
</blockquote></details>

classic Javascript (I can't believe that my concern about assuming Date() works ended up being valid)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/utils/interface.spec.js, line 87 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt5eluMqCBiYBC0mcss:-Kt5eluNdwtQK7h1z30M:b82ri21) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/652b9f55df44db9db6fe55e6caad2c7c95208cd9/test/utils/interface.spec.js#L87)):*
> ```JavaScript
>     t.same(mockQueue, ['one', 'two', 'three']);
> 
>     global.tagpro = {};
> ```

we should probably reset it to undefined, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by billmwong** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/utils/interface.spec.js, line 87 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt5eluMqCBiYBC0mcss:-Kt5g06QJYHGZSdUZfGU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/652b9f55df44db9db6fe55e6caad2c7c95208cd9/test/utils/interface.spec.js#L87)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

we should probably reset it to undefined, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by davidabrahams** [comment]
This seems like a small enough PR to just have one commit. Rebase and fixup?

---

Reviewed 1 of 1 files at r5.
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-:-Kt7ZNuR-a8RmvQSmTx5:bzi5mb)*

**Comment by shanek21** [comment]
Reviewed 1 of 3 files at r1, 3 of 4 files at r4, 1 of 1 files at r5.
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/interface.js, line 35 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt7_NaGSUWg1Iiizxrh:-Kt7_NaGSUWg1Iiizxri:b-3h6tw6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f6dfef69e75a73ac9b1164af150b0875accfe307/src/utils/interface.js#L35)):*
> ```JavaScript
>  * if so chats the first thing in the queue if it exists.
>  */
> export function dequeueMessages() {
> ```

Can you call this `dequeueChatMessages()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by billmwong** [comment]
Done

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/interface.js, line 35 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-Kt7_NaGSUWg1Iiizxrh:-Kt7csw6IsX53vX86fxw:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f6dfef69e75a73ac9b1164af150b0875accfe307/src/utils/interface.js#L35)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you call this `dequeueChatMessages()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195#-:-Kt7crxid2VWlyWSt6wP:bb6un1j)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r6.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r6.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r7.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r7.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/195)*

**Pull request merged**
