### PR TITLE
312: Use navmesh to calculate opponent path

### LINKED ISSUE #312: Use navmesh to calculate opponent path
Once we do this, we can eliminate all of the `cell` code in our codebase entirely

### PR DESCRIPTION
**Pull request by shanek21**
Closes #312

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/323)

### CODE REVIEW

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mH2A__a9bV8VZDbU0:-L0mH2A__a9bV8VZDbU1:b-7xbon8) (no related file):*
PR title same as issue title

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by billmwong** [comment]
Can you make that last commit shorter?  maybe just something like "make bot find enemy in center if it can't find them"

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/draw/drawings.js, line 272 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mHyyxeTd7fRl-LoIf:-L0mHyyyZCWW9QFOyA0I:b36c4am) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L272)):*
> ```JavaScript
>  */
> export function drawPolypointPath(polypointPathGraphics, polypointPath, polypointPathColor) {
>   polypointPathGraphics.clear();
> ```

oh shit is this clear() function a thing we should be using elsewhere too?

---

*[src/draw/drawings.js, line 314 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mI8vqzR7rfECbsuwJ:-L0mI8vqzR7rfECbsuwK:b-qiu1yk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L314)):*
> ```JavaScript
>  */
> export function clearSprites() {
>   // TODO(davidabrahams): what is the difference between removeChildren and clear?
> ```

did someone figure this out

---

*[src/draw/drawings.js, line 322 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mIYADaGCW1_Vl8gLn:-L0mIYADaGCW1_Vl8gLo:b-970c3z) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L322)):*
> ```JavaScript
> 
>   // Get a list of all sprites
>   const backgroundSprites = permNTSprite ? [permNTSprite] : []
> ```

why did we need this diff

---

*[src/helpers/fsm.js, line 20 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mIg8nGEHVhVa0UzGc:-L0mIg8nGEHVhVa0UzGd:b-x51a34) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L20)):*
> ```JavaScript
>     getEnemyGoal(),
>     getDTGraph(),
>   ), polypoint => enemyShortestPath.push(polypoint));
> ```

can you make the two parameters to the forEach() on their own lines

---

*[src/helpers/fsm.js, line 25 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mKEdoWBeqWV__RQkM:-L0mKEdoWBeqWV__RQkN:bt7pvg0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L25)):*
> ```JavaScript
>   const interceptionPolypoint = _.find(pointsAlongPath(enemyShortestPath), polypoint =>
>     getDist(polypoint.x, polypoint.y, me.x + BRP, me.y + BRP) <
>       getDist(polypoint.x, polypoint.y, enemyFC.x + BRP, enemyFC.y + BRP));
> ```

Wrap the arrow function with parens and make the function body on its own line separate from the closed parens like this:

```javascript
const interceptionPolypoint = _.find(pointsAlongPath(enemyShortestPath), polypoint => (
  getDist(polypoint.x, polypoint.y, me.x + BRP, me.y + BRP) < getDist(polypoint.x, polypoint.y, enemyFC.x + BRP, enemyFC.y + BRP)
));
```
https://github.com/airbnb/javascript/#arrows--paren-wrap

If the two getDists() are more than 100 chars can we save them to variables and then do `return myDist < enemyDist` or something?  I don't like this multiline comparison

---

*[src/helpers/fsm.js, line 27 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNSsm6JYkHyQU6O6X:-L0mNSsm6JYkHyQU6O6Y:bfqw8vq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L27)):*
> ```JavaScript
>       getDist(polypoint.x, polypoint.y, enemyFC.x + BRP, enemyFC.y + BRP));
>   if (interceptionPolypoint) {
>     // Subtract PPTL/2 because in getAccelValues in bot.js we add them back
> ```

Seems poopy but I assume you've looked into it and this is the best way without major refactor?

---

*[src/utils/fsmUtils.js, line 5 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNpCmMmUhPaN1dCtO:-L0mNpCmMmUhPaN1dCtP:b-7ycr0x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/utils/fsmUtils.js#L5)):*
> ```JavaScript
> 
> 
> export function pointsAlongPath(path, granularity = 40) {
> ```

getPointsAlongPath()?  pointsAlongPath sounds like it could return a boolean

---

*[src/utils/fsmUtils.js, line 5 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNwU4Sf9ysTbnkrRY:-L0mNwU5VtdajSsAFOc7:bmxq8qj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/utils/fsmUtils.js#L5)):*
> ```JavaScript
> 
> 
> export function pointsAlongPath(path, granularity = 40) {
> ```

docstring pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-:-L0mHCG2oXjsoYHReetp:bx9i9kx)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0n6k_facsiXGiHXQC6:-L0n6k_facsiXGiHXQC7:b-wkzcn7) (no related file):*
Even though this is Shane's PR, a lot of the comments are on code that I wrote, so I went through and responded to stuff that I thought I had good input on

---

*[src/draw/drawings.js, line 272 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mHyyxeTd7fRl-LoIf:-L0n6WpfX2xK0fg3Z07S:b-3kdapg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L272)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

oh shit is this clear() function a thing we should be using elsewhere too?
</blockquote></details>

When we have a single `PIXI` object who's children are all on the renderer, then rather than removing the `PIXI` object entirely from the renderer, we can just clear() its children. @shanek21 correct me if I'm wrong. I believe we're using this design pattern wherever possible.

---

*[src/draw/drawings.js, line 314 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mI8vqzR7rfECbsuwJ:-L0n6u9HUHklfMHVwDIC:bkm1q4r) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L314)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

did someone figure this out
</blockquote></details>

Nope. I'm waiting on an explanation from @shanek21. This was a question I had the night before as I was modifying code on his branch.

---

*[src/draw/drawings.js, line 322 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mIYADaGCW1_Vl8gLn:-L0n7-JuHPvODcP1jOMg:bac8yij) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L322)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why did we need this diff
</blockquote></details>

I believe this was me. I honestly don't entirely remember why this was necessary :( The perrils of writing code late at night before EXPO...

@shanek21 it might be worth investigating this...is permNTSprite ever `null` when this is called? If not, this is unnecessary. If it is, this seems alright.

---

*[src/helpers/fsm.js, line 27 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNSsm6JYkHyQU6O6X:-L0n7oCvuNwK8xBd9Rrb:bsaci0l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L27)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Seems poopy but I assume you've looked into it and this is the best way without major refactor?
</blockquote></details>

I wrote this. This was a quick fix the night before EXPO :P

In `bot.js`, we assume that our goal is the top left of a tile, and so we add PPTL/2 to get the center of it. I actually think it would be clear if all `goal` related functions returned an exact pixel location of where our bot should go, since this is pretty unintuitive (which is why I left the comment behind), and would allow us to be consistent. @shanek21 would you mind doing that refactor?

---

*[src/utils/fsmUtils.js, line 5 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNwU4Sf9ysTbnkrRY:-L0n9GgnX2kvObh5UGEP:b-1ztlg9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/utils/fsmUtils.js#L5)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

docstring pls
</blockquote></details>

Because I felt bad making Shane docstring a function I wrote, here's one he can copy paste:

```javascript
/**
 * @param {{point: {x: number, y: number}}[]} path - a list of objects with a point key.
 * @param {number} granularity - the euclidian distance the points along the path should be
 *   separated by.
 * @returns {{x: number, y: number}[]} a list of points along the path. These points result from
 *   connecting each point in the input path, then placing points along each line, separated by
 *   granularity
 */
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by shanek21** [comment]
> Can you make that last commit shorter?  maybe just something like "make bot find enemy in center if it can't find them"
Done.

---

Review status: 2 of 32 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mH2A__a9bV8VZDbU0:-L23JgJTypJyRe7VOPmx:b-896fix) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

PR title same as issue title
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 272 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mHyyxeTd7fRl-LoIf:-L22tDdkPnSNSqd-_7Dt:b-qoc0q3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L272)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

When we have a single `PIXI` object who's children are all on the renderer, then rather than removing the `PIXI` object entirely from the renderer, we can just clear() its children. @shanek21 correct me if I'm wrong. I believe we're using this design pattern wherever possible.
</blockquote></details>

If I remember correctly, the `clear` function removes all drawings on a `PIXI.Graphics` object. Drawings on a `PIXI.Graphics` object are different from children. We `clear` in this case, because the way we draw the paths is taking a path Graphics object and then draw on it - we don't add children to it.

---

*[src/draw/drawings.js, line 314 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mI8vqzR7rfECbsuwJ:-L22tkviRgKlxy_ffxqY:bccu0o0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L314)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Nope. I'm waiting on an explanation from @shanek21. This was a question I had the night before as I was modifying code on his branch.
</blockquote></details>

Explained above.

---

*[src/draw/drawings.js, line 322 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mIYADaGCW1_Vl8gLn:-L23KW_o4eS9VPeDi31V:bczlvbm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/draw/drawings.js#L322)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I believe this was me. I honestly don't entirely remember why this was necessary :( The perrils of writing code late at night before EXPO...

@shanek21 it might be worth investigating this...is permNTSprite ever `null` when this is called? If not, this is unnecessary. If it is, this seems alright.
</blockquote></details>

I looked into it a bit. This function, `clearSprites` is only called when the user toggles visuals. `permNTSprites` is defined as soon as we have access to the tagpro object in `index.js`, so I think it should never be `null`. 

---

*[src/helpers/fsm.js, line 20 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mIg8nGEHVhVa0UzGc:-L238dp5h7sP_emOAWop:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L20)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can you make the two parameters to the forEach() on their own lines
</blockquote></details>

Done.

---

*[src/helpers/fsm.js, line 25 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mKEdoWBeqWV__RQkM:-L23Cqi0m10jVHSvDbsf:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L25)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Wrap the arrow function with parens and make the function body on its own line separate from the closed parens like this:

```javascript
const interceptionPolypoint = _.find(pointsAlongPath(enemyShortestPath), polypoint => (
  getDist(polypoint.x, polypoint.y, me.x + BRP, me.y + BRP) < getDist(polypoint.x, polypoint.y, enemyFC.x + BRP, enemyFC.y + BRP)
));
```
https://github.com/airbnb/javascript/#arrows--paren-wrap

If the two getDists() are more than 100 chars can we save them to variables and then do `return myDist < enemyDist` or something?  I don't like this multiline comparison
</blockquote></details>

Done.

---

*[src/utils/fsmUtils.js, line 5 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNwU4Sf9ysTbnkrRY:-L23EW5-lcVgn5aZaKMs:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/utils/fsmUtils.js#L5)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Because I felt bad making Shane docstring a function I wrote, here's one he can copy paste:

```javascript
/**
 * @param {{point: {x: number, y: number}}[]} path - a list of objects with a point key.
 * @param {number} granularity - the euclidian distance the points along the path should be
 *   separated by.
 * @returns {{x: number, y: number}[]} a list of points along the path. These points result from
 *   connecting each point in the input path, then placing points along each line, separated by
 *   granularity
 */
```
</blockquote></details>

Done.

---

*[src/utils/fsmUtils.js, line 5 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNpCmMmUhPaN1dCtO:-L23EX9B4r70uYjTBfDS:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/utils/fsmUtils.js#L5)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

getPointsAlongPath()?  pointsAlongPath sounds like it could return a boolean
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-:-L23XvCZhutDczemM7Qm:bcbmech)*

**Comment by billmwong** [comment]
Review status: 2 of 32 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L24B2qQ2FhjqEQytO62:-L24B2qRq_MuJBBnGP6a:bgwv192) (no related file):*
Looks like you gotta rebase on new stuff, your diff is looking funky in here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by shanek21** [comment]
Review status: 1 of 22 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L24B2qQ2FhjqEQytO62:-L26V4fqDuUgk2sav8YB:b-896fix) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Looks like you gotta rebase on new stuff, your diff is looking funky in here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by shanek21** [comment]
Review status: 0 of 23 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/helpers/fsm.js, line 27 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L0mNSsm6JYkHyQU6O6X:-L26bdr_NLwgDaNbD14U:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/376ae0458cf85c447f12aebe285be6bb8d4fd4f4/src/helpers/fsm.js#L27)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I wrote this. This was a quick fix the night before EXPO :P

In `bot.js`, we assume that our goal is the top left of a tile, and so we add PPTL/2 to get the center of it. I actually think it would be clear if all `goal` related functions returned an exact pixel location of where our bot should go, since this is pretty unintuitive (which is why I left the comment behind), and would allow us to be consistent. @shanek21 would you mind doing that refactor?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by davidabrahams** [comment]
Reviewed 5 of 6 files at r4, 3 of 20 files at r5.
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by billmwong** [comment]
Reviewed 4 of 6 files at r4, 3 of 20 files at r5.
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Comment by billmwong** [comment]
Review status: 7 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323#-L2D5rOK7lgRAZsVzEBO:-L2D5rOK7lgRAZsVzEBP:b1b5izm) (no related file):*
Rebase again on master now that 211 is merged thank youuu

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/323)*

**Pull request merged**
