### PR TITLE
118: improved control

### LINKED ISSUE #118: Change decision for A* to be keypress instead of next cell, sanitize getTarget()

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #118.
pop

Instead of our bot calculating a path and then seeking along that path, it now calculates where it will be if it holds each of the 9 keypress possibilities (8 directions and nothing) for a given timestep [using constant acceleration physics equations](http://www.physicsclassroom.com/class/1DKin/Lesson-6/Kinematic-Equations). It then uses A* to calculate a path from each of its 9 potential locations toward its target, and chooses the shortest path as the one to "seek toward". **Basically, we seek toward the best of 9 possibly A* starting locations.**

The main issue right now is because at each frame we run A* 9 times, instead of once, we're reaaalllly running into some lag issues when the bot has a long distance to travel. I think we can deal with this with more cacheing (yay), but I'm going to open that as a new issue.

Let me know if you guys think this is a good next step for the bot. Right now there's a lot of clunkiness, but I think this is a step in the right direction and will give us something to build on moving forward. Here are all the things I either have left to do or that we need to work on going forward:

- [ ] Get full unit test coverage on new code
- [ ] Right now when the game starts, the bot spews errors to the command line. Unsure why
- [ ] If one of the 9 potential locations is off the grid, bot spews errors (though functions as it should)
- [ ] I think at some point im confusing left/right/up/down and their representations in the tagpro grid. I left this as a TODO comment. The bot works as expected, but the code that makes it work is not what I think it should be.
- [ ] Bot is unable to run A* 9 times for long distance travels without intense lag

Let me know which of these you think should be addressed in this PR, and which should be issues (my plan is the first 4 will be in this PR, the last is a new issue).

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/142)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsRY_qDapVE434T162-:b55c04t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
> ```JavaScript
> 
> export default function botLoop() {
>   seekTowardDirection(getNextDirectionTowardTarget());
> ```

is this more like moveTowardDirection? Idk about the naming here

---

*[src/helpers/path.js, line 202 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRZnrqZC45i0Y469qE:-KsRZnrqZC45i0Y469qF:bv0z7xh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L202)):*
> ```JavaScript
> /*
>  * @param {number} traversabilityCells - 2D array of cells. Traversable cells are 1s, others are 0.
>  * @param {Object} target - object with target's position in cells, xc and yc
> ```

is this doc still accurate

---

*[src/helpers/path.js, line 212 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRYnfkZAHRgdVHnltF:-KsRYnfkZAHRgdVHnltG:b-fzmf3q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L212)):*
> ```JavaScript
>   const myvxp = me.vx * tilesPerMeter; // me.vx is in meters/second
>   const myvyp = me.vy * tilesPerMeter;
>   const directions = [
> ```

I would declare this constant outside of the function, no need to make this variable each time this function is called.

Actually this is used in interface too? Put this in the constants file.

---

*[src/helpers/path.js, line 247 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRZTvAeKlSLH0oYRQP:-KsRZTvAeKlSLH0oYRQQ:b1nlp5b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L247)):*
> ```JavaScript
>     // the best one so far
>     if (path) {
>       if (path.length < smallestDistance) {
> ```

would it makes sense to combine these two lines? `if (path && path.length < smallestDistance)`

---

*[src/utils/interface.js, line 106 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_BXIHsIX3SlLuXq8:-KsR_BXIHsIX3SlLuXq9:bj7vp6p) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L106)):*
> ```JavaScript
>  */
> export function seekTowardDirection(direction) {
>   const directions = [
> ```

Put this in the constants file as per above

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsR_G5PwkOoIIDY7Lho:b6ws7t9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
> ```JavaScript
>     { x: 1, y: 1 },
>   ];
>   // TODO: these keypresses seem backward from the directions listed above, but when running the
> ```

Can we get in the habit of making issues instead of TODOs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
Review status: 2 of 20 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsRi3Wy4ZboyyYq7KNv:bgi6ms7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is this more like moveTowardDirection? Idk about the naming here
</blockquote></details>

Sorta? We hold the key, but we don't actually move in the direction of our keypress (because if the velocity is in a diff direction, we'll go that way). LMK if you have thoughts on renaming the functio

---

*[src/helpers/path.js, line 202 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRZnrqZC45i0Y469qE:-KsRiqGsPw61eTB9RQ7U:b2nhswy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L202)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is this doc still accurate
</blockquote></details>

Yes

---

*[src/helpers/path.js, line 212 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRYnfkZAHRgdVHnltF:-KsRlvj2ZddZlI9kIzIZ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L212)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I would declare this constant outside of the function, no need to make this variable each time this function is called.

Actually this is used in interface too? Put this in the constants file.
</blockquote></details>

Done.

---

*[src/helpers/path.js, line 247 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRZTvAeKlSLH0oYRQP:-KsRlwiOTumjbouhlEcq:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L247)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

would it makes sense to combine these two lines? `if (path && path.length < smallestDistance)`
</blockquote></details>

Done.

---

*[src/utils/interface.js, line 106 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_BXIHsIX3SlLuXq8:-KsRmDIYpPRGDcT00ZSo:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L106)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Put this in the constants file as per above
</blockquote></details>

Done.

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsRmF4gmSGqq1KX7bGD:b-m1g2b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Can we get in the habit of making issues instead of TODOs
</blockquote></details>

I wasn't planning on merging this PR until this TODO was fixed, so I figured this was the best way to make a note for myself without confusing other people? Its an issue introduced by this PR, so it didn't seem like an issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by altodyte** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/helpers/path.js, line 78 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRy_YD5bC32iMEYt7p:-KsRy_YD5bC32iMEYt7q:b-bmntta) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/helpers/path.js#L78)):*
> ```JavaScript
>       _.each(diagNeighbors, n => {
>         // use sqrt(2) as heuristic distance for diagonals
>         n.g = this.g + 1.4142; // eslint-disable-line no-param-reassign
> ```

This isn't actually right, since the TagPro universe is manhattan-distance based. Balls travel faster diagonally in a pure kph sense. The max speed is along the major axes, rather than arbitrary space.

---

*[src/helpers/path.js, line 103 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRzmCJhdLtpQ7TZU-u:-KsRzmCJhdLtpQ7TZU-v:b-h377rl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/helpers/path.js#L103)):*
> ```JavaScript
>  * example). The unit for tStep should be the denominator on the `v` and `a` inputs.
>  */
> export function projectedLocation(x, y, vx, vy, ax, ay, tStep) {
> ```

I haven't really considered the consequences yet (and don't really understand what this does) but it seems like it could be related.
https://chrome.google.com/webstore/detail/tagpro-live-player-positi/loamdlpijahnieaimdeeeabnmngadmhh?hl=en
Also, here's snaps' version w/ damping:
https://gist.github.com/chrahunt/8b6f5124f7335689f6ac

---

*[src/utils/interface.js, line 100 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS03IDOoejsL_0gjqg:-KsS03IDOoejsL_0gjqh:b-h1am8g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L100)):*
> ```JavaScript
>  * ---------
>  * 3 | 4 | 5
>  * ---------
> ```

I'm irrationally angry that this doesn't match the ordering of numbers in a numpad.

---

*[src/utils/interface.js, line 108 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS1FDZ7LZeYtVOv2QQ:-KsS1D75MfJprgzuBMDj:b-ar89f7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L108)):*
> `sendKeyPress` {Function} - sends a key press event to the server. Tracks the keys already being pressed as well as the number of the key event sent.
> Parameters:
> `direction` {string} - the direction to send the key event for. One of "left", "right", "up", or "down".
> `released` {boolean} - whether this is a key being released.
> Returns: none

From the TagPro api (https://www.reddit.com/r/TagPro/wiki/api), the boolean flags on `sendKeyPress` are super unintuitive. Send `false` when you want that key to be pressed, send `true` when you want it released.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/utils/interface.js, line 100 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS03IDOoejsL_0gjqg:-KsS2_1J56hjYLPX272-:bv3dwte) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L100)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

I'm irrationally angry that this doesn't match the ordering of numbers in a numpad.
</blockquote></details>

https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Numpad.svg/1200px-Numpad.svg.png

What the hell am I supposed to do about the 0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsSBbrMc3vJ5sfLOwNN:b-tg8rhr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I wasn't planning on merging this PR until this TODO was fixed, so I figured this was the best way to make a note for myself without confusing other people? Its an issue introduced by this PR, so it didn't seem like an issue
</blockquote></details>

Just reread that sentence. *It's a problem introduced by this PR, so opening an issue seemed incorrect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsTyEqJmoBeW9BWtDd7:baw8hex) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Sorta? We hold the key, but we don't actually move in the direction of our keypress (because if the velocity is in a diff direction, we'll go that way). LMK if you have thoughts on renaming the functio
</blockquote></details>

hmm I like "move" better than "seek" but still not great. Technically it's "accelerate", but is that too confusing?

---

*[src/helpers/path.js, line 202 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRZnrqZC45i0Y469qE:-KsTvyV3iu3XJbbnh1Yp:b5pap3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L202)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Yes
</blockquote></details>

I think I got confused before, I thought this was the return value.  Can you add a return val doc?

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsTwF-vWClYVfVxQVrW:bzdikkc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Just reread that sentence. *It's a problem introduced by this PR, so opening an issue seemed incorrect
</blockquote></details>

Uhh okay. Maybe give a label or a comment or something if you want reviews but your PR is not done yet?  Usually code review means it's functional and done

---

*[src/utils/interface.js, line 108 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS1FDZ7LZeYtVOv2QQ:-KsTwOQQNlrWkN7oA-WS:b-8mnxmj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L108)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

> `sendKeyPress` {Function} - sends a key press event to the server. Tracks the keys already being pressed as well as the number of the key event sent.
> Parameters:
> `direction` {string} - the direction to send the key event for. One of "left", "right", "up", or "down".
> `released` {boolean} - whether this is a key being released.
> Returns: none

From the TagPro api (https://www.reddit.com/r/TagPro/wiki/api), the boolean flags on `sendKeyPress` are super unintuitive. Send `false` when you want that key to be pressed, send `true` when you want it released.
</blockquote></details>

Hmm do we want to abstract that? We could make a keypress helper function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsVfHyP1Ee3t4_JrUOF:b-se8d7l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

hmm I like "move" better than "seek" but still not great. Technically it's "accelerate", but is that too confusing?
</blockquote></details>

`pressTowardDirection`? since thats what we actually do

---

*[src/helpers/path.js, line 202 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRZnrqZC45i0Y469qE:-KsVfBMJ-EZNZ4k_YZpa:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/helpers/path.js#L202)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I think I got confused before, I thought this was the return value.  Can you add a return val doc?
</blockquote></details>

Done.

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsVeSgtKUL0ifIfNgco:bxt8h00) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Uhh okay. Maybe give a label or a comment or something if you want reviews but your PR is not done yet?  Usually code review means it's functional and done
</blockquote></details>

Shane and I have been started following a convention that assigning someone as a reviewer means it's not done yet, assigning someone as an assignee means its completely functional and done. @shanek21 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by shanek21** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsVe3Yi6hYEzfRluxXc:b-dqkhzx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

hmm I like "move" better than "seek" but still not great. Technically it's "accelerate", but is that too confusing?
</blockquote></details>

I like move or accelerate. I don't like seek as much.

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsVfwfBQpz0Ic_JFWVs:b-6yyhl8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Shane and I have been started following a convention that assigning someone as a reviewer means it's not done yet, assigning someone as an assignee means its completely functional and done. @shanek21 
</blockquote></details>

This is true. Though, I am no longer a fan of intermediate reviews. So I probably won't review something until I'm assigned.

---

*[src/utils/interface.js, line 108 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS1FDZ7LZeYtVOv2QQ:-KsVgEtJqivwm4BTaXFh:bx8c1f5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L108)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmm do we want to abstract that? We could make a keypress helper function
</blockquote></details>

Yeah we should definitely wrap that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsVgfQxze4wessEM-Rd:bpy1jp1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

This is true. Though, I am no longer a fan of intermediate reviews. So I probably won't review something until I'm assigned.
</blockquote></details>

I think there should be some way to get high level "is this a good idea and how do I improve it" feedback, before investing all time energy to get a code ready for review. What should our procedure be for that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by billmwong** [comment]
*[src/utils/interface.js, line 120 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsR_G5PwkOoIIDY7Lhn:-KsVkDxh5_zGDhUEy_MN:b-6lid8u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/utils/interface.js#L120)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I think there should be some way to get high level "is this a good idea and how do I improve it" feedback, before investing all time energy to get a code ready for review. What should our procedure be for that?
</blockquote></details>

I made myself a note to bring this up in our retro, no need to address here :dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsWux2VMK-ThciSeDLV:b-u6xlse) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I like move or accelerate. I don't like seek as much.
</blockquote></details>

I'd be fine with either of: press, move, or accelerate.  Your judgement

---

*[src/helpers/path.js, line 204 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsWvD-Hi5zoh6JhF0je:-KsWvD-I-kpc6Igekyq8:brco52o) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ffe0c502d3a700d44e173cd0ba724438288e9dbc/src/helpers/path.js#L204)):*
> ```JavaScript
>  * @param {number} traversabilityCells - 2D array of cells. Traversable cells are 1s, others are 0.
>  * @param {Object} target - object with target's position in cells, xc and yc
>  * @return {{direction: number, path: Array}} an object containing both which keypress we should
> ```

Seems like we just use {Object} and then explain the properties in the doc? This seems fine to me but convention might be good

---

*[src/utils/interface.js, line 108 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS1FDZ7LZeYtVOv2QQ:-KsWvSZWCatmwnrUVsow:bgv700q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L108)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yeah we should definitely wrap that.
</blockquote></details>

:thumbsup: Don't have to do it in this PR, you can make an issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/bot.js, line 81 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRY_qDapVE434T161z:-KsX3O-ZLxF3ifL938x9:bulfugp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/06b74ae8086886178e48c27a278fee987712b3ec/src/bot.js#L81)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I'd be fine with either of: press, move, or accelerate.  Your judgement
</blockquote></details>

I'm going with `dangoTowardDirection`. Jk i did `accelerate`

---

*[src/helpers/path.js, line 78 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRy_YD5bC32iMEYt7p:-KsX4FcBByE1LZKQJ3m2:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/helpers/path.js#L78)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

This isn't actually right, since the TagPro universe is manhattan-distance based. Balls travel faster diagonally in a pure kph sense. The max speed is along the major axes, rather than arbitrary space.
</blockquote></details>

Done.

---

*[src/helpers/path.js, line 103 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsRzmCJhdLtpQ7TZU-u:-KsX4SMy2LCYdWXFrwr6:b3xi6mw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/helpers/path.js#L103)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

I haven't really considered the consequences yet (and don't really understand what this does) but it seems like it could be related.
https://chrome.google.com/webstore/detail/tagpro-live-player-positi/loamdlpijahnieaimdeeeabnmngadmhh?hl=en
Also, here's snaps' version w/ damping:
https://gist.github.com/chrahunt/8b6f5124f7335689f6ac
</blockquote></details>

For agility sake, I'm going to put these docs in an issue to investigate later. Can we call this resolved?

---

*[src/helpers/path.js, line 204 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsWvD-Hi5zoh6JhF0je:-KsX5gcEamI4d744N2BC:br9z6dj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ffe0c502d3a700d44e173cd0ba724438288e9dbc/src/helpers/path.js#L204)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Seems like we just use {Object} and then explain the properties in the doc? This seems fine to me but convention might be good
</blockquote></details>

Jsdoc specifies multiple valid conventions for defining objects. Both are valid. I actually like this version, where you specify what's in the object. I think at some point we should go back and cleanse the {Object} tags to be more specific. I'll make an issue!

---

*[src/utils/interface.js, line 108 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsS1FDZ7LZeYtVOv2QQ:-KsX6tNOvrJAiGLH8tcA:b-e5gpw5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c0fff14480c49bed75542cf26b0bcdd5e075af46/src/utils/interface.js#L108)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

:thumbsup: Don't have to do it in this PR, you can make an issue
</blockquote></details>

Yeah 118 is slowing down and lots of stuff is blocked by it, so I'll make an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/helpers/path.js, line 204 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-KsWvD-Hi5zoh6JhF0je:-KsXREz9CweBPfXqgmLI:b-9ifl1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ffe0c502d3a700d44e173cd0ba724438288e9dbc/src/helpers/path.js#L204)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Jsdoc specifies multiple valid conventions for defining objects. Both are valid. I actually like this version, where you specify what's in the object. I think at some point we should go back and cleanse the {Object} tags to be more specific. I'll make an issue!
</blockquote></details>

OK sounds good, didn't know that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
*[src/helpers/path.js, line 141 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-Ks_joiW6tsvSiAYx1rR:-Ks_joiW6tsvSiAYx1rS:b-3r745q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b9e5eb09aa721da580cdef672bec0504d1a59245/src/helpers/path.js#L141)):*
> ```JavaScript
>  * @param {number} traversabilityCells - 2D array of cells. Traversable cells are 1s, others are 0.
>  */
> export function getShortestPath(myxc, myyc, target, traversabilityCells) {
> ```

per shake's comment, change this to xc and yc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by davidabrahams** [comment]
*[src/helpers/path.js, line 141 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142#-Ks_joiW6tsvSiAYx1rR:-Ks_jvM-JP5xn9YEhddY:b263mui) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b9e5eb09aa721da580cdef672bec0504d1a59245/src/helpers/path.js#L141)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

per shake's comment, change this to xc and yc
</blockquote></details>

*shane's

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/142)*

**Comment by billmwong** [comment]
Closing this until unblocked

**Pull request closed without merging**
