### PR TITLE
417: enable LQR

### LINKED ISSUE #417: Enable/Tweak LQR controller
Once the cards are done and it is better than the old controller

delete the old controller code

### PR DESCRIPTION
**Pull request by shanek21**
Closes #417

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/start.js, line 39 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLwPtuD_cp-FGj_T_S:-LCLwPtuD_cp-FGj_T_T:b-mqub61) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/90928004bb5c50c51b641b3e8db560b5c24069d3/src/start.js#L39)):*
> ```JavaScript
> 
>   const polypointShortestPath = time(getShortestPolypointPath, [
>     getPlayerCenter(me),
> ```

assign getPlayerCenter to a const and then you can use it up here too

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by shanek21** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/start.js, line 39 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLwPtuD_cp-FGj_T_S:-LCLwrlD0_VUqQKDuJ2H:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/90928004bb5c50c51b641b3e8db560b5c24069d3/src/start.js#L39)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

assign getPlayerCenter to a const and then you can use it up here too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 96 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLwiJx-lSIpduWd_R5:-LCLwiJx-lSIpduWd_R6:b-2lvgb0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/90928004bb5c50c51b641b3e8db560b5c24069d3/src/control/lqr.js#L96)):*
> ```JavaScript
>   }
> 
>   // Calculated a weird K matrix, and should recalculate
> ```

weird -> "insufficient" or "not enough"

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 96 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLwsYoEdco8pmZdIUz:-LCLwsYp7FiOgCqMslTm:b-cemgxd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/90928004bb5c50c51b641b3e8db560b5c24069d3/src/control/lqr.js#L96)):*
> ```JavaScript
>   }
> 
>   // Calculated a weird K matrix, and should recalculate
> ```

matrix -> matrices

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by billmwong** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/control/lqr.js, line 97 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLyraU0k6Ax_EiA7RA:-LCLyraU0k6Ax_EiA7RB:bii7kqg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c30ff1633a9d0b72bc1e19d1004477b0f1e33fa2/src/control/lqr.js#L97)):*
> ```JavaScript
> 
>   // Calculated a weird K matrix, and should recalculate
>   if (!currentKs || currentKs.shape()[0] <= 1) {
> ```

Does this case happen anymore now that we've floored deadline?

---

*[src/control/lqr.worker.js, line 109 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLydi-4rPW_x9OJk5U:-LCLydi-4rPW_x9OJk5V:baovzgj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c30ff1633a9d0b72bc1e19d1004477b0f1e33fa2/src/control/lqr.worker.js#L109)):*
> ```JavaScript
> 
>   const Q = new Matrix(math.diag([0, 0, 0, 0])); // intermediate state cost
>   const F = new Matrix(math.diag([6000, 2000, 6000, 2000])); // terminal state cost
> ```

ooh nice does this work better you find?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by shanek21** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/control/lqr.js, line 96 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLwiJx-lSIpduWd_R5:-LCLytZH1NJksaNh9Dcl:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/90928004bb5c50c51b641b3e8db560b5c24069d3/src/control/lqr.js#L96)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

weird -> "insufficient" or "not enough"
</blockquote></details>

Done.

---

*[src/control/lqr.js, line 96 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLwsYoEdco8pmZdIUz:-LCLytq1DT-cOG2mzyJc:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/90928004bb5c50c51b641b3e8db560b5c24069d3/src/control/lqr.js#L96)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

matrix -> matrices
</blockquote></details>

Done.

---

*[src/control/lqr.js, line 97 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLyraU0k6Ax_EiA7RA:-LCLyxi5EViaik4oY2ta:b-ee9ml0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c30ff1633a9d0b72bc1e19d1004477b0f1e33fa2/src/control/lqr.js#L97)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Does this case happen anymore now that we've floored deadline?
</blockquote></details>

Yeah, it does... :(
I don't know why.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by shanek21** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/control/lqr.worker.js, line 109 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLydi-4rPW_x9OJk5U:-LCLz4zJDdqukthW6GgL:b3ngf7j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c30ff1633a9d0b72bc1e19d1004477b0f1e33fa2/src/control/lqr.worker.js#L109)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

ooh nice does this work better you find?
</blockquote></details>

I can't honestly say that it is definitively better on average. Though, it is better in at least one specific case (The case where we are really close to the flag, but not going to it. These increased costs will increase our incentive to go towards it.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 97 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/469#-LCLyraU0k6Ax_EiA7RA:-LCLzDqy3rPYM_OewmNQ:b-336mwq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c30ff1633a9d0b72bc1e19d1004477b0f1e33fa2/src/control/lqr.js#L97)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yeah, it does... :(
I don't know why.
</blockquote></details>

OK, so we now just hope that this time around, our deadline is different enough that we'll generate sufficient Ks

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)*

**Pull request merged**
