### PR TITLE
341: break getAccelValues up into blocks in start.js

### LINKED ISSUE #341: Break `getAccelValues` up into multiple functions
Right now this function basically runs our entire bot, but it's unintuitive that this is the function that does everything. We should refactor move to do something like this:

```
me = getMe()
target = FSM(me)
updateAndRedrawEntireNavmesh(tagpro.map)
polypointShortestPath = getShortestPolyPointPath(...)
drawAllyPPPath(ppShortestPath)
target = getTargetFromPath() // a function we could create using a chunk of code from this function
desiredMultipliers = desiredAccelerationMultiplier(...)
move(desiredMultipliers)
```

and then not have the getAccelValues() function anymore

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #341

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/385)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/start.js, line 22 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/385#-L7wfGXZvWqr11IjxapC:-L7wfGXZvWqr11IjxapD:bsjci88) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e80d048f678f6c5ab9d915f23fd4e8275fa34150/src/start.js#L22)):*
> ```JavaScript
>   if (isAutonomousMode()) {
>     move(getAccelValues());
>   } else if (isVisualMode()) {
> ```

you've changed the logic so that the bot still does stuff in the background when both autonomous and visual modes are off, was that intentional?

---

*[src/start.js, line 48 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/385#-L7weh3y4BaVEUxTWUQO:-L7weh3y4BaVEUxTWUQP:b-ij26wp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L48)):*
> ```JavaScript
>   const me = getMe();
>   const goal = FSM(me);
>   updateAndRedrawEntireNavmesh(map);
> ```

is this function name accurate now that we have dynamic updates? we don't redraw every time right?

---

*[src/start.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/385#-L7wey1ZN6rUQTzbF4ys:-L7wey1ZN6rUQTzbF4yt:bc8npzs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L50)):*
> ```JavaScript
>   updateAndRedrawEntireNavmesh(map);
> 
>   const polypointShortestPath = getShortestPolypointPath(
> ```

FYI probably not in this PR, but now that we have funnelling, none of these paths are polypoints anymore and should probably be renamed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/385)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/start.js, line 50 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wey1ZN6rUQTzbF4ys:-L8bmF309EHMsHPyQW-z:b-vzrwnn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

FYI probably not in this PR, but now that we have funnelling, none of these paths are polypoints anymore and should probably be renamed
</blockquote></details>

I feel like that change could ride on this PR if @davidabrahams is up for it.

---

*[src/start.js, line 65 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L8bn-kE2WWscu8qu4Ww:-L8bn-kE2WWscu8qu4Wx:btk2w3b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L65)):*
> ```JavaScript
>     me.x + BRP, // the x center of our ball, in pixels
>     me.y + BRP, // the y center of our ball, in pixels
>     me.vx, // our v velocity
> ```

Should be `me.vx, // our x velocity`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/start.js, line 50 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wey1ZN6rUQTzbF4ys:-L8bngArEyxLlziMVk--:b-2kv9xd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L50)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I feel like that change could ride on this PR if @davidabrahams is up for it.
</blockquote></details>

Nevermind, I see that @billmwong made that change in a later PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/start.js, line 50 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wey1ZN6rUQTzbF4ys:-L8cdxfoC5hfXtisLVn6:b1k8i6j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L50)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Nevermind, I see that @billmwong made that change in a later PR.
</blockquote></details>

I refactored the names inside the draw/ file but nowhere else cause that looked like a lot of work

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/start.js, line 65 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L8bn-kE2WWscu8qu4Ww:-L8ce87Z599rj4z0tRkz:byeofih) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L65)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Should be `me.vx, // our x velocity`?
</blockquote></details>

Hahahaha

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by davidabrahams** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/start.js, line 22 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wfGXZvWqr11IjxapC:-L93PmdP-2vcxUJqBdCk:b-6zdmm8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e80d048f678f6c5ab9d915f23fd4e8275fa34150/src/start.js#L22)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

you've changed the logic so that the bot still does stuff in the background when both autonomous and visual modes are off, was that intentional?
</blockquote></details>

I believe this was the behavior of the bot beforehand as well (as far as I know, this PR doesn't actually functionally change the bot at all)

I may be wrong about that. Open to discuss it

---

*[src/start.js, line 48 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7weh3y4BaVEUxTWUQO:-L93PZ184ZtTzl100xnQ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L48)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is this function name accurate now that we have dynamic updates? we don't redraw every time right?
</blockquote></details>

Done.

---

*[src/start.js, line 50 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wey1ZN6rUQTzbF4ys:-L96rXFx2XtLSkl5C1wS:bndo7bt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I refactored the names inside the draw/ file but nowhere else cause that looked like a lot of work
</blockquote></details>

I did a small refactor so `getShortestPolypointPath` actually returns polypoints now

---

*[src/start.js, line 65 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L8bn-kE2WWscu8qu4Ww:-L93PhxH10qs78GjSsIB:baezu3i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dd445a3c46b528b912d034d31f9e7ce39145dcdd/src/start.js#L65)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hahahaha
</blockquote></details>

uhh yep that's been there for like 8 months

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/start.js, line 22 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wfGXZvWqr11IjxapC:-L9BcMMYDXZvEdXBhTeS:b-krltr4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e80d048f678f6c5ab9d915f23fd4e8275fa34150/src/start.js#L22)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I believe this was the behavior of the bot beforehand as well (as far as I know, this PR doesn't actually functionally change the bot at all)

I may be wrong about that. Open to discuss it
</blockquote></details>

Return in the beginning if both modes are off, as per in person discussion

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by davidabrahams** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/start.js, line 22 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L7wfGXZvWqr11IjxapC:-L9BfFgj38nY-QKQIfHg:b40w3sh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e80d048f678f6c5ab9d915f23fd4e8275fa34150/src/start.js#L22)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Return in the beginning if both modes are off, as per in person discussion
</blockquote></details>

Done. Nice catch

---

*[src/plan/funnel.js, line 107 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L9BfZpyCDK1xOG92ymn:-L9BfZpyCDK1xOG92ymo:bvygne7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc099714e823318eed9544b32aeca5fbfe5d1ab5/src/plan/funnel.js#L107)):*
> ```JavaScript
>  */
> export function funnelPolypoints(path, triangleGraph) {
>   // Don't bother funnelling if our path has no intermediate polypoints, or the path is null
> ```

FYI the reason I had to add this is because earlier, the call to `funnelPolypoints` was done in `getShortestPolypointPath`, which returned early if the path was `null`. Now, we always pass the output of `getShortestPolypointPath` to `funnelPolypoints`, so I added the null check.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/start.js, line 61 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L9BgCCbDumcYOcf07pB:-L9BgCCbDumcYOcf07pC:b-fh3n9w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc099714e823318eed9544b32aeca5fbfe5d1ab5/src/start.js#L61)):*
> ```JavaScript
>   );
> 
>   const funneledPath = funnelPolypoints(polypointShortestPath, getDTGraph());
> ```

funneled -> funnelled

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/start.js, line 62 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L9Bg6m4-SBK9kH9Wabq:-L9Bg6m4-SBK9kH9Wabr:b-tl6di1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc099714e823318eed9544b32aeca5fbfe5d1ab5/src/start.js#L62)):*
> ```JavaScript
> 
>   const funneledPath = funnelPolypoints(polypointShortestPath, getDTGraph());
>   drawAllyPath(funneledPath);
> ```

drawAllyPath is okay with funnelledPath being null?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/plan/funnel.js, line 107 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L9BfZpyCDK1xOG92ymn:-L9BikVL4uc5CvJay1tM:b32w0x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dc099714e823318eed9544b32aeca5fbfe5d1ab5/src/plan/funnel.js#L107)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI the reason I had to add this is because earlier, the call to `funnelPolypoints` was done in `getShortestPolypointPath`, which returned early if the path was `null`. Now, we always pass the output of `getShortestPolypointPath` to `funnelPolypoints`, so I added the null check.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by shanek21** [comment]
Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by billmwong** [comment]
*[src/start.js, line 62 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L9Bm4PL1-4gxxwHGYxG:-L9BlBST5NMLPurJOubr:b-ovi4ap) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/89b08939607a0dc042257f7402f31a21d372f604/src/start.js#L62)):*
> ```JavaScript
> 
>   const funnelledPath = funnelPolypoints(polypointShortestPath, getDTGraph());
>   drawAllyPath(funnelledPath);
> ```

FYI On second thought it is kinda weird that we're handling this null case inside each of these two functions but up to you

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/start.js, line 62 at r4](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385#-L9Bm4PL1-4gxxwHGYxG:-L9BmAE92cgxfL4wsbvD:bpwsffr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/89b08939607a0dc042257f7402f31a21d372f604/src/start.js#L62)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

FYI On second thought it is kinda weird that we're handling this null case inside each of these two functions but up to you
</blockquote></details>

agreed it's gross, but in person decided this is the cleanest way to do it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/385)*

**Pull request merged**
