### PR TITLE
373: bot roles

### LINKED ISSUE #373: Assign Bot Roles based on team chat
Assign a certain role that is complementary to the other bots on your team, or choose a role and declare to the team what your role is

- If no one has declared, choose offense
- If there exists one offense bot, choose defense
- If there exists one defense and one offense bot, choose offense
- If there are two def, choose offense
- If there are two off, choose defense

Do nothing with this role except store it and chat it

### PR DESCRIPTION
**Pull request by shanek21**
Closes #373

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 11 of 11 files at r2.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/interface/chat.js, line 17 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUoZxDAMAhetejitYb:-LAUoZxDAMAhetejitYc:b50fj3k) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L17)):*
> ```JavaScript
> 
> 
> // FIFO queue for delaying chat messages
> ```

can you leave comment explaining what each object in the list has? (`{chat: string, message: string}` or similar)

---

*[src/interface/chat.js, line 58 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUq7IUCLVG9FT1esZy:-LAUq7IUCLVG9FT1esZz:b-fci1ud) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L58)):*
> ```JavaScript
> 
> /**
>  * Checks the first word in the given chat data for a key word and reacts appropriately.
> ```

Can you put a comment explaining that all the fields in `chatData` are things `tagpro` provides for us? (ie, this is just how we receive chat messages with the tagpro api)

---

*[src/interface/chat.js, line 77 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUqrMo955-7PVtO4q4:-LAUqrMo955-7PVtO4q5:biay37l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L77)):*
> ```JavaScript
>         `received ${KEY_WORDS.INFORM.ROLE} second parameter that was non-role: ${role}`,
>       );
>       playerRoles[chatData.from] = role;
> ```

FYI just checking here: we still want to make this assignment even if we're reading our own message? (based on the next if statement, im guessing this function gets triggered even from our own chats)

---

*[src/interface/chat.js, line 80 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUpFbmBfj1HvDU0yc9:-LAUpFbmBfj1HvDU0ycA:b-7rt337) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L80)):*
> ```JavaScript
>       if (
>         !idIsMine(chatData.from) &&
>         playerRoles[getMe().id] === ROLES.UNDEFINED &&
> ```

I'm realizing now that I don't like that we use "undefined" as a special string. its scary because `undefined` is also a javascript thing. When i read this, its not immediately obvious `ROLES.UNDEFINED` is a string, not `undefined`. Could we change it to "NOTDEFINED" or similar?

---

*[src/interface/chat.js, line 83 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUqeuCC9wpUG9nACIk:-LAUqeuCC9wpUG9nACIl:b-vgzvf0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L83)):*
> ```JavaScript
>         isMyTurnToAssumeRole()
>       ) {
>         assumeComplementaryRole();
> ```

This is super readable. Well done

---

*[src/interface/chat.js, line 109 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUrGzFC8PKyrgnyuJ-:-LAUrGzFC8PKyrgnyuJ0:b2z4t2u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L109)):*
> ```JavaScript
>       if (idIsMine(playerId)) {
>         playerRoles[playerId] = role;
>         sendMessageToChat(CHATS.TEAM, `${KEY_WORDS.INFORM.ROLE} ${role}`);
> ```

can you explain the workflow again for when another bot would command us to a certain role? or is this just functionality that we're implementing, but not using yet?

---

*[src/look/constants.js, line 9 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUriHy10s627y7_m-1:-LAUriHy10s627y7_m-2:b7rk7ir) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/look/constants.js#L9)):*
> ```JavaScript
>   OFFENSE: 'OFFENSE',
>   CHASING: 'CHASING',
>   DEFENSE: 'DEFENSE',
> ```

FYi This was the placement that felt strangest to me. I thought a bit about it, and I think its the correct place for this to go. It's not completely intuitive, but I can't think of a better place

---

*[src/look/gameState.js, line 71 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUsgEQEMzbW51BvXSF:-LAUsgEQEMzbW51BvXSG:bowjamf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/look/gameState.js#L71)):*
> ```JavaScript
>   });
> 
>   // Add ROLES.UNDEFINED roles to players that aren't bots
> ```

FYI reminder to open a card that we want some special functionality/role for players on our team who aren't bots

---

*[src/look/gameState.js, line 73 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUsbj62ec-SaMAsp1j:-LAUsbj62ec-SaMAsp1k:b-u9p8mw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/look/gameState.js#L73)):*
> ```JavaScript
>   // Add ROLES.UNDEFINED roles to players that aren't bots
>   _.forEach(tagpro.players, player => {
>     // if (playerIsOnMyTeam(player) && !playerRoleIsKnown(player) && !playerIsSomeBall(player)) {
> ```

remove comment

---

*[src/look/gameState.js, line 91 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUsziM8crgBgmyAxtY:-LAUsziM8crgBgmyAxtZ:b-u3mqh1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/look/gameState.js#L91)):*
> ```JavaScript
> 
> export function getNumTeammates() {
>   let numTeammates = 0;
> ```

```return _.filter(tagpro.players, player => playerIsOnMyTeam(player) && !playerIsMe(player)).length```
```


---

*[src/look/gameState.js, line 113 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUtNRoB20RUwLq5ckO:-LAUtNRoB20RUwLq5ckP:bqjkk51) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/look/gameState.js#L113)):*
> ```JavaScript
>  */
> export function isMyTurnToAssumeRole() {
>   cleanTeammateRoles();
> ```

why do we call this here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*
<!-- Sent from Reviewable.io -->

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
Reviewed 10 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/interface/chat.js, line 23 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV1J152rxm6oHmrZRT:-LAV1J152rxm6oHmrZRU:bzi8yei) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/chat.js#L23)):*
> ```JavaScript
> /**
>  * Enqueues the message in the message queue to be chatted when appropriate.
>  * @param {string} message - the message to chat
> ```

add param for chat here

---

*[src/interface/chat.js, line 90 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV4T5gBDJhlgMkpGnh:-LAV4T5gBDJhlgMkpGni:b-l788xh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/chat.js#L90)):*
> ```JavaScript
>       assert(
>         !_.isNaN(playerId),
>         `received ${KEY_WORDS.REQUEST.ROLE} first parameter that was non-number: ${msg[1]}`,
> ```

FYI these asserts make it so that another user can maliciously break our app through chats, idk how we feel about this

---

*[src/interface/constants.js, line 8 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV5YQD-PP_gGnHWxI2:-LAV5YQD-PP_gGnHWxI3:b-yajl8a) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/constants.js#L8)):*
> ```JavaScript
> export const KEY_WORDS = {
>   INFORM: {
>     ROLE: 'TPBIR',
> ```

what do you think of making these 'TPB-IR'

---

*[src/interface/constants.js, line 14 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV5Rm73lAyIpKl9Ih6:-LAV5Rm73lAyIpKl9Ih7:br33iap) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/constants.js#L14)):*
> ```JavaScript
>   },
>   COMMAND: {
>     ROLE: 'TPBCR',
> ```

is there a future reason why these are nested objects instead of just INFORM_ROLE being one key?

---

*[src/look/gameState.js, line 50 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV67955ASBa9su0JvK:-LAV67955ASBa9su0JvL:bt1pbx4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L50)):*
> ```JavaScript
> 
> 
> function playerIsSomeBall(player) {
> ```

is this how we want to determine bots vs. non bots for now?  Maybe include in the handling non-bots card that we can use players that don't respond appropriately to chats to determine that they're not bots

---

*[src/look/gameState.js, line 63 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV6V3V48Ezo6fYa06H:-LAV6V3V48Ezo6fYa06I:b-kwhh3o) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L63)):*
> ```JavaScript
> /**
>  * Remove roles for players that are no longer in the game and add ROLES.UNDEFINED roles for each
>  *   player that think is not a bot
> ```

that think -> that we think

---

*[src/look/gameState.js, line 125 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV9-fq-cjWrBMOzs4K:-LAV9-fq-cjWrBMOzs4L:b-z8ukju) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L125)):*
> ```JavaScript
>   let numDefense = 0;
> 
>   _.forEach(playerRoles, playerRole => {
> ```

what do you think about `_.countBy(playerRoles)`

which would return an object like `{ OFFENSE: 2, DEFENSE: 1 }`, but if there is no one on defense that key won't exist in the object so it may be more work that it's worth

---

*[src/look/gameState.js, line 129 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV9gXo2N4rLU1xcoPH:-LAV9gXo2N4rLU1xcoPI:bweb50x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L129)):*
> ```JavaScript
>     else if (playerRole === ROLES.DEFENSE) numDefense += 1;
>   });
>   if (numDefense < numOffense) playerRoles[getMe().id] = ROLES.DEFENSE;
> ```

what do you think about a `assignMyselfToRole()` function, and you could use it in the chat file too

also a `getMyRole()` function?

---

*[src/look/setup.js, line 59 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAVA5fZ6UGzd2v8RqRt:-LAVA5fZ6UGzd2v8RqRu:bi240ie) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/setup.js#L59)):*
> ```JavaScript
> export function setupRoleCommunication() {
>   const numTeammates = getNumTeammates();
>   if (numTeammates === 0) {
> ```

make this an inline call to getNumTeammates()

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[src/interface/chat.js, line 17 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUoZxDAMAhetejitYb:-LAj511d16zaK2JPylx4:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L17)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

can you leave comment explaining what each object in the list has? (`{chat: string, message: string}` or similar)
</blockquote></details>

Done.

---

*[src/interface/chat.js, line 58 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUq7IUCLVG9FT1esZy:-LAj5fFl7-GHJMQUAWGi:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L58)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Can you put a comment explaining that all the fields in `chatData` are things `tagpro` provides for us? (ie, this is just how we receive chat messages with the tagpro api)
</blockquote></details>

Done.

---

*[src/interface/chat.js, line 77 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUqrMo955-7PVtO4q4:-LAj5hV8EPdkIYkb0xQo:bhsgjcs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L77)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI just checking here: we still want to make this assignment even if we're reading our own message? (based on the next if statement, im guessing this function gets triggered even from our own chats)
</blockquote></details>

I left it in just so we can overwrite our own role if we want. Thoughts?

---

*[src/interface/chat.js, line 80 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUpFbmBfj1HvDU0yc9:-LAj6Hdb2S50jeYZwMNH:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L80)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I'm realizing now that I don't like that we use "undefined" as a special string. its scary because `undefined` is also a javascript thing. When i read this, its not immediately obvious `ROLES.UNDEFINED` is a string, not `undefined`. Could we change it to "NOTDEFINED" or similar?
</blockquote></details>

Done.

---

*[src/interface/chat.js, line 23 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV1J152rxm6oHmrZRT:-LAj5MTpEIZQTxw6vrjD:b-g2bjml) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/chat.js#L23)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

add param for chat here
</blockquote></details>

Done. Is that how you document something with limited options?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[src/interface/chat.js, line 23 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV1J152rxm6oHmrZRT:-LAj9MC20W4t_b_rm5VC:b30hx99) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/chat.js#L23)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done. Is that how you document something with limited options?
</blockquote></details>

OK seems dank to me

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 5 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/interface/chat.js, line 77 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAUqrMo955-7PVtO4q4:-LAjsGQ0BEBFtEzRxVRm:b1penbq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0efd47380bd89ab5922cbd868badef47dc7c50c7/src/interface/chat.js#L77)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I left it in just so we can overwrite our own role if we want. Thoughts?
</blockquote></details>

Ah makes sense. :dango: 

---

*[src/interface/constants.js, line 14 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV5Rm73lAyIpKl9Ih6:-LAjsvP69ZrKzhcgp9Gw:b-szmli6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/constants.js#L14)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I had dreams of being able to communicate other things, though that might be pretty far off (maybe things like where the enemy FC is if one bot can see them and another bot can). I could un-nest stuff for now if you like?
</blockquote></details>

I like dreaming big.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
*[src/look/gameState.js, line 50 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV67955ASBa9su0JvK:-LAkaoctBDC8Vjn1cgLB:b-1vd5gt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L50)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
https://app.zenhub.com/workspace/o/chauncy-crib/tagprobot/issues/407
</blockquote></details>

are we keeping this function even if it's not used?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/interface/chat.js, line 90 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV4T5gBDJhlgMkpGnh:-LAkbDNQBRcR1mzd1n7B:b-x5trhf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/chat.js#L90)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yeah good point... thoughts? Just log something in the console?
</blockquote></details>

Yeah maybe that's better

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by shanek21** [comment]
Review status: 5 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/look/gameState.js, line 50 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV67955ASBa9su0JvK:-LAtN1NzAUETJW_vLLgv:b3dtjai) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

are we keeping this function even if it's not used?
</blockquote></details>

I was going to leave it. Should I remove it?

---

*[src/look/gameState.js, line 129 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV9gXo2N4rLU1xcoPH:-LAtN8mC5TaMg8lxte5P:b-qhu9sq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L129)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what do you think about a `assignMyselfToRole()` function, and you could use it in the chat file too

also a `getMyRole()` function?
</blockquote></details>

Done. I called them `getMyRole()` and `setMyRole()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by shanek21** [comment]
Review status: 5 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/interface/chat.js, line 90 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV4T5gBDJhlgMkpGnh:-LAtPgOh8p8sUontMuYk:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/interface/chat.js#L90)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Yeah maybe that's better
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 3 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/global/utils.js, line 5 at r7](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAtcAyNBZEdlj2KP5b7:-LAtcAyNBZEdlj2KP5b8:b-65gbv3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e9e11a937cb3ed25fd1a5e0fea84504b6013c76a/src/global/utils.js#L5)):*
> ```JavaScript
>  * is specified, then a default error message is thrown.
>  *
>  * condition: the condition, which, if false, will cause an error to be thrown
> ```

lol wow how did we have this. thanks shane!

---

*[src/global/utils.js, line 35 at r7](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAtcFSQ-CAaJPPv-FPb:-LAtcFSQ-CAaJPPv-FPc:b77lgik) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3aa0df0cbd6a032d610de35e381d5d69d00ca4f1/src/global/utils.js#L35)):*
> ```JavaScript
> /**
>  * A less strict version of the assert function above. Sends the specified error message to the
>  *   cosole if the condition is not true.
> ```

Where's the cosole? Why would we send messages there

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by shanek21** [comment]
Review status: 6 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/global/utils.js, line 35 at r7](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAtcFSQ-CAaJPPv-FPb:-LAtdnTv57fTLQ7C-ewu:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3aa0df0cbd6a032d610de35e381d5d69d00ca4f1/src/global/utils.js#L35)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Where's the cosole? Why would we send messages there
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
Reviewed 4 of 5 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/look/gameState.js, line 50 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV67955ASBa9su0JvK:-LAtlWyz3WMdonSs017i:b-e6w99f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L50)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I was going to leave it. Should I remove it?
</blockquote></details>

Hmm what does @davidabrahams think

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/look/gameState.js, line 50 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-LAV67955ASBa9su0JvK:-LAxVatrCMK0eg1O2CNF:b80ujun) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/5b7f5ac6f74432dae542e3f5ec2fc488bfabd515/src/look/gameState.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmm what does @davidabrahams think
</blockquote></details>

I think given that an issue exists which references using this funciton, we should keep it aruond

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 2 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404)*

**Comment by davidabrahams** [comment]
:dango:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/404#-:-LB2a3In56ZDCgl2mOxv:bcbqss6)*

**Pull request merged**
