### PR TITLE
166: Restructure the test directory to mirror the src directory

### LINKED ISSUE #166: Make the structure in the `test/` directory mirror the structure in the `src/`
For example, `map.spec.js` should be `test/helpers/map.spec.js`

### PR DESCRIPTION
**Pull request by shanek21**
Closes #166

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/170)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/170)*

**Comment by davidabrahams** [comment]
Grrrr I like opening tests to be easy...but we should probably do this. I'm just so lazy with typing out paths.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/170#-:-KsWq33dZG-3fqiwPgxv:b7dy0z5)*

**Comment by davidabrahams** [comment]
:dango:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/170#-:-KsWqANnmi-i8Xz8f7J8:bcbqss6)*

**Comment by davidabrahams** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/170)*

**Pull request merged**
