### PR TITLE
192: Fix tagpro object mock declaration in test

### LINKED ISSUE #192: Fix tagpro object mock declaration in test
:fire:

### PR DESCRIPTION
**Pull request by billmwong**
Closes #192

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/193)

### CODE REVIEW

**Comment by shanek21** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193#-KsykK5c_0YfzOu5FPPJ:-KsykK5c_0YfzOu5FPPK:b-8ujshx) (no related file):*
Commit message should have an issue number

---

*[test/helpers/finders.spec.js, line 25 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193#-KsykT33k5xqUnvB4ICj:-KsykT33k5xqUnvB4ICk:b-yvt8f4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/73765268dde7331743faac38636196da89aa0e92/test/helpers/finders.spec.js#L25)):*
> ```JavaScript
>       [blank,   spike,    bomb   ],
>     ],
>   };
> ```

Uh... I don't understand, but if it works, then I'm happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193)*

**Comment by billmwong** [comment]
*[test/helpers/finders.spec.js, line 25 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193#-KsykT33k5xqUnvB4ICj:-KsykblwlzdY-JsqiiuO:bh0yg1m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/73765268dde7331743faac38636196da89aa0e92/test/helpers/finders.spec.js#L25)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Uh... I don't understand, but if it works, then I'm happy.
</blockquote></details>

If `global.tagpro` is not defined yet, then you can't try to set `global.tagpro.map` directly.  Travis may have been running the tests in a different order than locally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193)*

**Comment by billmwong** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193#-KsykK5c_0YfzOu5FPPJ:-KsykqTj_-Ad5jSxyxfR:bnjoe47) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Commit message should have an issue number
</blockquote></details>

:sob: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193)*

**Comment by davidabrahams** [comment]
:dango:

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/193#-:-KsymjpwYsgPtRTf8PT9:bcbqss6)*

**Pull request merged**
