### PR TITLE
164: Change eslintconfig to airbnb-base instead of full airbnb

### LINKED ISSUE #164: Change eslintconfig to airbnb-base instead of full airbnb
The full airbnb includes the react linters, which we don't need.  I didn't know before the airbnb-base was a thing.  This will clean up our dependencies.

### PR DESCRIPTION
**Pull request by billmwong**
Closes #164

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/165)

### CODE REVIEW

**Comment by shanek21** [comment]
You have a commit message with the issue number in it?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-:-KsVdD5ZFAlt172DnRuM:bi947ap)*

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165)*

**Comment by billmwong** [comment]
Yeah I just do that sometimes not a convention we need to follow

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-:-KsWu5AaTr8BCS94Ch3x:b2nojb6)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package-lock.json, line 0 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-KsX8UvF6PRUcb82UgWU:-KsX8UvF6PRUcb82UgWV:b-px8hz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8ee80eeafae170678a10ec761a3e40a0388dfa3c/package-lock.json#L0)):*
padding your "delete" count i see

---

*[webpack.config.js, line 2 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-KsX8YmGrl04HNNLOhWe:-KsX8YmGrl04HNNLOhWf:b-nj6d5a) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/185a2c76b6b9ec062bd6a29bf2caa3c76acc8ed0/webpack.config.js#L2)):*
> ```JavaScript
> var path = require('path');
> var glob = require('glob');
> ```

maybe webpack supplies `glob` by default? man idk. Make sure its not in package.json or something (assuming we don't need it there? unsure)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package-lock.json, line  at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-KsX8UvF6PRUcb82UgWU:-KsXQq4pkrC6Eg0zE9ox:b-6298bo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8ee80eeafae170678a10ec761a3e40a0388dfa3c/package-lock.json#L)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

padding your "delete" count i see
</blockquote></details>

Hahahah yep

---

*[webpack.config.js, line 2 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-KsX8YmGrl04HNNLOhWe:-KsXQwEcgXNtA9IH8FKu:b-t9d9cf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/185a2c76b6b9ec062bd6a29bf2caa3c76acc8ed0/webpack.config.js#L2)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

maybe webpack supplies `glob` by default? man idk. Make sure its not in package.json or something (assuming we don't need it there? unsure)
</blockquote></details>

Yeah I checked, we're not requiring it in package.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165)*

**Comment by davidabrahams** [comment]
Get rid of the merge commit, otherwise this is gucci

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165#-:-KsZW-9nWgvDVwBhKenW:b-ozk2vi)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/165)*

**Pull request merged**
