### PR TITLE
89: Send command options to chat at beginning of each game

### LINKED ISSUE #89: Start each game with a chat message that prints our available commands
We currently only have Q and V, but I already forget them all the time.

### PR DESCRIPTION
**Pull request by shanek21**
Closes #89

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/120)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index.js, line 46 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120#-KrMtPOyJKykiwdwCjSz:-KrMtPOyJKykiwdwCjT-:b-nu8j3a) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/87461a8c2d6989fe777bc2d831e2613b09076f1c/src/index.js#L46)):*
> ```JavaScript
>   }
> }
> ```

Lol the main purpose of this PR was just to add whitespace, wasn't it

---

*[src/utils/interface.js, line 12 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120#-KrMtbw89OKr_8zr2Yjm:-KrMtbw89OKr_8zr2Yjn:b-55t7da) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/87461a8c2d6989fe777bc2d831e2613b09076f1c/src/utils/interface.js#L12)):*
> ```JavaScript
> let lastMessage = 0;
> export function chat(chatMessage) {
>   // Seems that TagPro keeps you from sending a chat message faster than every
> ```

Thanks for commenting this. I'm not sure I ever paid attention to this block of code

---

*[src/utils/interface.js, line 75 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120#-KrMtuxpAlY1KKsJPh3e:-KrMtuxpAlY1KKsJPh3f:b-hwyt5n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/87461a8c2d6989fe777bc2d831e2613b09076f1c/src/utils/interface.js#L75)):*
> ```JavaScript
>       chat(`Visuals ${visualsMode}`);
>       break;
>     } default:
> ```

Do you need an explicit empty default case? Just curious

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 46 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120#-KrMtPOyJKykiwdwCjSz:-KrOHohW0MehuR9_woMt:bn190wv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/87461a8c2d6989fe777bc2d831e2613b09076f1c/src/index.js#L46)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Lol the main purpose of this PR was just to add whitespace, wasn't it
</blockquote></details>

https://en.wikipedia.org/wiki/Rider_(legislation)

---

*[src/utils/interface.js, line 75 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120#-KrMtuxpAlY1KKsJPh3e:-KrOHtswEXVXS2cRo1n8:b-uvhwkm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/87461a8c2d6989fe777bc2d831e2613b09076f1c/src/utils/interface.js#L75)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Do you need an explicit empty default case? Just curious
</blockquote></details>

Yeah, the linter made me have a default case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120)*

**Comment by altodyte** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120)*

**Comment by altodyte** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/120)*

**Pull request merged**
