### PR TITLE
136: only update visuals for cells that did change, instead of cells that might have changed

### LINKED ISSUE #136: Only update visuals for cells that did change, instead of cells that might have changed.
See pr #126

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #136

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/274)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/draw/drawings.js, line 31 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAZr3VejFYjDyVVdjr:-KzAZr3VejFYjDyVVdjs:b-rrbpn4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/draw/drawings.js#L31)):*
> ```JavaScript
> // then store null. This object is size tagpro_map_length * CPTL x tagpro_map_width * CPTL
> let tempNTSprites = [];
> let tempNTSpritesOnScreen = false;
> ```

`tempNTSpritesDrawn`?
`tempNTSpritesRendered`?

On screen kind of sounds like it could mean they are drawn, but just not visible from the user's current screen view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/helpers/map.js, line 8 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzA_NLxKaXonPQFVR-u:-KzA_NLxKaXonPQFVR-v:bqbdqfv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L8)):*
> ```JavaScript
>   generatePermanentNTSprites,
>   areNTSpritesOnScreen,
>   setNTSpritesOnScreen } from '../draw/drawings';
> ```

each thing on its own line

---

*[src/helpers/map.js, line 240 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzA_WdA3yGHnjgIOdQe:-KzA_WdA3yGHnjgIOdQf:b97u20t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L240)):*
> ```JavaScript
>       tilesToUpdateValues[i] = tileId;
>       // O(CTPL^2)
>       // console.log(xy);
> ```

no console

---

*[src/helpers/map.js, line 280 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAac4g0IEbkKUd5srQ:-KzAac4g0IEbkKUd5srR:bh1a5pp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L280)):*
> ```JavaScript
>     }
>     // Otherwise, update all non-permanent sprites
>     if (!areNTSpritesOnScreen()) updateNTSprites(xy.xt, xy.yt, mapTraversabilityCells);
> ```

I don't quite understand the logic in these four lines, can you explain?

---

*[src/helpers/map.js, line 282 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAaSU_bDn18R4Kfwx3:-KzAaSU_bDn18R4Kfwx4:b-c5ephu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L282)):*
> ```JavaScript
>     if (!areNTSpritesOnScreen()) updateNTSprites(xy.xt, xy.yt, mapTraversabilityCells);
>   }
>   setNTSpritesOnScreen(true);
> ```

what do you think of updating this in updateNTSprites() instead of making the user set it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAb-we5piU_ZiJImQM:-KzAb-we5piU_ZiJImQN:bj25x50) (no related file):*
FYI your PR title is riding the fence with how close it is to the issue title  :flushed: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by davidabrahams** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/draw/drawings.js, line 31 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAZr3VejFYjDyVVdjr:-KzAe88ieoTxcZ_wQceD:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/draw/drawings.js#L31)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

`tempNTSpritesDrawn`?
`tempNTSpritesRendered`?

On screen kind of sounds like it could mean they are drawn, but just not visible from the user's current screen view.
</blockquote></details>

Done.

---

*[src/helpers/map.js, line 8 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzA_NLxKaXonPQFVR-u:-KzAeIgcMdU018FXEmTu:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L8)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

each thing on its own line
</blockquote></details>

Done.

---

*[src/helpers/map.js, line 240 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzA_WdA3yGHnjgIOdQe:-KzAeL1maFV9S8bAg4Gg:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L240)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

no console
</blockquote></details>

Done.

---

*[src/helpers/map.js, line 280 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAac4g0IEbkKUd5srQ:-KzAeWhFkC6hOuBSYBGr:bbid84h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L280)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I don't quite understand the logic in these four lines, can you explain?
</blockquote></details>

Might be easier in person?

---

*[src/helpers/map.js, line 282 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAaSU_bDn18R4Kfwx3:-KzAeQ9fO92RLq8f9RqK:bceisi7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L282)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what do you think of updating this in updateNTSprites() instead of making the user set it
</blockquote></details>

It actually has to be here, because updateNTSprites is called multiple times by this function. You only want to change the variable after all of the calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/helpers/map.js, line 5 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAfR4IiJEXgeinQU-6:-KzAfR4IiJEXgeinQU-7:bgujep3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d493a928f14975f14870e7b853b3ad8a3a6af52a/src/helpers/map.js#L5)):*
> ```JavaScript
> import { assert, assertGridInBounds } from '../utils/asserts';
> import { tileHasName, getTileProperty, tileHasProperty, tileIsOneOf } from '../tiles';
> import { updateNTSprites,
> ```

each thing on its own line for the first thing too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
*[src/helpers/map.js, line 282 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAgpKbi0BWv8WhTzib:-KzAgpKbi0BWv8WhTzic:bj9hedx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d493a928f14975f14870e7b853b3ad8a3a6af52a/src/helpers/map.js#L282)):*
> ```JavaScript
>     if (!areNTSpritesOnScreen()) updateNTSprites(xy.xt, xy.yt, mapTraversabilityCells);
>   }
>   setNTSpritesOnScreen(true);
> ```

Are we setting this to true every frame?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/helpers/map.js, line 280 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAac4g0IEbkKUd5srQ:-KzBG55vAwd3kvZZkiO4:b-d4ys7d) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L280)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Might be easier in person?
</blockquote></details>

Done. in person

---

*[src/helpers/map.js, line 5 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAfR4IiJEXgeinQU-6:-KzAjS80ghgKBuhdsMYd:b-qsx7u6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d493a928f14975f14870e7b853b3ad8a3a6af52a/src/helpers/map.js#L5)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

each thing on its own line for the first thing too
</blockquote></details>

Done. Oops.

---

*[src/helpers/map.js, line 282 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAgpKbi0BWv8WhTzib:-KzBGTDQ1KOkEdwukew6:b-gds3kj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d493a928f14975f14870e7b853b3ad8a3a6af52a/src/helpers/map.js#L282)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Are we setting this to true every frame?
</blockquote></details>

Done. Now only when visualMode is on

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 280 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAac4g0IEbkKUd5srQ:-KzF5V2IVJTS6f_m869T:b-gjy3z6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L280)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done. in person
</blockquote></details>

I probably understood when you explained, but the fact that I no longer understand even after reading your comments here multiple times makes me think this needs better documentation somehow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by davidabrahams** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 280 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAac4g0IEbkKUd5srQ:-KzGJjb1UvnWzdWRX1hr:b-5fbro5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L280)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I probably understood when you explained, but the fact that I no longer understand even after reading your comments here multiple times makes me think this needs better documentation somehow
</blockquote></details>

Uhhh. I added more comments. Let me know if there is more confusion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r6.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzLNgnclmSnMNIns0RX:-KzLNgnclmSnMNIns0RY:bg0qb81) (no related file):*
commit should start with a verb

---

*[src/helpers/map.js, line 284 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzLN_TTAt5dKWBlpdBE:-KzLN_TdET2gnhow9xmS:b-o3cpxb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ac1516994fe612d2e0a23d61cee679f8b2f1ea46/src/helpers/map.js#L284)):*
> ```JavaScript
>     // If the NT sprites are not already on the screen, then update the sprites for all tiles. This
>     // ensures that when visual mode is turned on, new sprites are generated for all temp-NT tiles.
>     // If visual mode is off, then the call to updateNTSprites does nothing.
> ```

Add indentation on multiline comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by davidabrahams** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzLNgnclmSnMNIns0RX:-KzLxmCOJ2fwjSKJ0j_E:bb6un1j) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

commit should start with a verb
</blockquote></details>

Done

---

*[src/helpers/map.js, line 284 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzLN_TTAt5dKWBlpdBE:-KzLQdmSt4im3GOKm4Bq:b-3js43o) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ac1516994fe612d2e0a23d61cee679f8b2f1ea46/src/helpers/map.js#L284)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Add indentation on multiline comments.
</blockquote></details>

Is that our convention? If it is...i want to note that I don't like it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by davidabrahams** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/helpers/map.js, line 284 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzLN_TTAt5dKWBlpdBE:-KzLxqv6_AMaflnbHNNN:bmfxgbn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ac1516994fe612d2e0a23d61cee679f8b2f1ea46/src/helpers/map.js#L284)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Is that our convention? If it is...i want to note that I don't like it.
</blockquote></details>

Done :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r7.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 411 at r7](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzR_L5qk8XG5xCZy_fW:-KzR_L5qk8XG5xCZy_fX:b-fo7n07) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1e168aae7af0fc1401e8da3ff8ba57c6e07649a5/src/draw/drawings.js#L411)):*
> ```JavaScript
> }
> 
> export function areNTSpritesOnScreen() {
> ```

can you rename this to reflect the new name of this variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by davidabrahams** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 411 at r7](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzR_L5qk8XG5xCZy_fW:-KzRefF0pfs-m5aE7Iqs:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1e168aae7af0fc1401e8da3ff8ba57c6e07649a5/src/draw/drawings.js#L411)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can you rename this to reflect the new name of this variable
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r7, 3 of 3 files at r8.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/map.js, line 280 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KzAac4g0IEbkKUd5srQ:-KzRYtcAz_VTfBwjovGA:bg5yeix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e90015559a8e5e73dc998e495d5fe59d56af8b0/src/helpers/map.js#L280)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Uhhh. I added more comments. Let me know if there is more confusion?
</blockquote></details>

OK Yeah now I understand. The confusion for me was the nested if's, because the first if is checking if the tile has changed state, and the second if is checking if the sprites are on screen.  And these two lines are not an if-else block, because one is nested and one is not nested.  But now I understand

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r8.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/draw/drawings.js, line 415 at r8](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274#-KziqwvaOFEAifAPkSbr:-KziqwvaOFEAifAPkSbs:bwp5d1y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/807a527fbb50a2abb69181a9ad41de7490dad193/src/draw/drawings.js#L415)):*
> ```JavaScript
> }
> 
> export function setNTSpritesOnScreen(b) {
> ```

This name is a bit odd to me. Could we use the word drawn in this function name or would that seem to much like this actually draws them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r9.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r9.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/274)*

**Pull request merged**
