### PR TITLE
391: defense fsm

### LINKED ISSUE #391: Implement Defense FSM
Abstract out "flaccid position" to be just sitting on the flag for now.

- If enemy has flag: chase them
- If enemy has flag but we can’t see them: go to their base
- If we’re not in our base (some distance away from our flag): go back to base
- If enemy has rolling bomb: chase them (with their target set to our flag)
- If one enemy: flaccid position
- If greater than one enemies: choose enemy closer to flag to flaccid
- Else no enemies: sit on flag

### PR DESCRIPTION
**Pull request by shanek21**
Closes #391

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 11 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/start.js, line 53 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd2UNy1g7TBOh7W3P4:-LBd2UNy1g7TBOh7W3P5:b-9v25vr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/start.js#L53)):*
> ```JavaScript
>   const { map } = tagpro;
>   const me = getMe();
>   const { goal, enemyShortestPath } = FSM(me);
> ```

probably leaving comment in the wrong spot, but `enemyShortestPath` should be null if enemy doesnt have flag

---

*[src/look/playerLocations.js, line 16 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd2tR3-30mnIwbKRLi:-LBd2tR3-30mnIwbKRLj:bst2cw1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/playerLocations.js#L16)):*
> ```JavaScript
>     player.flag &&
>     !player.dead &&
>     player.draw
> ```

can you leave a comment for what `draw` is? I checked the API to clarify, its the only one of these fields which isn't self-documenting

---

*[src/look/playerLocations.js, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd33wX7r5WdHaZOn6b:-LBd33wX7r5WdHaZOn6c:b-63uxj5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/playerLocations.js#L35)):*
> ```JavaScript
> 
> export function playerIsNearPoint(player, point, distance = 300) {
>   if (!(_.has(player, 'x') && _.has(player, 'y'))) return false;
> ```

in which situation does this if statement happen?

---

*[src/look/playerLocations.js, line 36 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd3Bx98ShbzvtKajNx:-LBd3Bx98ShbzvtKajNy:bgrzeaj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/playerLocations.js#L36)):*
> ```JavaScript
> export function playerIsNearPoint(player, point, distance = 300) {
>   if (!(_.has(player, 'x') && _.has(player, 'y'))) return false;
>   return point.distance(new Point(player.x, player.y)) <= distance;
> ```

I believe this is using player's top-left location, and the base's center location?

---

*[src/look/playerLocations.js, line 56 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd3NwU7w7ex3t_8qK5:-LBd3NwU7w7ex3t_8qK6:b-ambwwy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/playerLocations.js#L56)):*
> ```JavaScript
>  */
> export function getPlayerClosestToPoint(players, point) {
>   return _.min(players, player => point.distance(new Point(player.x, player.y)));
> ```

same comment as above WRT top-left?

---

*[src/look/setup.js, line 60 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd3UXB32uA24GDqC3C:-LBd3UXB32uA24GDqC3D:b-l6mwxj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/setup.js#L60)):*
> ```JavaScript
> export function setupRoleCommunication() {
>   if (getNumTeammates() === 0) {
>     // setMyRole(ROLES.OFFENSE);
> ```

remove

---

*[src/look/test/playerLocations.spec.js, line 21 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd3gwY0WFtX-S2mkL5:-LBd3gwY0WFtX-S2mkL6:b-2nssx6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/test/playerLocations.spec.js#L21)):*
> ```JavaScript
>     const point = new Point(0, 0);
> 
>     t.is(playerIsNearPoint(mockPlayer, point), false);
> ```

FYI these tests test the default behavior of your func. Maybe add a test that tests the non-default behavior? (ie, when you specify dist?)

---

*[src/think/fsm.js, line 188 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd49NF503oWRGIw1g2:-LBd49NF503oWRGIw1g3:byjnt9g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/think/fsm.js#L188)):*
> ```JavaScript
>     // If we are not in our base, go to the ally flag station
>     const base = findAllyFlagStation();
>     if (!playerIsNearPoint(me, new Point(base.xp, base.yp))) {
> ```

FYI let's do an in person test of each of these FSM states before merging this

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by billmwong** [comment]
*[src/look/playerLocations.js, line 48 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgZdN_AYamURIWHeVD:-LBgZdN_AYamURIWHeVE:bvihk9s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/look/playerLocations.js#L48)):*
> ```JavaScript
> 
> 
> export function playerIsNearPoint(player, point, distance = 300) {
> ```

distance -> maxDistance or threshold or something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by billmwong** [comment]
*[src/think/fsm.js, line 183 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgfe4z-XPxp7Otmo-_:-LBgfe4z-XPxp7Otmo-a:b67b49x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/think/fsm.js#L183)):*
> ```JavaScript
>       const goal = findEnemyFlagStation();
>       const enemyShortestPath = null;
>       updateStateMessage('Enemy has the flag. Headed towards the center flag station!');
> ```

center flag -> enemy flag

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by billmwong** [comment]
*[src/think/fsm.js, line 187 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgfuX4EOvcvxamIiak:-LBgfuX4EOvcvxamIial:b-1zq8gf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/think/fsm.js#L187)):*
> ```JavaScript
>     }
>     // If we are not in our base, go to the ally flag station
>     const base = findAllyFlagStation();
> ```

are we calling this a base or a flag station

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by billmwong** [comment]
*[src/think/fsm.js, line 150 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBggNNW2czKzz0WZ6zu:-LBggNNW2czKzz0WZ6zv:b-czkbdj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/think/fsm.js#L150)):*
> ```JavaScript
> function twoFlagFSM(me) {
>   const myRole = getMyRole();
>   if (myRole === ROLES.OFFENSE) {
> ```

what do you think about further separating out twoFlagOffenseFSM() and twoFlagDefenseFSM()

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by billmwong** [comment]
Reviewed 7 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/look/playerLocations.js, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd33wX7r5WdHaZOn6b:-LBgujYP1604RWHbKbgJ:b-2f2reu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/playerLocations.js#L35)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

If the player isn't in view, then they don't have the `x` and `y` attributes. Maybe it should assert that instead? Or prefer it?
</blockquote></details>

Assert is gucci

---

*[src/look/playerLocations.js, line 48 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgZdN_AYamURIWHeVD:-LBguZPw5Fm3JR0PT3Ak:b-uflbx4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/look/playerLocations.js#L48)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

distance -> maxDistance or threshold or something?
</blockquote></details>

FYI I like threshold

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by shanek21** [comment]
Review status: 7 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/look/playerLocations.js, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd33wX7r5WdHaZOn6b:-LBhRs1F4948VpIPMEZR:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/look/playerLocations.js#L35)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Assert is gucci
</blockquote></details>

Done.

---

*[src/look/playerLocations.js, line 48 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgZdN_AYamURIWHeVD:-LBhTS5y-Sza5UWDItFC:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/look/playerLocations.js#L48)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI I like threshold
</blockquote></details>

Done.

---

*[src/think/fsm.js, line 150 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBggNNW2czKzz0WZ6zu:-LBhSra93jZYtKIEW7xm:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/think/fsm.js#L150)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what do you think about further separating out twoFlagOffenseFSM() and twoFlagDefenseFSM()
</blockquote></details>

Done.

---

*[src/think/fsm.js, line 183 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgfe4z-XPxp7Otmo-_:-LBhT-BZ5F4VDYWOw_PY:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/think/fsm.js#L183)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

center flag -> enemy flag
</blockquote></details>

Done.

---

*[src/think/fsm.js, line 187 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBgfuX4EOvcvxamIiak:-LBhTQhJ1BZb1AXzD02k:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3e3b8c6d03c2ee790a19cda17f2d78108a33aada/src/think/fsm.js#L187)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

are we calling this a base or a flag station
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/think/fsm.js, line 188 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd49NF503oWRGIw1g2:-LBr4ko14szbpuH8lSRF:b1n0nav) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/think/fsm.js#L188)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Good idea.
</blockquote></details>

Cool to merge once you test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/think/fsm.js, line 188 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/425#-LBd49NF503oWRGIw1g2:-LBr5jWsD3JPx8P3r2L4:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7eb7d84136029e627ccd33b4b8910bcb1d1b5e1c/src/think/fsm.js#L188)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Cool to merge once you test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)*

**Pull request merged**
