### PR TITLE
458 cache triangulation

### LINKED ISSUE #458: Cache/load dtGraph

### LINKED ISSUE #482: Use flatted to parse/load our cache
https://github.com/WebReflection/flatted#flatted

### LINKED ISSUE #483: Keep a global counter so that each TriangleTreeNode has a unique ID

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #458
Closes #482 
Closes #483

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/start.js, line 123 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRFkE22HG-eJN9Ekh3:-LCRFkE22HG-eJN9Ekh4:b2vs1uy) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/start.js#L123)):*
> ```JavaScript
>     timeLog('Initialized tiles to update.');
>   }
>   initNavMesh(internalMap, !isCached());
> ```

move this inside the if statement and don't pass in isCached

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/start.js, line 123 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRFkE22HG-eJN9Ekh3:-LCRHfFB0GMhkvVZhxBp:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/start.js#L123)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

move this inside the if statement and don't pass in isCached
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Reviewed 18 of 18 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[webpack.config.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRFBbuEIYlC3pRdVX5:-LCRFBbv2Azcn71t3MOM:b-y19aqo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/webpack.config.js#L22)):*
> ```JavaScript
>           test: [/\.js$/],
>           // Only include files in the client directory (so we don't compile our node modules or
>           // server side code)
> ```

delete server side code mentions

---

*[src/interpret/class/Triangle.js, line 44 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRGjgK6j_phSOndTOU:-LCRGjgK6j_phSOndTOV:b-3ih78v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/Triangle.js#L44)):*
> ```JavaScript
> 
>   fromObject(o) {
>     this.p1 = (new Point()).fromObject(o.p1);
> ```

Wait until @shanek21 looks at this, but I say make this use the deserializePoint() helper function

---

*[src/interpret/class/TriangleGraph.js, line 60 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRGvG8BzCKCYnE4Mlg:-LCRGvG8BzCKCYnE4Mlh:bxtj8px) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/TriangleGraph.js#L60)):*
> ```JavaScript
>       }),
>     )).fromObject(o.polypoints);
>     // TODO
> ```

did you forget to do something or forget to delete this comment

---

*[src/interpret/class/TriangleGraph.js, line 63 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRHC1XAop9O4DDloy-:-LCRHC1YBtZYuFrcCSmY:befvycp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/TriangleGraph.js#L63)):*
> ```JavaScript
>     this.rootNode = (new TriangleTreeNode()).fromObject(o.rootNode, []);
>     _.forOwn(o.fixedAdj, (adjList, pointStr) => {
>       this.fixedAdj[pointStr] = _.map(adjList, p => (new Point()).fromObject(p));
> ```

same thing here about using deserializePoint

---

*[src/interpret/class/TriangleTreeNode.js, line 95 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRIIut-6Eufqp1UldT:-LCRIIuuCdeWyXgmlnTS:b-r5np9u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/TriangleTreeNode.js#L95)):*
> ```JavaScript
>     this.id = o.id;
>     this.children = _.map(o.children, c => {
>       const childId = c.id;
> ```

could do `const { id } = c;`  

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRIzwZ8BzSryuJQhFS:-LCRIzwZ8BzSryuJQhFT:bdwzwjc) (no related file):*
says "closes" for all three cache cards, but make the commit message only reference the 458 card

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
Review status: 2 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRIzwZ8BzSryuJQhFS:-LCRJmHKA8dGx0dfdMgZ:b-8t60qr) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

says "closes" for all three cache cards, but make the commit message only reference the 458 card
</blockquote></details>

 done

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
*[src/interpret/class/TriangleTreeNode.js, line 95 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRIIut-6Eufqp1UldT:-LCRKSmJCW8g8TpkOo8I:b-5u2s33) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/TriangleTreeNode.js#L95)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

could do `const { id } = c;`  
</blockquote></details>

I feel like this is a little more readable, just since we're inside a tree node, but the `id` is the `childId`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r3.
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
Review status: 2 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[webpack.config.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRFBbuEIYlC3pRdVX5:-LCRKIUT4VCotfkqNmzJ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/webpack.config.js#L22)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

delete server side code mentions
</blockquote></details>

Done.

---

*[src/interpret/class/TriangleGraph.js, line 60 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRGvG8BzCKCYnE4Mlg:-LCRKQWf4bFwAt6D93Kq:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/TriangleGraph.js#L60)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

did you forget to do something or forget to delete this comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Reviewed 14 of 18 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/start.js, line 105 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRQKl50NzAwilVaBDi:-LCRQKl69z4zE6q1iPED:b-92qkyb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/start.js#L105)):*
> ```JavaScript
> function start() {
>   timeLog('Tagpro id recieved.');
>   initMe();
> ```

Move to after `startTime`?

---

*[src/start.js, line 107 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRQI14-Gar3HsgbHWm:-LCRQI14-Gar3HsgbHWn:b-92qkyb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/start.js#L107)):*
> ```JavaScript
>   initMe();
>   timeLog('Initialized me.');
>   loadCache();
> ```

Move to after `startTime`?

---

*[src/start.js, line 117 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRQ_WPD7FS-LRTHxRY:-LCRQ_WPD7FS-LRTHxRZ:brolyxw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/start.js#L117)):*
> ```JavaScript
>   initIsCenterFlag();
>   timeLog('Initialized isCenterFlag().');
>   if (!isCached()) {
> ```

Thoughts on renaming `isCached()` to something like `mapWasCached()` or `mapLoadedFromCache()`?

---

*[src/cache/cache.js, line 2 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRPqGo7Q1Mey9aJkGg:-LCRPqGo7Q1Mey9aJkGh:bg2obve) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/cache/cache.js#L2)):*
> ```JavaScript
> import { parse } from 'flatted/esm';
> import _cache from '../../data/cache.txt';
> ```

Rename to something else? `cacheString`?

---

*[src/cache/cache.js, line 12 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRQoWZ1YA6xGGUhb0o:-LCRQoWZ1YA6xGGUhb0p:b-f6da51) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/cache/cache.js#L12)):*
> ```JavaScript
> 
> 
> let cached = false;
> ```

See above potential renaming comment. `mapWasCached`?

---

*[src/cache/point.js, line 8 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRR9RXENsS8jir3cX4:-LCRR9RY5kgXLv_vci9q:bcv75k1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/cache/point.js#L8)):*
> ```JavaScript
> export function deserializePoint(o) {
>   if (o.t) {
>     return new Polypoint(o.x, o.y, (new Triangle()).fromObject(o.t));
> ```

Can this be one line?

---

*[src/cache/point.js, line 11 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRUdfO7U_MQMXPAdsW:-LCRUdfO7U_MQMXPAdsX:b-8lai0t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/cache/point.js#L11)):*
> ```JavaScript
>   }
>   return (new Point()).fromObject(o);
> }
> ```

I feel like this helper function is the cleanest looking way of deserializing any of our serializable objects. Thoughts on having one of these helpers for each of the classes we need to deserialize? I think I just don't like the empty constructors being everywhere (eg `(new Triangle())`.

---

*[src/interpret/setup.js, line 94 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRSV1HAJLYFSU8Bys1:-LCRSV1HAJLYFSU8Bys2:b-2zfzqr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/interpret/setup.js#L94)):*
> ```JavaScript
>     dtGraph.delaunayAddVertex(vertex);
>   });
>   timeLog('Added triangulation vertices.');
> ```

We don't like the indent on these messages anymore?

---

*[src/interpret/setup.js, line 100 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRSfzy680OJlJC6QMH:-LCRSfzy680OJlJC6QMI:b-kffes2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/interpret/setup.js#L100)):*
> ```JavaScript
>     dtGraph.delaunayAddConstraintEdge(e);
>   });
>   timeLog('Added triangulation constrained edges.');
> ```

Same indent thing as above.

---

*[src/interpret/class/Triangle.js, line 44 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRGjgK6j_phSOndTOU:-LCRStug1NVEnoL0rDfP:bn2cymq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/Triangle.js#L44)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Wait until @shanek21 looks at this, but I say make this use the deserializePoint() helper function
</blockquote></details>

I think it looks cleaner using `deserializePoint()`, even if it is definitely just a `Point` object.

---

*[src/interpret/class/TriangleGraph.js, line 63 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRHC1XAop9O4DDloy-:-LCRT6zQ54W0V1rEGVex:b-ya81ng) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e1f5967555c84877fb63149264ab5b1722b5cb62/src/interpret/class/TriangleGraph.js#L63)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

same thing here about using deserializePoint
</blockquote></details>

Same as above

---

*[src/interpret/class/TriangleTreeNode.js, line 90 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRTMrs2uFMqEy6futL:-LCRTMrs2uFMqEy6futM:b-c7hu2f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/8d9f858ccb1d055c8ec19d602e594580c4df6642/src/interpret/class/TriangleTreeNode.js#L90)):*
> ```JavaScript
> 
> 
>   fromObject(o, createdNodes) {
> ```

`@param` for `createdNodes`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
*[src/cache/cache.js, line 2 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRsKsP4_bVS8gtZ7_q:-LCRtFmR8ld1hGSlxISy:b-gtwpz7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/599e34c98fe2ab03b0f6814ab643ba19115cbb4e/src/cache/cache.js#L2)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

pls `String`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
*[src/cache/cache.js, line 2 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRsKsP4_bVS8gtZ7_q:-LCRtLB3AhaoLyKKLKqv:bnccyzj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/599e34c98fe2ab03b0f6814ab643ba19115cbb4e/src/cache/cache.js#L2)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

pls `String`
</blockquote></details>

pls `cacheString`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Reviewed 2 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
*[src/cache/cache.js, line 2 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRsKsP4_bVS8gtZ7_q:-LCRtzPW7zZLrohTdcr-:bnlk1gs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/599e34c98fe2ab03b0f6814ab643ba19115cbb4e/src/cache/cache.js#L2)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

pls `cacheString`
</blockquote></details>

`cacheInStringFormat`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cache/point.js, line 6 at r5](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRucba37HQf2D4jLAa:-LCRucba37HQf2D4jLAb:b80x1m5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f9add6a65e307a8f2d9b6ca89b6437d47ac24d03/src/cache/point.js#L6)):*
> ```JavaScript
> 
> 
> export function deserializePoint(o) {
> ```

Make one of these for each class that we need to deserialize, as per in person discussion. Rename file to `src/cache/classes.js`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
*[src/cache/cache.js, line 2 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRsKsP4_bVS8gtZ7_q:-LCRx9161B7rJIKiENVp:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/599e34c98fe2ab03b0f6814ab643ba19115cbb4e/src/cache/cache.js#L2)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

`cacheInStringFormat`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Review status: 12 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRzYIr6ETd87EJwbKJ:-LCRzYIr6ETd87EJwbKK:b-o2trpp) (no related file):*
> 458: move deserialization functions to cache/classes
Can you add .js to this? I just want it to be more clear that it's a file, not a folder or something.`458: move deserialization functions to cache/classes.js`

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Reviewed 6 of 7 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r6, 4 of 7 files at r7, 2 of 3 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRzYIr6ETd87EJwbKJ:-LCSGi8i3xg8A_lkOf-e:bgh2bje) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

> 458: move deserialization functions to cache/classes
Can you add .js to this? I just want it to be more clear that it's a file, not a folder or something.`458: move deserialization functions to cache/classes.js`
</blockquote></details>

Done b/c those commits arent in this PR anymore

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by davidabrahams** [comment]
*[src/cache/point.js, line 6 at r5](https://reviewable.io/reviews/chauncy-crib/tagprobot/485#-LCRucba37HQf2D4jLAa:-LCSGkcPDNqGXUOkxOyF:bnr75r5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f9add6a65e307a8f2d9b6ca89b6437d47ac24d03/src/cache/point.js#L6)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Make one of these for each class that we need to deserialize, as per in person discussion. Rename file to `src/cache/classes.js`
</blockquote></details>

Done. via issue #497

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by shanek21** [comment]
Reviewed 7 of 9 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Comment by billmwong** [comment]
Reviewed 6 of 9 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/485)*

**Pull request merged**
