### PR TITLE
161: adding comments to getTarget

### LINKED ISSUE #161: Document `getTarget`
It's now readable

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #161. Code courtesy of @altodyte on my laptop

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/162)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162)*

**Comment by shanek21** [comment]
Your commit message is not in the simple present tense.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162#-:-Ks_af3x1ju_Sd28gH_o:b-cn5otr)*

**Comment by shanek21** [comment]
*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162#-Ks_aqDdYI1rKBl5Lbo3:-Ks_aqDdYI1rKBl5Lbo4:b-cn5otr) (no related file):*
Your commit message is not in the simple present tense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162)*

**Comment by davidabrahams** [comment]
Your mother is in the simple present :tent:s. Fixed

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162#-:-Ks_iTxxtJtioUHSA8HB:b-l0q97i)*

**Comment by billmwong** [comment]
:dango:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162#-:-Ks_lklRdWIiUi-Bu-fB:bcbqss6)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/162)*

**Pull request merged**
