### PR TITLE
393: PGP Position with no boosts/bombs

### LINKED ISSUE #393: PGP Position with no boosts/bombs
Calculate the enemy velocity vector when they will hit the flag, and position ourselves 0.25 seconds away in that direction.

Use regular velocity projections assuming they hold arrow keys to end up at flag

Don't handle if the position bounces off a wall

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #393

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/control/physics.js, line 44 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd2z-56R7SHTTFwdb3:-LBd2z-56R7SHTTFwdb4:b3naklv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/control/physics.js#L44)):*
> ```JavaScript
>  *   the keypress in the x direction. Default to 1
>  * @param {number} accMultY - a multiplier to apply to the acceleration resulting from
>  *   the keypress in the y direction. Default to 1
> ```

We recently found that JSDocs has a convention for optional parameters that includes what to do for default values. @billmwong has an example in `control/class/Matrix.js`. I put it below as well.
`@param {0|1} [axis=0] - 0 to append matrix as a row, 1 to append matrix as a column`

---

*[src/control/physics.js, line 75 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd2UnF-ECag0WfyhVz:-LBd2UnF-ECag0WfyhW-:b-t400pb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/control/physics.js#L75)):*
> ```JavaScript
> /**
>  * Given a starting location/velocity in pixels, the keys to press, the multipliers for each
>  * direction, and the total time and timestep, return the final position/velocity.
> ```

indent multiple line description

---

*[src/control/physics.js, line 120 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd43j5-qZZKhIg4oQv:-LBd43j5-qZZKhIg4oQw:b-tzczov) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/control/physics.js#L120)):*
> ```JavaScript
>   while (hi - lo > threshold) {
>     const mid = (hi + lo) / 2;
>     const position = runSimulation(pos, 0, vel, 0, { x: 'RIGHT' }, mid, 0, time, step).xp;
> ```

FYI love this helper

---

*[src/plan/pgp.js, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd4_Z7-kMfeW2-lhdx:-LBd4_Z7-kMfeW2-lhdy:bxevnmt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/plan/pgp.js#L5)):*
> ```JavaScript
> import { getDesiredAccelerationMultipliers, runSimulation } from '../control/physics';
> 
> export function getPGP(player, bumperTime = 0.25) {
> ```

Should this be named `getPGPPosition()`? Since you're getting the position to post-grab pop from?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBghdcI2Nq644jBdDCO:-LBghdcI2Nq644jBdDCP:b-1aib2i) (no related file):*
do you have a screenshot or can i get a live demo of this working

---

*[src/plan/pgp.js, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBgiOvY7jUFlf4WK1Vd:-LBgiOvY7jUFlf4WK1Ve:bjpu14x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/plan/pgp.js#L5)):*
> ```JavaScript
> import { getDesiredAccelerationMultipliers, runSimulation } from '../control/physics';
> 
> export function getPGP(player, bumperTime = 0.25) {
> ```

jsdoc pls

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/control/physics.js, line 44 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd2z-56R7SHTTFwdb3:-LBlNtvD1nmjll9xPMYf:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/control/physics.js#L44)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

We recently found that JSDocs has a convention for optional parameters that includes what to do for default values. @billmwong has an example in `control/class/Matrix.js`. I put it below as well.
`@param {0|1} [axis=0] - 0 to append matrix as a row, 1 to append matrix as a column`
</blockquote></details>

Done.

---

*[src/control/physics.js, line 75 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd2UnF-ECag0WfyhVz:-LBlNw655mi7qmmLd9pl:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/control/physics.js#L75)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

indent multiple line description
</blockquote></details>

Done.

---

*[src/control/physics.js, line 120 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd43j5-qZZKhIg4oQv:-LBlNxNuC_4uM_zI_YFu:beqipdb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/control/physics.js#L120)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

FYI love this helper
</blockquote></details>

tenks :)

---

*[src/plan/pgp.js, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBgiOvY7jUFlf4WK1Vd:-LBlQMbAEOJnYaQhzV_T:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/plan/pgp.js#L5)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

jsdoc pls
</blockquote></details>

Done.

---

*[src/plan/pgp.js, line 7 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBg9G240g2pZ1JFEWjU:-LBlTRYw3nEmUubDkSmc:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/plan/pgp.js#L7)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

(and by "this" I mean getting the center of a player)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by davidabrahams** [comment]
*[src/plan/pgp.js, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBd4_Z7-kMfeW2-lhdx:-LBlTuiPE84NbFb8MLAw:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/plan/pgp.js#L5)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Should this be named `getPGPPosition()`? Since you're getting the position to post-grab pop from?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by davidabrahams** [comment]
*[src/plan/pgp.js, line 7 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBg9G240g2pZ1JFEWjU:-LBmv1IaD2N7vqgs3kjw:bi79g61) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/f1031d1a975c898990988650ebff959549b633a6/src/plan/pgp.js#L7)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

JK. not done yet. working on rebase.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/plan/pgp.js, line 9 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBlWsF7-HoMxEaYTGCq:-LBn-2PZ9RjWicLZ6n8x:bbrlu46) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c57f875599f1a717947369617fbbc3c69c087bd3/src/plan/pgp.js#L9)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

we may want to change this 0.3 or something larger in the future if this time is too close.  So this param description is more like "the time to wait to pop the enemy after they grab" or something
</blockquote></details>

If anything I think we should make it less, since people tend to try to get away from us after they grab the flag

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/plan/pgp.js, line 9 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBlWsF7-HoMxEaYTGCq:-LBnDAPT8imBWN3IjJNp:b-9lc571) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c57f875599f1a717947369617fbbc3c69c087bd3/src/plan/pgp.js#L9)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

If anything I think we should make it less, since people tend to try to get away from us after they grab the flag
</blockquote></details>

True, in any case this param description should be decoupled from the actual invincibility time

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBghdcI2Nq644jBdDCO:-LBr4Y6MAxNx3vbElkPD:b-rkt28u) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

do you have a screenshot or can i get a live demo of this working
</blockquote></details>

Not too exciting, but here it is sitting on the PGP



---

*[src/plan/pgp.js, line 9 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/424#-LBlWsF7-HoMxEaYTGCq:-LBr477RErLV6Y-NHz5J:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c57f875599f1a717947369617fbbc3c69c087bd3/src/plan/pgp.js#L9)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

True, in any case this param description should be decoupled from the actual invincibility time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)*

**Pull request merged**
