### PR TITLE
269: Only use one instance of `PIXI.Graphics` when applicable

### LINKED ISSUE #269: Only use one instance of `PIXI.Graphics` when applicable
In the case of the path and permNTSprites, we have a list of several Graphics objects. We could just have one

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #269

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/270)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 40 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSy8XaQTxwN0p4yjB:-KysSy8XaQTxwN0p4yjC:b-5j2dx3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L40)):*
> ```JavaScript
> // A grid of NT-sprites, which are subject to change. If there isn't a NT-object at the given cell,
> // then store null. This object is size tagpro_map_length * CPTL x tagpro_map_width * CPTL
> let tempNTSprites = [];
> ```

Is this refactor not possible for tempNTSprites? 

---

*[src/draw/drawings.js, line 74 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSmK1B3lhg4IVuWoZ:-KysSmK29gXxeSgTF0jv:bvubve7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L74)):*
> ```JavaScript
>  *   alpha, and color
>  */
> function getPixiRect(xp, yp, width, height, alpha, color, graphics) {
> ```

You can use Javascript default parameter syntax here instead of on the next line

---

*[src/draw/drawings.js, line 82 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-Kysd4zUebPRZYBZEULp:-Kysd4zUebPRZYBZEULq:b-wasv5n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L82)):*
> ```JavaScript
>     height,
>   ).alpha = alpha;
>   return pixiRect;
> ```

@shanek21 How nasty would it be to refactor the keypress viz to not need to return a new Graphics class here?

---

*[src/draw/drawings.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysMn5cgk8lswLwWVVL:-KysMn5cgk8lswLwWVVM:b-jarj4u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L245)):*
> ```JavaScript
>   pathSprite = new PIXI.Graphics();
>   _.forEach(path, cell => {
>     getPixiSquare(cell.xc * PPCL, cell.yc * PPCL, PPCL, PATH_ALPHA, PATH_COLOR, pathSprite);
> ```

@shanek21 we're okay with this weird naming for now because you're fixing it in your PR?

---

*[src/draw/drawings.js, line 247 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysNyKrK7mp-esiTCrL:-KysNyKrK7mp-esiTCrM:b-so6zco) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L247)):*
> ```JavaScript
>     getPixiSquare(cell.xc * PPCL, cell.yc * PPCL, PPCL, PATH_ALPHA, PATH_COLOR, pathSprite);
>   });
>   console.log(pathSprite);
> ```

get this outta here

---

*[src/draw/drawings.js, line 293 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdMVzt0U4fryjEr9j:-KysdMVzt0U4fryjEr9k:b38905q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bbed69c3cce98552303d5e9f398aa9729028f1b0/src/draw/drawings.js#L293)):*
> ```JavaScript
>   tempNTSprites = [];
>   triangulationSprite = null;
>   polypointSprite = null;
> ```

why do we get rid of these?

---

*[src/draw/drawings.js, line 297 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdRxbpwAp6A0bTCu9:-KysdRxbpwAp6A0bTCuA:bgwj0zk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L297)):*
> ```JavaScript
> 
> /**
>  * Iterates over permNTSprites and adds each sprite to the renderer. Runtime: O(P)
> ```

runtime is constant now right?

---

*[src/draw/drawings.js, line 402 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdpROu4diZqFZ7FyB:-KysdpROu4diZqFZ7FyC:b-4lg5qc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L402)):*
> ```JavaScript
>     return;
>   }
>   triangulationSprite = triangulationSprite || drawGraph(
> ```

what do you think of renaming drawGraph to `getGraphGraphics` or something? Because this function no longer actually draws the graph

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 74 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSmK1B3lhg4IVuWoZ:-KytCjPdx1RxPhQnMkU7:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L74)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

You can use Javascript default parameter syntax here instead of on the next line
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 247 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysNyKrK7mp-esiTCrL:-KytCp0mIJ07v6pODq3o:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L247)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

get this outta here
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 297 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdRxbpwAp6A0bTCu9:-KytD0swQFRCcPUSrvWJ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L297)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

runtime is constant now right?
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 402 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdpROu4diZqFZ7FyB:-KytD7l_JfDp1KB3qaqy:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L402)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what do you think of renaming drawGraph to `getGraphGraphics` or something? Because this function no longer actually draws the graph
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 293 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdMVzt0U4fryjEr9j:-KytDXlWrwqRZ2jQbzzR:bnlz1r3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/bbed69c3cce98552303d5e9f398aa9729028f1b0/src/draw/drawings.js#L293)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why do we get rid of these?
</blockquote></details>

Because now, the Graphics objects are permanent (in that, we never recreate them). We create the objects once when we initially calculate the triangulation, and then when we toggle visualizations, we just add/remove these sprite from the renderer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 40 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSy8XaQTxwN0p4yjB:-KytDhsYp3DEnlOZfaC8:b600vq9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L40)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Is this refactor not possible for tempNTSprites? 
</blockquote></details>

Talk in person

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysMn5cgk8lswLwWVVL:-KytE8uyDGljVbB_9wiL:b-4zhqkj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L245)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

@shanek21 we're okay with this weird naming for now because you're fixing it in your PR?
</blockquote></details>

^ I'm unclear if this is actually the case. I dont remember the resolution on the name of this function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by billmwong** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/draw/drawings.js, line 74 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSmK1B3lhg4IVuWoZ:-KytPQwoIBUaFcIclp8u:b-8nyi3w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L74)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---

*[src/draw/drawings.js, line 247 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysNyKrK7mp-esiTCrL:-KytPXHL0AswFfkYDRWN:b-8nyi3w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L247)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---

*[src/draw/drawings.js, line 297 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdRxbpwAp6A0bTCu9:-KytPgmhdzcMB9RckjPJ:b-8nyi3w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L297)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---

*[src/draw/drawings.js, line 402 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdpROu4diZqFZ7FyB:-KytPjKsWjU8W3nk5L0f:b-8nyi3w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L402)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/draw/drawings.js, line 74 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSmK1B3lhg4IVuWoZ:-KyvbUY__na8SCx7hvf-:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L74)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 247 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysNyKrK7mp-esiTCrL:-KyvbVdR4CG1Xc_ZqAgn:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L247)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 297 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdRxbpwAp6A0bTCu9:-KyvbWPJlX9Eij2PCPJn:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L297)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 402 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysdpROu4diZqFZ7FyB:-KyvbXD9u5X5YOBZCqag:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L402)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 40 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysSy8XaQTxwN0p4yjB:-KywmJWVOlZ98OEuOWpe:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L40)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Talk in person
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 82 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-Kysd4zUebPRZYBZEULp:-KzACpwF-db3oBwZSkTo:b9oh4zu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L82)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

@shanek21 How nasty would it be to refactor the keypress viz to not need to return a new Graphics class here?
</blockquote></details>

Unclear. I can maybe address it in my PR.

---

*[src/draw/drawings.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KysMn5cgk8lswLwWVVL:-KzAD1Im4u9Td4Y1HrCu:bzddf44) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L245)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

^ I'm unclear if this is actually the case. I dont remember the resolution on the name of this function
</blockquote></details>

Yeah, I'm reworking this bit.

---

*[src/draw/drawings.js, line 312 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KzADlsVPjNkiFC0wgJ3:-KzADlsW6TNuq5NSdX0m:b-6cr489) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/45cfbf6f0065e3a9495dc8dd6d4d05d2327d1238/src/draw/drawings.js#L312)):*
> ```JavaScript
>   assertGridInBounds(cellTraversabilities, xt * CPTL, yt * CPTL);
>   assertGridInBounds(cellTraversabilities, ((xt + 1) * CPTL) - 1, ((yt + 1) * CPTL) - 1);
>   permNTSprite = permNTSprite || new PIXI.Graphics();
> ```

FYI

I still don't like this...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 82 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-Kysd4zUebPRZYBZEULp:-KzAHDI-c-OEAhLy74Ph:brhhmzv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L82)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Unclear. I can maybe address it in my PR.
</blockquote></details>

What's the verdict here? We might want to just open a card to do this refactor.

---

*[src/draw/drawings.js, line 312 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KzADlsVPjNkiFC0wgJ3:-KzAHNhbHtD4tWzqh1U7:b-plyvtg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/45cfbf6f0065e3a9495dc8dd6d4d05d2327d1238/src/draw/drawings.js#L312)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

FYI

I still don't like this...
</blockquote></details>

What would you prefer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 82 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-Kysd4zUebPRZYBZEULp:-KzAHY3Ksd2TmMBMLfVx:bi7fd1t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/23dd0f1eb62cdfcca672e1fdd2cffcdcc9612d97/src/draw/drawings.js#L82)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

What's the verdict here? We might want to just open a card to do this refactor.
</blockquote></details>

I'm doing it in my PR....

---

*[src/draw/drawings.js, line 312 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270#-KzADlsVPjNkiFC0wgJ3:-KzAH_DN99JAf_9JYR4e:bii6287) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/45cfbf6f0065e3a9495dc8dd6d4d05d2327d1238/src/draw/drawings.js#L312)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

What would you prefer?
</blockquote></details>

I don't want to change it, I just want to be openly upset about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/270)*

**Pull request merged**
