### PR TITLE
215: Perform Delaunay Triangulation on Map Vertices

### LINKED ISSUE #215: Perform Delaunay Triangulation on Map Vertices
- Function to return containing polygon given a point
- Visualize it
- Unit tests

### PR DESCRIPTION
**Pull request by billmwong**
Closes #215

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/247)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 3 of 6 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 3 of 6 files at r1, 9 of 9 files at r2, 1 of 3 files at r3.
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/constants.js, line 38 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCPKhsy7dkO5w-ahPk:-KyCPKhsy7dkO5w-ahPl:b-r7wmuj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/constants.js#L38)):*
> ```JavaScript
> export const KEY_OFF_ALPHA = 0.2;
> export const NAV_MESH_COLOR = 0x9400ff; // Purple
> export const NAV_MESH_ALPHA = 0.2; // Purple
> ```

So transparent that it's purple.

---

*[src/draw/drawings.js, line 330 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCPjGbg4OuRxxH56ak:-KyCPjGbg4OuRxxH56al:b1iliax) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/draw/drawings.js#L330)):*
> ```JavaScript
>   const graphGraphics = new PIXI.Graphics().lineStyle(thickness, color);
> 
>   graphGraphics.alpha = NAV_MESH_ALPHA;
> ```

Can you not do this on the previous line with the `lineStyle`? If not, can we split `lineStyle` on its own line as well so that it looks like how the `alpha` line currently is?

---

*[src/draw/drawings.js, line 340 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCQ5MUdhoYgXoTNEnK:-KyCQ5MUdhoYgXoTNEnL:bwilqhp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/draw/drawings.js#L340)):*
> ```JavaScript
>   });
> 
>   tagpro.renderer.layers.foreground.addChild(graphGraphics);
> ```

FYI

Well that was easy.

---

*[src/navmesh/graph.js, line 46 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCRLDG_pDtG56VdTbF:-KyCRLDHvyZ4T41QLmL1:b-imc1ey) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L46)):*
> ```JavaScript
>  *   insertedPoint
>  * @returns {boolean} true if the opposite point is not inside the circle which touches e.p1, e.p2,
>  *   insertedPoint
> ```

Is this 80 character or 100 character wrapping? We've moved all jsdocs to 100 characters.

---

*[src/navmesh/graph.js, line 76 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCRcxNuLBJLLD1Ft1l:-KyCRcxNuLBJLLD1Ft1m:b-xfpy4y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L76)):*
> ```JavaScript
>     (ma * mb * (p1.y - p3.y)) + (mb * (p1.x + p2.x)) + (-ma * (p2.x + p3.x))) /
>     (2 * (mb - ma)
>     );
> ```

Weird indentation?

---

*[src/navmesh/graph.js, line 76 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCT_px75yuzmhBgfg1:-KyCT_px75yuzmhBgfg2:b-osj4sn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L76)):*
> ```JavaScript
>     (ma * mb * (p1.y - p3.y)) + (mb * (p1.x + p2.x)) + (-ma * (p2.x + p3.x))) /
>     (2 * (mb - ma)
>     );
> ```

More comments pls. I'm confused.

---

*[src/navmesh/graph.js, line 188 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCYlJJBwHhP8WBiSWL:-KyCYlJJBwHhP8WBiSWM:bk2v98i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L188)):*
> ```JavaScript
>    *   triangles, unique has all points contained in exactly one of the triangles
>    */
>   categorizePoints(other) {
> ```

Use lodash `_.intersectionBy()`?

---

*[test/navmesh/graph.spec.js, line 65 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCoPy_pVP3O3-wsZ9E:-KyCoPy_pVP3O3-wsZ9F:bno2jsn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/test/navmesh/graph.spec.js#L65)):*
> ```JavaScript
> 
>   t.end();
> });
> ```

Some of these tests don't follow THE ONE TRUE NEWLINE CONVENTION FOR UNIT TESTS

setup
NEWLINE
asserts
NEWLINE
cleanup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 2 of 3 files at r3.
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r3.
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/navmesh/graph.spec.js, line 65 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCoPy_pVP3O3-wsZ9E:-KyD0YbG6JSFvdIYbmhU:b-k37j6f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/test/navmesh/graph.spec.js#L65)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Some of these tests don't follow THE ONE TRUE NEWLINE CONVENTION FOR UNIT TESTS

setup
NEWLINE
asserts
NEWLINE
cleanup
</blockquote></details>

I just want to say this is (as always) my fault, and that i'm sorry that @billmwong has to fix it :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/drawings.js, line 330 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCPjGbg4OuRxxH56ak:-KyD2MLgDAAFkHD9VKhb:b-6nmtuh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/draw/drawings.js#L330)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you not do this on the previous line with the `lineStyle`? If not, can we split `lineStyle` on its own line as well so that it looks like how the `alpha` line currently is?
</blockquote></details>

I dont think you can do it on the previous line, because you have to assign the alpha property of the object. Done

---

*[src/navmesh/graph.js, line 46 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCRLDG_pDtG56VdTbF:-KyD2dlIhsVO5AQTKzHV:btlcc37) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L46)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Is this 80 character or 100 character wrapping? We've moved all jsdocs to 100 characters.
</blockquote></details>

it's 100 (these lines are 89 and 99 chars long)

---

*[src/navmesh/graph.js, line 76 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCRcxNuLBJLLD1Ft1l:-KyD2kqsmrsXK_MPhoE_:b-x1gkgz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L76)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Weird indentation?
</blockquote></details>

Tried changing it...this is what eslint wants :(

---

*[src/navmesh/graph.js, line 76 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCT_px75yuzmhBgfg1:-KyD3V5TWaiprTOTsE4F:bb6un1j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L76)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

More comments pls. I'm confused.
</blockquote></details>

Done

---

*[test/navmesh/graph.spec.js, line 65 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCoPy_pVP3O3-wsZ9E:-KyD3i565P6wXHvKkLXZ:b-jy21i6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/test/navmesh/graph.spec.js#L65)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I just want to say this is (as always) my fault, and that i'm sorry that @billmwong has to fix it :(
</blockquote></details>

I fixed this. I also think that maybe this convention shouldnt be followed for rly short tests, but meh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/navmesh/graph.js, line 188 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCYlJJBwHhP8WBiSWL:-KyDDeCwGR2LjWaj2MzW:bwfex6g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L188)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Use lodash `_.intersectionBy()`?
</blockquote></details>

Done. thanks for finding this lol. Cut 22 lines of code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r4.
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 1 of 3 files at r4.
Review status: 10 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/draw/drawings.js, line 330 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCPjGbg4OuRxxH56ak:-KyDFBWs019XyDCVOWbG:b817ry8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/draw/drawings.js#L330)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I dont think you can do it on the previous line, because you have to assign the alpha property of the object. Done
</blockquote></details>

Talked in person

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 2 of 3 files at r4.
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/draw/drawings.js, line 330 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCPjGbg4OuRxxH56ak:-KyDGAB88fziiEE_HnYY:bk68yzk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/draw/drawings.js#L330)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Talked in person
</blockquote></details>

Looks like alpha is an optional third parameter to `lineStyle`, so maybe do it all on one line? http://pixijs.download/dev/docs/PIXI.Graphics.html#lineStyle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r6.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r6.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/constants.js, line 38 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCPKhsy7dkO5w-ahPk:-KyDI9ZrX2mcrAokMHIm:bb6un1j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/constants.js#L38)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

So transparent that it's purple.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by billmwong** [comment]
*[src/navmesh/graph.js, line 76 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247#-KyCRcxNuLBJLLD1Ft1l:-KyE9gQHESc1X5yXsn7x:b3iqdje) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/03c3ecb825b433cb5dd2c9a7a807195d902ffdd9/src/navmesh/graph.js#L76)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Tried changing it...this is what eslint wants :(
</blockquote></details>

I investigated here a bit and turns out we had mismatched parens so I fixed it.  Re-review pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by billmwong** [comment]
Reviewed 1 of 6 files at r1, 7 of 9 files at r2, 2 of 3 files at r3, 1 of 3 files at r4, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r7.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r7.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/247)*

**Pull request merged**
