### PR TITLE
348: dynamic update vertex drawings

### LINKED ISSUE #348: Add/Remove vertex drawing when it gets added/removed from the Trianglulation Graph

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #348

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/376)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/interpret/class/test/TriangleGraph.spec.js, line 18 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NZ1IzjOUpV7Sh_t99:-L7NZ1IzjOUpV7Sh_t9A:ba0mgt1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/interpret/class/test/TriangleGraph.spec.js#L18)):*
> ```JavaScript
> import {
>   setupPixiAndTagpro,
>   resetPixiAndTagpro } from '../../../draw/class/test/DrawableGraph.spec';
> ```

each item in multi-line list on its own line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by billmwong** [comment]
*[src/draw/class/test/DrawableGraph.spec.js, line 9 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NZuxn1Yh9auwfrkNL:-L7NZuxn1Yh9auwfrkNM:b-hpzi4n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L9)):*
> ```JavaScript
> 
> 
> export function setupPixiAndTagpro() {
> ```

Looks like we use these two functions in two other files too, would it make sense to have a test utils file or something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by billmwong** [comment]
:dango:

---

Reviewed 13 of 13 files at r1.
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/draw/class/DrawableGraph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NaZ9y6Fujwp8JYSgs:-L7NaZ9y6Fujwp8JYSgt:bh34g3y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/DrawableGraph.js#L44)):*
> ```JavaScript
>     if (drawingIndex < this.indexToVertex.length - 1) {
>       this.drawingContainer.removeChildAt(drawingIndex);
>       this.drawingContainer.addChildAt(lastDrawing, drawingIndex);
> ```

Is this constant time or linear time to add a child at a specific index (also to remove a child at a specific index)

---

*[src/draw/class/test/DrawableGraph.spec.js, line 9 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7N_JntOuuh4sI7KsYl:-L7N_JntOuuh4sI7KsYm:buejgjx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L9)):*
> ```JavaScript
> 
> 
> export function setupPixiAndTagpro() {
> ```

this returns a lot of things, can you make a doc?

---

*[src/draw/class/test/DrawableGraph.spec.js, line 64 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7N_h9YOW5faW-L-mDc:-L7N_h9YOW5faW-L-mDd:bi2y3rj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L64)):*
> ```JavaScript
>   });
> 
>   tester.test('addVertex', t => {
> ```

these two tests should have different and more specific strings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-:-L7Nb6GfyAKUdqaNRRl_:bcbqss6)*

**Comment by davidabrahams** [comment]
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/draw/class/DrawableGraph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NaZ9y6Fujwp8JYSgs:-L7Nx4nGEPtK2TEWQR8R:b-7oez13) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/DrawableGraph.js#L44)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Is this constant time or linear time to add a child at a specific index (also to remove a child at a specific index)
</blockquote></details>

Unclear. I have a feeling linear, but there's nothing we can do about it (when you delete something, PIXI left-shifts everything to the right of it. There's no `replaceWith` or similar to avoid this)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by billmwong** [comment]
*[src/draw/class/DrawableGraph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NaZ9y6Fujwp8JYSgs:-L7RagplMbpj-hDX-5v3:bqwqqpe) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/DrawableGraph.js#L44)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Unclear. I have a feeling linear, but there's nothing we can do about it (when you delete something, PIXI left-shifts everything to the right of it. There's no `replaceWith` or similar to avoid this)
</blockquote></details>

Hmmm there's like on the order of 100 vertices and edges or so? What do you think, is it worth having multiple containers or something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by shanek21** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/draw/keys.js, line 10 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376#-L7RlAfpDsKrOH85qiZI:-L7RlAfpDsKrOH85qiZJ:b-tcv8r4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/keys.js#L10)):*
> ```JavaScript
> 
> // PIXI DisplayObjectContainer for drawing the key press visualizations.
> // Used instead of Container because tagpro uses PIXI 2.0.
> ```

Indent two spaces

---

*[src/draw/class/test/DrawableGraph.spec.js, line 82 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376#-L7S2LDp3Im1it_sgep_:-L7S2LDp3Im1it_sgepa:b-tcv8r4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L82)):*
> ```JavaScript
> 
>     // Should move the last drawing in the container to replace 2, 2. removeChildAt should be called
>     // twice
> ```

Indent two spaces

---

*[src/draw/class/test/DrawableGraph.spec.js, line 100 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376#-L7S2Neu6Fv6LHq2IH0s:-L7S2Neu6Fv6LHq2IH0t:b-e1ws12) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L100)):*
> ```JavaScript
> 
>     resetPixiAndTagpro();
> ```

No newline

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376)*

**Comment by davidabrahams** [comment]
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/draw/keys.js, line 10 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7RlAfpDsKrOH85qiZI:-L7V_lwFTB82bXB_58MN:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/keys.js#L10)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Indent two spaces
</blockquote></details>

Done.

---

*[src/draw/class/DrawableGraph.js, line 44 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NaZ9y6Fujwp8JYSgs:-L7RqFccIYK43OQ9kDFp:bx2g3cx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/DrawableGraph.js#L44)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmmm there's like on the order of 100 vertices and edges or so? What do you think, is it worth having multiple containers or something
</blockquote></details>

I believe left-shifting ~100 things is instant. I think we should finish all update-related optimizations, and then if there's still noticable lag, we can look into if the `removeChildAt` and `addChildAt` are the cause

---

*[src/draw/class/test/DrawableGraph.spec.js, line 9 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NZuxn1Yh9auwfrkNL:-L7RycqECqb0t_XJZL36:bg2cp7g) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L9)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Looks like we use these two functions in two other files too, would it make sense to have a test utils file or something
</blockquote></details>

I agree. the reason I put it here was because the mocks specifically allow DrawableGraphs to be tested. Do you have a suggestion for where to put these functions?

---

*[src/draw/class/test/DrawableGraph.spec.js, line 9 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7N_JntOuuh4sI7KsYl:-L7VbCmiI8hijQodVH-e:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L9)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

this returns a lot of things, can you make a doc?
</blockquote></details>

Done.

---

*[src/draw/class/test/DrawableGraph.spec.js, line 64 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7N_h9YOW5faW-L-mDc:-L7VbEFNPq3j944uoVOV:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L64)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

these two tests should have different and more specific strings
</blockquote></details>

Done.

---

*[src/draw/class/test/DrawableGraph.spec.js, line 82 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7S2LDp3Im1it_sgep_:-L7V_9ykNiLaZI9bPERm:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L82)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Indent two spaces
</blockquote></details>

Done.

---

*[src/draw/class/test/DrawableGraph.spec.js, line 100 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7S2Neu6Fv6LHq2IH0s:-L7V_AClWWTIDrDHn0lI:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/draw/class/test/DrawableGraph.spec.js#L100)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

No newline
</blockquote></details>

Done.

---

*[src/interpret/class/test/TriangleGraph.spec.js, line 18 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7NZ1IzjOUpV7Sh_t99:-L7V_O7MRzTnVkfOhgNy:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d83a9561a26659810e1417c43a9d06c52dc702d6/src/interpret/class/test/TriangleGraph.spec.js#L18)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

each item in multi-line list on its own line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/class/test/DrawableGraph.spec.js, line 11 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376#-L7VbaKH8GZ6vuaKxeYs:-L7VbaKH8GZ6vuaKxeYt:b-tcv8r4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cc56abddb988184d1bf7af546adfd04f4ffbfc4b/src/draw/class/test/DrawableGraph.spec.js#L11)):*
> ```JavaScript
> /**
>  * Mocks tagpro.renderer.layers.foreground.addChild(), and the PIXI object in order for a
>  * DrawableGraph to be initialized during testing
> ```

Indent two spaces

---

*[src/draw/class/test/DrawableGraph.spec.js, line 18 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376#-L7Vbijg60bk6qhNcDZR:-L7Vbijh2uGHDJVZYASo:b-yq6qv5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cc56abddb988184d1bf7af546adfd04f4ffbfc4b/src/draw/class/test/DrawableGraph.spec.js#L18)):*
> ```JavaScript
>  *   spies on the tagpro.renderer.layers.foreground.addChild,
>  *   PIXI.DisplayObjectContainer.addChildAt, and PIXI.DisplayObjectContainer.removeChildAt
>  *   functions.
> ```

Are these comments to 100 characters?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: 10 of 13 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by davidabrahams** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/class/test/DrawableGraph.spec.js, line 11 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7VbaKH8GZ6vuaKxeYs:-L7Ve6gZf33kyH4SJMs7:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cc56abddb988184d1bf7af546adfd04f4ffbfc4b/src/draw/class/test/DrawableGraph.spec.js#L11)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Indent two spaces
</blockquote></details>

Done.

---

*[src/draw/class/test/DrawableGraph.spec.js, line 18 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376#-L7Vbijg60bk6qhNcDZR:-L7VdvMI0Imc73_-t_Vr:bo1dzuz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cc56abddb988184d1bf7af546adfd04f4ffbfc4b/src/draw/class/test/DrawableGraph.spec.js#L18)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Are these comments to 100 characters?
</blockquote></details>

I packed the lines greadily (didn't want to split up the long function call chains)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/376)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/376)*

**Pull request merged**
