### PR TITLE
344: Set up issue template/PR template

### LINKED ISSUE #344: Set up issue template/PR template
https://github.com/blog/2111-issue-and-pull-request-templates

### PR DESCRIPTION
**Pull request by billmwong**
Closes #344

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/353)

### CODE REVIEW

**Comment by shanek21** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 3 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/353#-L6N2K_23mKlb3VVJEvr:-L6N2K_23mKlb3VVJEvs:b-uehcjn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d111a38a525b370e5d209d691d2a38ca20305b55/.github/PULL_REQUEST_TEMPLATE.md#L3)):*
> ```Markdown
> Closes #
> 
> [Screenshot if relevant]
> ```

Please add [Poetic expression of intentions of PR if relevant]

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/353)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/353)*

**Comment by billmwong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 3 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/353#-L6N2K_23mKlb3VVJEvr:-L6NZz3fNi-m0vNTwr9N:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d111a38a525b370e5d209d691d2a38ca20305b55/.github/PULL_REQUEST_TEMPLATE.md#L3)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Please add [Poetic expression of intentions of PR if relevant]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/353)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/353)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 1 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/353#-L6N_IQHhLlKrIiwTbPo:-L6N_IQHhLlKrIiwTbPp:b6vbpqw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c90297b30fd242f0b963ac3729fd5974c5e99a37/.github/PULL_REQUEST_TEMPLATE.md#L1)):*
> ```Markdown
> Closes #
> ```

Im upset that this C is capitalized

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/353)*

**Pull request merged**
