### PR TITLE
111: updating unit test phrasing

### LINKED ISSUE #111: Specify unit tests with vague phrasing
For example, `return correctly with varying inputs` is pretty vague. Could probably be split into more tests and made more specific?

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #111

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/149)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/149)*

**Comment by billmwong** [comment]
Idk if this fully closes that issue but it's a good first step

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/149#-:-KsRaBd1vxmTWkpMoRnr:bx2w3sr)*

**Comment by altodyte** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/149)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/149)*

**Pull request merged**
