### PR TITLE
90: documenting the setupVelocity function

### LINKED ISSUE #90: Document the usefulness of the `setupVelocity` function
No idea what it's doing.

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #90

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/148)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/interface.js, line 133 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148#-KsOOAGUVzjU60-KJW2r:-KsOOAGUVzjU60-KJW2s:b9ioyha) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c42d6e1a67c43aa47f5ae7aa3adbdaec04d0cf4a/src/utils/interface.js#L133)):*
> ```JavaScript
>  * Velocity is saved in player.vx and vy. The refresh rate on our access to server size physics is
>  * only 4 Hz. We can check our client-side velocity at a much higher refresh rate (60 Hz), so we use
>  * this and store it in the me object.
> ```

Is our line character limit 100 characters? Why is it not 80 characters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/interface.js, line 133 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148#-KsOOAGUVzjU60-KJW2r:-KsP5doTu2HVsmYD1ISF:b-ufm8ip) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c42d6e1a67c43aa47f5ae7aa3adbdaec04d0cf4a/src/utils/interface.js#L133)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Is our line character limit 100 characters? Why is it not 80 characters?
</blockquote></details>

JS convention is 100. (Python is 79, I believe Java is 80). JS lines tend to be longer, so they're allowed to be longer haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148)*

**Comment by billmwong** [comment]
most :dango: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148#-:-KsR_ozimbntwivnTE5k:bxucfct)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/148)*

**Pull request merged**
