### PR TITLE
405 clarify functions

### LINKED ISSUE #405: Clarify Edge.isCollinearWith(), Edge.isBetweenPoints(), and Triangle.intersectsEdge()

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #405

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/interpret/class/Edge.js, line 62 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj0w1h3PXwjUYCUWe6:-LAj0w1h3PXwjUYCUWe7:b-wrxnbq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Edge.js#L62)):*
> ```JavaScript
>   isBetweenPoints(p1, p2, strict = true) {
>     const res = detD(this.p1, this.p2, p1) * detD(this.p1, this.p2, p2);
>     if (strict) return res < 0;
> ```

you could do a ternary oneline return

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by billmwong** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/interpret/class/Triangle.js, line 115 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj178E6RgmW7ieNaeO:-LAj178E6RgmW7ieNaeP:bw3qia9) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Triangle.js#L115)):*
> ```JavaScript
> 
>   /**
>    *
> ```

do we do this one empty line if the function has no general description

---

*[src/interpret/class/test/Triangle.spec.js, line 99 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1xDA8z2ZUhsIICjQ:-LAj1xDA8z2ZUhsIICjR:b3mwyx4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Triangle.spec.js#L99)):*
> ```JavaScript
>   });
> 
>   // TODO: is this expected behavior?
> ```

what do you wanna do about this TODO

---

*[src/think/fsm.js, line 6 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj22Xp0D1gART0rcWv:-LAj22Xp0D1gART0rcWw:b-e9jlhw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/think/fsm.js#L6)):*
> ```JavaScript
> import { drawEnemyPath } from '../draw/triangulation';
> import {
>   amRed,
> ```

FYI nice

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by shanek21** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/interpret/class/Edge.js, line 47 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1o2rE3OvGgqaqx5s:-LAj1o2t4jlK-CCPkNve:bdntj7d) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Edge.js#L47)):*
> ```JavaScript
>    * @returns {boolean} true if the point would lay on the infinite extension of this edge
>    */
>   isCollinearWithPoint(p) {
> ```

I think the name for a point occurring on a line is coincidence. Could be `isCoincidentWithPoint`?

---

*[src/interpret/class/Triangle.js, line 115 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj178E6RgmW7ieNaeO:-LAj4GKxEUpyZz0iPQgj:b32wsm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Triangle.js#L115)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

do we do this one empty line if the function has no general description
</blockquote></details>

no

---

*[src/interpret/class/test/Edge.spec.js, line 28 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj27TE018JAGBWEpnN:-LAj27TE018JAGBWEpnO:b-c1ovr6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Edge.spec.js#L28)):*
> ```JavaScript
>   });
> 
>   tester.test('returns strict behavior when one point is collinear with edge', t => {
> ```

Coincident, not collinear?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by davidabrahams** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/interpret/class/Edge.js, line 47 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1o2rE3OvGgqaqx5s:-LAj4ba9BvPIhZvDzrM8:b-7fmviv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Edge.js#L47)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I think the name for a point occurring on a line is coincidence. Could be `isCoincidentWithPoint`?
</blockquote></details>

this function doesn't check coincidence tho...it checks that collinearity? (ie, it returns true if E is [(0, 0), (1, 0)] and P is (2, 0))

---

*[src/interpret/class/Edge.js, line 62 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj0w1h3PXwjUYCUWe6:-LAj556j83J-Heqi_pZW:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Edge.js#L62)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

you could do a ternary oneline return
</blockquote></details>

Done.

---

*[src/interpret/class/Triangle.js, line 115 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj178E6RgmW7ieNaeO:-LAj4rIO-JbLqjvXnuH0:b-4qw81) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Triangle.js#L115)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

no
</blockquote></details>

lol oops

---

*[src/interpret/class/test/Edge.spec.js, line 28 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj27TE018JAGBWEpnN:-LAj5ff97z35MIkBuwfc:b-n2ympo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Edge.spec.js#L28)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Coincident, not collinear?
</blockquote></details>

so....this function returns true in the collinear case (coincidence is a subset of collinear). I illustrated this with another test case.

---

*[src/interpret/class/test/Triangle.spec.js, line 99 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1xDA8z2ZUhsIICjQ:-LAj5pbXDFfprFUd_Swm:b-nyndo4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Triangle.spec.js#L99)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what do you wanna do about this TODO
</blockquote></details>

i was hoping you knew the answer LOL

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by davidabrahams** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/interpret/class/test/Edge.spec.js, line 28 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj27TE018JAGBWEpnN:-LAj68k-AfiYgzeB--lP:b-srknim) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Edge.spec.js#L28)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

so....this function returns true in the collinear case (coincidence is a subset of collinear). I illustrated this with another test case.
</blockquote></details>

Sorry. i should have said it returns true if strict=false in the collinear case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/interpret/class/test/Triangle.spec.js, line 99 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1xDA8z2ZUhsIICjQ:-LAj95xC9iQ4QqXGCh8q:b-itel85) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Triangle.spec.js#L99)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i was hoping you knew the answer LOL
</blockquote></details>

damn seems bad, make a card maybe?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by davidabrahams** [comment]
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/interpret/class/test/Triangle.spec.js, line 99 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1xDA8z2ZUhsIICjQ:-LAsoFirAYl1_tZzEcKZ:b-c0ra7x) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/test/Triangle.spec.js#L99)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

damn seems bad, make a card maybe?
</blockquote></details>

Done. See #408. LMK if description makes sense. I labeled it a `concern`, since for now we don't know if it's causing any problems.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/interpret/class/Edge.js, line 47 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/406#-LAj1o2rE3OvGgqaqx5s:-LAspKnQ8syHm6iQm8tj:b-mpnu6h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/cd77f134c8576b00b39781280dfa9fa406e8e81e/src/interpret/class/Edge.js#L47)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

this function doesn't check coincidence tho...it checks that collinearity? (ie, it returns true if E is [(0, 0), (1, 0)] and P is (2, 0))
</blockquote></details>

Ah, I see. Cool.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)*

**Pull request merged**
