### PR TITLE
134: Allow visuals to be enabled while in manual mode

### LINKED ISSUE #134: Allow visuals to be enabled while in manual mode
In this mode, obstacles and planned path are still visualized, but the bot can be manually controlled and will not try to move along its planned path.

### PR DESCRIPTION
**Pull request by shanek21**
Closes #134

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/179)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179)*

**Comment by billmwong** [comment]
So autonomous mode off means nothing is visualized, but mobility off means just no movement?  What the difference between this and just turning visuals on but autonomous off?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179#-:-KseyXj4PToSrdTueVYY:b-rxxe6z)*

**Comment by shanek21** [comment]
Autonomy must be on in order for the things that get visualized to be calculated. So, if you have autonomojs mode off and visuals on, then nothing will happen because the things that should get visualized will be empty. You should try it out! It's pretty fun.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179#-:-KsiBPTeH9qz_jVOVdOs:b-v3gybk)*

**Comment by billmwong** [comment]
On Tue, Aug 29, 2017, 9:35 AM Shane Kelly <notifications@github.com> wrote:

> Autonomy must be on in order for the things that get visualized to be
> calculated. So, if you have autonomojs mode off and visuals on, then
> nothing will happen because the things that should get visualized will be
> empty. You should try it out! It's pretty fun.
>
Makes sense. Is it needed to have all three of these then? Cause now if I
have both V and M off it's the same as having A off right? Honest question

------------------------------

**Comment by shanek21** [comment]
Hmm that's a good point. I can rework it to not need a mobility button but get the same results.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179#-:-KsiXybTBn-cvmf-m_dq:b-o3sjok)*

**Comment by billmwong** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/interface.js, line 65 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179#-Ksspoz66NaOuapmUOTn:-Ksspoz66NaOuapmUOTo:b-gnet7k) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9ce84faaac9735205b5aa6881edb75dda0edc46d/src/utils/interface.js#L65)):*
> ```JavaScript
>       autonomous = !autonomous;
>       visuals = autonomous;
>       if (!visuals) {
> ```

:dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/179)*

**Pull request merged**
