### PR TITLE
358: make getEdges runtime O(E)

### LINKED ISSUE #358: Make getEdges() run in O(E)

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #358

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/360)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/interpret/class/Graph.js, line 158 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6dFsIvSQCmW3mj3i4A:-L6dFsIvSQCmW3mj3i4B:b8osxhq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/Graph.js#L158)):*
> ```JavaScript
>       _.forEach(this.adj[p1], p2 => {
>         const e = new Edge(p1, p2);
>         const edgeExists = _.has(edgesSet, `p1: ${p1.toString()}, p2: ${p2.toString()}`);
> ```

is there an edge.toString() we could use/make instead of doing this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/interpret/class/Point.js, line 71 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/360#-L6j3hmk1BrFKUcMz6iX:-L6j3hmk1BrFKUcMz6iY:b-k82ii8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/Point.js#L71)):*
> ```JavaScript
>    * @returns {Point} a new Point object
>    */
>   static fromString(s) {
> ```

We don't use this anymore, but David and I are torn about keeping it vs getting rid of it. @billmwong, thoughts?

---

*[src/interpret/class/TriangleGraph.js, line 383 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/360#-L6j32xt7cRFpBcglEjd:-L6j32xuCH63WsUNukIx:bmpjd8m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/TriangleGraph.js#L383)):*
> ```JavaScript
>       _.forEach(this.fixedAdj[p1], p2 => {
>         const e = new Edge(p1, p2);
>         const edgeExists = _.has(edgesSet, `p1: ${p1.toString()}, p2: ${p2.toString()}`);
> ```

Also use Edge toString() stuff here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/360)*

**Comment by davidabrahams** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/interpret/class/Graph.js, line 158 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6dFsIvSQCmW3mj3i4A:-L6j_fJwwsl27rsTl3fM:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/Graph.js#L158)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is there an edge.toString() we could use/make instead of doing this?
</blockquote></details>

Done.

---

*[src/interpret/class/Point.js, line 71 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6j3hmk1BrFKUcMz6iX:-L6j_hach6gduVTmLbqW:be2852q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/Point.js#L71)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

We don't use this anymore, but David and I are torn about keeping it vs getting rid of it. @billmwong, thoughts?
</blockquote></details>

I decided to remove it. Can revert the commit if we choose thats what we want

---

*[src/interpret/class/TriangleGraph.js, line 383 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6j32xt7cRFpBcglEjd:-L6j_qZ7LVONsQh5fUvp:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/TriangleGraph.js#L383)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Also use Edge toString() stuff here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by billmwong** [comment]
*[src/interpret/class/Point.js, line 71 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6j3hmk1BrFKUcMz6iX:-L6sH7FE8G7B92O6sg6t:b60xk5w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c7340540c6ab36709e2a4f18271abe15337df1dd/src/interpret/class/Point.js#L71)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I decided to remove it. Can revert the commit if we choose thats what we want
</blockquote></details>

OK sounds dank to me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by billmwong** [comment]
*[src/interpret/class/Point.js, line 54 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6sHD60fVnz6xDvheVn:-L6sHD60fVnz6xDvheVo:b-c5vokl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/59cba220755869782977e061f2177495d800bca1/src/interpret/class/Point.js#L54)):*
> ```JavaScript
> 
>   toString() {
>     return JSON.stringify({ x: this.x, y: this.y });
> ```

does this not need to stringify anymore now that we don't use fromString()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by billmwong** [comment]
Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by davidabrahams** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6n5CZE53Yz0WpBxt6H:-L6wfMrGV0VI2oCY0_j-:bb6un1j) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

When you refer to a class method in a commit can you call it Class.theMethod()? e.g. `add Edge.toString()`
</blockquote></details>

Done

---

*[src/interpret/class/Point.js, line 54 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6sHD60fVnz6xDvheVn:-L6wc-eDBQYEv3WjUHEQ:bb6un1j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/59cba220755869782977e061f2177495d800bca1/src/interpret/class/Point.js#L54)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

does this not need to stringify anymore now that we don't use fromString()?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by davidabrahams** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360#-L6n5CZE53Yz0WpBxt6H:-L6wfStJ5X0OBfrmGAgH:bwo40n3) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done
</blockquote></details>

Also updated our comments convention wiki: https://github.com/chauncy-crib/tagprobot/wiki/Conventions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/360)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/360)*

**Pull request merged**
