### PR TITLE
261: Implement Funnel Path-Planning on Polypoints

### LINKED ISSUE #261: Implement Funnel Path-Planning on Polypoints
delete code for adding edge midpoints to polypoint graph

### PR DESCRIPTION
**Pull request by billmwong**
Closes #261 
screenshot from 2017-12-12 23 52 30

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/302)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 3 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/navmesh/graph.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Mc8msUIcSo0ZQ4lEp:-L0Mc8msUIcSo0ZQ4lEq:b-lcusnm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/graph.js#L292)):*
> ```JavaScript
>     );
>     assert(
>       !((p1.x === p2.x && p2.x === p3.x) ||
> ```

I believe we have a `threePointsInALine` or something like that laying around somewhere. You could use that to do this check!

---

*[src/navmesh/path.js, line 69 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MexmgZBMtC142s5Tz:-L0MexmgZBMtC142s5U-:b-h5lmcf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L69)):*
> ```JavaScript
>     if (i === 1) {
>       // This is the first iteration, arbitrarily add one point to each list
>       leftPoints.push(portalPoints[0]);
> ```

Do we not need to check which point is actually on the left? (ie, what do you mean arbitrarily? why does this work?)

---

*[src/navmesh/path.js, line 73 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MfGaUqgwIV3M29rCJ:-L0MfGaUqgwIV3M29rCK:b3z6lxf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L73)):*
> ```JavaScript
>     } else {
>       // Consecutive portals are connected by one same point, figure out which point to add to which
>       //   list by checking which list ends in one of the portal points
> ```

Based on your comment, I would have guessed you could do (this is pseudocode):

```javascript
[p1, p2] = portalPoints;
p1IsRepeat = last(leftPoints).equal(p1) || last(rightPoints).equal(p1)
repeatPoint = p1IsRepeat ? p1 : p2;
otherPoint = p1IsRepeat ? p2 : p1;
if last(leftPoints).equal(repeatPoint):
  leftPoints.push(repeatPoint)
  rightPoints.push(otherPoint)
else:
  leftPoints.push(otherPoint)
  rightPoints.push(repeatPoint)
```
I think this is a little more lines, but potentially more readable. (Also, I may be completely misunderstanding whats supposed to happen here, in which case this code is nonsense).

Let me know what you think!

---

*[src/navmesh/path.js, line 118 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MhvlVjrDPCXX2l-DL:-L0MhvlVjrDPCXX2l-DM:b227gbn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L118)):*
> ```JavaScript
> 
>     if (!currLeft.equal(newLeft) && i > leftI) {
>       // New left point is different
> ```

This block looks really similar to the one below. I don't understand it that well, but I'm wondering if there's a way to refactor this a bit into a helper and then call that in two places?

---

*[src/navmesh/path.js, line 129 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MhbOU9SaaSZKDoyVg:-L0MhbOU9SaaSZKDoyVh:b-dw62c2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L129)):*
> ```JavaScript
> 
>           // Find next funnel index
>           while (rightPoints[rightI].equal(currRight)) rightI += 1;
> ```

FYI this nested 1 line while loop is a little scary to me. I think it'd be really helpful if you walked through the funnelPolypoints alg w/ me in person (I was able to understand the other alg on my own...this one I'm a little lost)

---

*[test/navmesh/path.spec.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Mi6hrB_GQFvAd2w9Z:-L0Mi6hrB_GQFvAd2w9_:bymq65v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/test/navmesh/path.spec.js#L43)):*
> ```JavaScript
>   tester.test('stretches around a corner to the bottom', t => {
>     const FP = [
>       new Point(35, 75),
> ```

FYI I'm so sorry you had to write these test cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/navmesh/path.js, line 117 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MlTo7VK7mmgcNxLww:-L0MlTo7VK7mmgcNxLwx:b1t6ply) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L117)):*
> ```JavaScript
>     const newRight = rightPoints[i];
> 
>     if (!currLeft.equal(newLeft) && i > leftI) {
> ```

Is `i `ever `<= leftI`? try testing this with an assert

---

*[src/navmesh/path.js, line 121 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MmEO_VI_4WzjBv0K_:-L0MmEO_VI_4WzjBv0Ka:btcc92d) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L121)):*
> ```JavaScript
>       if (pointsOnSameSide(newLeft, currRight, leftEdge)) {
>         // New left point narrows the funnel
>         if (!pointsOnSameSide(newLeft, currLeft, rightEdge)) {
> ```

FYI switch if else logic for readability?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/navmesh/path.js, line 129 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MhbOU9SaaSZKDoyVg:-L0Mo-3kj6Sd7Vt5dJjD:b-45vd0r) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L129)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI this nested 1 line while loop is a little scary to me. I think it'd be really helpful if you walked through the funnelPolypoints alg w/ me in person (I was able to understand the other alg on my own...this one I'm a little lost)
</blockquote></details>

Nevermind. Nested loop makes sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/navmesh/path.js, line 109 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Mo6fi8ViGDoJgKYkO:-L0Mo6fi8ViGDoJgKYkP:bzglk2d) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L109)):*
> ```JavaScript
>   let rightI = 0; // the index in rightPoints of the right point of the funnel
> 
>   for (let i = 1; i < leftPoints.length; i++) {
> ```

FYI refactor `i` to a better name? `portalIndex`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by billmwong** [comment]
*[src/navmesh/path.js, line 69 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MexmgZBMtC142s5Tz:-L0MtF6I60OoOFDqfwJ9:b-7l2a1z) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L69)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Do we not need to check which point is actually on the left? (ie, what do you mean arbitrarily? why does this work?)
</blockquote></details>

The names "left" and "right" really doesn't matter, it's more like "oneSide" and "otherSide".  It just matters that they contain all the points on a given side.  I could rename everything, but left and right are possibly easier to understand?  What do you think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by billmwong** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/navmesh/graph.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Mc8msUIcSo0ZQ4lEp:-L0MuZPU2ZP7Z7SGRw8e:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/graph.js#L292)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I believe we have a `threePointsInALine` or something like that laying around somewhere. You could use that to do this check!
</blockquote></details>

Done.

---

*[src/navmesh/path.js, line 73 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MfGaUqgwIV3M29rCJ:-L0Mt7pO-w6M0Uv6g4G9:b-s713j5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L73)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Based on your comment, I would have guessed you could do (this is pseudocode):

```javascript
[p1, p2] = portalPoints;
p1IsRepeat = last(leftPoints).equal(p1) || last(rightPoints).equal(p1)
repeatPoint = p1IsRepeat ? p1 : p2;
otherPoint = p1IsRepeat ? p2 : p1;
if last(leftPoints).equal(repeatPoint):
  leftPoints.push(repeatPoint)
  rightPoints.push(otherPoint)
else:
  leftPoints.push(otherPoint)
  rightPoints.push(repeatPoint)
```
I think this is a little more lines, but potentially more readable. (Also, I may be completely misunderstanding whats supposed to happen here, in which case this code is nonsense).

Let me know what you think!
</blockquote></details>

Done, yeah I was having trouble writing this in a readable way.  I like your version more :thumbsup: 

---

*[src/navmesh/path.js, line 109 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Mo6fi8ViGDoJgKYkO:-L0MyQGiVdnqXb4rkAQS:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L109)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI refactor `i` to a better name? `portalIndex`?
</blockquote></details>

Done.

---

*[src/navmesh/path.js, line 117 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MlTo7VK7mmgcNxLww:-L0MzKF67L8fQSk5nhbX:b-1ogsv4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L117)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Is `i `ever `<= leftI`? try testing this with an assert
</blockquote></details>

Apparently so :man_shrugging: 

---

*[src/navmesh/path.js, line 121 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MmEO_VI_4WzjBv0K_:-L0Mylpwyw_qOfrFVEdH:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L121)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI switch if else logic for readability?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/path.js, line 69 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MexmgZBMtC142s5Tz:-L0NU-1Uw6kWFWA9yp9V:b-dxcbu5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L69)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

The names "left" and "right" really doesn't matter, it's more like "oneSide" and "otherSide".  It just matters that they contain all the points on a given side.  I could rename everything, but left and right are possibly easier to understand?  What do you think
</blockquote></details>

Makes sense!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by billmwong** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/navmesh/path.js, line 118 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0MhvlVjrDPCXX2l-DL:-L0OGbWC-tfNZ4iGmCbV:b-1e6xy5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/14f5790ffc727c3fd15d44764992f8ecf74a9b48/src/navmesh/path.js#L118)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This block looks really similar to the one below. I don't understand it that well, but I'm wondering if there's a way to refactor this a bit into a helper and then call that in two places?
</blockquote></details>

Done, let me know what you think.  This was the easiest way I could think of doing it without passing in 7 variables to a helper function.  This seems harder to read but maybe I can name my variables better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/path.js, line 124 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0QC4-vPJDKNc4PZWIY:-L0QC4-vPJDKNc4PZWIZ:b-49akur) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/20e66ace2382dc518249ec83548bb50f97d02f82/src/navmesh/path.js#L124)):*
> ```JavaScript
>     // Look for funnel updates for the left and the right side
>     for (let i = 0; i < 2; i++) {
>       const j = i === 0 ? 1 : 0; // the other index
> ```

`j = 1 - i`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/navmesh/path.js, line 123 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0QCOFSpPRPhBmiEHof:-L0QCOFSpPRPhBmiEHog:b-a7guxq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/20e66ace2382dc518249ec83548bb50f97d02f82/src/navmesh/path.js#L123)):*
> ```JavaScript
> 
>     // Look for funnel updates for the left and the right side
>     for (let i = 0; i < 2; i++) {
> ```

FYI i -> `curr`, j -> `other`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by billmwong** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/path.js, line 123 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0QCOFSpPRPhBmiEHof:-L0QDFZqYsbj3k_W0JtB:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/20e66ace2382dc518249ec83548bb50f97d02f82/src/navmesh/path.js#L123)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI i -> `curr`, j -> `other`
</blockquote></details>

Done.

---

*[src/navmesh/path.js, line 124 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0QC4-vPJDKNc4PZWIY:-L0QDF7Feb0syeQigEpU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/20e66ace2382dc518249ec83548bb50f97d02f82/src/navmesh/path.js#L124)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

`j = 1 - i`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by shanek21** [comment]
Reviewed 2 of 4 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/path.js, line 85 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Qc335jKaJQCXeCkj4:-L0Qc336v_of9J_MtMJv:bzb3o8u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/83210a18e2b03e2a36ae764c4e53b2d15065c8a0/src/navmesh/path.js#L85)):*
> ```JavaScript
>         rightPoints.push(repeatPoint);
>       }
>     }
> ```

I think you could make this else statement a bit more concise if you wanted.
```javascript
if (_.last(leftPoints).equal(p1)) {
  leftPoints.push(p1);
  rightPoints.push(p2);
} else {
  leftPoints.push(p1);
  rightPoints.push(p2);
}
```
Though, for what it's worth, I am kind of a fan of the verbosity of the code in this else statement as it stands. Very readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by billmwong** [comment]
*[src/navmesh/path.js, line 85 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Qc335jKaJQCXeCkj4:-L0QdqFGOR6u7RNzneqJ:b-acbd0u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/83210a18e2b03e2a36ae764c4e53b2d15065c8a0/src/navmesh/path.js#L85)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I think you could make this else statement a bit more concise if you wanted.
```javascript
if (_.last(leftPoints).equal(p1)) {
  leftPoints.push(p1);
  rightPoints.push(p2);
} else {
  leftPoints.push(p1);
  rightPoints.push(p2);
}
```
Though, for what it's worth, I am kind of a fan of the verbosity of the code in this else statement as it stands. Very readable.
</blockquote></details>

I'm assuming you meant:
```javascript
if (_.last(leftPoints).equal(p1)) {
  leftPoints.push(p1);
  rightPoints.push(p2);
} else {
  leftPoints.push(p2);
  rightPoints.push(p1);
}
```
I don't think this code would work because it doesn't catch the case where p1 is on the left side but not connected to the last leftPoint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/path.js, line 106 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302#-L0Rvgb-KEIzvT1ajnMn:-L0Rvgb-KEIzvT1ajnMo:b-op5ogu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/83210a18e2b03e2a36ae764c4e53b2d15065c8a0/src/navmesh/path.js#L106)):*
> ```JavaScript
>   const [leftPoints, rightPoints] = allPortalPoints;
> 
>   const funnelledPath = [path[0]];
> ```

funnelled is a weird word

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by shanek21** [comment]
Reviewed 2 of 4 files at r1, 1 of 4 files at r2.
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r4.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/302)*

**Pull request merged**
