### PR TITLE
292: Make our bot demoable for two-flag games

### LINKED ISSUE #292: Make our bot demoable for two-flag games
- Figure out if we're in two-flag or center-flag game, have code handle both
- Keypress toggle for offence/defence

Two-flag FSM:
- If we have the flag, cap
- If enemy has flag, chase
- If neither has flag: offence: grab flag, defence: sit on flag

### PR DESCRIPTION
**Pull request by shanek21**
Closes #292

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/308)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r1, 2 of 3 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/finders.js, line 32 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308#-L0XtcwECzAbhCS_NyDf:-L0XtcwECzAbhCS_NyDg:b-45g198) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4b0d9b0da12c86de1dfff3e4eb7dd8eec4abc617/src/helpers/finders.js#L32)):*
> ```JavaScript
>     }
>   }
>   return undefined;
> ```

`null` is better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308)*

**Comment by shanek21** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/finders.js, line 32 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308#-L0XtcwECzAbhCS_NyDf:-L0XuE3NxGUB-IfdqPXN:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4b0d9b0da12c86de1dfff3e4eb7dd8eec4abc617/src/helpers/finders.js#L32)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

`null` is better
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308)*

**Comment by billmwong** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308#-L0fIStQ8SOvK-Mk4gbl:-L0fIStQ8SOvK-Mk4gbm:b-cfip4d) (no related file):*
PR title same as issue title pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308#-L0fIStQ8SOvK-Mk4gbl:-L0zAocMdDT_EyV4sdoI:b-896fix) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

PR title same as issue title pls
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/308)*

**Pull request merged**
