### PR TITLE
223: improve runtime of graph using adjacency list

### LINKED ISSUE #223: Improve runtime of Graph api
Right now its implemented w/ a list of vertices and a list of edges. Almost every operation is O(V) or O(E). By using [adjacency lists](https://en.wikipedia.org/wiki/Adjacency_list), these operations should be O(1), or at worst O(E/V) (which is at most 4...so O(1))

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #223

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/238)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/navmesh/graph.js, line 28 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxVzHe0ZbMQCF8ZiAer:-KxVzHe0ZbMQCF8ZiAes:b-kdtoz5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/src/navmesh/graph.js#L28)):*
> ```JavaScript
> export class Graph {
>   constructor() {
>     this.adj = {}; // map from point object to adjacent points
> ```

adjacent points -> list of adjacent points

---

*[src/navmesh/graph.js, line 76 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxVzoQl1Z4p-kULCRUD:-KxVzoQl1Z4p-kULCRUE:bf143qk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/src/navmesh/graph.js#L76)):*
> ```JavaScript
>    */
>   getVertices() {
>     // return _.keys(this.adj);
> ```

:expressionless: 

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-FbUsHl4tumwP7Mp:-KxW-FbUsHl4tumwP7Mq:bg4phw4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/draw/drawings.spec.js#L292)):*
> ```JavaScript
>     mockGraph.addVertex(middle);
>     mockGraph.addVertex(left);
>     mockGraph.addVertex(down);
> ```

so the API is such that the user needs to make sure to add vertices before adding edges between them? Has this always been the case and is it the desirable case?

---

*[test/navmesh/polygon.spec.js, line 229 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-VReJJKxZKIyited:-KxW-VReJJKxZKIyitee:buo4uhw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/navmesh/polygon.spec.js#L229)):*
> ```JavaScript
>     ]);
>     t.is(graph.getEdges().length, 32);
>     t.ok(graph.isConnected(new Point(0, 0), new Point(0, 40)));
> ```

t.true pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by davidabrahams** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/navmesh/graph.js, line 28 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxVzHe0ZbMQCF8ZiAer:-KxWEiGQ1dQmEcDaAgLo:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/src/navmesh/graph.js#L28)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

adjacent points -> list of adjacent points
</blockquote></details>

Done.

---

*[src/navmesh/graph.js, line 76 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxVzoQl1Z4p-kULCRUD:-KxWEZ5h89ZQ7zh0mKrL:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/src/navmesh/graph.js#L76)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

:expressionless: 
</blockquote></details>

Done.

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-FbUsHl4tumwP7Mp:-KxWEjP4NuDmGVpCfs9v:b-udy6q1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

so the API is such that the user needs to make sure to add vertices before adding edges between them? Has this always been the case and is it the desirable case?
</blockquote></details>

This has not always been the case. I would say that it is desirable. I added asserts to make the error explicit if you put an edge between points not in the graph.

---

*[test/navmesh/polygon.spec.js, line 229 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-VReJJKxZKIyited:-KxWFr4FgZ883o8LS08P:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/navmesh/polygon.spec.js#L229)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

t.true pls
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r2.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-FbUsHl4tumwP7Mp:-KxWIwt8UonAT9FkvPEo:b-i5pgwd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This has not always been the case. I would say that it is desirable. I added asserts to make the error explicit if you put an edge between points not in the graph.
</blockquote></details>

make a helper to add vertices and edges in one go as discussed offline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by davidabrahams** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-FbUsHl4tumwP7Mp:-KxWJI1N05JblnFOufx6:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

make a helper to add vertices and edges in one go as discussed offline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
*[src/navmesh/graph.js, line 46 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxWJWULQBf8BfsVHbtD:-KxWJWULQBf8BfsVHbtE:byk0jxr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c8f011c30744d36e1c9c2026c46e5016f2659dc9/src/navmesh/graph.js#L46)):*
> ```JavaScript
>     this.addVertex(point1);
>     this.addVertex(point2);
>     if (this.isConnected(point1, point2)) {
> ```

call addEdge here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by davidabrahams** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graph.js, line 46 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxWJWULQBf8BfsVHbtD:-KxWJmImi9PoTYHdBtk3:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c8f011c30744d36e1c9c2026c46e5016f2659dc9/src/navmesh/graph.js#L46)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

call addEdge here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-FbUsHl4tumwP7Mp:-KxWJmzFomRayNuWT145:b-73wqvr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done.
</blockquote></details>

use the helper here too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by davidabrahams** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/draw/drawings.spec.js, line 292 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxW-FbUsHl4tumwP7Mp:-KxWK-QcXGzmYgO_dnOQ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a999ae3bb81a1e2db00221dafddcc117a6193e30/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

use the helper here too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r5.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by shanek21** [comment]
change point to p

---

Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graph.js, line 43 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxhpybKBWVgDMGm9AEI:-KxhpybKBWVgDMGm9AEJ:bub9d3v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c76bbf710d1627a09d9a25f4a12cf6ab58b5b3cd/src/navmesh/graph.js#L43)):*
> ```JavaScript
>   }
> 
>   addEdgeAndVertices(point1, point2) {
> ```

FYI

makes more sense to be `addVerticesAndEdge`, no?

---

*[test/draw/drawings.spec.js, line 292 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxhsbrDievToRh_mmdM:-KxhsbrDievToRh_mmdN:b-q0o3e5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c76bbf710d1627a09d9a25f4a12cf6ab58b5b3cd/test/draw/drawings.spec.js#L292)):*
> ```JavaScript
>     mockGraph.addEdgeAndVertices(middle, left);
>     mockGraph.addEdgeAndVertices(middle, down);
>     mockGraph.addEdgeAndVertices(down, left);
> ```

We didn't have to add the vertices before, but we do now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-:-KxhsCdoYZXquVRQeFm3:b-qb3eje)*

**Comment by davidabrahams** [comment]
Done

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/navmesh/graph.js, line 43 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxhpybKBWVgDMGm9AEI:-KxiJTl6eaasYxYvXbNT:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c76bbf710d1627a09d9a25f4a12cf6ab58b5b3cd/src/navmesh/graph.js#L43)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

FYI

makes more sense to be `addVerticesAndEdge`, no?
</blockquote></details>

Done.

---

*[test/draw/drawings.spec.js, line 292 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxhsbrDievToRh_mmdM:-KxiJOH-ZCirzR_pdRzo:b-gtm8wn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c76bbf710d1627a09d9a25f4a12cf6ab58b5b3cd/test/draw/drawings.spec.js#L292)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

We didn't have to add the vertices before, but we do now?
</blockquote></details>

Yeah we were doing something weird before where we could store edges between vertices that weren't in the graph. We can't anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-:-KxiIBStKvEzFE34rQuy:bb6un1j)*

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r6.
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/navmesh/graph.js, line 43 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxiTAvVqA3yIYTW6Q1Q:-KxiTAvVqA3yIYTW6Q1R:bqr5njk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7b0c0da8ac6222f800c39b2419d7ee94f4d263a2/src/navmesh/graph.js#L43)):*
> ```JavaScript
>   }
> 
>   addVerticesAndEdges(p1, p2) {
> ```

Should the edge be singular? `addVerticesAndEdge`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r6.
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/navmesh/graph.js, line 43 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxiTAvVqA3yIYTW6Q1Q:-Kxi_iK7u9uQYB-FV8oF:b-2fncl7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7b0c0da8ac6222f800c39b2419d7ee94f4d263a2/src/navmesh/graph.js#L43)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Should the edge be singular? `addVerticesAndEdge`?
</blockquote></details>

To me addEdgeAndVertices was more intuitive because it seems more clear that the user wants to primarily add an edge between those two points, and secondarily add the points if they don't exist. addVerticesAndEdge seems less intuitive what the edge is for, but I don't feel strongly 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r7.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r7.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/navmesh/graph.js, line 43 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238#-KxiTAvVqA3yIYTW6Q1Q:-KxnErnxayNZhHZfgQIe:b-eq19gb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/7b0c0da8ac6222f800c39b2419d7ee94f4d263a2/src/navmesh/graph.js#L43)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

To me addEdgeAndVertices was more intuitive because it seems more clear that the user wants to primarily add an edge between those two points, and secondarily add the points if they don't exist. addVerticesAndEdge seems less intuitive what the edge is for, but I don't feel strongly 
</blockquote></details>

Fight! Yeah I don’t feel strongly either way. I think I side slightly with Billo. @shanek21 thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r8.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r8.
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/238)*

**Pull request merged**
