### PR TITLE
452: cache unmerged and merged graph

### LINKED ISSUE #457: Cache/load internalMap, tilesToUpdate, and tilesToUpdateValues
Will require changing the construction of unmergedGraph, mergedGraph, and dtGraph to used cached maps, rather than real map. Then dynamic updates should fix the objects.

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #457

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 1 of 12 files at r2.
Review status: 1 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/start.js, line 33 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMrR_9-nU9q7TU-a1L:-LCMrR_9-nU9q7TU-a1M:b-2p3eug) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/start.js#L33)):*
> ```JavaScript
> import { isCached } from './cache/cache';
> import { updateCache } from './cache/save';
> import { loadCache } from './cache/load'; // keep track of how many times we have run loop()
> ```

WTF DAVID

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by shanek21** [comment]
Review status: 1 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/start.js, line 37 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMrWaFCJaoAIOAwW3z:-LCMrWaFCJaoAIOAwW4-:b-72nbw0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/start.js#L37)):*
> ```JavaScript
> 
> window.onkeydown = onKeyDown; // run onKeyDown any time a key is pressed to parse user input
> let loopCount = 0;
> ```

what is this? pls leave a comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by shanek21** [comment]
Reviewed 3 of 12 files at r2.
Review status: 4 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/start.js, line 41 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMrcQc4Lj-gQlP94pq:-LCMrcQc4Lj-gQlP94pr:btranw8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/start.js#L41)):*
> ```JavaScript
> 
> // Run onKeyDown any time a key is pressed to parse user input
> window.onkeydown = onKeyDown;
> ```

Make comment inline?

---

*[src/interpret/setup.js, line 105 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMsUQ3CtLLYeYXnz0b:-LCMsUQ3CtLLYeYXnz0c:bjk9ye4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/interpret/setup.js#L105)):*
> ```JavaScript
> 
> /**
>  * @param {num} map - array of all vertices
> ```

Change `{num}`?

---

*[src/interpret/setup.js, line 106 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMsXT5A1y4NCEpKHs-:-LCMsXT5A1y4NCEpKHs0:b-rlclqf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/interpret/setup.js#L106)):*
> ```JavaScript
> /**
>  * @param {num} map - array of all vertices
>  * @returns {Graph} graph of the triangulation of all the vertices
> ```

Add `@param` for `calcGraphs`?

---

*[src/look/gameState.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMs7rHAx9f-fQxq_KG:-LCMs7rHAx9f-fQxq_KH:b-hl4voj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/look/gameState.js#L31)):*
> ```JavaScript
> 
> 
> export function getColor() {
> ```

Maybe rename to `getMyColor()`? Or `getMyTeam()`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by shanek21** [comment]
Reviewed 7 of 12 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by davidabrahams** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCHmppUCe_r7NWM4lkG:-LCMyNQ20rwNZygIPa4A:bxcedzy) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Pls update
</blockquote></details>

Sorry. works now. JSMB is a wizard

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/start.js, line 33 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMrR_9-nU9q7TU-a1L:-LCMy__sA49WOX7lJV7u:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/start.js#L33)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

WTF DAVID
</blockquote></details>

Done.

---

*[src/start.js, line 37 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMrWaFCJaoAIOAwW3z:-LCMy_tw7fxZI93pibDU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/start.js#L37)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

what is this? pls leave a comment
</blockquote></details>

Done.

---

*[src/start.js, line 41 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMrcQc4Lj-gQlP94pq:-LCMycyy3R6QvvwtUyh4:b-1e3f88) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/start.js#L41)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I think this diff is from the bad rebase
</blockquote></details>

oh yeah oops its in here twice my bad

---

*[src/interpret/setup.js, line 105 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMsUQ3CtLLYeYXnz0b:-LCMz9ex8Lqu3jnpyHhj:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/interpret/setup.js#L105)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Change `{num}`?
</blockquote></details>

Done.

---

*[src/interpret/setup.js, line 106 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMsXT5A1y4NCEpKHs-:-LCMzALS3aZI24fplhhv:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/interpret/setup.js#L106)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Add `@param` for `calcGraphs`?
</blockquote></details>

Done.

---

*[src/look/gameState.js, line 31 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/462#-LCMs7rHAx9f-fQxq_KG:-LCMzK3nEHMZXMq2Nj7o:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c493072fe12db96d1fba1635e1ba54be05e96e76/src/look/gameState.js#L31)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Maybe rename to `getMyColor()`? Or `getMyTeam()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/462)*

**Pull request merged**
