### PR TITLE
197: Add Travis Notifications to Slack

### LINKED ISSUE #197: Add Travis Notifications to Slack
Overriding my sprint goals for this because we've had some master breaking this sprint and I want to set this up to try and catch them earlier.

### PR DESCRIPTION
**Pull request by billmwong**
Closes #197

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/198)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198#-KtA5nCyOUaujRL_O-QA:-KtA5nCz9VsYKWmf7Ahf:b3qptm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/824901b1d060e11c0297476163d9cafdbb8cc90f/.travis.yml#L12)):*
> ```YAML
>   slack:
>     rooms:
>       secure: RKW2Fyda7cPnSVvUeLkr2x63GT4Wt24YWIE5/sbttw1lMHd8aa3ZOzbgxWsUsszBgbArCB7W4g9xNG9QpKB7/VSub8qZgSjiA3DX4EHzcXJYOcqzW1w3KLxfU1hC9q6qTS8bFR88lnvC2WJ+xcqX+rcAR8SMI1meIR/q61aecJN5b/IhXTVMtGqQvin/Kky2PButQuUmwrBu99ixghKE8xC+fLyzA+pNyUJRiEHzYEK4Tu9Ljir+9afrf5naSODmjFzuob0SiSJGrtUsQWLVvZZHjuOYokPHQ3O1no54BxpWroMJfO9k2pDfw0uNZFeyeL8OipY/IdKIGmqqGBtXHTdIYe5elA+ymq9qkyLq3S7Kv96ZytuyQbmeIoAFoI3SdGwvAs39adqdHpS9XjU+zw1lfwIxbZLcuSS38V5mMQQZgcDCkR3BuVZgMcq8AY6g6thLhhusOt/BjwpvZgPuBIEvj0X9DFaElz2fUQOIT8Z+Js45ypWkiucptyGwKJPfdCO9fvC1m9aq/VaQVy2UCDFt0J50ddlyYkQXpBbRrQc85td/oxlmT8C+fEYNKRWFOXWaJIR/gJht/eY644uITQxeoMyJMPUvvlUDQCcmk+JPz7qdRtZdOAI/7c5mu+ZstAjRfI/xTdXcQm+eznJajkphGBqkaun3/uLIDGH/n7c=
> ```

is committing this safe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198)*

**Comment by billmwong** [comment]
*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198#-KtA5nCyOUaujRL_O-QA:-KtA6-lnkPtEwkthfnWG:b-h3vk5f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/824901b1d060e11c0297476163d9cafdbb8cc90f/.travis.yml#L12)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

is committing this safe?
</blockquote></details>

Yeah this is actually the safe encrypted version of the key.  I had to generate it on my machine, Travis suggested using this encrypted version instead of the default key

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198)*

**Comment by davidabrahams** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198#-KtA5nCyOUaujRL_O-QA:-KtA6s-8_6BbPLsH1AJI:bqyiiei) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/824901b1d060e11c0297476163d9cafdbb8cc90f/.travis.yml#L12)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Yeah this is actually the safe encrypted version of the key.  I had to generate it on my machine, Travis suggested using this encrypted version instead of the default key
</blockquote></details>

:dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/198)*

**Pull request merged**
