### PR TITLE
252: make keypress visualization toggle with other visualizations

### LINKED ISSUE #252: Turn off arrow key viz when toggling visualization state

### PR DESCRIPTION
**Pull request by shanek21**
Closes #252

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/256)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/draw/drawings.js, line 253 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256#-KyHuR7SVYSRFYqiXbzH:-KyHuR7SVYSRFYqiXbzI:b-pi9d9n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e01e8285c74956ef5b2704ec6a3eb53a1fdf2fe6/src/draw/drawings.js#L253)):*
> ```JavaScript
>   const allSprites = permNTSprites
>     .concat(pathSprites)
>     .concat(graphSprite || [])
> ```

remove this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256)*

**Comment by shanek21** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/draw/drawings.js, line 253 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256#-KyHuR7SVYSRFYqiXbzH:-KyJFymM6Gp3HZCI1UHl:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e01e8285c74956ef5b2704ec6a3eb53a1fdf2fe6/src/draw/drawings.js#L253)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/256)*

**Pull request merged**
