### PR TITLE
90: setup velocity documentation

### PR DESCRIPTION
**Pull request by davidabrahams**
sorry guys :(

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/168)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Comment by altodyte** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Comment by shanek21** [comment]
commit tense is weird

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168#-:-KsZMMiO8Ksjr7_ry6pS:b-a9h7zo)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Comment by davidabrahams** [comment]
what's weird about it?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168#-:-Ks_jUs3ojNK-LuQFlEC:b1og2qr)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/utils/interface.js, line 102 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168#-Ksa0fe0cemqv8mkq45H:-Ksa0fe0cemqv8mkq45I:b-7kr1z8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/ffffe01255529f8d39f5470093ac331cb9bc3dc4/src/utils/interface.js#L102)):*
> ```JavaScript
> export function move(destination) {
>   // TODO: address deadband variable with a comment
>   const deadband = 4;
> ```

Did we already talk about why this TODO is here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/168)*

**Pull request merged**
