### PR TITLE
285: add third dummy point to initial containing triangle

### PR DESCRIPTION
**Pull request by shanek21**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/291)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/navmesh/triangulation.js, line 28 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-XzU5QTnFUoBbQOwvu:-L-XzU5QTnFUoBbQOwvv:b4df91v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e905f29e41ea50e315de67cbdc0c14e33396325/src/navmesh/triangulation.js#L28)):*
> ```JavaScript
>   const numVertices = DTGraph.getVertices().length;
>   assert(DTGraph.getVertices().length === 0, `DTGraph had ${numVertices} vertices.`);
>   const highestP = getHighestPoint(vertices);
> ```

This functions probs no longer necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by billmwong** [comment]
:dango:

---

Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-:-L-Y-IXRbovNHSW1r9eF:bcbqss6)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y-wPVYsd6hYZe4sS7:-L-Y-wPVYsd6hYZe4sS8:b-itg5wq) (no related file):*
Update wiki with new command center link, re-hardcode endzone tiles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by shanek21** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y-wPVYsd6hYZe4sS7:-L-Y5kimHA_Di5oLuD-M:b-896fix) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Update wiki with new command center link, re-hardcode endzone tiles
</blockquote></details>

Done.

---

*[src/navmesh/triangulation.js, line 28 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-XzU5QTnFUoBbQOwvu:-L-Y6Beu5KAssrUImQwP:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0e905f29e41ea50e315de67cbdc0c14e33396325/src/navmesh/triangulation.js#L28)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This functions probs no longer necessary
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by shanek21** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y-wPVYsd6hYZe4sS7:-L-Y6Vs18931wD68Vojc:bz0osxy) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://github.com/chauncy-crib/tagprobot/wiki/Useful-Links

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 3 files at r2.
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/bot.js, line 30 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y6jUJkXW6O6EGGTqH:-L-Y6jUJkXW6O6EGGTqI:bb6ucnz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/234aa3359faa99af7d5078fec88d6e015e155a56/src/bot.js#L30)):*
> ```JavaScript
>   // If the bot has the flag, go to the endzone
>   if (me.flag) {
>     goal = amRed() ? { xp: 1360, yp: 1560 } : { xp: 640, yp: 440 };
> ```

Dank

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r2.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bot.js, line 37 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y6qlORbprYVxVFhef:-L-Y6qlPPHEvOsS4Xs9w:b-r535jc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/234aa3359faa99af7d5078fec88d6e015e155a56/src/bot.js#L37)):*
> ```JavaScript
>     let enemyShortestPath = [];
>     if (enemyFC) { // If an enemy player in view has the flag, chase
>       const enemyGoal = amBlue() ? { xp: 1320, yp: 1360 } : { xp: 440, yp: 400 };
> ```

do we need to update these three endzones down here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by shanek21** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bot.js, line 37 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y6qlORbprYVxVFhef:-L-Y8JHMzzUZWbqqZpWq:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/234aa3359faa99af7d5078fec88d6e015e155a56/src/bot.js#L37)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

do we need to update these three endzones down here too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/bot.js, line 28 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291#-L-Y8N6JrJ1fIqpH6OCJ:-L-Y8N6JrJ1fIqpH6OCK:b835n5l) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/c686594642338a9aa72d721df54c9a2b6fd08c0a/src/bot.js#L28)):*
> ```JavaScript
>   let goal;
>   const redEndzone = { xp: 1360, yp: 1560 };
>   const blueEndzone = { xp: 640, yp: 440 };
> ```

FYI I like this update. Nice change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/291)*

**Pull request merged**
