### PR TITLE
99: Add unit tests for findTile function

### PR DESCRIPTION
**Pull request by shanek21**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/144)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsRY4GaFb9S48cylUVl:b-p15dh0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
> ```JavaScript
>     requestAnimationFrame(loop);
>     if (isAutonomous()) {
>       botLoop(tagpro.map);
> ```

why, what is this revision

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by altodyte** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/helpers/map.js, line 198 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsSCyNGO0wZvPOGkOEl:-KsSCyNGO0wZvPOGkOEm:bdo671f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/helpers/map.js#L198)):*
> ```JavaScript
>         const tileId = tileIdArray[i];
>         if (map[x][y] === tileId) {
>           return { x: x * PPTL, y: y * PPTL };
> ```

Why don't we care about xc, yc now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsTBSm24f9A4FdXvUiK:b-a9trcd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why, what is this revision
</blockquote></details>

Adding unit tests for the `findTile` function hahaha

---

*[src/helpers/map.js, line 198 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsSCyNGO0wZvPOGkOEl:-KsTBFXFyy65LCTHxiuo:b6cmt16) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/helpers/map.js#L198)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

Why don't we care about xc, yc now?
</blockquote></details>

We never use it. I don't remember a time when we did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsTJEjQd9VbUh5wVWsk:b-fz4v3s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Adding unit tests for the `findTile` function hahaha
</blockquote></details>

Why is the diff passing tagpro.map into botloop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsThQrMonMrmUEK36LW:b5uwuj4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Why is the diff passing tagpro.map into botloop
</blockquote></details>

It passes all the way down to `findTile`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsTiem2X8a8Vn3OMfpw:b-5izdc1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

It passes all the way down to `findTile`
</blockquote></details>

Why is that necessary for this unit tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsTin3FP61ytt1MnqNF:bp943jv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Why is that necessary for this unit tests
</blockquote></details>

It's not necessary, but it makes the unit testing more easier and the information flow more intuitive (at least to me - thoughts?). It's easier to see that a function depends on a variable if it is passed in rather than using a global inside of it. Now we only grab `tagpro.map` from the API in one place and pass it to wherever it is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
*[src/index.js, line 68 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsRY4GaFb9S48cylUVk:-KsTleGkfltknopMi5dT:brfe14s) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L68)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

It's not necessary, but it makes the unit testing more easier and the information flow more intuitive (at least to me - thoughts?). It's easier to see that a function depends on a variable if it is passed in rather than using a global inside of it. Now we only grab `tagpro.map` from the API in one place and pass it to wherever it is needed.
</blockquote></details>

I'd rather store it in constants or something similar to how to handle `me`, and then import the tagproMap var from that constants file where we need it but I could be convinced otherwise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index.js, line 71 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsUcSz4SAwDw2SeEXBV:-KsUcSz4SAwDw2SeEXBW:b-sjnodm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L71)):*
> ```JavaScript
>     }
>   }
> ```

I think helpers should take in the map, but index.js and bot.js should use the global

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index.js, line 71 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsUcSz4SAwDw2SeEXBV:-KsUckKTYOCtbcx8u3HV:bmmislr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L71)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I think helpers should take in the map, but index.js and bot.js should use the global
</blockquote></details>

I meant to reply to the previous conversation but I think I messed up

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by shanek21** [comment]
So, I got half way done with these changes, took a half hour nap, woke up having no idea if I was even alive and then finished the rest of the changes. I'm pretty sure the second solar eclipse happened during my last commit.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-:-KsVaIlvJDGAON0sPt4P:bo4q160)*

**Comment by altodyte** [comment]
:dango:

---

Reviewed 2 of 7 files at r4.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-:-KsVanuQwM3rKQsbHQb9:bcbqss6)*

**Comment by shanek21** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/index.js, line 71 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-KsUcSz4SAwDw2SeEXBV:-KsVbn42U_MhzcqNZsCg:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/48a7fb8a0f410658f17eb21c2e91888d0064f721/src/index.js#L71)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I meant to reply to the previous conversation but I think I messed up
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
Minimize the diff here as we discussed, I think that was the conclusion

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-:-KsWxNfO7v0hC8RG6ops:bi06xe3)*

**Comment by davidabrahams** [comment]
Reviewed 12 of 12 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
*[src/bot.js, line 25 at r7](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-Ksa0SmBQZn6hYUUm2Nw:-Ksa0SmBQZn6hYUUm2Nx:b-syiovv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/600dea7d4d2850bc5de94ca6a7b0ebf238205354/src/bot.js#L25)):*
> ```JavaScript
> function getGoalPos() {
>   const me = getMe();
>   let goal;
> ```

why did you change this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
Reviewed 1 of 9 files at r4, 1 of 12 files at r6, 6 of 15 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/bot.js, line 25 at r7](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-Ksa0SmBQZn6hYUUm2Nw:-Ksa0qxS5k21RDwgwTZX:b-18z19e) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/600dea7d4d2850bc5de94ca6a7b0ebf238205354/src/bot.js#L25)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why did you change this line
</blockquote></details>

After our long discussion on the topic of this PR, I wanted to make it as clear as possible what each function depends on, even though we opted to not pass in globals like `me` and `map`. Therefore, I moved the obtaining of the globals that each function depends on to the top through either a variable assignment or an assert that the global is not `undefined`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by billmwong** [comment]
*[src/bot.js, line 25 at r7](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-Ksa0SmBQZn6hYUUm2Nw:-Ksa1SjUE5mTI7ctT8mk:bdgwgxb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/600dea7d4d2850bc5de94ca6a7b0ebf238205354/src/bot.js#L25)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

After our long discussion on the topic of this PR, I wanted to make it as clear as possible what each function depends on, even though we opted to not pass in globals like `me` and `map`. Therefore, I moved the obtaining of the globals that each function depends on to the top through either a variable assignment or an assert that the global is not `undefined`
</blockquote></details>

Damn man that's a really good reason :lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144)*

**Comment by davidabrahams** [comment]
:dango:

---

Reviewed 1 of 12 files at r6, 6 of 15 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/144#-:-Ksa3wrWPHle9zOWX3nn:bcbqss6)*

**Pull request merged**
