### PR TITLE
132: missing properties

### PR DESCRIPTION
**Pull request by davidabrahams**
getTileProperty throws an error if you provide a property it doesn't have. Use tileHasProperty instead.

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/137)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/tiles.js, line 79 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137#-KrpKgrntI74HXqJRD7b:-KrpKc8H2ReZLFEUDDRJ:b-t10y1u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1725d3d3117563ecf048e3ff77fcbc67773e100e/src/tiles.js#L79)):*
> ```JavaScript
>   assert(has(tileNames, tileIDString), `Unknown tileID: ${tileID}`);
>   const tileName = tileNames[tileID];
>   assert(has(tileInfo[tileName], property), `Unknown property for tile: ${tileName}`);
> ```

Shouldn't this use `tileHasProperty`?

---

*[test/tiles.spec.js, line 141 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137#-KrpKuzum1YMMIM91unW:-KrpKuzum1YMMIM91unX:b-mkkivx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1725d3d3117563ecf048e3ff77fcbc67773e100e/test/tiles.spec.js#L141)):*
> ```JavaScript
>   teardownTiles();
> 
>   t.end();
> ```

Yo, this :white_large_square: :space_invader: is :dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/tiles.js, line 79 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137#-KrpKgrntI74HXqJRD7b:-KrpNcwaHOdOX6DgXqzP:b-4k9whs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/1725d3d3117563ecf048e3ff77fcbc67773e100e/src/tiles.js#L79)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Shouldn't this use `tileHasProperty`?
</blockquote></details>

Oh. Ya it should

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137#-Krr2PnGT2M64i9Lxqhr:-Krr2PnGT2M64i9Lxqhs:bexp2zo) (no related file):*
Fix Travis pls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137#-Krr2PnGT2M64i9Lxqhr:-Krr83DGNJeglKyXFtpI:b-wfx1yr) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Fix Travis pls
</blockquote></details>

lol i forgot like 4 semicolons

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/tiles.js, line 91 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137#-KrrMmblBdiX16hl4-04:-KrrMmblBdiX16hl4-05:bqqnnoq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/adfb5f2b50b442837782f24f59d342c573f75c97/src/tiles.js#L91)):*
> ```JavaScript
>  */
> export function getTileProperty(tileID, property) {
>   assert(tileHasProperty(tileID, property), `Unknown property for tile: ${tileID}, ${property}`);
> ```

Couldn't have addressed it better myself!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Comment by altodyte** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/137)*

**Pull request merged**
