### PR TITLE
Matrix math functions

### LINKED ISSUE #390: Matrix math functions
Write:
- the dot between two matrices
- subtraction
- addition
- inverse
- access by index

make matrix a class, model it after numpy arrays

### PR DESCRIPTION
**Pull request by billmwong**
Closes #390

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/398)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/control/class/Matrix.js, line 4 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96rvRu5wDS73MfgXNg:-L96rvRu5wDS73MfgXNh:b-y3dzpv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L4)):*
> ```JavaScript
> 
> 
> export class Matrix {
> ```

Comment at top of class explaining the purpose of it

---

*[src/control/class/Matrix.js, line 5 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96rqKTA5Td9fnLzbz8:-L96rqKTA5Td9fnLzbz9:b-4yx09q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L5)):*
> ```JavaScript
> 
> export class Matrix {
>   constructor(array) {
> ```

Can you add a docstring to the constructor specifying that `array` is an array of arrays?

---

*[src/control/class/Matrix.js, line 9 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96sI_lARyq54imQKMq:-L96sI_lARyq54imQKMr:b-4ipepu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L9)):*
> ```JavaScript
>   }
> 
>   dot(other) {
> ```

can you comment this function? (it's the only one thats not super obvious what it does)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by billmwong** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/control/class/Matrix.js, line 4 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96rvRu5wDS73MfgXNg:-L9BfKtr7s7D0wgjbQgj:b-896fig) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L4)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Comment at top of class explaining the purpose of it
</blockquote></details>

Done?

---

*[src/control/class/Matrix.js, line 5 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96rqKTA5Td9fnLzbz8:-L9BfKjO20XNdjnN4uCH:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L5)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Can you add a docstring to the constructor specifying that `array` is an array of arrays?
</blockquote></details>

Done.

---

*[src/control/class/Matrix.js, line 9 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96sI_lARyq54imQKMq:-L9BfKUx9UjGOB4qZiem:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L9)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

can you comment this function? (it's the only one thats not super obvious what it does)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by davidabrahams** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/control/class/Matrix.js, line 4 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96rvRu5wDS73MfgXNg:-L9BgM1R52-3930y-ilb:bddbts0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L4)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Hows:

```
A wrapper around 2-d javascript arrays which supports matrix math operations
```

?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by billmwong** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/control/class/Matrix.js, line 4 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L96rvRu5wDS73MfgXNg:-L9BiD46A9A8CUTsJ8zu:b6t2uxi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e6ae8c08712c54e07a32565863537f8e8f233153/src/control/class/Matrix.js#L4)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Hows:

```
A wrapper around 2-d javascript arrays which supports matrix math operations
```

?
</blockquote></details>

DOOOONE

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by shanek21** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/control/class/Matrix.js, line 5 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L9BkvIqCxowmWgO94fn:-L9BkvIs4zJ1b_ZcZYEw:btpxf9t) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/6c3d8575d528ef15248b988e99ac79ba02540a44/src/control/class/Matrix.js#L5)):*
> ```JavaScript
> 
> /**
>  * A wrapper around 2-d javascript arrays which supports matrix math operations
> ```

super nit, but can you change `2-d` to `2D`? I think that's how we use it everywhere else (and how you use it later in this file)

---

*[src/control/class/Matrix.js, line 21 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L9Blxcm6w29el1G5zKU:-L9Blxco6fh5DgnQDO3b:biymby3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/6c3d8575d528ef15248b988e99ac79ba02540a44/src/control/class/Matrix.js#L21)):*
> ```JavaScript
>   /**
>    * Returns the dot product of this matrix and another matrix.  Equivalent to matrix multiplication
>    * for 2D arrays, and inner product of vectors for 1D arrays.
> ```

indent by two spaces

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by billmwong** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/control/class/Matrix.js, line 5 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L9BkvIqCxowmWgO94fn:-L9Boy5TAn2zRPwo2rht:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/6c3d8575d528ef15248b988e99ac79ba02540a44/src/control/class/Matrix.js#L5)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

super nit, but can you change `2-d` to `2D`? I think that's how we use it everywhere else (and how you use it later in this file)
</blockquote></details>

Done.

---

*[src/control/class/Matrix.js, line 21 at r3](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398#-L9Blxcm6w29el1G5zKU:-L9BoylR1uO8vu7ChTV3:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/6c3d8575d528ef15248b988e99ac79ba02540a44/src/control/class/Matrix.js#L21)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

indent by two spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/398)*

**Pull request merged**
