### PR TITLE
211: Find endzones dynamically

### LINKED ISSUE #211: Find endzones dynamically
- Find endzones dynamically in any map
- Find first endzone tile

Currently, we search through the tiles in the map in a page-reading fashion looking for the first appropriately colored endzone tile. This always results in an endzone tile that is against a wall, which is often unreachable once the NT buffer is added to all NTOs.

I have a bad hardcoded solution currently in the code, but it should likely be changed to be less bad and less hardcoded. My current solution affects [this line](https://github.com/chauncy-crib/tagprobot/blob/4afb8eab51d455ee45b9e96d6128bdd534b8d35a/src/bot.js#L44) and [this line](https://github.com/chauncy-crib/tagprobot/blob/4afb8eab51d455ee45b9e96d6128bdd534b8d35a/src/bot.js#L49).

When addressing this issue, the following code may be applicable:
`import { getMe, getAllyEndzoneTileName, getEnemyEndzoneTileName } from './helpers/player';`

`goal = findTile(getEnemyEndzoneTileName());`

`goal = findTile(getAllyEndzoneTileName());`

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #211

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/315)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 7 of 7 files at r1.
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Comment by shanek21** [comment]
Reviewed 7 of 7 files at r1.
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r3.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r3.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/315)*

**Pull request merged**
