### PR TITLE
257: mock foreground in drawing test

### LINKED ISSUE #257: [HOT FIX] drawing tests fail because foreground is not mocked

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #257

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/258)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258#-KyI8DtLT-qb2tjKs5BF:-KyI8DtLT-qb2tjKs5BG:b255wl0) (no related file):*
travis failed for some reason

---

*[src/draw/drawings.js, line 246 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258#-KyI7war4xnGIYYoe0uE:-KyI7war4xnGIYYoe0uF:b-mx108p) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d87d692ed5267d68cb8c13a46440666a1a67109a/src/draw/drawings.js#L246)):*
> ```JavaScript
>   const foregroundSprites = []
>     .concat(triangulationSprite || [])
>   _.forEach(foregroundSprites, s => tagpro.renderer.layers.foreground.removeChild(s));
> ```

didn't you just tell me to write this the other way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 246 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258#-KyI7war4xnGIYYoe0uE:-KyI8alwDoWwYSDochso:b-e2z4zz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d87d692ed5267d68cb8c13a46440666a1a67109a/src/draw/drawings.js#L246)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

didn't you just tell me to write this the other way
</blockquote></details>

Yeah. In my next PR, I'm adding another sprite for the polypoint graph. I figured since there's going to be two, it's easier to concat them together? I can also just make that change later, and rewrite it the way you had it in this PR. THoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258)*

**Comment by davidabrahams** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258#-KyI8DtLT-qb2tjKs5BF:-KyI8vC3_gdnHRRUuEzP:busaxrw) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

travis failed for some reason
</blockquote></details>

Fixed it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 246 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258#-KyI7war4xnGIYYoe0uE:-KyI92hVZTOEmPxyQEyv:brpii5c) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/d87d692ed5267d68cb8c13a46440666a1a67109a/src/draw/drawings.js#L246)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Yeah. In my next PR, I'm adding another sprite for the polypoint graph. I figured since there's going to be two, it's easier to concat them together? I can also just make that change later, and rewrite it the way you had it in this PR. THoughts?
</blockquote></details>

OK nah this is fine then :dango: 

---

*[src/draw/drawings.js, line 245 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258#-KyI98pVGsGaj5gMZgx0:-KyI98pVGsGaj5gMZgx1:bs6mgva) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/6159ee93f6372a9d1f8629e18821120242b4beaf/src/draw/drawings.js#L245)):*
> ```JavaScript
>   _.forEach(backgroundSprites, s => tagpro.renderer.layers.background.removeChild(s));
>   const foregroundSprites = []
>     .concat(triangulationSprite || []);
> ```

FYI where's your autolinter now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/258)*

**Pull request merged**
