### PR TITLE
131: Change any tileInfo IDs with decimals to Strings

### LINKED ISSUE #131: Change all tileInfo IDs with decimals to Strings
I believe the inactive boosts (called speedpads by the API) are strings, not numbers.

### PR DESCRIPTION
**Pull request by shanek21**
Closes #131 

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/147)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by billmwong** [comment]
Closes #131

**Comment by billmwong** [comment]
If this works sounds :dango: to me

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-:-KsPotZRTCDIqGmwvBT8:b-r3i5j6)*

**Comment by shanek21** [comment]
Throws an error when after a cap before the flag is reset at the spawn point - will check it out in the morning:
```
Uncaught Error: Unable to find tile: 16,16.1
    at findTile (eval at E_c (:3:221), <anonymous>:1633:9)
    at findFlagStation (eval at E_c (:3:221), <anonymous>:9288:28)
    at getGoalPos (eval at E_c (:3:221), <anonymous>:6053:39)
    at getNextTargetPos (eval at E_c (:3:221), <anonymous>:6065:34)
    at botLoop (eval at E_c (:3:221), <anonymous>:6092:44)
    at loop (eval at E_c (:3:221), <anonymous>:4947:24)
```

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsRXU1UMWEIsvxVKlEC:-KsRXU1UMWEIsvxVKlED:bq5rn1f) (no related file):*
Throws an error when after a cap before the flag is reset at the spawn point - will check it out in the morning:
```
Uncaught Error: Unable to find tile: 16,16.1
    at findTile (eval at E_c (:3:221), <anonymous>:1633:9)
    at findFlagStation (eval at E_c (:3:221), <anonymous>:9288:28)
    at getGoalPos (eval at E_c (:3:221), <anonymous>:6053:39)
    at getNextTargetPos (eval at E_c (:3:221), <anonymous>:6065:34)
    at botLoop (eval at E_c (:3:221), <anonymous>:6092:44)
    at loop (eval at E_c (:3:221), <anonymous>:4947:24)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by shanek21** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsRXU1UMWEIsvxVKlEC:-KsUfUsHh7zDJ2q4Ph8t:b-2zfop2) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Throws an error when after a cap before the flag is reset at the spawn point - will check it out in the morning:
```
Uncaught Error: Unable to find tile: 16,16.1
    at findTile (eval at E_c (:3:221), <anonymous>:1633:9)
    at findFlagStation (eval at E_c (:3:221), <anonymous>:9288:28)
    at getGoalPos (eval at E_c (:3:221), <anonymous>:6053:39)
    at getNextTargetPos (eval at E_c (:3:221), <anonymous>:6065:34)
    at botLoop (eval at E_c (:3:221), <anonymous>:6092:44)
    at loop (eval at E_c (:3:221), <anonymous>:4947:24)
```
</blockquote></details>

Alright, so, I investigated this a bit and it seems like any tile ID with a decimal is actually stored as a string in the tagpro API. So, I made them all Strings, and I haven't encountered any more errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsRXU1UMWEIsvxVKlEC:-KsWcuA5YSM8HqwA9fVl:b-pwucau) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Alright, so, I investigated this a bit and it seems like any tile ID with a decimal is actually stored as a string in the tagpro API. So, I made them all Strings, and I haven't encountered any more errors.
</blockquote></details>

Why was this not throwing errors before this PR existed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsRXU1UMWEIsvxVKlEC:-KsWmuW4HhR-z-Yff64i:bkiv1fp) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Why was this not throwing errors before this PR existed?
</blockquote></details>

I actually think it might have. But i'm really not sure. @shanek21 , your thoughts on instead of doing this, updating `findTile`comparison from `if (tagpro.map[x][y] === tile) {` to `if (tagpro.map[x][y].toString() === tile.toString()) {`?

This would make us not have to worry about storing strings and numbers.

Another alternative would be to update `getTileId` to do the string cast for you:

```
export function getTileId(name) {
  assert(_.has(tileInfo, name), `Unknown tileName: ${name}`);
  const tileId = tileInfo[name].id;
  if !Number.isInteger(tileId) {
    return tileId.toString();
  }
  return tileId;
}
```

I think the second one is the best solution. I like the wrapper functions handling weird shit for us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsRXU1UMWEIsvxVKlEC:-KsWpNmWcqO5gUpIiU5y:baq8dc) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I actually think it might have. But i'm really not sure. @shanek21 , your thoughts on instead of doing this, updating `findTile`comparison from `if (tagpro.map[x][y] === tile) {` to `if (tagpro.map[x][y].toString() === tile.toString()) {`?

This would make us not have to worry about storing strings and numbers.

Another alternative would be to update `getTileId` to do the string cast for you:

```
export function getTileId(name) {
  assert(_.has(tileInfo, name), `Unknown tileName: ${name}`);
  const tileId = tileInfo[name].id;
  if !Number.isInteger(tileId) {
    return tileId.toString();
  }
  return tileId;
}
```

I think the second one is the best solution. I like the wrapper functions handling weird shit for us.
</blockquote></details>

^ this isn't valid JS....I coded it in reviewable. I just realized the if statement should be `if (!Number.isInteger(tileId)) {`. But you get the idea

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/tiles.js, line 105 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsaYIWk6G84hmWGW3UE:-KsaYIWk6G84hmWGW3UF:bnmwtgh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/05943eba68ebf4d8ee343d33317920fd8a0565b6/src/tiles.js#L105)):*
> ```JavaScript
>   assert(_.has(tileInfo, name), `Unknown tileName: ${name}`);
>   const tileId = tileInfo[name].id;
> ```

holy whitespace batman

---

*[test/tiles.spec.js, line 157 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsaYXKd7tGqXNndoSB6:-KsaYXKd7tGqXNndoSB7:b-ewdkg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/05943eba68ebf4d8ee343d33317920fd8a0565b6/test/tiles.spec.js#L157)):*
> ```JavaScript
>   t.ok(tileIsType(4, 'BLUE_FLAG'));
>   t.ok(tileIsType(5.1, 'SPEEDPAD_INACTIVE'));
>   t.ok(tileIsType(16.1, 'YELLOW_FLAG_TAKEN'));
> ```

Can you add a unittest where the input is a string? I believe there's a potential use case for that:

`t.ok(tileIsType('16.1', 'YELLOW_FLAG_TAKEN'));`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/tiles.spec.js, line 157 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsaYXKd7tGqXNndoSB6:-KsaYx7V1ei69B5QD1rD:b559cqk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/05943eba68ebf4d8ee343d33317920fd8a0565b6/test/tiles.spec.js#L157)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Can you add a unittest where the input is a string? I believe there's a potential use case for that:

`t.ok(tileIsType('16.1', 'YELLOW_FLAG_TAKEN'));`
</blockquote></details>

What's the use case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/tiles.spec.js, line 157 at r4](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsaYXKd7tGqXNndoSB6:-KsafM3b89yKToj1OO1J:b-gpndwf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/05943eba68ebf4d8ee343d33317920fd8a0565b6/test/tiles.spec.js#L157)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

What's the use case?
</blockquote></details>

I'm honestly not sure. Okay so the `tileIsType` doc specifies that `tileID` is a number. We need to update that to be `{(number|string)}`. We should allow it to take in the strings from the `tagpro.map`. Then, `getTileId` should convert the decimals in `tileInfo` to strings and return them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
I'm not sure if this PR is the place for this, but I think it would be smart if we just removed `getTileId` function, and forced ourself to never explicitly pass an Id around. It seems much safer. We should pass tile names around, and if we check for equality, use `tileIsType`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-:-KsagjT8rXexRFZkx25E:biz2tx3)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tiles.js, line 98 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdS1WKLr28xMObNS02:-KsdS1WLeyk1CTmnBZri:b-ppzrdl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/091bc87019fb1e9c14eeca4a94a4cb466577f43e/src/tiles.js#L98)):*
> ```JavaScript
>  * @return the id for the input tile name
>  */
> export function getTileId(name) {
> ```

Don't export this function, since a user should never need to use it.

---

*[src/tiles.js, line 110 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdSJ6gbYlUEvIWodqs:-KsdSJ6gbYlUEvIWodqt:bk87lvl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/091bc87019fb1e9c14eeca4a94a4cb466577f43e/src/tiles.js#L110)):*
> ```JavaScript
> export function tileIsType(tileId, name) {
>   assert(_.has(tileInfo, name), `Unknown tileName: ${name}`);
>   return tileId === tileInfo[name].id;
> ```

Should this be a call to getTildId()? If not, I think you can just remove the getTileId function completely

---

*[src/helpers/player.js, line 27 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdSabc4PpvdpS5wHGs:-KsdSabc4PpvdpS5wHGt:by8czdp) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/091bc87019fb1e9c14eeca4a94a4cb466577f43e/src/helpers/player.js#L27)):*
> ```JavaScript
> 
> export function getAllyEndzoneTileName() {
>   return amBlue() ? 'BLUE_ENDZONE' : 'RED_ENDZONE';
> ```

So clean. Love it

---

*[test/helpers/finders.spec.js, line 16 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdSqrjhYbU9HNbeSWQ:-KsdSqrjhYbU9HNbeSWR:b7jswtz) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/9aabf86f9ce87529214cd81543baaef78280f66c/test/helpers/finders.spec.js#L16)):*
> ```JavaScript
>   const redgate = getTileId('RED_GATE');
>   const bluegate = getTileId('BLUE_GATE');
>   const blank = getTileId('REGULAR_FLOOR');
> ```

I know writing this was annoying, so i want you to have this :dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/tiles.js, line 98 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdS1WKLr28xMObNS02:-KsdTBt5l_ZAhHKhp_vV:ba9qe1u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/091bc87019fb1e9c14eeca4a94a4cb466577f43e/src/tiles.js#L98)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Don't export this function, since a user should never need to use it.
</blockquote></details>

Whoops, meant to delete this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/tiles.js, line 44 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdrhsQ0a07T6jR0TQ0:-KsdrhsQ0a07T6jR0TQ1:bwej9oc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/tiles.js#L44)):*
> ```JavaScript
>     BLUE_GATE: { id: 9.3, traversable: amBlue(), permanent: false },
>     BOMB: { id: 10, traversable: false, radius: 15, permanent: false },
>     INACTIVE_BOMB: { id: '10.1', traversable: true, permanent: false },
> ```

so, just confirming, these are what we think the ids stored in the Tagpro API, correct?

---

*[src/tiles.js, line 75 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-Ksdui9uxDpb3GeYTC6Y:-Ksdui9uxDpb3GeYTC6Z:bu8sona) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/tiles.js#L75)):*
> ```JavaScript
> export function getTileName(id) {
>   assert(_.has(tileNames, id), `Unknown tile ID: ${id}`);
>   const name = _.findKey(tileInfo, tile => tile.id === id);
> ```

This is an O(N) operation. We should think of how to make this O(1) (you could store a map from Id to Name and do a lookup into that, to be O(1))

---

*[src/helpers/finders.js, line 29 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdvM9d3EBUdCgrypIa:-KsdvM9d3EBUdCgrypIb:bn9npvq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/helpers/finders.js#L29)):*
> ```JavaScript
>     for (let yt = 0, yl = tagpro.map[0].length; yt < yl; yt++) {
>       for (let i = 0; i < tileNameArray.length; i++) {
>         if (tileNameArray[i] === getTileName(tagpro.map[xt][yt])) {
> ```

I think this line was better the way it was before. We can discuss offline?

---

*[src/helpers/map.js, line 127 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdvYBVpCiX2Rldyi0C:-KsdvYBVpCiX2Rldyi0D:b4ekt7w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/helpers/map.js#L127)):*
> ```JavaScript
>       fillGridWithSubgrid(
>         mapTraversabilityCells,
>         getTileTraversabilityInCells(tileName),
> ```

Me no likey conversion. Why doesn't `getTileTraversabilityInCells` take in an Id?

---

*[src/helpers/map.js, line 167 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdvdcEVWOx496OgSlI:-KsdvdcEVWOx496OgSlJ:buo9nmt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/helpers/map.js#L167)):*
> ```JavaScript
>       fillGridWithSubgrid(
>         mapTraversabilityCells,
>         getTileTraversabilityInCells(getTileName(map[xy.x][xy.y])),
> ```

Same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by billmwong** [comment]
*[src/tiles.js, line 75 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-Ksdui9uxDpb3GeYTC6Y:-Kseds83Etuhj8aZBs8_:b-7lpeq6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/tiles.js#L75)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This is an O(N) operation. We should think of how to make this O(1) (you could store a map from Id to Name and do a lookup into that, to be O(1))
</blockquote></details>

can't this use tileNames? that would be O(1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by billmwong** [comment]
*[src/tiles.js, line 44 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdrhsQ0a07T6jR0TQ0:-Kseekjyea1ZXay5r8Kq:bsmm64c) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/tiles.js#L44)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

so, just confirming, these are what we think the ids stored in the Tagpro API, correct?
</blockquote></details>

I'm confused are we coding it in the data now? This is my way isn't it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/tiles.js, line 44 at r6](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdrhsQ0a07T6jR0TQ0:-KsdvxpIxsW-VmgG2zgb:b-xslz3f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/dfb22368e10436241c49c50699b7e4d536e5e198/src/tiles.js#L44)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

so, just confirming, these are what we think the ids stored in the Tagpro API, correct?
</blockquote></details>

If a tile existed during any of my testing on Command Center, then we have the correct Tagpro API ID. Otherwise, it threw an error (and there were lots of errors)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/tiles.js, line 110 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsdSJ6gbYlUEvIWodqs:-KsefsUBY4k1CDzgKW27:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/091bc87019fb1e9c14eeca4a94a4cb466577f43e/src/tiles.js#L110)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Should this be a call to getTildId()? If not, I think you can just remove the getTileId function completely
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by billmwong** [comment]
:no_entry_sign: :dango: :lgtm_cancel: Waiting on david to make new one

---

Reviewed 2 of 6 files at r5, 6 of 6 files at r6.
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-:-KsqZS7RaITQvbiEYXcr:bf6cd7y)*

**Comment by billmwong** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-Ksq_AZ_1LLMBPlCaeWV:-Ksq_AZ_1LLMBPlCaeWW:b-4cure0) (no related file):*
:no_good: putting this in a new discussion so i can block on this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147#-KsvyY_TqFNhgFRtY6nn:-KsvyY_TqFNhgFRtY6no:bl19ksf) (no related file):*
Blocking myself here b/c I just pushed my update to 131. It's branched off of this and then rebased onto master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/147)*

**Comment by billmwong** [comment]
Closing this, we're going with #188 instead

**Pull request closed without merging**
