### PR TITLE
125: unittest answers inline

### LINKED ISSUE #125: In unit tests, put the answer inline instead of in a variable
for example

```
t.same(mockMapTraversabilityCells, [
  [0, 1, 0],
  [0, 1, 1],
  [1, 0, 0],
]);
```

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #125

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/150)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by billmwong** [comment]
Love it :fire: 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/convolve.spec.js, line 110 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-KsRafWmut5BKmAVIOpM:-KsRafWmut5BKmAVIOpN:b-38a9fm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3055b3304cf6c8df91706f75cca2aa8754ff8183/test/convolve.spec.js#L110)):*
> ```JavaScript
>     [2],
>   ];
>   /* eslint-enable no-multi-spaces, array-bracket-spacing */
> ```

Can you get rid of this? You shouldn't have to explicitly enable rules

---

*[test/convolve.spec.js, line 132 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-KsRakHoZ5WQBmBHlBic:-KsRakHoZ5WQBmBHlBid:b-2guby3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3055b3304cf6c8df91706f75cca2aa8754ff8183/test/convolve.spec.js#L132)):*
> ```JavaScript
>     [6, 7, 8],
>   ];
>   /* eslint-enable no-multi-spaces, array-bracket-spacing */
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-:-KsRapfWysXiIgZzMUW8:b-qxu27q)*

**Comment by davidabrahams** [comment]
Review status: 2 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/convolve.spec.js, line 110 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-KsRafWmut5BKmAVIOpM:-KsS8tZ4YYFVsqTnZs6g:bmjir7b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3055b3304cf6c8df91706f75cca2aa8754ff8183/test/convolve.spec.js#L110)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Can you get rid of this? You shouldn't have to explicitly enable rules
</blockquote></details>

Good catch. Those were leftovers from old code

---

*[test/convolve.spec.js, line 132 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-KsRakHoZ5WQBmBHlBic:-KsS9DAiwitPtj9B7lke:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3055b3304cf6c8df91706f75cca2aa8754ff8183/test/convolve.spec.js#L132)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by billmwong** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-Ks_cx6_9g-XiUIw0wel:-Ks_cx6_9g-XiUIw0wem:b-80z06a) (no related file):*
wrong commit tense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by shanek21** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-Ks_cx6_9g-XiUIw0wel:-Ks_diDmKe8p3m25S7YW:b-896fja) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

wrong commit tense
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150#-Ks_cx6_9g-XiUIw0wel:-Ks_gAcgC7ZWJu7IBtWN:bgc7vqv) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done!
</blockquote></details>

:heart: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by billmwong** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Comment by shanek21** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/150)*

**Pull request merged**
