### PR TITLE
388: Generate K-matrices and use them to move

### LINKED ISSUE #388: Generate K-matrix for 1000 time steps
Generate them in javascript

Use the same Ks as long as we're going towards the same goal, and just iterate over them

### LINKED ISSUE #389: Use K-matrix to move
ask shane for the equation

figure out acceleration that needs to be applied in either direction and feather appropriate keys

### PR DESCRIPTION
**Pull request by billmwong**
Closes #388
Closes #389 

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)

### CODE REVIEW

**Comment by billmwong** [comment]
*[src/control/lqr.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDxrupCUJ4HSD9sqDY:-LBE11en3vyFwptAZqzJ:bfje534) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L22)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I thought the K matrix applies to all timesteps? (ie, you use the same K matrix at each step). I'm probably confused on this. Can you explain?
</blockquote></details>

We thought that was true (when we thought about just using the placeholder K matrix), but it turns out to not work out so well in our situation.  We need a different K matrix for each time step

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/control/lqr.js, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDxrupCUJ4HSD9sqDY:-LBI4Emb3_2Q8IviBFjn:b-q4s91f) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L22)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

We thought that was true (when we thought about just using the placeholder K matrix), but it turns out to not work out so well in our situation.  We need a different K matrix for each time step
</blockquote></details>

interesting. could you explain why this is again? (either in person or via slack is probs cool)

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by billmwong** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/control/lqr.js, line 140 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDyNoUCT9v7uM7w8Oh:-LBI3ME80Cr9dqHzcWWK:bt531ez) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L140)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

you could just use our global/util `boundValue` function here, and then not do the below
</blockquote></details>

Oh dang didn't know about this! Done

---

*[src/control/class/Matrix.js, line 15 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDyZGD2UvtZq1QqVOG:-LBI3b9j2yMTr_9-KoCe:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/class/Matrix.js#L15)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

use _.isNumber to be consistent?
</blockquote></details>

Done.

---

*[src/control/class/Matrix.js, line 25 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDysC-AG2zp5MfaO02:-LBI3dy0CImdHxxKgozx:b9mvw0u) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/class/Matrix.js#L25)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

put the input index in the error message?

Also, a matrix is a 2d array, right? does this function `get` a row of the matrix?
</blockquote></details>

Done.

And yeah, this gets a row.  We use it to get a specific K matrix at a time, and also to get a specific cost at a time

---

*[src/control/class/Matrix.js, line 34 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDzBv88FY4Qf4JzAiY:-LBI50Wb3JV13i-TQSRe:bd8vr00) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/class/Matrix.js#L34)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

@param types on this func?
</blockquote></details>

Done, let me know if that makes sense

---

*[src/control/class/Matrix.js, line 49 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDzKZZ2Kh5WP2gcdp2:-LBI5rX8BFfPN-Jw3Xaj:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/class/Matrix.js#L49)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

@return doc on this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/control/class/Matrix.js, line 49 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDzKZZ2Kh5WP2gcdp2:-LBI8B5-2oBCZGVoxuJb:b-178r6i) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/class/Matrix.js#L49)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What if is 3D? could probably just test  and see

---

*[src/control/class/Matrix.js, line 8 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBI7s2hAs1HoyfGr2u2:-LBI7s2hAs1HoyfGr2u3:b-odcoq5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/class/Matrix.js#L8)):*
> ```JavaScript
> 
> /**
>  * A wrapper around 2D javascript arrays which supports matrix math operations
> ```

this can store 3-D arrays, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by billmwong** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/control/class/Matrix.js, line 49 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBDzKZZ2Kh5WP2gcdp2:-LBIBysU5kuxSEr8Uxqu:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/class/Matrix.js#L49)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

What if is 3D? could probably just test  and see
</blockquote></details>

Done.

---

*[src/control/class/Matrix.js, line 8 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBI7s2hAs1HoyfGr2u2:-LBIBzR63TD3DP9KoW2r:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/class/Matrix.js#L8)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

this can store 3-D arrays, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by shanek21** [comment]
Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBIBBfE8aVf48iR8HVo:-LBIBBfE8aVf48iR8HVp:bp2xrm2) (no related file):*
I don't really like commits that say `address comments`. Is there any way to distill or summarize what most of the changes were about? I always like the classic `cleanup and refactor` commit.

---

*[src/control/lqr.js, line 6 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBI6EE69wd7mJCc-m8e:-LBI6EE69wd7mJCc-m8f:b-ufbdr2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L6)):*
> ```JavaScript
> import { Matrix } from './class/Matrix';
> import { FPS, ACCEL, DAMPING_FACTOR } from './constants';
> ```

Add another newline here?

---

*[src/control/lqr.js, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBI4nq69ZHNZiSay6lE:-LBI4nq69ZHNZiSay6lF:b-jfy0e7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L41)):*
> ```JavaScript
>   // Cost at each time step
>   const Ps = new Matrix(math.zeros([T, Q.shape()[0], Q.shape()[1]]));
>   Ps.set(Ps.array.length - 1, F);
> ```

Thoughts on using `Matrix.shape()` anywhere that `Matrix.array.length` is used?

---

*[src/control/lqr.js, line 72 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBI7z8E3U4vfrNd9kCO:-LBI7z8E3U4vfrNd9kCP:b-1es7vw) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L72)):*
> ```JavaScript
>         ))
>         .add(Q);
>     Ps.set(t, cost);
> ```

FYI it's pretty cool seeing how powerful all this chaining is

---

*[src/control/lqr.js, line 99 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBI9QKY9OvG6hfqYkXK:-LBI9QKY9OvG6hfqYkXL:b-2b7mj8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L99)):*
> ```JavaScript
>     [0, 0, 1, dt], // y = y + (dy/dt * dt)
>     [0, 0, 0, 1 - (b * dt)], // dy/dt = dx/dt + (dy/dt * (-b * dt))
>   ]);
> ```

I just noticed that I made a comment mistake in `simulation/src/physics.py` that carried over to here. I also think the negative in the second and fourth lines of this matrix could be rearranged to better match the comments (again a thing I should have done in the simulation code). Sorry about that! This whole thing should read as follows:
```javascript
// Difference equations
  const A = new Matrix([
    [1, dt, 0, 0], // x = x + (dx/dt * dt)
    [0, 1 + (-b * dt), 0, 0], // dx/dt = dx/dt + (dx/dt * (-b * dt))
    [0, 0, 1, dt], // y = y + (dy/dt * dt)
    [0, 0, 0, 1 + (-b * dt)], // dy/dt = dy/dt + (dy/dt * (-b * dt))
]);
```
Any chance you could also make these changes in `simulation/src/physics.py`?

---

*[src/control/lqr.js, line 114 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBIAbMx0aWjDO4f2nD6:-LBIAbMx0aWjDO4f2nD7:b-mro23v) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L114)):*
> ```JavaScript
> 
>   currentKs = dlqr(A, B, Q, F, R, goalState, T);
>   currentTime = 1;
> ```

Is this the hard coded deadline stuff?

---

*[src/control/class/Matrix.js, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBIBb0tEMWZp6VstWdd:-LBIBb0tEMWZp6VstWde:bi94ngf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/class/Matrix.js#L36)):*
> ```JavaScript
>   /**
>    * @param {Matrix|Array} other - matrix to append to this matrix
>    * @param {0|1} axis - (optional) 0 to append matrix as a row, 1 to append matrix as a column
> ```

Is this the jsdocs convention for optional parameters?

---

*[src/control/test/lqr.spec.js, line 19 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICAt_8FD-Pm7ScuUJ:-LBICAt_8FD-Pm7ScuUK:b-uwk60b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/test/lqr.spec.js#L19)):*
> ```JavaScript
> 
>     const multipliers = getLQRAccelerationMultipliers(x0, goal, 5);
> ```

No newline here. https://github.com/chauncy-crib/tagprobot/wiki/Conventions#new-lines-2

---

*[src/control/test/lqr.spec.js, line 35 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICKyU4pXYBEm1TiG-:-LBICKyU4pXYBEm1TiG0:b-nf0qfe) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/test/lqr.spec.js#L35)):*
> ```JavaScript
>     RewireAPI.__Rewire__('currentTime', null);
>     RewireAPI.__Rewire__('dlqr', dlqrSpy);
> ```

No newline here

---

*[src/control/test/lqr.spec.js, line 57 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICNWKArGtjtYZX1f9:-LBICNWKArGtjtYZX1fA:b-nf0qfe) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/test/lqr.spec.js#L57)):*
> ```JavaScript
>     RewireAPI.__Rewire__('currentTime', null);
>     RewireAPI.__Rewire__('dlqr', dlqrSpy);
> ```

No newline here

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/control/class/Matrix.js, line 12 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICj0U3-0m23gzDxAW:-LBICj0U3-0m23gzDxAX:b-25n1et) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b46dd6b7c6bfeabb2a663ab4974aa0688ab3894d/src/control/class/Matrix.js#L12)):*
> ```JavaScript
> export class Matrix {
>   /**
>    * @param {number|number[]|number[][]|number[][][]} array - an array of arrays of numbers
> ```

FYI hahaha oh god

---

*[src/control/class/Matrix.js, line 55 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICuN86dyImsLJ4U9m:-LBICuN86dyImsLJ4U9n:boc10l6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b46dd6b7c6bfeabb2a663ab4974aa0688ab3894d/src/control/class/Matrix.js#L55)):*
> ```JavaScript
>   /**
>    * @returns {number[]} the number of rows, columns, and third-dimensions in the matrix according
>    *   to how many dimensions it has.  Takes the format [rows, columns, third-dimensions]
> ```

Does `depth`make sense to replace`third-dimensions`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by davidabrahams** [comment]
Reviewed 3 of 4 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/control/class/Matrix.js, line 55 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICuN86dyImsLJ4U9m:-LBII-je12fTHsZgq66G:bo8o1dr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b46dd6b7c6bfeabb2a663ab4974aa0688ab3894d/src/control/class/Matrix.js#L55)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmm "number of depths"?
</blockquote></details>

i like `the number of rows and columns, and depth, of the matrix`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by shanek21** [comment]
*[src/control/class/Matrix.js, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBIBb0tEMWZp6VstWdd:-LBIIBEj35avdousDEpB:bv91zkl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/class/Matrix.js#L36)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done, apparently not: http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values
</blockquote></details>

Oh, cool! From that link, it looks like you also indicate if it has a default value, so should be `[axis=0]`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by shanek21** [comment]
*[src/control/class/Matrix.js, line 55 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICuN86dyImsLJ4U9m:-LBIISezCu19v13bvBRi:bxfasig) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b46dd6b7c6bfeabb2a663ab4974aa0688ab3894d/src/control/class/Matrix.js#L55)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

i like `the number of rows and columns, and depth, of the matrix`?
</blockquote></details>

I think I agree with @davidabrahams 

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by shanek21** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/control/lqr.js, line 114 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBIAbMx0aWjDO4f2nD6:-LBIIgw0CGInU5q6cHzo:btn5jp1) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/e73abc6e5c6a78cf51a29d91b6e2c5dbecf4a2ea/src/control/lqr.js#L114)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

No, actually since we don't use the getLQRAccelerationMultipliers anywhere yet nothing is "hardcoded".  You just pass in the totalTime to that function.  (When I was testing it on the bot I used 5 seconds but that's not in this PR)
</blockquote></details>

Gotcha

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by billmwong** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/control/class/Matrix.js, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBIBb0tEMWZp6VstWdd:-LBIIsH6DSETviSJwmS7:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/50e4e34265b887df0cd0ce175e5457e8e0c31fc1/src/control/class/Matrix.js#L36)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Oh, cool! From that link, it looks like you also indicate if it has a default value, so should be `[axis=0]`.
</blockquote></details>

Done.

---

*[src/control/class/Matrix.js, line 55 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/416#-LBICuN86dyImsLJ4U9m:-LBIIs_Q6B0WvfnNQgFo:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/b46dd6b7c6bfeabb2a663ab4974aa0688ab3894d/src/control/class/Matrix.js#L55)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

I think I agree with @davidabrahams 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)*

**Pull request merged**
