### PR TITLE
457: cache internalMap, tilesToUpdate, tilesToUpdateValues

### LINKED ISSUE #457: Cache/load internalMap, tilesToUpdate, and tilesToUpdateValues
Will require changing the construction of unmergedGraph, mergedGraph, and dtGraph to used cached maps, rather than real map. Then dynamic updates should fix the objects.

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #457

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCHmdu_2lxDqhgX7uX0:-LCLlD63B5vKNu1xEKVz:b-lyplhp) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Don't review this PR yet. subsequent cache PRs don't work (the browser crashes), so I want to do some investigating before you guys spend time reviewing
</blockquote></details>

Review now

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/start.js, line 2 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLlZ-f9JDsLVCjyRtN:-LCLlZ-f9JDsLVCjyRtO:b15fgko) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L2)):*
> ```JavaScript
> import _ from 'lodash';
> import FileSaver from 'file-saver';
> ```

newline between package imports and file imports

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/start.js, line 168 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLmZ822QbQxf-jtXYf:-LCLmZ822QbQxf-jtXYg:bojg6wj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L168)):*
> ```JavaScript
>   updateCache();
>   const totalTime = secondsSince(stateTime);
>   console.debug(`Startup script time: ${totalTime}`);
> ```

make timeLog start at zero instead of doing this

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/start.js, line 64 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLmvs0-euqu_Qnie5e:-LCLmvs0-euqu_Qnie5f:bhwud6y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L64)):*
> ```JavaScript
> 
> 
> export function loadCache() {
> ```

move all these to a cache.js or something

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
*[src/start.js, line 52 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLn1FIEBzjzI1p6P4S:-LCLn1FIEBzjzI1p6P4T:blcnhgo) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L52)):*
> ```
> cached
> ```


---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/start.js, line 190 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLnyn73WuRPe9Tf2oZ:-LCLnyn73WuRPe9Tf2o_:b-4d99vn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/src/start.js#L190)):*
> ```JavaScript
> function setupSocketCallbacks() {
>   timeLog('Setting up socket callbacks...');
>   setupMapCallback(() => {
> ```

setupMapCallback -> onMapReady or something more descriptive?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/start.js, line 46 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLoOfl3MDGowH5DGQG:-LCLoOfl3MDGowH5DGQH:b7fkvkb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/src/start.js#L46)):*
> ```JavaScript
> 
> 
> function mapKey() {
> ```

getMapKey?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by davidabrahams** [comment]
*[src/start.js, line 52 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLn1FIEBzjzI1p6P4S:-LCLoYM18Q3vSIFKvL3r:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L52)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

> ```
> cached
> ```


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[cache.json, line 0 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLotoY6h-DphrFknZn:-LCLotoY6h-DphrFknZo:b-hgqu63) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/cache.json#L0)):*
move this json to cache folder too

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
Reviewed 4 of 11 files at r1, 6 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
*[src/start.js, line 168 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLmZ822QbQxf-jtXYf:-LCLpJ7qD9lPLB1kMftw:b9gopcq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L168)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

make timeLog start at zero instead of doing this
</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 5 of 11 files at r1, 7 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by davidabrahams** [comment]
*[src/start.js, line 168 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLmZ822QbQxf-jtXYf:-LCLpV8P0mImQetIsuFY:b-k73z76) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L168)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>


</blockquote></details>

thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/start.js, line 168 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLmZ822QbQxf-jtXYf:-LCLpTl19PTAXu0NQ6Ed:b6y1yv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L168)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>


</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/global/timing.js, line 15 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCM-JDVE8OMXz9IConM:-LCM-JDVE8OMXz9IConN:bqxo2ew) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69b7580ab9e5517b9276981712ef7013f965301e/src/global/timing.js#L15)):*
> ```JavaScript
> 
> 
> export function time() {
> ```

Thoughts on naming this `getTime()` or `getCurrTime()`? The way it is, I almost feel like `Date.now()` was more self-documenting.

---

*[src/global/timing.js, line 39 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCM-cPRD6nLyJcbJ_LP:-LCM-cPRD6nLyJcbJ_LQ:b-twuzld) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69b7580ab9e5517b9276981712ef7013f965301e/src/global/timing.js#L39)):*
> ```JavaScript
> export function timeLog(message, baseTime = startTime) {
>   console.debug(`${secondsSince(baseTime).toFixed(3)}: ${message}`);
>   resetStartTime();
> ```

If you reset `startTime` after every call to `timeLog`, then it is no longer the start time. I was imagining a new file-level variable called `lastTimeLogTime` or something, which you updated instead (thus, keeping `startTime` as the start time).

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/global/timing.js, line 15 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCM-JDVE8OMXz9IConM:-LCM1FWOALmBH5BxMjlX:b38lv9p) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69b7580ab9e5517b9276981712ef7013f965301e/src/global/timing.js#L15)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Thoughts on naming this `getTime()` or `getCurrTime()`? The way it is, I almost feel like `Date.now()` was more self-documenting.
</blockquote></details>

:open_mouth: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
Reviewed 1 of 6 files at r5.
Review status: 11 of 15 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 1 of 5 files at r4, 4 of 6 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by davidabrahams** [comment]
Review status: 11 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/start.js, line 2 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLlZ-f9JDsLVCjyRtN:-LCMC2dLCmmExsOcWiCk:bosommu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L2)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

newline between package imports and file imports
</blockquote></details>

Done. in all code in cache/

---

*[src/start.js, line 64 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLmvs0-euqu_Qnie5e:-LCMCHyu4fIHHStNARWa:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/0d1c78d60157ac57c39d93371097bb3bb110d69a/src/start.js#L64)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

move all these to a cache.js or something
</blockquote></details>

Done.

---

*[src/start.js, line 46 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLoOfl3MDGowH5DGQG:-LCMCE_A-Ei0QbEeAokQ:b3fk74n) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/src/start.js#L46)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

getMapKey?
</blockquote></details>

Done. in cache.js

---

*[src/start.js, line 132 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLr32o9rD6cSsplZFC:-LCMCP8n8kRdbZ5xvrpC:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/src/start.js#L132)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>


</blockquote></details>

Done.

---

*[src/start.js, line 162 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLqvMJDmkgddldtpIP:-LCMCUwI9XSzs2yxBDx5:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/src/start.js#L162)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Pass `timeLog` a second optional parameter, which defaults to `startTime`
</blockquote></details>

Done.

---

*[src/start.js, line 190 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLnyn73WuRPe9Tf2oZ:-LCMCdtL3YZtMP0C9SbW:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/src/start.js#L190)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

setupMapCallback -> onMapReady or something more descriptive?
</blockquote></details>

Done.

---

*[src/global/timing.js, line 15 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCM-JDVE8OMXz9IConM:-LCMCm7I0lj04hfscc_d:bw8t5nb) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69b7580ab9e5517b9276981712ef7013f965301e/src/global/timing.js#L15)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

:open_mouth: 
</blockquote></details>

I was copying this:

https://docs.python.org/2/library/time.html#time.time

---

*[src/global/timing.js, line 39 at r4](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCM-cPRD6nLyJcbJ_LP:-LCMDDTiExqWGzsBaEAM:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/69b7580ab9e5517b9276981712ef7013f965301e/src/global/timing.js#L39)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

If you reset `startTime` after every call to `timeLog`, then it is no longer the start time. I was imagining a new file-level variable called `lastTimeLogTime` or something, which you updated instead (thus, keeping `startTime` as the start time).
</blockquote></details>

Done.

---

*[cache.json, line  at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCLotoY6h-DphrFknZn:-LCMBoidBbNE_T5YL4E4:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/685c9aec8b9370382279b2a8cca795ff76e614ef/cache.json#L)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

move this json to cache folder too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
*[src/start.js, line 159 at r8](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCMGOBB1K0Y89mT5Dej:-LCMGOBB1K0Y89mT5Dek:b-31v1fl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/371c83e8c9857f79d69acdeee172a64a73ad30bf/src/start.js#L159)):*
> ```JavaScript
>  */
> tagpro.ready(() => {
>   setupSocketCallbacks();
> ```

now that this is one function, we could do `tagpro.ready(setupSocketCallbacks);` in one line, thoughts

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
Reviewed 1 of 5 files at r4, 1 of 6 files at r5, 2 of 3 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/cache/load.js, line 7 at r8](https://reviewable.io/reviews/chauncy-crib/tagprobot/461#-LCMGk-5DKYTQ4Ny2DUU:-LCMGk-5DKYTQ4Ny2DUV:b-emx4na) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/371c83e8c9857f79d69acdeee172a64a73ad30bf/src/cache/load.js#L7)):*
> ```JavaScript
> import { timeLog } from '../global/timing';
> 
> export function loadCache() {
> ```

FYI I'd put these all in cache.js

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 2 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/461)*

**Pull request merged**
