### PR TITLE
403: time stamped logs of the startup sequence

### LINKED ISSUE #403: Console log the time each startup algorithm takes

### PR DESCRIPTION
**Pull request by shanek21**
Closes #403

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2ucxo3mA0--VZUYPb:-LB2ucxp4C4raDv1rNH4:bvbiu84) (no related file):*
Can you fixup all your commits into one? This PR is pretty small

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by shanek21** [comment]
*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2ucxo3mA0--VZUYPb:-LB2ukBT0C9_yN05Rb18:bgakfpr) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Can you fixup all your commits into one? This PR is pretty small
</blockquote></details>

but then I'll forget that billo made me capitalize all the time logs ;(

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2ucxo3mA0--VZUYPb:-LB2ur6E0wfeZZzi9gCl:b-tdj627) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

but then I'll forget that billo made me capitalize all the time logs ;(
</blockquote></details>

I hate this project

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by shanek21** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2ucxo3mA0--VZUYPb:-LB2uuRw6skkM1d0GKJa:b-cf3obm) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I hate this project
</blockquote></details>

Repo deleted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by billmwong** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/global/utils.js, line 97 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2uge03zrHPDjpvmvN:-LB2uge03zrHPDjpvmvO:b79eh2e) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4ee9619cbae53fb75d99119bf489e0768d53c25d/src/global/utils.js#L97)):*
> ```JavaScript
>  */
> function secondsSinceStart() {
>   return secondsSince(startTime);
> ```

FYI kinda weird that you made two helper functions here and 17 more lines to do some subtraction

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2ucxo3mA0--VZUYPb:-LB2vd-VCB8k6OtVBclp:b-896fix) (no related file):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Repo deleted.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/global/utils.js, line 97 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2uge03zrHPDjpvmvN:-LB2viI12Y-NcKGrpOoO:bsc18zq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4ee9619cbae53fb75d99119bf489e0768d53c25d/src/global/utils.js#L97)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

FYI kinda weird that you made two helper functions here and 17 more lines to do some subtraction
</blockquote></details>

Yeah I debated how many helper functions to draw this out into.... I felt like `secondsSince()` was more generally useful, which is why I kept it around instead of moving that functionality into `secondsSinceStart()`. Want me to do that?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by billmwong** [comment]
*[src/global/utils.js, line 97 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2uge03zrHPDjpvmvN:-LB2wXbIB_oxap9IfVBd:b-rz89so) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4ee9619cbae53fb75d99119bf489e0768d53c25d/src/global/utils.js#L97)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yeah I debated how many helper functions to draw this out into.... I felt like `secondsSince()` was more generally useful, which is why I kept it around instead of moving that functionality into `secondsSinceStart()`. Want me to do that?
</blockquote></details>

That's true, could be a useful function.  I'd rather delete `secondsSinceStart` and just call `secondsSince(startTime)` in the timeLog function

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by shanek21** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/global/utils.js, line 97 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/415#-LB2uge03zrHPDjpvmvN:-LB2x1p4AWbWZDKjEMGq:bund9tt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4ee9619cbae53fb75d99119bf489e0768d53c25d/src/global/utils.js#L97)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

That's true, could be a useful function.  I'd rather delete `secondsSinceStart` and just call `secondsSince(startTime)` in the timeLog function
</blockquote></details>

I agree with you. Changed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)*

**Pull request merged**
