### PR TITLE
326: update npm packages

### LINKED ISSUE #326: Update npm packages
Looks like fibonacci heap needs to be version 2.0.7: https://david-dm.org/chauncy-crib/tagprobot

To get rid of our "out-of-date" badge on our repo

Also looks like there's security vulnerability in uglify, update that too

### PR DESCRIPTION
**Pull request by shanek21**
Closes #326

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/433)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/433)*

**Comment by davidabrahams** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 43 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/433#-LC0GcycCUF_asnSxS05:-LC0GcycCUF_asnSxS06:b-f1krz2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/25965bd9139eb835130f6250caf463ff8432e6bc/package.json#L43)):*
> ```JSON
>     "tap-webpack-plugin": "^2.0.0",
>     "tape": "^4.7.0",
>     "webpack": "^4.8.1",
> ```

FYI just checking we still need webpack if we also have webpackcli. Just acknowledge this away if the answer is yes

---

*[webpack.config.js, line 12 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/433#-LC0Gnx07eP1sIbuexd3:-LC0Gnx07eP1sIbuexd4:b-7zthap) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/25965bd9139eb835130f6250caf463ff8432e6bc/webpack.config.js#L12)):*
> ```JavaScript
>       path: path.resolve(__dirname, 'public')
>     },
>     mode: 'development',
> ```

Should we have separate dev and prod build scripts?

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/433)*

**Comment by billmwong** [comment]
*[package.json, line 43 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/433#-LC0GcycCUF_asnSxS05:-LC0IWuL7Z4Fmz_uR6CL:bczzh05) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/25965bd9139eb835130f6250caf463ff8432e6bc/package.json#L43)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI just checking we still need webpack if we also have webpackcli. Just acknowledge this away if the answer is yes
</blockquote></details>

Yeah we do

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/433)*

**Comment by billmwong** [comment]
*[webpack.config.js, line 12 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot/433#-LC0Gnx07eP1sIbuexd3:-LC0I_BV8gwUjqSDGab4:bnmfr92) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/25965bd9139eb835130f6250caf463ff8432e6bc/webpack.config.js#L12)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Should we have separate dev and prod build scripts?
</blockquote></details>

It's possible that our bot could fun faster with a minimized prod bundle.  I made #435, could be useful for expo

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/433)*

**Pull request merged**
