### PR TITLE
428: go to alternate goal if current path cost is too high

### LINKED ISSUE #428: Choose different goal if cost is too high to cap
Determine a maximum cost we're willing to pay to cap, and if the cost is too high (i.e. there are too many enemies in the right locations) then choose another location to go to

### PR DESCRIPTION
**Pull request by shanek21**
Closes #428

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/plan/astar.js, line 111 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/478#-LCMy74ODxQz0q3-6ESj:-LCMy74P6pfidZG3nABi:b34uqgs) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/13524b085487983747648d7cd2817493a0c6270d/src/plan/astar.js#L111)):*
> ```JavaScript
>   const targetPositionState = new PolypointState(new Polypoint(target.x, target.y, endTriangle));
>   const fullPath = [initialPositionState].concat(_.slice(path, 1, -1)).concat(targetPositionState);
>   return { shortestPath: fullPath, pathCost: path[path.length - 1].g };
> ```

FYI _.last here

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/plan/astar.js, line 111 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot/478#-LCMy74ODxQz0q3-6ESj:-LCN-I57-sNT40yC-G2t:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/13524b085487983747648d7cd2817493a0c6270d/src/plan/astar.js#L111)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI _.last here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)*

**Comment by davidabrahams** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)*

**Pull request merged**
