### PR TITLE
290: Have dedicated buttons to toggle each kind of visualization, and print commands to team-chat.

### LINKED ISSUE #290: Have dedicated buttons to toggle each kind of visualization, and print commands to team-chat.

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #290

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/317)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 6 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 273 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mObJOpBFFj_KEoJMX:-L0mObJOpBFFj_KEoJMY:bcsphfa) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L273)):*
> ```JavaScript
> export function toggleKeyPressVis(setTo) {
>   if (setTo === keyPressOn) return;
>   if (setTo !== undefined) keyPressOn = setTo;
> ```

can you explain the whole setTo function logic for this and those other functions too, is it ever undefined?

---

*[src/draw/drawings.js, line 488 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPmMT1GX_0OPBA4tS:-L0mPmMT1GX_0OPBA4tT:b-ngiqb6) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L488)):*
> ```JavaScript
>  */
> export function clearSprites() {
>   // TODO(davidabrahams): what is the difference between removeChildren and clear?
> ```

did you find this out? This comment is also in shane's PR for some reason

---

*[src/helpers/map.js, line 196 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPyxacWSmMHh5ZXlL:-L0mPyxbbvB8mN33qz9j:bm5tx03) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/helpers/map.js#L196)):*
> ```JavaScript
> //   getDTGraph().calculatePolypointGraph();
> //   drawNavMesh();
> // }
> ```

what are all these comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/draw/drawings.js, line 273 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mObJOpBFFj_KEoJMX:-L0n9WHpYfx2Mh3JGH6U:b-nvixj7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L273)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can you explain the whole setTo function logic for this and those other functions too, is it ever undefined?
</blockquote></details>

Yep. If you call these functions without an input, then it toggles the visual (if its on, it turns off). If you call it with a `setTo` param, it makes sure the visuals match `setTo`. Ie, if they're on, and `setTo` is true, nothing happens (see the first line of the function). Sometimes all we want to do is toggle (when a user presses a key for the visual), sometimes we want to force the state (when we turn visual mode on/off, we need to set everything on/off)

---

*[src/draw/drawings.js, line 488 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPmMT1GX_0OPBA4tS:-L0n9tZRVoiB5YNnWfPf:bz4sr8m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L488)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

did you find this out? This comment is also in shane's PR for some reason
</blockquote></details>

Yeah I left it behind in his PR, and then rebased this code off of that.

---

*[src/helpers/map.js, line 196 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPyxacWSmMHh5ZXlL:-L0nA-xc_tGmgohQflYk:bw425ge) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/helpers/map.js#L196)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what are all these comments
</blockquote></details>

For expo I just completely disabled all the dynamic update code just in case it had bugs. I guess 206 won't get merged until its well tested, so I'll add it back in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 273 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mObJOpBFFj_KEoJMX:-L0pgB2-OgTpxIBmblz8:b-3emenk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L273)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Yep. If you call these functions without an input, then it toggles the visual (if its on, it turns off). If you call it with a `setTo` param, it makes sure the visuals match `setTo`. Ie, if they're on, and `setTo` is true, nothing happens (see the first line of the function). Sometimes all we want to do is toggle (when a user presses a key for the visual), sometimes we want to force the state (when we turn visual mode on/off, we need to set everything on/off)
</blockquote></details>

Hmmm after reading [this](https://stackoverflow.com/questions/456177/function-overloading-in-javascript-best-practices) there doesn't seem to be a consensus on how to overload functions.  Since we're just doing two possible overloads, what do you think about using default parameter syntax and saying `toggleKeyPressVis(setTo = !keyPressOn) {}` Then you don't need the undefined check.

Seems similar to this rule: https://github.com/airbnb/javascript/#es6-default-parameters

---

*[src/draw/drawings.js, line 488 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPmMT1GX_0OPBA4tS:-L0phFFJINlE3Q0EaJiP:b8zyy53) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L488)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Yeah I left it behind in his PR, and then rebased this code off of that.
</blockquote></details>

Okay well because you added a bunch of stuff here, git thinks you deleted the previous clearSprites() and wrote your own new one, so when this get resolved in shane's PR you'll have to remember to delete it here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/draw/drawings.js, line 273 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mObJOpBFFj_KEoJMX:-L0pjUzbQpf944gkYgyP:b-ea0dz0) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L273)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmmm after reading [this](https://stackoverflow.com/questions/456177/function-overloading-in-javascript-best-practices) there doesn't seem to be a consensus on how to overload functions.  Since we're just doing two possible overloads, what do you think about using default parameter syntax and saying `toggleKeyPressVis(setTo = !keyPressOn) {}` Then you don't need the undefined check.

Seems similar to this rule: https://github.com/airbnb/javascript/#es6-default-parameters
</blockquote></details>

Ah. didn't realize I could do that. Done.

---

*[src/draw/drawings.js, line 488 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPmMT1GX_0OPBA4tS:-L0pkv7t-yG2dnRFF-kM:b-7hsbgh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L488)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Okay well because you added a bunch of stuff here, git thinks you deleted the previous clearSprites() and wrote your own new one, so when this get resolved in shane's PR you'll have to remember to delete it here
</blockquote></details>

okiedokie

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by shanek21** [comment]
Reviewed 1 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by shanek21** [comment]
Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by billmwong** [comment]
*[src/draw/drawings.js, line 488 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPmMT1GX_0OPBA4tS:-L2DgSwOr4FdyaEu1AMl:b-g1qppi) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L488)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

okiedokie
</blockquote></details>

I think this is resolved once you rebase

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by davidabrahams** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/draw/drawings.js, line 488 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317#-L0mPmMT1GX_0OPBA4tS:-L2EwLgeybMpZMVtzMOm:b-elbe7k) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a17ad70d8daf46ce022440b3fa83040b8adb3bd6/src/draw/drawings.js#L488)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I think this is resolved once you rebase
</blockquote></details>

Done! :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r4.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Comment by shanek21** [comment]
Reviewed 3 of 3 files at r4.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/317)*

**Pull request merged**
