### PR TITLE
251: Convert Triangulation Graph class to polypoints

### LINKED ISSUE #251: Convert Triangulation Graph class to polypoints
To be used in A*

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #251

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/259)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 7 of 7 files at r1.
Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIcWChHfnbst5Vtot1:-KyIcWChHfnbst5Vtot2:b3z388r) (no related file):*
can i get a screenshot

---

*[src/draw/drawings.js, line 366 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIcvhemasqCVa50Sya:-KyIcvhemasqCVa50Syb:b1fqot3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/draw/drawings.js#L366)):*
> ```JavaScript
>     return;
>   }
>   assert(_.isNil(triangulationSprite), 'graphSprite is not null');
> ```

graphSprite -> triangulationSprite

---

*[src/draw/drawings.js, line 369 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyId39ShxKefQyr6tRZ:-KyId39ShxKefQyr6tR_:bps1s89) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/draw/drawings.js#L369)):*
> ```JavaScript
>   triangulationSprite = drawGraph(
>     getDTGraph(),
>     NAV_MESH_THICKNESS, NAV_MESH_EDGE_COLOR, NAV_MESH_VERTEX_COLOR, NAV_MESH_ALPHA,
> ```

here too

---

*[src/draw/drawings.js, line 375 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyId7By68Waip1PN948:-KyId7By68Waip1PN949:b5765bx) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/draw/drawings.js#L375)):*
> ```JavaScript
>     getDTGraph().polypoints,
>     TRIANGULATION_THICKNESS, TRIANGULATION_EDGE_COLOR, null,
>     TRIANGULATION_ALPHA, false,
> ```

what is this poop, put each param on its own line

---

*[src/navmesh/graph.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfeChik51_dk6PRqr:-KyIfeChik51_dk6PRqs:b9tf6dk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L245)):*
> ```JavaScript
>   calculatePolypointGraph() {
>     this.triangles.forEach(triangle => {
>       // for adding a polypoint in center of triangle
> ```

capitalize pls

---

*[src/navmesh/graph.js, line 249 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfdBtljoM6YfDGlIL:-KyIfdBtljoM6YfDGlIM:b9tf6dk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L249)):*
> ```JavaScript
>       this.polypoints.addVertex(triangleCenter);
>       const edgeCenters = triangle.getEdgeCenters();
>       // connect edge centers to triangle center
> ```

capitalize pls

---

*[src/navmesh/graph.js, line 254 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfg1md1gpJencGWRZ:-KyIfg1md1gpJencGWR_:b9tf6dk) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L254)):*
> ```JavaScript
>         this.polypoints.addEdge(ep, triangleCenter);
>       });
>       // connect all edge centers to eachother
> ```

capitalize pls

---

*[src/navmesh/graph.js, line 257 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIeClcib51xOxcsSv8:-KyIeCldQ-KMwpOcL76N:b22bq78) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L257)):*
> ```JavaScript
>       // this.polypoints.addEdge(edgeCenters[0], edgeCenters[1]);
>       // this.polypoints.addEdge(edgeCenters[0], edgeCenters[2]);
>       // this.polypoints.addEdge(edgeCenters[1], edgeCenters[2]);
> ```

do we need this or no

---

*[src/navmesh/triangulation.js, line 47 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIevwdkRNvRVVZLI81:-KyIevwdkRNvRVVZLI82:bi65h8j) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/triangulation.js#L47)):*
> ```JavaScript
>   DTGraph.removeVertexAndTriangles(dummyPoint2);
>   DTGraph.calculatePolypointGraph();
>   return shuffledVertices;
> ```

uhhh this shouldn't really return anything right?  I believe shane and I were using the return to test things, but this shouldn't be in production.  That was our fault but can you remove it here

---

*[test/navmesh/graph.spec.js, line 7 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfDevk-Hev9hpym8x:-KyIfDevk-Hev9hpym8y:b-rpmpn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/graph.spec.js#L7)):*
> ```JavaScript
>   getDTGraph,
>   __RewireAPI__ as TriangulationRewireAPI,
> } from '../../src/navmesh/triangulation';
> ```

the diff is saying you imported these things and then never changed anything else?

---

*[test/navmesh/triangulation.spec.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfVEHAG3rzUI9UX8m:-KyIfVEHAG3rzUI9UX8n:b-mmie1a) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/triangulation.spec.js#L50)):*
> ```JavaScript
>     t.is(DTGraph.triangles.size, 2);
>     t.is(DTGraph.polypoints.getVertices().length, 7);
>     t.is(DTGraph.polypoints.getEdges().length, 6);
> ```

could you test if the correct connections exist for the polypoints too? or is that an absurd number of lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIcWChHfnbst5Vtot1:-KyIi_kDTgWQrrzeKaok:bb6un1j) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can i get a screenshot
</blockquote></details>

Done

---

*[src/draw/drawings.js, line 366 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIcvhemasqCVa50Sya:-KyIgBGUH9g-NJi1BrLq:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/draw/drawings.js#L366)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

graphSprite -> triangulationSprite
</blockquote></details>

Done.

---

*[src/draw/drawings.js, line 369 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyId39ShxKefQyr6tRZ:-KyIgBfhlaFHVRfeEQCN:b2nifjl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/draw/drawings.js#L369)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

here too
</blockquote></details>

wut

---

*[src/draw/drawings.js, line 375 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyId7By68Waip1PN948:-KyIg3h8IAtxM82dZ2DY:bykqjql) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/draw/drawings.js#L375)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what is this poop, put each param on its own line
</blockquote></details>

Done. Was copying syntax from code that was above lol

---

*[src/navmesh/graph.js, line 245 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfeChik51_dk6PRqr:-KyIieOMgFY_MI8UaUyZ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L245)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

capitalize pls
</blockquote></details>

Done.

---

*[src/navmesh/graph.js, line 249 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfdBtljoM6YfDGlIL:-KyIiefIQgf1KjBtwRlh:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L249)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

capitalize pls
</blockquote></details>

Done.

---

*[src/navmesh/graph.js, line 254 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfg1md1gpJencGWRZ:-KyIgRM3mriLNRXxN4E4:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L254)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

capitalize pls
</blockquote></details>

Done.

---

*[src/navmesh/graph.js, line 257 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIeClcib51xOxcsSv8:-KyIgRbfWEkiC0cWElvz:bug4d9m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L257)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

do we need this or no
</blockquote></details>

Not sure, depends how we want to connect polypoints. Figured I'd leave it here so it was easy to change in the future.

---

*[src/navmesh/triangulation.js, line 47 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIevwdkRNvRVVZLI81:-KyIgdgBJDOYo4IFEmIO:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/triangulation.js#L47)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

uhhh this shouldn't really return anything right?  I believe shane and I were using the return to test things, but this shouldn't be in production.  That was our fault but can you remove it here
</blockquote></details>

Done.

---

*[test/navmesh/triangulation.spec.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfVEHAG3rzUI9UX8m:-KyIgq5vhCeAYLGIiCtG:bl1poz3) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/triangulation.spec.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

could you test if the correct connections exist for the polypoints too? or is that an absurd number of lines
</blockquote></details>

Sorta. The vertices are at decimal locations, so the tests would get gross. Here's where the vertices are:

```
    [ Point { x: 13, y: 10.666666666666666 },
      Point { x: 10, y: 8 },
      Point { x: 9.5, y: 12 },
      Point { x: 19.5, y: 12 },
      Point { x: 13, y: 5.333333333333333 },
      Point { x: 9.5, y: 4 },
      Point { x: 19.5, y: 4 } ]

```

You'd have to do something like `isConnected(x, y)` where x and y are values from the vertices.

LMK what you think

---

*[test/navmesh/graph.spec.js, line 7 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfDevk-Hev9hpym8x:-KyIgmA-esIvAssiebaj:b-ns021w) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/graph.spec.js#L7)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

the diff is saying you imported these things and then never changed anything else?
</blockquote></details>

Done. Oops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by billmwong** [comment]
Reviewed 4 of 4 files at r2.
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIcWChHfnbst5Vtot1:-KyIjab4nGGgqeoumAyF:b-qywgnf) (no related file):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Done
</blockquote></details>

OK sweet looks dank

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by billmwong** [comment]
*[test/navmesh/triangulation.spec.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfVEHAG3rzUI9UX8m:-KyIlstNCy9lCn8eYa8o:bha9kvh) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/triangulation.spec.js#L50)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Sorta. The vertices are at decimal locations, so the tests would get gross. Here's where the vertices are:

```
    [ Point { x: 13, y: 10.666666666666666 },
      Point { x: 10, y: 8 },
      Point { x: 9.5, y: 12 },
      Point { x: 19.5, y: 12 },
      Point { x: 13, y: 5.333333333333333 },
      Point { x: 9.5, y: 4 },
      Point { x: 19.5, y: 4 } ]

```

You'd have to do something like `isConnected(x, y)` where x and y are values from the vertices.

LMK what you think
</blockquote></details>

What do you think of testing the polypoints in a separate test with simpler and fewer points?  Would that make it palpable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by davidabrahams** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/navmesh/triangulation.spec.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfVEHAG3rzUI9UX8m:-KyIn0rTLeCps_NAyH9b:b5oiiw4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/triangulation.spec.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

What do you think of testing the polypoints in a separate test with simpler and fewer points?  Would that make it palpable
</blockquote></details>

It'd basically be impossible to avoid the decimal point locations. I think if we're going to test connectedness, we might as well do it here. thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by billmwong** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/navmesh/triangulation.spec.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfVEHAG3rzUI9UX8m:-KyInmuSzvZojumBtrQW:b-ifyx4y) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/triangulation.spec.js#L50)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

It'd basically be impossible to avoid the decimal point locations. I think if we're going to test connectedness, we might as well do it here. thoughts?
</blockquote></details>

make a new test with a square to avoid decimal points as discussed offline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by billmwong** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graph.js, line 257 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIeClcib51xOxcsSv8:-KyIqcHhFSh896kWCQsW:bysidx7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L257)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Not sure, depends how we want to connect polypoints. Figured I'd leave it here so it was easy to change in the future.
</blockquote></details>

Connect the edge centers and the triangle centers as discussed offline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by shanek21** [comment]
Reviewed 2 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graph.js, line 257 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIeClcib51xOxcsSv8:-KyOYrqsfcqODsxRjdcx:bbgs7qu) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L257)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Connect the edge centers and the triangle centers as discussed offline
</blockquote></details>

Nice! The commented-out code seems weird but for our special case here I think I can allow it.  Can I get a second screenshot with just the triangle centers connected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by davidabrahams** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/navmesh/graph.js, line 257 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIeClcib51xOxcsSv8:-KyOnFZ9wMeR59OWFZI_:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/src/navmesh/graph.js#L257)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Nice! The commented-out code seems weird but for our special case here I think I can allow it.  Can I get a second screenshot with just the triangle centers connected?
</blockquote></details>

Done.

---

*[test/navmesh/triangulation.spec.js, line 50 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyIfVEHAG3rzUI9UX8m:-KyOmafyXLVQdLAQZfHy:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/37204e0b8566cb6d5de23b440fa19f59f927bacc/test/navmesh/triangulation.spec.js#L50)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

make a new test with a square to avoid decimal points as discussed offline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by billmwong** [comment]
Reviewed 2 of 2 files at r5.
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyPnVCNEO_xviI8RqsW:-KyPnVCNEO_xviI8RqsX:b-cfip4d) (no related file):*
PR title same as issue title pls

---

*[src/navmesh/graph.js, line 130 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyPoXgvoomz5-K7iANc:-KyPoXgvoomz5-K7iANd:b-d61na2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4298ad8eeebe1cdb0fc554dade0cded051577785/src/navmesh/graph.js#L130)):*
> ```JavaScript
> 
>   removeVertex(vertex) {
>     // clear all edges attached to the vertex
> ```

why are we doing this now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by davidabrahams** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyPnVCNEO_xviI8RqsW:-KyR3gKY5RuSTiP9F8Ts:bb6un1j) (no related file):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

PR title same as issue title pls
</blockquote></details>

Done

---

*[src/navmesh/graph.js, line 130 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyPoXgvoomz5-K7iANc:-KyR3RXAosGYcBGqHM5l:b-3r7cu7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4298ad8eeebe1cdb0fc554dade0cded051577785/src/navmesh/graph.js#L130)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why are we doing this now
</blockquote></details>

I realized there was no reason not to before haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by shanek21** [comment]
Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 10 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyWikd_EmGanizpTNRj:-KyWikd_EmGanizpTNRk:b-2vpmtl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4298ad8eeebe1cdb0fc554dade0cded051577785/package.json#L10)):*
> ```JSON
>     "lint:fix": "eslint 'src/**/*.js' 'test/**/*.js' --fix",
>     "test": "babel-tape-runner \"test/**/*.js\" | tap-difflet --pessimistic",
>     "test:o": "babel-tape-runner \"test/**/*.js\" | tap-difflet",
> ```

what dis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 10 at r5](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259#-KyWikd_EmGanizpTNRj:-KyZ8wo5Qkuk4A-i7IoA:b-a5fnvl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/4298ad8eeebe1cdb0fc554dade0cded051577785/package.json#L10)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

what dis
</blockquote></details>

Added a "test optimistic" script. Running it with pessimistic only shows failing tests. Sometimes, I want to see all tests. Also, if an assertionError happens in a test, the console.log statements don't appear when you use pessimistic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/259)*

**Pull request merged**
