### PR TITLE
328: improve runtime of Graph class

### LINKED ISSUE #328: Improve Graph and TGraph Runtimes
Looks at some methods that are linear that can be easily made constant by using hashmaps

### PR DESCRIPTION
**Pull request by davidabrahams**
closes #328

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/352)

### CODE REVIEW

**Comment by billmwong** [comment]
Reviewed 1 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Comment by billmwong** [comment]
Reviewed 5 of 6 files at r1.
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/interpret/utils.js, line 201 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EcBr1aCnmXn2442Y_:-L6EcBr1aCnmXn2442Ya:b-opnv60) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/utils.js#L201)):*
> ```JavaScript
>  *   have the same x coordinate
>  */
> export function slope(p1, p2) {
> ```

can this be a class method

---

*[src/interpret/utils.js, line 215 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EcDSlrppNwLEd0wCS:-L6EcDSlrppNwLEd0wCT:b-opnv60) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/utils.js#L215)):*
> ```JavaScript
>  *   an x-coordinate. In this case, return their x-coordinate
>  */
> export function intercept(p1, p2) {
> ```

can this be a class method

---

*[src/interpret/class/Graph.js, line 160 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EdzDBPzpVk1AC31Xw:-L6EdzDCIQ2hSngx1Wjo:bsbqwct) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Graph.js#L160)):*
> ```JavaScript
>     _.forEach(this.getVertices(), p1 => {
>       _.forEach(this.adj[p1], p2 => {
>         // create new Point objects, because if the points are Polypoints, their toString method
> ```

capitalize first word of comment

---

*[src/interpret/class/Graph.js, line 161 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EenMo-ZTFS9qwCYdl:-L6EenMo-ZTFS9qwCYdm:b6l8oac) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Graph.js#L161)):*
> ```JavaScript
>       _.forEach(this.adj[p1], p2 => {
>         // create new Point objects, because if the points are Polypoints, their toString method
>         // includes the containing triangle.
> ```

Is this true? The Polypoint class does not modify the toString() method, so it only uses the x and y

---

*[src/interpret/class/Point.js, line 54 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6Ee7_HXJq_jyknkKYK:-L6Ee7_HXJq_jyknkKYL:b-ig2ihd) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Point.js#L54)):*
> ```JavaScript
> 
>   toString() {
>     return JSON.stringify({ x: this.x, y: this.y });
> ```

why did you change this

---

*[src/interpret/class/Point.js, line 67 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EfUbf4mtIurIDlmUu:-L6EfUbf4mtIurIDlmUv:bata5hj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Point.js#L67)):*
> ```JavaScript
>    * @returns {Point} a new Point object
>    */
>   static fromString(s) {
> ```

What are static methods generally?

---

*[src/interpret/test/graph.spec.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EeH3L6KhpmJ09PAtk:-L6EeH3L6KhpmJ09PAtl:b9wfddf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/test/graph.spec.js#L1)):*
> ```JavaScript
> import test from 'tape';
> ```

capitalize this file name to reflect the Graph class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/interpret/utils.js, line 201 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EcBr1aCnmXn2442Y_:-L6FmA7mlz-0GzLRTXRx:bm5wrci) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/utils.js#L201)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can this be a class method
</blockquote></details>

yes, but it seems like it should be a class method for the Edge class. @shanek21 can you do this in your PR?

---

*[src/interpret/utils.js, line 215 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EcDSlrppNwLEd0wCS:-L6FmFmD3a5SujTSryxx:b2nrehn) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/utils.js#L215)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

can this be a class method
</blockquote></details>

Same as above?

---

*[src/interpret/class/Graph.js, line 160 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EdzDBPzpVk1AC31Xw:-L6FmfeNnCEffdcG3W9c:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Graph.js#L160)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

capitalize first word of comment
</blockquote></details>

Done.

---

*[src/interpret/class/Graph.js, line 161 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EenMo-ZTFS9qwCYdl:-L6Fmfq42iMZqtC722an:b-vrd9m7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Graph.js#L161)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Is this true? The Polypoint class does not modify the toString() method, so it only uses the x and y
</blockquote></details>

Hm. Good point. I swear when debugging I was seeing the string representation of a triangle show up. I will have to investigate.

---

*[src/interpret/class/Point.js, line 54 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6Ee7_HXJq_jyknkKYK:-L6FmklxG1MdyGj45Jp7:b-pudk3q) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Point.js#L54)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

why did you change this
</blockquote></details>

So that we can do fromString() and have it take in this format

---

*[src/interpret/class/Point.js, line 67 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EfUbf4mtIurIDlmUu:-L6FmoZZFcbnx6DNGCwk:b-n7i1kl) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Point.js#L67)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

What are static methods generally?
</blockquote></details>

It belongs to the class, not an instance of the class. so, in this case, you would do `Point.fromString(someString)` to get a point from a string. Its a way to make a function a class method when it doesnt make sense for you to need an actual object of that class to call it.

---

*[src/interpret/test/graph.spec.js, line 1 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EeH3L6KhpmJ09PAtk:-L6FnNX4hR1Nm-GUl5pU:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/test/graph.spec.js#L1)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

capitalize this file name to reflect the Graph class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Comment by davidabrahams** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/interpret/class/Graph.js, line 161 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EenMo-ZTFS9qwCYdl:-L6FnS3cAt8_FqZcgOTI:b-k8aaly) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Graph.js#L161)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Hm. Good point. I swear when debugging I was seeing the string representation of a triangle show up. I will have to investigate.
</blockquote></details>

Setting myself to blocking until I figure out why I did this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Comment by billmwong** [comment]
Reviewed 3 of 3 files at r2.
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Comment by shanek21** [comment]
Reviewed 4 of 7 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 201 at r1](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/352#-L6EcBr1aCnmXn2442Y_:-L6N2aES4-MFMknrVBCy:bb77u1k) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/utils.js#L201)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

yes, but it seems like it should be a class method for the Edge class. @shanek21 can you do this in your PR?
</blockquote></details>

Yeah

---

*[src/interpret/class/Graph.js, line 141 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/352#-L6NjaK-95nLgTOPJl_s:-L6NjaK-95nLgTOPJl_t:b-eo939) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/Graph.js#L141)):*
> ```JavaScript
> 
>   /**
>    * @param {Graph} graph
> ```

remove graph as a parameter in docs

---

*[src/interpret/class/Graph.js, line 161 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/352#-L6N2z17CKrCX9aB_GqZ:-L6N2z17CKrCX9aB_Gq_:bd86eqt) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/Graph.js#L161)):*
> ```JavaScript
>       _.forEach(this.adj[p1], p2 => {
>         // Create new Point objects, because if the points are Polypoints, their toString method
>         // includes the containing triangle.
> ```

indent second line of comment

---

*[src/interpret/class/Point.js, line 54 at r2](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/352#-L6NZPfqEqkhyT_0hdaS:-L6NZPfr6Yuin5-lKW5H:b1nhwyq) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/Point.js#L54)):*
> ```JavaScript
> 
>   toString() {
>     return JSON.stringify({ x: this.x, y: this.y });
> ```

Can you explain the difference between this and how it was before?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/352)*

**Comment by davidabrahams** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/interpret/utils.js, line 201 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EcBr1aCnmXn2442Y_:-L6YTPyxLiM_JrJoreYN:b-r9cm46) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/utils.js#L201)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Yeah
</blockquote></details>

Your disposition is notok

---

*[src/interpret/class/Graph.js, line 161 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6EenMo-ZTFS9qwCYdl:-L6FnVwuFC48ifrcMI9h:b-xbx78a) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/3ff7ec1947fa0f0a74e5507d09622bbdf5ba6c2a/src/interpret/class/Graph.js#L161)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Setting myself to blocking until I figure out why I did this
</blockquote></details>

resolvedish by reverting code?

---

*[src/interpret/class/Graph.js, line 141 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6NjaK-95nLgTOPJl_s:-L6YTNzbshxLPvLOmn3n:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/Graph.js#L141)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

remove graph as a parameter in docs
</blockquote></details>

Done.

---

*[src/interpret/class/Graph.js, line 161 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6N2z17CKrCX9aB_GqZ:-L6YSxD_c7sHLz4d0w2g:b-4lrp95) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/Graph.js#L161)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

indent second line of comment
</blockquote></details>

For now, this code is reverted to previous state.

---

*[src/interpret/class/Point.js, line 54 at r2](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352#-L6NZPfqEqkhyT_0hdaS:-L6YT36hfgoYrufu6Ghy:by9scd2) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/07022d7b4aa770bf5bdc75f12ccab54fd57f9b5e/src/interpret/class/Point.js#L54)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you explain the difference between this and how it was before?
</blockquote></details>

This basically ensures compatibility with JSON.parse()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/chauncy-crib/tagprobot/352)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/352)*

**Pull request merged**
