### PR TITLE
139: our own astar

### LINKED ISSUE #139: Write an equivalent Astar implementation to the library, but in our own codebase

### PR DESCRIPTION
**Pull request by davidabrahams**
Closes #139 

This is equivalent to the library we're using, but all Astar code is in our codebase. This will be super helpful in terms of customizing the search in the future.

I used the pseudocode from this website: http://www.growingwiththeweb.com/2012/06/a-pathfinding-algorithm.html

I used a Fibonacci Heap, since its the most efficient data structure for Astar. I used an library Fib-heap implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot/140)

### CODE REVIEW

**Comment by shanek21** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/helpers/path.js, line 6 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOM_4ZetZ5OWiml92Y:-KsOM_4ZetZ5OWiml92Z:b-o8bqyv) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L6)):*
> ```JavaScript
>  */
> import _ from 'lodash';
> import FibonacciHeap from '@tyriar/fibonacci-heap';
> ```

Would it be that hard to write our own fibonacci heap?

---

*[src/helpers/path.js, line 17 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMiJ7ddYv1Srg1fDq:-KsOMiJ7ddYv1Srg1fDr:b-uazwu5) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L17)):*
> ```JavaScript
>     this.yc = yc;
> 
>     this.g = undefined; // the cost to the current state
> ```

Why is `g` the cost?

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsOMsP60lNwCnGt6PDR:b-xgxtae) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
> ```JavaScript
>     }
>     return xdiff + ydiff;
>   }
> ```

Why are the heuristic distance and geometric distance different? It just seems like they are different because Pythagorus did not get invited to the diagonal heuristic distance calculation party.

---

*[src/helpers/path.js, line 74 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOGNL7rbI1s8y5nsQK:-KsOGNL7rbI1s8y5nsQL:b-krvaob) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L74)):*
> ```JavaScript
>     _.each(potentialNeighbors, n => {
>       n.g = this.g + 1; // eslint-disable-line no-param-reassign
>       n.parent = this; // eslint-disable-line no-param-reassign
> ```

I didn't know you could make in-line modifications to the linter. I like it.

---

*[src/helpers/path.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsODMAAuQ_6fNXKQDfC:-KsODMAAuQ_6fNXKQDfD:b-8zmf0b) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L92)):*
> ```JavaScript
>  * @param {GameState} finalState
>  * @returns {Array} list of GameStates from starting state to final state, not including the
>  *   starting state.
> ```

Where are the `-`?

---

*[src/helpers/path.js, line 119 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOGIFT5EGnZjr1IdpR:-KsOGIFT5EGnZjr1IdpS:bi9489c) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L119)):*
> ```JavaScript
>   assert(_.has(me, 'yc'));
>   assert(_.has(target, 'xc'));
>   assert(_.has(target, 'yc'));
> ```

oooh thanks for adding these

---

*[src/helpers/path.js, line 133 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOLKnTglRXl_5ihA0u:-KsOLKnUCjdVhea_m_va:bg97veg) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L133)):*
> ```JavaScript
>   const openList = new Map();
>   // keep a list of the GameState keys of closed states
>   const closedList = new Set();
> ```

What's a closed state?

---

*[src/helpers/path.js, line 155 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsONRf_j5S8R8Wv0IJE:-KsONRfalGlBimocIqfy:b-zd0s3m) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L155)):*
> ```JavaScript
>         return;
>       }
>       // assign neighbor's f-cost
> ```

Maaaaan... now we have g cost AND f cost? What's the difference/what are they used for? I'm confused.

---

*[src/helpers/path.js, line 156 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOKV1udflqBQcoGsBn:-KsOKV1udflqBQcoGsBo:bvo6p8h) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L156)):*
> ```JavaScript
>       }
>       // assign neighbor's f-cost
>       // eslint-disable-next-line no-param-reassign
> ```

Showoff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by davidabrahams** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/helpers/path.js, line 6 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOM_4ZetZ5OWiml92Y:-KsP2kMX9Ts0kM6CDASP:b-o1wvr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L6)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Would it be that hard to write our own fibonacci heap?
</blockquote></details>

Eh. Sorta. I don't really understand how fibonacci heaps work, only their performance. I originally was going to write my own heap, but it was non-trivial so I went ahead with a library.

---

*[src/helpers/path.js, line 17 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMiJ7ddYv1Srg1fDq:-KsP2xn5pySWHd43BnrW:bp556hm) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L17)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why is `g` the cost?
</blockquote></details>

It's just convention for A*. Check out the [link](http://www.growingwiththeweb.com/2012/06/a-pathfinding-algorithm.html)

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsP4OS5mjn9fIosROdc:b-7ql1td) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Why are the heuristic distance and geometric distance different? It just seems like they are different because Pythagorus did not get invited to the diagonal heuristic distance calculation party.
</blockquote></details>

fixed

---

*[src/helpers/path.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsODMAAuQ_6fNXKQDfC:-KsP4tkx2y58Jg1tL1gH:bqed2tj) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L92)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Where are the `-`?
</blockquote></details>

This is the convention we're switching to, and eventually all comments will look like this one, in PR 146

---

*[src/helpers/path.js, line 133 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOLKnTglRXl_5ihA0u:-KsP52lpxm4v-ypSju7p:b-pk40ak) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L133)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

What's a closed state?
</blockquote></details>

Basically, a state which we know we've explored the shortest path to it. Once we know we've reached a state via its shortest path, no need to ever revisit it.

---

*[src/helpers/path.js, line 155 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsONRf_j5S8R8Wv0IJE:-KsP5JtL0dSGXHO-VsBo:b-ggpyh4) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L155)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Maaaaan... now we have g cost AND f cost? What's the difference/what are they used for? I'm confused.
</blockquote></details>

G cost is the actual cost we've calculated to a node. F cost is the G cost plus the estimated cost to the goal (F cost is approximated the total cost to reach the destination through this node)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by billmwong** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by shanek21** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/helpers/path.js, line 6 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOM_4ZetZ5OWiml92Y:-KsQ99ZOUluVt3uX2ZRR:bxwhgf8) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L6)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Eh. Sorta. I don't really understand how fibonacci heaps work, only their performance. I originally was going to write my own heap, but it was non-trivial so I went ahead with a library.
</blockquote></details>

I'll make it an issue :D

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsQ_xqbnazb7qyJkE8T:bpg1rdr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

fixed
</blockquote></details>

What is that equation supposed to be calculating? Diagonal distance? If so, I'm confused.

---

*[src/helpers/path.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsODMAAuQ_6fNXKQDfC:-KsQZt6SsPBgMm6PUcmC:b-6pzn9p) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L92)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This is the convention we're switching to, and eventually all comments will look like this one, in PR 146
</blockquote></details>

Hmm I think that the comment becomes noticeably less readable and am in favor of deviating from the convention. I thought you were in favor of the `-`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by davidabrahams** [comment]
Review status: 3 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsQex9Ui4sz2S0QI267:b-jb6h79) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

What is that equation supposed to be calculating? Diagonal distance? If so, I'm confused.
</blockquote></details>

Its the distance traveled between two points using a path like this:

x
 x
  x
   x
    xxxxx

Use pythagorean the calculate the first part of the distance, and the second part is linear

---

*[src/helpers/path.js, line 92 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsODMAAuQ_6fNXKQDfC:-KsQfCVbdvK1evGWC5pj:b-5ub9nr) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L92)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Hmm I think that the comment becomes noticeably less readable and am in favor of deviating from the convention. I thought you were in favor of the `-`?
</blockquote></details>

Alright switching back to the - :dango: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by davidabrahams** [comment]
Review status: 3 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsRW_HBjX6vgMoN-6qg:bvfddy7) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Its the distance traveled between two points using a path like this:

x
 x
  x
   x
    xxxxx

Use pythagorean the calculate the first part of the distance, and the second part is linear
</blockquote></details>

This doenst look like I intended. Attempt 2:

```
x
 x
  x
   x
    xxxxx
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by shanek21** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsTjcguiw0sxQWnOIi_:b6vfgyc) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

This doenst look like I intended. Attempt 2:

```
x
 x
  x
   x
    xxxxx
```
</blockquote></details>

Gotcha. It bothers me that at first glance there is a random hardcoded value in this equation. If you really like it the way it is, maybe at least change `1.4142` to `Math.sqrt(2)` and add a comment that explains what your text diagram above explains? Or you could break out that line into multiple lines that are more self-documenting like:
```
const diagDist = Math.sqrt(2) * Math.min(xDiff, yDiff);
const linDist = Math.abs(xDiff - yDiff);
return diagDist + linDist;
```

---

*[src/helpers/path.js, line 38 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsTkn21FvRvG4zZC8CL:-KsTkn21FvRvG4zZC8CM:b-agaw10) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a7c9e6855d6d9549a3ab78cc0a54515e72d0a992/src/helpers/path.js#L38)):*
> ```JavaScript
>   heuristic(targetState) {
>     const xdiff = Math.abs(this.xc - targetState.xc);
>     const ydiff = Math.abs(this.yc - targetState.yc);
> ```

Can you make these `xDiff` and `yDiff`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by davidabrahams** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/helpers/path.js, line 43 at r1](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsOMsP60lNwCnGt6PDQ:-KsVe6_Zbin1BUXZF0NN:b-pgr5lf) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/996ec4f0310fa1d75555ae4b9e0093834b15b1f4/src/helpers/path.js#L43)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Gotcha. It bothers me that at first glance there is a random hardcoded value in this equation. If you really like it the way it is, maybe at least change `1.4142` to `Math.sqrt(2)` and add a comment that explains what your text diagram above explains? Or you could break out that line into multiple lines that are more self-documenting like:
```
const diagDist = Math.sqrt(2) * Math.min(xDiff, yDiff);
const linDist = Math.abs(xDiff - yDiff);
return diagDist + linDist;
```
</blockquote></details>

Went the self documenting code route

---

*[src/helpers/path.js, line 38 at r3](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140#-KsTkn21FvRvG4zZC8CL:-KsVe9-ZDeyLi8nvLI6U:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot/blob/a7c9e6855d6d9549a3ab78cc0a54515e72d0a992/src/helpers/path.js#L38)):*
<details><summary><i>Previously, shanek21 (Shane Kelly) wrote…</i></summary><blockquote>

Can you make these `xDiff` and `yDiff`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by shanek21** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Comment by billmwong** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/chauncy-crib/tagprobot/140)*

**Pull request merged**
